go.mod
go.sum

Update to the version of fanal to validate using go-deb-version.

Update fanal version

---

pkg/run.go
pkg/scanner/scan.go

Suppress the warning message when specifying --clear-cache option

---

pkg/run.go

Enable --clear-cache and --refresh without specifying an image name

---

Dockerfile
README.md

Change Dokcerfile CMD to ENTRYPOINT

Change Dockerfile 

---

README.md
cmd/trivy/main.go
pkg/db/db.go
pkg/run.go

This pull request adds the auto-refresh option.
auto-refresh option is for updating automatically when trivy's dbVersion is updated on CI.

Add auto-refresh option

---

cmd/trivy/main.go
pkg/log/logger.go
pkg/run.go

Change log format.
Add stacktrace when debug option true.

Change log format

---

README.md

Changed CI example in README.  

---

cmd/trivy/main.go
pkg/db/db.go
pkg/vulnsrc/vulnerability/vulnerability.go
pkg/vulnsrc/vulnsrc.go

* Rewrite some if-else chains as a switch statements. Based on Go style
guide: https://golang.org/doc/effective_go.html#switch
* Simplify some functions.
* Some comments formatting.

Some code improvements.

---

.dockerignore
README.md

also add .circleci to .dockerignore
Please accept my modest contribution to this great project :)

Fix some typos in the README or improve phrasing

---

pkg/scanner/ospkg/scan.go
pkg/scanner/scan.go

No error on unsupported OS

---

README.md

It is better to use `--rm` option when `docker run`.

Update README about docker run

---

README.md
go.mod
go.sum
pkg/scanner/library/python/advisory.go
pkg/scanner/library/python/scan.go
pkg/scanner/library/scan.go

Support for Python package management tool Poetry.

Support Poetry

---

pkg/run.go
pkg/vulnsrc/vulnerability/const.go
pkg/vulnsrc/vulnsrc.go

Added alpine into dbnames

---

pkg/run.go

Fix https://github.com/knqyf263/trivy/issues/68

Fix --skip-update

---

pkg/vulnsrc/redhat/types.go

Remove `gorm:"-"`  from redhat.RedHatCVE in pkg/vulnsrc/redhat/types.go

remove nonsense struct tags

---

pkg/vulnsrc/nvd/nvd.go
pkg/vulnsrc/vulnsrc_test.go

used json.Unmarshal to reduce memory usage.
```
name          old time/op    new time/op    delta
Update/NVD-4     69.7s ± 5%     53.9s ± 8%  -22.68%  (p=0.008 n=5+5)
name          old alloc/op   new alloc/op   delta
Update/NVD-4    5.60GB ± 0%    1.32GB ± 0%  -76.47%  (p=0.029 n=4+4)
name          old allocs/op  new allocs/op  delta
Update/NVD-4     11.3M ± 0%     10.2M ± 0%   -9.86%  (p=0.008 n=5+5)
```

feat: improve nvd update

---

Dockerfile

Close https://github.com/knqyf263/trivy/issues/83

Embed trivy version in Docker

---

README.md

Thanks for your great product.
When I tried to use it in CircleCI, I found it.

fix CircleCI link in README

---

README.md

I maintained the packages in Arch Linux User Repository

Adding instructions for Install in Arch Linux

---

cmd/trivy/main.go
pkg/db/db.go
pkg/run.go
pkg/utils/utils.go

Revert #12 
I have not received the signed CLA, so I have to revert this PR. I'm so sorry...

Revert "Allow user specified cache directory (#12)"

---

README.md
cmd/trivy/main.go
pkg/db/db.go
pkg/run.go
pkg/utils/utils.go

Reimplement #12 due to CLA
Revert PR: https://github.com/knqyf263/trivy/pull/111

Reimplement --cache-dir option

---

README.md

Fix cannot found docker image

---

README.md

`--quiet` flag has changed https://github.com/aquasecurity/trivy/pull/125

README.md is out of date

---

go.mod
go.sum

Fix
- https://github.com/aquasecurity/trivy/issues/96
- https://github.com/aquasecurity/trivy/issues/147
Related PRs
- https://github.com/aquasecurity/fanal/pull/29
- https://github.com/aquasecurity/fanal/pull/34

Support distroless and ignore lock files under vendor dir

---

README.md
go.mod
go.sum
pkg/scanner/ospkg/scan.go

https://github.com/aquasecurity/trivy/issues/156

Warning when rpm not found

---

go.mod
go.sum

Ref. https://github.com/aquasecurity/fanal/pull/26
https://github.com/aquasecurity/trivy/issues/161

Support Kaniko

---

README.md

Typo fix.
Change 'occured' to 'occurred'.

Update README.md - typo fix

---

README.md

Slightly improve the install instruction for Ubuntu/Debian. User doesn't need to manually add the `code name` to the commands any more.

Improve ubuntu install

---

CONTRIBUTING.md
README.md

Once this is approved I'll add to funnel and vuln-list-update as well

add contribution guideline

---

pkg/utils/utils.go

Check returned error before deferring file close

---

cmd/trivy/main.go
pkg/run.go
pkg/scanner/scan.go
pkg/types/scanoptions.go

Add timeout option.
issue: #139 
note: 
https://github.com/aquasecurity/fanal/blob/master/analyzer/analyzer.go#L115
It is left as a default value of the fanal library.

Add timeout option

---

README.md

- Added Docker Image badge
- Corrected grammar
- Added missing punctuation's

Added Docker image badge & missing punctuation's

---

pkg/scanner/library/node/advisory.go

As this pull request merely corrects a small typo, I didn't open an issue for it - but I can change that if required.

Remove extra double quote

---

README.md

This is a working example in my pipeline for GitLab job, see this for more reference:
https://docs.gitlab.com/ee/ci/yaml/

Added example GitLab YML

---

pkg/app.go

This allows to enable autocompletion via
https://github.com/urfave/cli/blob/master/docs/v1/manual.md#bash-completion

Enable shell autocompletion

---

README.md

CLA-assistant wasn't able to correctly assess my contribution when I made a trivial correction to #250 so it's quicker just to create another PR

docs: typo correction

---

go.mod
go.sum

Update fanal version
https://github.com/aquasecurity/fanal/pull/44

fix(lockfile): files under vendor dir

---

README.md
go.mod
pkg/github/github.go

Close https://github.com/aquasecurity/trivy/issues/280

feat(github): add GITHUB_TOKEN for rate limiting

---

pkg/run.go

Close https://github.com/aquasecurity/trivy/issues/271

chore(log): add debug messages

---

integration/client_server_test.go
integration/integration_test.go
integration/standalone_test.go
internal/app.go
internal/rpc/server/ospkg/server.go
internal/rpc/server/server.go
internal/server/config/config.go
internal/server/config/config_test.go

https://github.com/aquasecurity/trivy/pull/295

test(integration): add integration tests for client/server

---

internal/client/run.go

fix(client): clear cache

---

README.md

Close https://github.com/aquasecurity/trivy/issues/336

chore(README): add 0.0.0.0 to the server example

---

go.mod
go.sum
integration/docker_engine_test.go
pkg/rpc/client/library/client.go
pkg/rpc/client/ospkg/client.go
pkg/rpc/retry.go

feat(client): retry HTTP request when getting an unavailable error

---

go.mod
go.sum

Close https://github.com/aquasecurity/trivy/issues/353
Close #354 
https://github.com/aquasecurity/fanal/pull/64

chore(dep): update

---

go.mod
go.sum
internal/client/run.go
internal/operation/operation.go
internal/standalone/run.go
internal/standalone/wire_gen.go

Fix issue: https://github.com/aquasecurity/trivy/issues/363
Also
Close https://github.com/aquasecurity/trivy/issues/362

Fix inifinite loop when resolving dependencies of packages in Alpine 

---

goreleaser.yml

Close https://github.com/aquasecurity/trivy/issues/360

chore: change a licence in goreleaser.yml

---

README.md
contrib/gitlab.tpl
goreleaser.yml

This PR integrates trivy with Gitlab Container Scanning and provides a
similar report. It adds the required template to the release tarball for easy
consumption.
https://docs.gitlab.com/ee/user/application_security/container_scanning/
https://gitlab.com/gitlab-org/gitlab/issues/11947
Sample output:
```
{
"version": "2.3",
"vulnerabilities": [
{
"category": "container_scanning",
"message": "binutils: Memory leak with the C++ symbol demangler routine in libiberty",
"description": "The C++ symbol demangler routine in cplus-dem.c in libiberty, as distributed in GNU Binutils 2.29, allows remote attackers to cause a denial of service (excessive memory allocation and application crash) via a crafted file, as demonstrated by a call from the Binary File Descriptor (BFD) library (aka libbfd).", …
```

Integrate with Gitlab Container Scanning

---

internal/client/config/config.go
internal/client/config/config_test.go
internal/standalone/config/config.go
internal/standalone/config/config_test.go

fix(cli): reject multiple images

---

README.md

This should have been updated with #359 (and #361) 😄

doc: Add Alpine Linux 3.11 to supported OS docs

---

README.md

Close https://github.com/aquasecurity/trivy/issues/403

chore(README): add explanation for self-compiled binaries/packages

---

.github/workflows/test.yaml

Even when it passes all tests, cross-compilation sometimes fails. We should test it in CI.

chore(ci): add cross-compile test

---

README.md

```
docker run -it docker:18.09-git sh
/ # rpm
sh: rpm: not found
/ #
```

fix circleci example

---

internal/app.go
internal/app_test.go

This PR fixes a few edge cases with the version flag.

app: Fix a few edge cases with version flag

---

go.mod
go.sum

Close https://github.com/aquasecurity/trivy/issues/288
Ref. https://github.com/aquasecurity/trivy-db/pull/35

fix(db): retry downloading the database if it is broken

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md

We introduced new labels.
https://github.com/aquasecurity/trivy/pull/473

chore(github): fix issue templates

---

internal/app.go

Before:
```
$ trivy --help
...
USAGE:
trivy [global options] command [command options] image_name
$ trivy image --help
...
USAGE:
trivy image [command options]
```
After:
```
$ trivy --help
...
USAGE:
trivy [global options] command [command options] target
$ trivy image --help
...
USAGE:
trivy image [command options] image_name
```

fix(app): add ArgsUsage

---

internal/config/global.go

Close https://github.com/aquasecurity/trivy/issues/515

fix(config): transpose arguments

---

go.mod
go.sum
integration/integration_test.go
internal/app_test.go
pkg/db/db.go
pkg/db/db_test.go
pkg/db/mock_db_operation.go

Use StoreMetadata from trivy-db

---

pkg/log/logger.go

Close https://github.com/aquasecurity/trivy/issues/537

fix(log): write error messages to stderr

---

README.md
contrib/junit.tpl
pkg/report/writer.go
pkg/report/writer_test.go

[Issue](https://github.com/aquasecurity/trivy/issues/93)

Added JUNIT support

---

go.mod
go.sum
pkg/vulnerability/vulnerability_test.go

Ref. https://github.com/aquasecurity/trivy-db/pull/54

feat(vulnerability): add CWE-ID

---

README.md
internal/app.go
internal/artifact/run.go
internal/config/image.go
pkg/report/writer.go
pkg/scanner/local/scan.go
pkg/scanner/local/scan_test.go
pkg/types/scanoptions.go

[Issue](https://github.com/aquasecurity/trivy/issues/548)

Added support of list-all-packages

---

Dockerfile
README.md

[issue](https://github.com/aquasecurity/trivy/issues/580)

Reverting fix for issue #570

---

contrib/sarif.tpl
integration/testdata/alpine-310.sarif.golden

sarif: Remove extra periods from short descriptions

---

internal/artifact/config/config.go
internal/artifact/config/config_test.go
internal/artifact/image.go
internal/client/config/config_test.go
internal/config/artifact.go
internal/config/artifact_test.go

Related the issue https://github.com/aquasecurity/trivy/issues/532.
It was changing the error to debug mode.

fix: remove error using no options

---

README.md
contrib/asff.tpl
integration/client_server_test.go
integration/testdata/alpine-310.asff.golden
pkg/report/writer.go
pkg/report/writer_test.go

[Issue](https://github.com/aquasecurity/trivy/issues/586)

Added test and support of ASFF template

---

.circleci/codecov.yml

Ref: https://github.com/testground/testground/pull/430

circleci: Allow coverage changes without a failure

---

pkg/detector/library/bundler/advisory.go
pkg/detector/library/bundler/advisory_test.go

Remove replacer in favor of https://github.com/aquasecurity/trivy/pull/552

refactor(bundler): remove unnecessary code

---

README.md

These part is not rendering correctly the [Result](https://github.com/aquasecurity/trivy#save-the-results-using-a-template).

fix(Readme) - Results using a template

---

README.md
integration/standalone_tar_test.go
integration/testdata/fluentd-multiple-lockfiles.json.golden
internal/app.go
internal/artifact/run.go
internal/config/artifact.go
pkg/scanner/local/scan.go
pkg/scanner/local/scan_test.go
pkg/types/scanoptions.go

Close https://github.com/aquasecurity/trivy/issues/620
Blocked by https://github.com/aquasecurity/trivy-test-images/pull/5

feat(cli): add --skip-files option

---

pkg/rpc/server/listen.go
pkg/rpc/server/listen_test.go

refactored and added tests for mux
- ref. https://github.com/aquasecurity/trivy/pull/644
- blocker: https://github.com/aquasecurity/trivy/pull/646
- This PR uses t.TempDir() introduced at Go 1.15

test: add tests for mux

---

README.md

This MR fixes a broken link in README

fix link for Clear images section in README

---

.circleci/config.yml

Resolves [issue](https://github.com/aquasecurity/trivy/issues/682).

Update remote Docker version in CircleCI config

---

pkg/scanner/local/scan.go

Fixes https://github.com/aquasecurity/trivy/issues/726
cc @knqyf263 
Happy Hacktober 🎃

Warn when a user attempts to use trivy without a detectable lockfile

---

README.md

Close https://github.com/aquasecurity/trivy/issues/757

chore(README): add TRIVY_INSECURE

---

pkg/vulnerability/vulnerability.go
pkg/vulnerability/vulnerability_test.go

Close https://github.com/aquasecurity/trivy/issues/755

fix(vulnerability): make an empty severity UNKNOWN

---

helm/trivy/.helmignore
helm/trivy/Chart.yaml
helm/trivy/README.md
helm/trivy/templates/NOTES.txt
helm/trivy/templates/_helpers.tpl
helm/trivy/templates/ingress.yaml
helm/trivy/templates/podsecuritypolicy.yaml
helm/trivy/templates/role.yaml
helm/trivy/templates/rolebinding.yaml
helm/trivy/templates/service.yaml
helm/trivy/templates/serviceaccount.yaml
helm/trivy/templates/statefulset.yaml
helm/trivy/values.yaml

Add helm chart to install trivy in server mode.

---

helm/trivy/Chart.yaml
helm/trivy/README.md
helm/trivy/templates/secret.yaml
helm/trivy/templates/statefulset.yaml
helm/trivy/values.yaml

And remove unnecessary config parameters.
Fixes #768

Add gitHubToken to prevent rate limit problems

---

.circleci/config.yml

It is already tested in golangci-lint.
https://github.com/aquasecurity/trivy/blob/793a1aa3c83f7a77355e454a12d034964bfa0088/.github/workflows/test.yaml#L9-L13

chore(circleci): remove gofmt

---

goreleaser.yml

shifted: brews.github to brews.tap

---

.circleci/config.yml
.github/workflows/test.yaml

Migrating CI to GitHub Actions gradually.

chore(ci): migrate unit tests to GitHub Actions

---

internal/operation/operation.go

Fix formatting of log message

---

helm/trivy/Chart.yaml
helm/trivy/README.md
helm/trivy/templates/statefulset.yaml
helm/trivy/values.yaml

Add imagePullSecrets to helm Chart

---

helm/trivy/Chart.yaml
helm/trivy/README.md
helm/trivy/templates/statefulset.yaml

Fix env variable for github token

---

contrib/sarif.tpl
integration/testdata/alpine-310.sarif.golden

Fix errors in SARIF format

---

README.md

Close https://github.com/aquasecurity/trivy/issues/806

docs(README): explain mandatory/optional fields

---

README.md

Solves #843 
* Unset `entrypoint` to make `script` section work.
* Add credentials to allow Trivy to authenticate to the registry.
* Skip cloning the source repo. It is not required in this CI job.
* Add Trivy version information to the job log.
* Fix a minor issue with the template path (and drop the `cd /`).

Fix "GitLab CI using Trivy container" usage example (fixes #843)

---

README.md
go.mod
go.sum
pkg/report/writer.go
pkg/report/writer_test.go

See #830 Added Sprig to get more possibilities to template engine.

Add Sprig to Template Engine

---

contrib/sarif.tpl
pkg/report/writer_test.go

remove SARIF helpUri if empty (#841)

---

README.md

This commit adds an example with multistage builds. Related to issue  #849

adds example with multistage build

---

.github/workflows/release.yaml
goreleaser.yml

Same as https://github.com/aquasecurity/starboard/pull/291

chore(ci): push the official image to public ECR

---

go.mod
go.sum
internal/artifact/fs.go
internal/artifact/image.go
internal/artifact/inject.go
internal/artifact/repository.go
internal/artifact/run.go
internal/artifact/wire_gen.go
internal/client/inject.go
internal/client/run.go
internal/client/wire_gen.go

Enable apk commands analyzer only when `--removed-pkgs` is passed.
https://github.com/aquasecurity/fanal/pull/153

feat: disable analyzers

---

.github/workflows/mkdocs-dev.yaml

https://aquasecurity.github.io/trivy/dev/

chore(ci): deploy dev docs only for the main branch

---

misc/triage/labels.yaml

Ref https://github.com/aquasecurity/trivy/pull/908

chore(triage): add lifecycle/active label

---

contrib/sarif.tpl
integration/testdata/alpine-310.sarif.golden
pkg/report/writer_test.go

[Issue](https://github.com/aquasecurity/trivy-action/issues/22)

Add package name in ruleID

---

contrib/junit.tpl
pkg/report/writer_test.go

Fix JUnit template for AWS CodeBuild compatibility

---

go.mod
go.sum
pkg/detector/library/maven/compare.go
pkg/detector/library/maven/compare_test.go

related: 
https://github.com/aquasecurity/trivy-db/pull/111
https://github.com/aquasecurity/trivy/issues/940

feat(java): support GitLab Advisory Database

---

.github/workflows/release.yaml
.github/workflows/test.yaml
goreleaser.yml

https://goreleaser.com/customization/release/

chore(ci): create a release discussion

---

go.mod
go.sum

Close https://github.com/aquasecurity/trivy/issues/968
Ref https://github.com/aquasecurity/fanal/pull/173

fix(fs): skip dirs

---

Dockerfile

[Issue](https://github.com/aquasecurity/trivy/issues/960)

Upgrade alpine to fix git and libcurl vulnerabilities in trivy docker image scan

---

go.mod
go.sum

Close https://github.com/aquasecurity/trivy/issues/1004

fix(gomod): handle go.sum with an empty line

---

.github/workflows/scan.yaml
go.mod
go.sum

Close https://github.com/aquasecurity/trivy/issues/997

chore(ci): add Go scanning and update dependencies

---

docs/integrations/github-actions.md

fix typo: github-actions.md

---

docs/vuln-detection/os.md

docs(ubuntu): fix supported versions

---

pkg/detector/library/comparer/compare.go
pkg/detector/library/comparer/compare_test.go

Closes https://github.com/aquasecurity/trivy/issues/1011

fix(go): if patchedVersion is empty mark it as vulnerable

---

helm/trivy/Chart.yaml
helm/trivy/values.yaml

chore: chart with 0.18.3

---

go.mod
go.sum
pkg/rpc/server/listen.go

This PR changed to gzip in http.Handler instead of gzip in Twirp.

refactor(server): support gzip

---

go.mod
go.sum

This commit updates Fanal library version to latest which
includes support for Google artifact repository.

feat: support Google Artifact Repository

---

helm/trivy/Chart.yaml
helm/trivy/templates/ingress.yaml
helm/trivy/values.yaml

fixes #1040 
parametrized ingress path
Signed-off-by: Abhinav Khanna <abhinav.khanna@salesforce.com>

fix(helm-chart): parametrized ingress path

---

.github/workflows/release.yaml
.gitignore
goreleaser.yml

Generate and publish SBOM as part of the release.

Generate SBOM

---

pkg/policy/policy.go

Close https://github.com/aquasecurity/trivy/issues/1113

fix(policy): fix panic on the first run

---

go.mod
go.sum

fix(image): disabled scanning of config files within container images

---

ci/deploy-deb.sh

chore (release): add ubuntu esm versions to deploy script

---

goreleaser.yml

chore(gorelease) change goreleaser config to include template examples

---

go.mod
go.sum

Fix out of memory issues
- https://github.com/aquasecurity/fanal/pull/294
Fix https://github.com/aquasecurity/trivy/issues/1242
Fix https://github.com/aquasecurity/trivy/issues/1190

fix(gobinary): skip large files

---

.github/workflows/release.yaml

Cc: @knqyf263, @masahiro331, @nscuro

Update SBOM generation

---

go.mod
go.sum

Closes #1355
Signed-off-by: Thomas Spear <tspear@conquestcyber.com>

mod: update containerd to v1.5.7 and docker-cli to v20.10.9

---

go.mod
go.sum
pkg/scanner/local/scan.go
pkg/types/misconfiguration.go

- adding line in file information to the misconfiguration result
- updating tfsec and cfsec versions to provide this additional info

feat(iac): Add line information

---

docs/advanced/integrations/bitbucket.md
mkdocs.yml

Close https://github.com/aquasecurity/trivy/issues/1307

docs: add Bitbucket Pipelines

---

contrib/sarif.tpl
integration/testdata/alpine-310.sarif.golden
pkg/report/template.go
pkg/report/writer_internal_test.go

fix(sarif): fix validation errors

---

pkg/utils/utils.go
pkg/utils/utils_test.go

remove: delete unused functions in utils package

---

docs/misconfiguration/comparison/cfsec.md
mkdocs.yml

docs: Add comparison for cfsec

---

.github/workflows/publish-chart.yaml
helm/trivy/Chart.yaml
helm/trivy/templates/ingress.yaml
helm/trivy/values.yaml

Fixing the helm deploy using `Ingress: true`.
Related to https://github.com/aquasecurity/trivy/issues/1320

fix: ingress helm manifest-update trivy image

---

.github/workflows/publish-chart.yaml

Applying the review of @danielpacak in helm starboard chart. 
https://github.com/aquasecurity/starboard/pull/819

chore: test the helm chart in the PR and used the commit hash

---

.github/workflows/test.yaml
goreleaser.yml

fixes https://github.com/aquasecurity/trivy/issues/1404

Replace deprecated option in goreleaser

---

contrib/sarif.tpl
integration/testdata/alpine-310.sarif.golden

Added `help` block with a detailed vulnerability description and changed a title for a specific result.
Fixes #1419

fix(sarif): change `help` field in the sarif template.

---

go.mod
go.sum

bumps dependency version for https://github.com/aquasecurity/fanal/pull/332
Closes #1385, Closes #1387

fix(hooks): exclude unrelated lib types from system files filtering

---

docs/advanced/air-gap.md

added instruction for misconfiguration detection
Closes #1301

docs(misconfiguration): added instruction for misconfiguration detection

---

.gitignore
ci/deploy-deb.sh

Fix #1455 
test passed on ubuntu

Add arm64 deb package

---

pkg/commands/app.go
pkg/commands/plugin/plugin.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

- Add plugin list and info commands
*List*
```bash
trivy plugin list                                        
Installed Plugins:
Name:    aqua
Version: v0.7.1
```
*Info* 
```bash
trivy plugin info aqua                                                                                                                                                                                                                                                                                                                
Plugin: aqua
Description:    A Trivy plugin that sends results to Aqua.
Version:        v0.7.1
Usage:          trivy aqua <srcPath>
```

feat (plugin): add list and info command for plugin

---

go.mod
go.sum

Updated dependency to fanal after merge [#342](https://github.com/aquasecurity/fanal/pull/342)
Closes #1479

fix: fixed skipFiles/skipDirs flags for relative path

---

contrib/gitlab-codequality.tpl
integration/testdata/alpine-310.gitlab-codequality.golden

Hi.
This PR adds a [required field](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) for gitlab codequality template. Without this field in the Gitlab UI it shows no changes while the information is generated correctly.
Connected issue #1540
Signed-off-by: Jasstkn <mariia.kotliarevskaia@gmail.com>

fix: add fingerprint option to codequality template

---

pkg/commands/app.go

feat(cli): Do not set default commands when a plugin is being run (#1548)

---

docs/advanced/integrations/circleci.md
docs/advanced/integrations/travis-ci.md
pkg/commands/app.go

See https://github.com/aquasecurity/trivy/discussions/1515

BREAKING: remove root command

---

docs/vulnerability/detection/language.md
go.mod
go.sum

Add support PAR files.
- Close #1562

feat(java): add support PAR files

---

.github/pull_request_template.md
CONTRIBUTING.md

docs: add PR template

---

mkdocs.yml

Add a link for ACR
https://aquasecurity.github.io/trivy/dev/advanced/

docs: add ACR navigator

---

docs/misconfiguration/iac.md
docs/misconfiguration/options/filter.md
examples/misconf/mixed/README.md

defauls -> defaults
- Close #XXX
- [] I've included a "before" and "after" example to the description (if the PR is a user interface change).

docs: fix typos in markdown docs

---

.github/workflows/publish-chart.yaml
helm/trivy/Chart.yaml

- Upgrade app version of the helm chart
- Fix a basic test of using Ingress enabled with true

chore: Upgrade helm chart version

---

go.mod
go.sum
pkg/purl/purl.go
pkg/purl/purl_test.go

Add generate purl utilities.  
specification: https://github.com/package-url/purl-spec
for: https://github.com/aquasecurity/trivy/pull/1522, https://github.com/aquasecurity/trivy/pull/1081

feat(purl): add generate purl package utilities

---

pkg/commands/artifact/option.go
pkg/commands/client/option.go
pkg/commands/option/report.go
pkg/commands/option/report_test.go

This PR adds consideration on `cli.App.Writer` when supplies with a value.
- Close #1721

feat(report): considering App.Writer when printing results

---

.golangci.yaml
pkg/commands/artifact/option.go
pkg/commands/artifact/option_test.go
pkg/commands/client/option.go
pkg/commands/client/option_test.go
pkg/commands/option/report.go
pkg/commands/option/report_test.go

https://github.com/aquasecurity/trivy/pull/1632 was imcomplete

fix(option): warn list-all-pkgs only with the table format

---

docs/getting-started/installation.md

Fix erroneous command in the documentation.

docs: remove erroneous command

---

helm/trivy/Chart.yaml

chore(helm): bump chart to trivy 0.24.0

---

go.mod

chore: bump up Go to 1.17

---

helm/trivy/templates/podsecuritypolicy.yaml
helm/trivy/templates/role.yaml

chore(helm): remove psp from helm manifest

---

go.mod
go.sum

Update fanal version to fix a panic. https://github.com/aquasecurity/fanal/pull/417
- Close #1773

fix(hcl): fix panic in hcl2json

---

go.mod
go.sum
integration/docker_engine_test.go

- panics when checking for HttpTokens requirement
- panics when converting results with no logicalID
- Close #1792

fix(terraform): resolve panics in defsec

---

pkg/report/json.go

fix(report): ensure json report got a final new line

---

.github/workflows/release.yaml
.github/workflows/test.yaml
goreleaser.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
- Close #1660

build: sign container image

---

docs/vulnerability/detection/language.md

.NET packages.config added by #1095 to the documentation.

docs: add packages.config for .NET

---

misc/triage/labels.yaml

added new issue labels:
* co/terraform
* co/cloudformation
* co/dockerfile
* co/kubernetes

chore(issue labels): added new labels

---

docs/docs/references/troubleshooting.md
go.mod
go.sum

- Close #1869 
- https://github.com/aquasecurity/fanal/pull/448
- https://github.com/aquasecurity/go-dep-parser/pull/90

feat(jar): allow setting Maven Central URL using environment variable

---

docs/docs/vulnerability/languages/golang.md

docs(go): fix version

---

.github/pull_request_template.md
docs/docs/vulnerability/distributions/cbl-mariner.md
mkdocs.yml

Add a dedicated page for CBL-Mariner. Other distributions are coming soon.

docs: add CBL-Mariner

---

Dockerfile

alpine 3.15.3 has 2 critical vulnerabilities:
```
alpine:3.15.3 (alpine 3.15.3)
=============================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 2)
+------------+------------------+----------+-------------------+---------------+---------------------------------------+
|  LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+------------+------------------+----------+-------------------+---------------+---------------------------------------+
| busybox    | CVE-2022-28391   | CRITICAL | 1.34.1-r4         | 1.34.1-r5     | CVE-2022-28391 affecting              |
|            |                  |          |                   |               | package busybox 1.35.0                |
|            | …
```

chore(deps): bump alpine from 3.15.3 to 3.15.4

---

pkg/detector/ospkg/alpine/alpine.go

feat(alpine): warn mixing versions

---

go.mod
go.sum

See https://github.com/aquasecurity/fanal/pull/487

fix(go): check if go.sum is nil

---

helm/trivy/Chart.yaml

Upgrade helm app version to 26.0

chore: app version 26.0

---

docs/docs/misconfiguration/custom/index.md
docs/docs/misconfiguration/policy/builtin.md

We added 'Containerfile' support as a config file in aquasecurity/fanal/pull/475.
This PR will apply this update as follows.
```
$ ls ../test/
Containerfile   Dockerfile
$ ./trivy config ../test/
2022-04-23T08:28:13.332+0900    INFO    Detected config files: 1
Dockerfile (dockerfile)
=======================
Tests: 23 (SUCCESSES: 22, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | …
```

feat(dockerfile): support 'Containerfile' as config filename

---

docs/docs/vulnerability/detection/language.md

Update the go part of the language list from go.sum to go.mod.

docs(go): change from go.sum to go.mod

---

helm/trivy/Chart.yaml

chore: app version 0.27.0

---

.github/workflows/scan.yaml

Update trivy-issue-action
- Close https://github.com/aquasecurity/trivy/issues/2080
- https://github.com/knqyf263/trivy-issue-action/pull/3

chore(deps): bump trivy-issue-action to v0.0.4

---

go.mod
go.sum

fix(misconf): Fix coloured output in Goland terminal

---

go.mod
go.sum
pkg/report/json.go
pkg/types/report.go

Remove Highlighted from the json output
While preserving

fix: remove Highlighted from json output

---

go.mod
go.sum

chore(deps): Update fanal (for less verbose code in misconf results)

---

v0.28.0/docs/kubernetes/operator/installation/helm/index.html
v0.28.0/docs/kubernetes/operator/installation/kubectl/index.html

Patch the docs - targets gh-pages branch

docs: patch the docs for installing trivy operator

---

go.mod
go.sum

update trivy-kubernetes to latest release, fixing a few bugs.
- Close https://github.com/aquasecurity/trivy/issues/2148
- Close https://github.com/aquasecurity/trivy/issues/2134

fix(k8s): update trivy-kubernetes

---

docs/docs/vulnerability/detection/os.md
pkg/detector/ospkg/redhat/redhat.go

Adds support for the newly released Red Hat Universal Base Image v9.
- Close #2182

chore(redhat): Add support for Red Hat UBI 9.

---

docs/docs/kubernetes/cli/scanning.md
pkg/commands/app.go

before:
after:
- Close https://github.com/aquasecurity/trivy/issues/2137

feat(k8s): scan secrets

---

pkg/k8s/table.go

- Close https://github.com/aquasecurity/trivy/issues/2174

fix(k8s): properly instantiate TableWriter

---

go.mod
go.sum
pkg/commands/app.go
pkg/commands/option/kubernetes.go
pkg/k8s/run.go

```
$ trivy k8s --report summary  # scans default context
$ trivy k8s --report summary --context not-default
$ trivy k8s --report summary --context not-default2
```
- Close https://github.com/aquasecurity/trivy/issues/2159

feat(k8s): add --context flag

---

mkdocs.yml

docs: update operator release

---

docs/docs/misconfiguration/custom/index.md

Updates the custom policy docs to reflect latest defsec/fanal changes

docs: Update custom rego policy docs

---

contrib/asff.tpl

Outputs misconfigurations in the ASFF template. Previously only vulnerabilities were supported.
- Close #2166

feat(report): Add misconfiguration support to ASFF report template

---

docs/docs/vulnerability/distributions.md
go.mod
go.sum

Added added support for CBL-Mariner Distroless v2.0
```bash
➜  trivy image mcr.microsoft.com/cbl-mariner/distroless/base:2.0
2022-06-09T14:58:38.668+0600    INFO    Detected OS: cbl-mariner
2022-06-09T14:58:38.668+0600    INFO    Detecting CBL-Mariner vulnerabilities...
2022-06-09T14:58:38.669+0600    INFO    Number of language-specific files: 0
mcr.microsoft.com/cbl-mariner/distroless/base:2.0 (cbl-mariner 2.0.20220527)
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 0, CRITICAL: 0)
┌─────────────┬───────────────┬──────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────┐
│   Library   │ Vulnerability │ Severity │ Installed Version │ Fixed Version │                         Title                          │ …
```

feat(mariner): added support for CBL-Mariner Distroless v2.0

---

docs/docs/kubernetes/cli/scanning.md
docs/docs/kubernetes/operator/configuration-auditing/built-in-policies.md
docs/docs/kubernetes/operator/getting-started.md
docs/docs/kubernetes/operator/vulnerability-scanning/index.md

docs(kubernetes): dead links

---

go.mod
go.sum
pkg/k8s/run.go

- Close https://github.com/aquasecurity/trivy/issues/2258

fix: do not exit if one resource is not found

---

go.sum

Removed an old dependency github.com/aquasecurity/trivy-kubernetes v0.3.0

chore: run `go mod tidy`

---

.github/workflows/test.yaml

Added running `go mod tidy` for the check.

ci: add `go mod tidy` check

---

go.mod
go.sum

Added check for looping when evaluating variables when parsing pom.xml files.
- Close https://github.com/aquasecurity/trivy/issues/2202

fix(java): added check for looping for variable evaluation in pom file

---

pkg/types/report.go

Fixes #2366. 
p.s. this is my first OSS pull request and excuse me if there's anything stupid with this pull request.
- #2366

fix(secret): use secret result when determining Failed status

---

go.mod
go.sum

fix(misconf): Update defsec (v0.68.5) to fix docker rego duplicate key

---

docs/docs/index.md
docs/docs/sbom/index.md
pkg/commands/app.go
pkg/commands/artifact/run.go
pkg/commands/artifact/sbom.go
pkg/commands/option/sbom.go

https://github.com/aquasecurity/trivy/discussions/2407

BREAKING(sbom): change 'trivy sbom' to scan SBOM

---

go.mod
go.sum

Fix false positive with use of cos images
- Close #2398

fix: Update defsec to v0.68.6 to fix false positive when using COS images

---

integration/testdata/debian-stretch.json.golden
integration/testdata/distroless-base.json.golden
integration/testdata/distroless-python27.json.golden

Debian 9 [is no longer updated](https://wiki.debian.org/LTS).
Changed Debian 9 based golden files for integration tests.

test: fix golden files for debian 9 for integration tests

---

docs/docs/vulnerability/distributions.md

Structure of `container-manifest-2` file in `CBL-Mariner Distroless 1.0` has been changed to supported format.
We now support rpm discovery for these images.
```
root@eb35b52738a7:/# trivy image mcr.microsoft.com/cbl-mariner/distroless/base:1.0
2022-07-07T04:22:00.847Z	INFO	Vulnerability scanning is enabled
2022-07-07T04:22:00.847Z	INFO	Secret scanning is enabled
2022-07-07T04:22:00.847Z	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-07T04:22:00.847Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.2/docs/secret/scanning/#recommendation for faster secret detection
2022-07-07T04:22:01.737Z	INFO	Detected OS: cbl-mariner
2022-07-07T04:22:01.737Z	INFO	Detecting CBL-Mariner vulnerabilities...
2022-07-07T04:22:01.739Z	INFO …
```

docs(mariner): distroless 1.0 supported

---

pkg/flag/cache_flags_test.go
pkg/flag/options.go
pkg/flag/report_flags_test.go
pkg/flag/scan_flags.go
pkg/flag/scan_flags_test.go

test: add cache flag test

---

pkg/commands/artifact/run.go
pkg/flag/scan_flags.go

- `--security-checks` flag in config file can be used as a slice.

fix(cli): fix cobra cli errors

---

integration/testdata/secrets.json.golden
pkg/fanal/types/secret.go

Adds file/lines to secrets output which was omitted due to cache issue.
- Close #2463

fix: Fix secrets output not containing file/lines

---

pkg/commands/app.go

feat: add examples for commands

---

helm/trivy/README.md

Corrected a typo correction in Helm chart Readme.

docs(helm): Typo correction bitnami chart

---

docs/docs/references/troubleshooting.md

Add information about using multiple servers to troubleshooting

docs: add information about using multiple servers to troubleshooting

---

.github/CODEOWNERS

This PR adds code owners for misconfiguration scanning

chore: add owners for misconfiguration scanning

---

docs/docs/attestation/sbom.md
mkdocs.yml

Add documentation describing how to create an attestation of SBOM.
- Close #2506

docs(sbom): add sbom attestation

---

go.mod
go.sum

```
$ trivy k8s -n kube-system --report summary all
34 / 34 [-------------------------------------------------------------------------------------------------------] 100.00% 1 p/s
┌─────────────┬──────────────────────────────────────┬─────────────────────┬────────────────────┬───────────────────┐
│  Namespace  │               Resource               │   Vulnerabilities   │ Misconfigurations  │      Secrets      │
│             │                                      ├───┬────┬───┬────┬───┼───┬───┬───┬────┬───┼───┬───┬───┬───┬───┤
│             │                                      │ C │ H  │ M │ L  │ U │ C │ H │ M │ L  │ U │ C │ H │ M │ L │ U │
├─────────────┼──────────────────────────────────────┼───┼────┼───┼─ …
```

fix: k8s controlplane scanning

---

pkg/detector/ospkg/alma/alma.go

feat(alma): set AlmaLinux 9 EOL

---

docs/getting-started/installation.md

( Update docs)Instructions to connect to a third-party repository
- Close #2180

docs:  follow Debian's "instructions to connect to a third-party repository"

---

pkg/flag/aws_flags.go

docs(cli): fix help typo

---

pkg/scanner/local/scan.go
pkg/scanner/local/scan_test.go

When using `--list-all-pkgs` flag we need to show all packages. Trivy currently includes only targets with vulnerabilities.
Before:
``` bash
➜ trivy -q rootfs -f json --list-all-pkgs without_vulns.jar
{
"SchemaVersion": 2,
"ArtifactName": "without_vulns.jar",
"ArtifactType": "filesystem",
"Metadata": {
"ImageConfig": {
"architecture": "",
"created": "0001-01-01T00:00:00Z",
"os": "",
"rootfs": {
"type": "",
"diff_ids": null
},
"config": {}
}
}
}
```
After:
``` bash
➜ ./trivy -q rootfs -f json --list-all-pkgs without_vulns.jar
{
"SchemaVersion": 2,
"ArtifactName": "without_vulns.jar",
"ArtifactType": "filesystem",
"Metadata": {
"ImageConfig": {
"architecture": "",
"created": "0001-01-01T00:00:00Z",
"os": "",
"rootfs": {
"type": "",
"diff_ids": null
},
"config": {}
}
},
"Results": [
{ …
```

fix: don't skip packages that don't contain vulns, when using --list-all-pkgs flag

---

pkg/scanner/local/scan.go

dynamic links support for scan results
- Close #2837 
- Related #2455 
needed).

feat: dynamic links support for scan results

---

docs/docs/sbom/cyclonedx.md
docs/docs/sbom/index.md
docs/docs/sbom/spdx.md

docs(sbom): add SPDX scanning

---

docs/docs/kubernetes/cli/scanning.md

Fix a typo
- [x ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.

docs: fix a typo

---

pkg/flag/report_flags.go

update compliance flag description
- Close #3159

fix: update compliance flag description

---

.github/CODEOWNERS

Add @AnaisUrlichs and @itaysk to owners of some documentation sections

chore: update codeowners for docs

---

.github/CODEOWNERS

chore: update code owners for misconfigurations

---

pkg/fanal/image/remote.go

Support OS wildcard for multi-arch images like `--platform */amd64`. If there are several OSes, it just picks up the first OS.

feat(image): support wildcard for platform os

---

pkg/fanal/analyzer/pkg/rpm/rpm.go

Add Rocky Linux for systemFiles detection.

fix(rocky): add rocky to osVendors

---

docs/ecosystem/cicd.md

docs: Adding Concourse resource for trivy

---

docs/tutorials/kubernetes/gitops.md

Fix typo in fluxcd
- Close #3266

docs: fix typo in fluxcd

---

docs/docs/sbom/supported.md
docs/docs/vulnerability/detection/language.md

add information about languages with support for dependency locations

docs: add information about languages with support for dependency locations

---

.github/workflows/roadmap.yaml

This action add issues to `roadmap` project and changes their  `Priority`.
```
'kind/feature' AND 'priority/backlog' labels -> 'Backlog' column
'kind/feature' AND 'priority/important-longterm' labels -> 'Important (long-term)' column
'kind/feature' AND 'priority/important-soon' labels -> 'Important (soon)' column
'kind/feature' AND 'priority/critical-urgent' labels -> 'Urgent' column
```
Example:

ci: add workflow to add issues to roadmap project

---

docs/docs/vulnerability/detection/os.md
pkg/detector/ospkg/alpine/alpine.go

Add support for Alpine 3.17
- Close #3317

feat: add support for Alpine 3.17

---

integration/testdata/centos-7-cyclonedx.json.golden
integration/testdata/fluentd-multiple-lockfiles-cyclonedx.json.golden
pkg/sbom/cyclonedx/marshal.go
pkg/sbom/cyclonedx/marshal_test.go

Added FixedVersion as a recommendation to BOV (Bill of Vulnerability).
- Close #2628

feat(cyclonedx): add recommendation

---

integration/integration_test.go

`spdx`: add sort for  Relationships.
`cyclonexd`: add sort for Properties.

test: fix integration tests for spdx and cycloneDX

---

docs/docs/references/troubleshooting.md

Fix a small spelling error in the documentation.
N/A

docs: fix spelling error

---

go.mod
go.sum
pkg/detector/ospkg/alma/alma.go
pkg/detector/ospkg/oracle/oracle.go
pkg/detector/ospkg/rocky/rocky.go

The Custom advisory details is forwarded to DetectedVulnerabilties Custom field
- Close #3443

feat(alma, rocky): Extended advisory data

---

integration/integration_test.go

The order is inconsistent now and it fails tests.
- Close https://github.com/aquasecurity/trivy/issues/3463

test(cyclonedx): sort cyclonedx components

---

pkg/fanal/image/daemon/containerd.go

Fix a potential temporary file leak in case of error during a containerd image inspection.

fix: Fix a temporary file leak in case of error

---

.github/DISCUSSION_TEMPLATE/show-and-tell.yml

adding show-and-tell template to GH discussions
Note: I am not sure if this is working as expected

docs: adding show-and-tell template to GH discussions

---

pkg/fanal/secret/scanner.go

change bytes to string method to optimize secret scanning memory usage
- Close #3452

perf(secret): optimize secret scanning memory usage

---

.golangci.yaml
pkg/fanal/analyzer/all/import.go
pkg/fanal/analyzer/config_analyzer.go
pkg/fanal/analyzer/const.go
pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
pkg/fanal/analyzer/imgconf/secret/secret.go
pkg/fanal/analyzer/imgconf/secret/secret_test.go
pkg/fanal/applier/applier.go
pkg/fanal/applier/applier_test.go
pkg/fanal/artifact/image/image.go
pkg/fanal/test/integration/library_test.go
pkg/fanal/types/artifact.go
pkg/scanner/local/scan.go

Trivy currently detects secrets on files in container images. This PR adds support for scanning container image config. `--image-config-scanners secret` enables this feature. It is especially useful to detect credentials in environmental variables.
This example scans files inside the container for vulnerabilities and container image config for secrets.
```
$ trivy image --scanners vuln --image-config-scanners secret vuln-image
```
<details>
<summary>Result</summary>
```
vuln-image (alpine 3.17.1)
==========================
vuln-image (secrets)
====================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 2)
CRITICAL: GitHub (github-pat)
═════════════════════════════════════════════════════════════════════════ …
```

feat(image): secret scanning on container image config

---

docs/docs/vulnerability/languages/java.md
mkdocs.yml

docs: add java vulnerability page

---

pkg/vulnerability/vulnerability.go

changed the constructor to accept interface.

refactor: db client changed

---

pkg/fanal/artifact/image/image.go

fix(image): close layer streams

---

pkg/fanal/image/remote.go

Check proxy settings from env for remote images
- Close #3592
- Close #3602

fix(image): check proxy settings from env for remote images

---

.github/workflows/semantic-pr.yaml

`action-semantic-pull-request` [added](https://github.com/amannn/action-semantic-pull-request/pull/226) regex suppor.
We need to quote pros in `c++`.

ci: quote pros in c++ for semantic pr

---

docs/docs/misconfiguration/policy/builtin.md

Update dockerfile link in misconfig section
- Close #3609

docs(misconf): update dockerfile link

---

pkg/javadb/client.go

- add update `maxCount `
- add sort by `groupID`

fix(java): fix groupID selection by ArtifactID for jar files.

---

Dockerfile

Fix CVE-2023-0286 currently part of the Container image

fix: Update to Alpine 3.17.2

---

go.mod
go.sum

adjust job name when node name exceed k8s label limit
- Close #3668

fix: k8s label size

---

docs/docs/misconfiguration/custom/index.md
docs/docs/misconfiguration/custom/schema.md
docs/docs/misconfiguration/policy/builtin.md
mkdocs.yml

Add documentation for defining custom input schemas.

docs(misconf): Add guide on input schema

---

go.mod
go.sum
pkg/fanal/analyzer/language/nodejs/pkg/pkg_test.go

feat(nodejs): add id for package.json files

---

docs/docs/advanced/plugins.md

The user asked to add the information about plugin archive to the documentation.
- Close #3715

docs: add information about plugin format

---

.github/workflows/scan.yaml

Bump `trivy-issue-action` to `v0.0.5`.
Skip `pkg` dir, because this dir currently contains a lot of test files.

chore(deps): bump trivy-issue-action to v0.0.5

---

docs/getting-started/faq.md
docs/index.md
docs/tutorials/kubernetes/cluster-scanning.md
mkdocs.yml

changing docs in accordance with the changes discussed with @giorod3 in #3460

docs: changing docs in accordance with #3460

---

docs/docs/misconfiguration/policy/builtin.md

docs(misconf): Fix links to built in policies

---

pkg/parallel/pipeline.go
pkg/parallel/pipeline_test.go
pkg/parallel/walk.go

Add a utility for concurrent processing
- Rewrite the PR with this utility

refactor: add pipeline for concurrent processing

---

docs/docs/misconfiguration/custom/selectors.md
mkdocs.yml

Add documentation on how to use selectors with policies.
- Close https://github.com/aquasecurity/defsec/issues/1201

docs(misconf): Add information about selectors

---

go.mod
go.sum

This PR is continuation of #3826.
More information [here](https://github.com/aquasecurity/go-dep-parser/pull/196).
- #3840

fix(nodejs): improvement logic for package-lock.json v2-v3

---

pkg/flag/db_flags.go

This PR fixes an incorrect comment in the `skip-update` flag.
- [ x I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.

docs: Update incorrect comment for skip-update flag

---

.github/workflows/reusable-release.yaml
.gitignore

Fix https://github.com/aquasecurity/trivy/actions/runs/4579418741/jobs/8087173033
- https://github.com/aquasecurity/trivy/pull/3612

chore: ignore gpg key

---

.github/workflows/reusable-release.yaml
.github/workflows/test.yaml
docs/getting-started/installation.md
goreleaser.yml

This reverts commit 67572dff6d089791726f5477bdb2d40332083ccb.

chore: Revert "ci: add gpg signing for RPM packages (#3612)"

---

docs/docs/vulnerability/examples/others.md

Improve glob usage documentation

docs(cli): Improve glob documentation

---

pkg/fanal/analyzer/secret/secret_test.go
pkg/fanal/analyzer/secret/testdata/config.yaml
pkg/fanal/analyzer/secret/testdata/skip-tests-config.yaml
pkg/fanal/secret/builtin-allow-rules.go
pkg/fanal/secret/scanner.go
pkg/fanal/secret/scanner_test.go
pkg/fanal/secret/testdata/allow-path.yaml
pkg/fanal/secret/testdata/allow-regex-outside-group.yaml
pkg/fanal/secret/testdata/allow-regex.yaml
pkg/fanal/secret/testdata/config-disable-allow-rule-md.yaml
pkg/fanal/secret/testdata/config-disable-rule1.yaml
pkg/fanal/secret/testdata/config-enable-ghp.yaml
pkg/fanal/secret/testdata/config-happy-keywords.yaml
pkg/fanal/secret/testdata/config-sad-keywords.yaml
pkg/fanal/secret/testdata/config-without-severity.yaml
pkg/fanal/secret/testdata/config.yaml
pkg/fanal/secret/testdata/exclude-block.yaml
pkg/fanal/secret/testdata/global-allow-regex.yaml
pkg/fanal/secret/testdata/global-exclude-block.yaml
pkg/fanal/secret/testdata/multiple-secret-groups.yaml
pkg/fanal/secret/testdata/skip-test.yaml

* fix built-in rule `tests` for skipping test files in the root folder
* add debug logs
- Close #3801

fix(secret): update built-in rule `tests` 

---

helm/trivy/templates/ingress.yaml

fix(helm): update networking API version detection

---

.github/workflows/test.yaml
aqua.yaml
go.mod
go.sum
integration/integration_test.go
integration/testdata/conda-spdx.json.golden
pkg/report/spdx/spdx.go
pkg/sbom/spdx/marshal.go
pkg/sbom/spdx/marshal_test.go
pkg/sbom/spdx/unmarshal.go
pkg/sbom/spdx/unmarshal_test.go
pkg/types/sbom.go

This PR updates spdx/tools-golang to v0.5.0.
- Close #4057

feat(spdx): add support for SPDX 2.3

---

docs/docs/references/configuration/cli/trivy_config.md
docs/docs/references/configuration/cli/trivy_filesystem.md
pkg/commands/app.go

add compliance report support for config and fs
- Close #3339 
usage :
```
trivy config ~/data/input.json   --compliance=@/Users/name/data/custom_spec.yaml --report summary
```
```
trivy fs ~/data/input.json   --compliance=@/Users/name/data/custom_spec.yaml --report all
```

feat: config and fs compliance support

---

pkg/k8s/scanner/scanner.go

fix: k8s quiet flag

---

pkg/cloud/aws/commands/run_test.go

Skip downloading of policies for tests

test: skip downloading of policies for tests

---

integration/testdata/conda-spdx.json.golden
pkg/sbom/cyclonedx/marshal.go
pkg/sbom/cyclonedx/marshal_test.go
pkg/sbom/spdx/marshal.go
pkg/sbom/spdx/marshal_test.go

feat(sbom): add supplier field

---

pkg/commands/artifact/wire_gen.go
pkg/detector/ospkg/detect.go
pkg/fanal/applier/applier.go
pkg/rpc/server/wire_gen.go
pkg/scanner/langpkg/scan.go
pkg/scanner/local/scan.go
pkg/scanner/local/scan_test.go
pkg/scanner/ospkg/scan.go

- Close https://github.com/aquasecurity/trivy/issues/3982
- https://github.com/aquasecurity/trivy/pull/3983

refactor: define vulnerability scanner interfaces

---

Dockerfile

https://alpinelinux.org/posts/Alpine-3.18.0-released.html

chore(alpine): Update Alpine to 3.18

---

docs/docs/references/configuration/cli/trivy_kubernetes.md
go.mod
go.sum
pkg/flag/kubernetes_flags.go
pkg/k8s/commands/cluster.go

node-collector custom namespace support
- Close #4371
usage:
```
trivy k8s cluster --report summary --node-collector-namespace trivy-local
```

feat: node-collector custom namespace support

---

docs/overrides/main.html
mkdocs.yml

Add a versioning banner on top to show if on an outdated version.
- Close #4359 

docs(cli): Add versioning banner

---

pkg/cache/remote.go

feat(cli): add retry to cache operations

---

pkg/commands/app.go

Group subcommands
```
$ trivy -h
...
Additional Commands:
aws         [EXPERIMENTAL] Scan AWS account
completion  Generate the autocompletion script for the specified shell
image       Scan a container image
config      Scan config files for misconfigurations
filesystem  Scan local filesystem
help        Help about any command
kubernetes  [EXPERIMENTAL] Scan kubernetes cluster
module      Manage modules
plugin      Manage plugins
repository  Scan a remote repository
rootfs      Scan rootfs
sbom        Scan SBOM for vulnerabilities
server      Server mode
version     Print the version
vm          [EXPERIMENTAL] Scan a virtual machine image
```
```
$ trivy -h
...
Scanning Commands
aws         [EXPERIMENTAL] Scan AWS account
config      Scan config files for misconfigurations
filesystem …
```

feat: group subcommands

---

docs/docs/scanner/vulnerability/language/index.md

We [switched](https://github.com/aquasecurity/trivy-db/pull/314) `GitLab Advisories Community` to `GitHub Advisory Database` for `Go`.
Update docs.

docs: switch glad to ghsa for Go

---

docs/getting-started/installation.md

docs: Update compilation instructions

---

pkg/compliance/spec/compliance_test.go
pkg/sbom/spdx/marshal_test.go

unnecessary use of fmt.Sprintf (S1039)

chore: unnecessary use of fmt.Sprintf (S1039)

---

go.mod
go.sum
integration/testdata/amazonlinux2-gp2-x86-vm.json.golden
integration/testdata/fixtures/db/amazon.yaml
integration/testdata/fixtures/db/ubuntu.yaml
integration/testdata/fixtures/db/vulnerability.yaml
integration/testdata/ubuntu-gp2-x86-vm.json.golden
integration/vm_test.go
internal/testutil/gzip.go
magefiles/fixture.go
magefiles/magefile.go

Update go-ext4-filesystem 
https://github.com/masahiro331/go-ext4-filesystem/pull/7
https://github.com/masahiro331/go-ext4-filesystem/pull/6

fix(vm): update ext4-filesystem parser for parse multi block extents

---

pkg/sbom/spdx/marshal.go

fix: format arg error

---

pkg/detector/ospkg/suse/suse.go

all dates are taken from https://www.suse.com/lifecycle#suse-linux-enterprise-server-15

feat(suse): add SUSE Linux Enterprise Server 15 SP5 and update SP4 eol date

---

.github/workflows/test.yaml

https://github.com/aquasecurity/trivy/pull/4614 didn't work well.

ci: do not trigger tests in main

---

go.mod
go.sum
pkg/k8s/scanner/scanner.go
pkg/k8s/scanner/scanner_test.go
pkg/sbom/cyclonedx/core/cyclonedx.go
pkg/sbom/cyclonedx/core/cyclonedx_test.go
pkg/sbom/cyclonedx/marshal.go

cyclonedx custom property support
- Close #4029

feat: cyclondx sbom custom property support

---

docs/docs/supply-chain/sbom.md
docs/docs/supply-chain/vex.md
go.mod
go.sum
integration/k8s_test.go
integration/testdata/conda-cyclonedx.json.golden
integration/testdata/fixtures/sbom/centos-7-cyclonedx.json
integration/testdata/fixtures/sbom/fluentd-multiple-lockfiles-cyclonedx.json
pkg/attestation/sbom/rekor_test.go
pkg/fanal/analyzer/sbom/testdata/cdx.json
pkg/fanal/artifact/image/testdata/cyclonedx.json
pkg/fanal/artifact/sbom/testdata/bom.json
pkg/fanal/artifact/sbom/testdata/os-only-bom.json
pkg/k8s/scanner/scanner.go
pkg/k8s/scanner/scanner_test.go
pkg/rekortest/server.go
pkg/sbom/cyclonedx/core/cyclonedx_test.go
pkg/sbom/cyclonedx/marshal_test.go
pkg/sbom/cyclonedx/testdata/happy/bom.json
pkg/sbom/cyclonedx/testdata/happy/empty-bom.json
pkg/sbom/cyclonedx/testdata/happy/empty-metadata-component-bom.json
pkg/sbom/cyclonedx/testdata/happy/group-in-name.json
pkg/sbom/cyclonedx/testdata/happy/independent-library-bom.json
pkg/sbom/cyclonedx/testdata/happy/infinite-loop-bom.json
pkg/sbom/cyclonedx/testdata/happy/os-only-bom.json
pkg/sbom/cyclonedx/testdata/happy/third-party-bom-no-os.json
pkg/sbom/cyclonedx/testdata/happy/third-party-bom.json
pkg/sbom/cyclonedx/testdata/happy/unrelated-bom.json
pkg/sbom/cyclonedx/testdata/sad/invalid-purl.json
pkg/vex/testdata/cyclonedx.json

- Related #4029
- Close #4709 
```
{
"$schema": "http://cyclonedx.org/schema/bom-1.5.schema.json",
"bomFormat": "CycloneDX",
"specVersion": "1.5",
"serialNumber": "urn:uuid:049ea19f-edbc-478f-a39d-a84c2d7d63ff",
"version": 1,
"metadata": {
"timestamp": "2023-06-25T05:46:22+00:00",
"tools": [
{
"vendor": "aquasecurity",
"name": "trivy",
"version": "dev"
}
],
"component": {
"bom-ref": "d2e2a084-a854-40df-84dc-1a7a6f523030",
"type": "platform",
"name": "kind-kind",
"properties": []
}
},
"components": [
{
"bom-ref": "000ff0c6-9aa5-4592-a3c2-a10eacfc037d",
"type": "operating-system",
"name": "ubuntu",
"version": "21.04",
"properties": [
{
"name": "aquasecurity:trivy:Class",
"value": "os-pkgs"
},
{
"name": "aquasecurity:trivy:Type",
"value": "ubuntu"
}
]
},
{
"bom-ref": …
```

feat: kbom and cyclonedx v1.5 spec support

---

pkg/detector/ospkg/amazon/amazon.go

https://aws.amazon.com/jp/blogs/aws/update-on-amazon-linux-ami-end-of-life/

fix: update Amazon Linux 1 EOL

---

.github/DISCUSSION_TEMPLATE/bugs.yml

Fix documentation.
- Close https://github.com/aquasecurity/trivy/issues/4589

fix: documentation about reseting trivy image

---

docs/tutorials/kubernetes/cluster-scanning.md

docs: correcting the trivy k8s tutorial

---

go.mod
go.sum

fix: remove trivy-db package replacement

---

docs/tutorials/additional-resources/community.md

adding a blog post to resource list

docs: adding blog post on ec2

---

docs/docs/scanner/vulnerability.md

docs: vulnerability typo

---

Dockerfile.protoc

PR Title: Optimize Dockerfile for Efficiency and Size
What this PR does / why we need it:
Optimizes the Dockerfile to reduce the number of layers, improve efficiency, and decrease the overall image size.
Special notes for reviewer:
The main changes involve grouping related commands and cleaning up after installations to reduce image size.
Details:
Combined related commands to reduce Docker layers.
Grouped the installation of tools and libraries into a single RUN command.
Cleaned up the apt cache and removed unnecessary files post-installation.
Combined environment variable declarations for clarity.
How to test this PR:
Build the Docker image using the updated Dockerfile.
Run the container and ensure all functionalities are working as expected.
Screenshots:
N/A
Additional context:
This …

perf: Optimize Dockerfile for reduced layers and size

---

docs/docs/configuration/filtering.md

I have added an extra "-" in " "--ignore-status" it was previously "-ignore-status"
- Close #5129

docs: typo error in filtering.md

---

docs/ecosystem/ide.md

This PR is to add an AWS CDK Construct Library to Ecosystem.
- Close #XXX

docs: add image-scanner-with-trivy for ecosystem

---

go.mod
go.sum

bump trivy-kubernetes-latest
- Close #5160 

chore: bump trivy-kubernetes-latest

---

.github/workflows/auto-update-labels.yaml
magefiles/magefile.go

Auto apply labels, when the [labels.yaml](https://github.com/aquasecurity/trivy/blob/daae88287b033e583fec1496a0661970166917d4/misc/triage/labels.yaml) is updated.
Test run - https://github.com/DmitriyLewen/trivy/actions/runs/6218787900/job/16875761369#step:5:38
- Close #5199

ci: auto apply labels

---

docs/docs/coverage/language/nodejs.md

Added information that Trivy supports scanning in projects with the Yarn package manager

docs: update info about license scanning in Yarn projects

---

docs/ecosystem/ide.md

mange -> manage.
Fix small typo on `docs/` folder.

fix: typo on `ide.md`

---

docs/docs/scanner/secret.md

Changed `simbols` to `symbols`
- [✓] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [✓] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [n/a] I've added usage information (if the PR introduces new options)
- [n/a] I've included a "before" and "after" example to the description (if the PR is a user interface change).

docs: typo in secret.md

---

docs/ecosystem/cicd.md

Found the plugin mentioned here https://jaosorior.dev/2022/trivy-security-scanning-in-buildkite/ by 
Equinix Metal

docs: add buildkite repository to ecosystem page

---

.github/DISCUSSION_TEMPLATE/adopters.yml

small changes to make the experience frictionless: reorder fields, emphasize optional fields, simplify labels, etc.

chore: update adopters template

---

docs/getting-started/installation.md

As is the title.
- N/A
- N/A
-----
Thank you.

docs(misconf): fix broken table for `Use container image` section

---

pkg/detector/ospkg/amazon/amazon.go

Remove an unused field
- Close #XXX

chore: remove unused logger attribute in amazon detector

---

docs/ecosystem/prod.md

Hi all,
Trivy has been integrated into Zora, as described in [this discussion](https://github.com/aquasecurity/trivy/discussions/5489) and I would like to include this integration in documentation.

docs: add Zora integration into Ecosystem session

---

docs/docs/target/kubernetes.md

docs(k8s): fix link in kubernetes.md

---

integration/k8s_test.go
pkg/k8s/scanner/scanner.go

Fail to fetch node name on k8s resource scanning 
- Close #5528

fix: fail k8s resource scanning

---

pkg/fanal/test/integration/containerd_test.go

Containerd tests are unstable: https://github.com/aquasecurity/trivy/actions/runs/6866661287/job/18673348185#step:5:1405
This PR changes the containerd setup to retries connecting to `containerd.sock` several times until it's ready.
- https://github.com/aquasecurity/trivy/pull/5546

test: retry containerd initialization

---

docs/docs/scanner/vulnerability.md

docs(vuln): fix link anchor

---

.github/DISCUSSION_TEMPLATE/adopters.yml

Based on the conversation with Itay adding two fields to the adopters discussion template

docs: update adopters discussion template

---

pkg/k8s/report/report.go
pkg/k8s/scanner/scanner.go

filter k8s core components vuln results
- Close #5675

feat: filter k8s core components vuln results

---

contrib/gitlab.tpl
integration/testdata/alpine-310.gitlab.golden
pkg/report/template.go
pkg/report/template_test.go
pkg/report/writer.go

Update Gitlab [Container Scanning](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscontainer_scanning) template from version 14 to 15, compatible with Gitlab 16.
Discussion #4235
Some information: Gitlab has different reports:
- [Codequality](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscodequality)
- [Schema](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types), [Reference in Gitlab docs](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool)
- The [template in this repo](https://github.com/aquasecurity/trivy/blob/main/contrib/gitlab-codequality.tpl) works with Gitlab 16
- [Container Scanning](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscontainer …

fix(report): update Gitlab template

---

docs/docs/configuration/filtering.md

improve documentation of `--ignore-policy`
- Close https://github.com/aquasecurity/trivy/issues/3486
I think this can replace https://github.com/aquasecurity/trivy/pull/4455

docs: improve filter by rego

---

docs/ecosystem/miscellaneous.md

This PR updates the `ecosystem/misc.` documentation to include a new additional reference to a community-supported streamlit-based UI to view Trivy reports.
N/A

docs: ✨ Updated ecosystem docs with reference to new community app

---

docs/community/contribute/discussion.md

docs: update link to data sources

---

docs/community/governance.md
mkdocs.yml

Define core principles.
- Close https://github.com/aquasecurity/trivy/issues/6091

docs: add governance

---

docs/community/principles.md
mkdocs.yml

Reflect feeback
- https://github.com/aquasecurity/trivy/pull/6090

docs: rename governance to principles

---

docs/docs/target/sbom.md

update kbom distribution for scanning
-  #5988

docs: update kbom distribution for scanning

---

docs/getting-started/installation.md

Added install instruction for FreeBSD where trivy is now also available as a package.

docs: Added install instructions for FreeBSD

---

pkg/iac/adapters/terraform/aws/s3/adapt_test.go
pkg/iac/adapters/terraform/aws/s3/bucket.go

Added checking that one of the possible encryption algorithms is being used.
- Close https://github.com/aquasecurity/trivy/issues/5212

fix(terraform): сhecking SSE encryption algorithm validity

---

docs/docs/coverage/iac/index.md

docs(terraform): add file patterns for Terraform Plan

---

pkg/iac/adapters/cloudformation/aws/elasticsearch/domain.go
pkg/iac/adapters/cloudformation/aws/elasticsearch/elasticsearch_test.go

- Close https://github.com/aquasecurity/trivy/issues/6423

fix(cloudformation): resolve `DedicatedMasterEnabled` parsing issue

---

docs/docs/target/container_image.md
docs/docs/target/kubernetes.md

docs(k8s,image): fix command-line syntax issues

---

pkg/dependency/parser/java/pom/parse.go

fix: close pom.xml

---

integration/testdata/fixtures/sbom/minikube-kbom.json
pkg/sbom/io/decode.go

This PR shows a warning message for multiple OSes in SBOM rather than returning an error. It's a kind of workaround that allows KBOM scanning to be done successfully.
```
$ trivy sbom ./sbom-k8s-cluster.json
2024-04-23T10:49:22+04:00       INFO    Vulnerability scanning is enabled
2024-04-23T10:49:22+04:00       INFO    Detected SBOM format    format="cyclonedx-json"
2024-04-23T10:49:22+04:00       FATAL   Fatal error     sbom scan error: scan error: scan failed: failed analysis: SBOM decode error: failed to decode: failed to decode components: multiple OS components are not supported
```
```
$ trivy sbom ./sbom-k8s-cluster.json
2024-04-23T11:06:41+04:00       INFO    Vulnerability scanning is enabled
2024-04-23T11:06:41+04:00       INFO    Detected SBOM format    format="cyclonedx-json" …
```

fix(sbom): change error to warning for multiple OSes

---

pkg/plugin/plugin.go

fix: close plugin.yaml

---

docs/docs/target/container_image.md

docs: fix usage of image-config-scanners

---

pkg/iac/terraform/schema.go

- Close https://github.com/aquasecurity/trivy/issues/6644

feat(misconf): add Terraform 'removed' block to schema

---

pkg/iac/debug/cgo_disabled.go
pkg/iac/debug/cgo_enabled.go
pkg/iac/debug/debug.go

Removes some unnecessary code.

chore(misconf): Clean up iac logger

---

examples/module/spring4shell/spring4shell.go
pkg/module/module.go
pkg/module/serialize/types.go

The details in https://github.com/aquasecurity/trivy/issues/6654
- Close https://github.com/aquasecurity/trivy/issues/6654

refactor: re-define module structs for serialization

---

pkg/fanal/analyzer/imgconf/apk/apk.go

fix: close APKINDEX archive file

---

.golangci.yaml

simplify gosec rules exclusion

ci(deps): simplify gosec rules exclusion

---

pkg/iac/adapters/terraform/aws/ec2/vpc.go
pkg/iac/adapters/terraform/aws/ec2/vpc_test.go

- Close https://github.com/aquasecurity/trivy/issues/6764

feat(misconf): support for VPC resources for inbound/outbound rules

---

pkg/fanal/test/integration/docker/docker.go

fix: close testfile

---

pkg/fanal/applier/docker.go
pkg/fanal/applier/docker_test.go

Replace https://github.com/aquasecurity/trivy/pull/5844 and https://github.com/aquasecurity/trivy/pull/6682
- Close https://github.com/aquasecurity/trivy/issues/5857
- #5844 
- #6682

fix(debian): take installed files from the origin layer

---

pkg/iac/rego/metadata.go
pkg/iac/rego/metadata_test.go

Related issue: https://github.com/aquasecurity/trivy/issues/6930

fix(misconf): fix parsing of engine links and frameworks

---

.github/actions/trivy-triage/helpers.js
.github/actions/trivy-triage/helpers.test.js

auto labeling workflow incorrectly handled discussions categories other than "ideas". fixed and added tests
- https://github.com/aquasecurity/trivy/pull/5259

ci: correctly handle categories

---

docs/docs/coverage/language/golang.md
docs/docs/scanner/vulnerability.md
docs/docs/supply-chain/sbom.md

clarified non-packaged software section & documented sbom detection in container images

docs: non-packaged and sbom clarifications

---

pkg/fanal/analyzer/analyzer.go
pkg/fanal/analyzer/analyzer_test.go
pkg/fanal/analyzer/fs.go

refactor(fs): remove unused field for CompositeFS

---

pkg/rpc/server/server.go

- Close https://github.com/aquasecurity/trivy/issues/7202

fix(server): pass license categories to options

---

pkg/fanal/secret/builtin-rules.go

This PR added rule severity fields for export.

feat: share build-in rules

---

pkg/sbom/core/bom.go
pkg/sbom/cyclonedx/marshal_test.go
pkg/sbom/io/encode.go
pkg/sbom/io/encode_test.go
pkg/sbom/spdx/marshal_test.go

Add image labels into:
- [metadata.component.properties](https://cyclonedx.org/docs/1.6/json/#metadata_component_properties) for `CycloneDX` reports.
- [Packages.PackageAttributionTexts](https://spdx.github.io/spdx-spec/v2.3/package-information/#723-package-attribution-text-field) for `SPDX` reports.
examples:
```json
"component": {
"bom-ref": "934bb60f-fb6b-4cb5-8b4b-30ca2c2a1b86",
"type": "container",
"name": "test",
"properties": [
{
"name": "aquasecurity:trivy:DiffID",
"value": "sha256:9110f7b5208f035f4d4f99b5169338169e1df9bb2519d1b047f50f54430bacc2"
},
{
"name": "aquasecurity:trivy:ImageID",
"value": "sha256:6e29a990365e345fad58f36b8a317ebf4197450175619961bb5675395eec48af"
},
{
"name": "aquasecurity:trivy:Labels:vendor",
"value": "aquasecurity"
},
{
"name": …
```

feat(sbom): add image labels into `SPDX` and `CycloneDX` reports

---

docs/ecosystem/reporting.md

Documentation update: ecosystem page reporting with plopsec.com app

docs: update ecosystem page reporting with plopsec.com app

---

pkg/iac/adapters/cloudformation/aws/s3/bucket.go
pkg/iac/adapters/cloudformation/aws/s3/s3_test.go
pkg/iac/adapters/terraform/aws/s3/adapt_test.go
pkg/iac/adapters/terraform/aws/s3/bucket.go
pkg/iac/providers/aws/s3/bucket.go
pkg/iac/rego/schemas/cloud.json

- https://github.com/aquasecurity/trivy/issues/7239

feat(misconf): support for policy and bucket grants

---

pkg/purl/purl.go

refactor: replace ftypes.Gradle with packageurl.TypeGradle

---

docs/docs/configuration/filtering.md
docs/docs/coverage/iac/cloudformation.md
docs/docs/coverage/iac/helm.md
docs/docs/coverage/iac/terraform.md
docs/docs/scanner/misconfiguration/custom/debug.md
docs/docs/scanner/misconfiguration/custom/index.md
docs/docs/scanner/misconfiguration/index.md
docs/tutorials/misconfiguration/terraform.md

Updates a few more areas which got missed last time.

docs(misconf): Update callsites to use correct naming

---

pkg/iac/rego/embed.go
pkg/iac/rego/embed_test.go

- Close https://github.com/aquasecurity/trivy/issues/6929

feat(misconf): ignore duplicate checks

---

docs/docs/references/configuration/config-file.md
magefiles/docs.go

Add pkg flags to [config file page](https://aquasecurity.github.io/trivy/dev/docs/references/configuration/config-file/#report-options).
- Close #7369

docs: add pkg flags to config file page

---

pkg/iac/rego/embed.go

fix(misconf): do not register Rego libs in checks registry

---

pkg/iac/rego/scanner.go

Partially addresses: https://github.com/aquasecurity/trivy/issues/6138

fix(misconf): Fix logging typo

---

pkg/fanal/image/registry/azure/azure.go

- Close https://github.com/aquasecurity/trivy/issues/7562

fix(misconf): Fixed scope for China Cloud

---

go.mod
go.sum

With a clean Go cache, builds fails with :
```
$ go mod tidy
go: github.com/aquasecurity/trivy/pkg/rekor imports
github.com/sigstore/rekor/pkg/client imports
github.com/sigstore/rekor/pkg/util imports
github.com/sigstore/sigstore/pkg/signature imports
github.com/sigstore/sigstore/pkg/cryptoutils imports
github.com/letsencrypt/boulder/goodkey tested by
github.com/letsencrypt/boulder/goodkey.test imports
github.com/letsencrypt/boulder/web imports
github.com/letsencrypt/boulder/log imports
github.com/jmhodges/clock: github.com/openvex/discovery@v0.1.1-0.20240802171711-7c54efc57553 (replaced by github.com/knqyf263/discovery@v0.1.1-0.20240726113521-97873005fd03): version "v0.1.1-0.20240726113521-97873005fd03" invalid: unknown revision 97873005fd03
...
go: github.com/aquasecurity/trivy/pkg/vex …
```

chore(deps): remove broken replaces for opa and discovery

---

.github/workflows/test.yaml

Add `workflow_dispatch` trigger to add ability to run tests on command.

ci: add `workflow_dispatch` trigger for test workflow.

---

docs/docs/references/configuration/cli/trivy_config.md
docs/docs/references/configuration/cli/trivy_filesystem.md
docs/docs/references/configuration/cli/trivy_image.md
docs/docs/references/configuration/cli/trivy_kubernetes.md
docs/docs/references/configuration/cli/trivy_repository.md
docs/docs/references/configuration/cli/trivy_rootfs.md
docs/docs/references/configuration/config-file.md
pkg/flag/rego_flags.go

Disable deprecated checks by default

fix(misconf): Disable deprecated checks by default

---

pkg/javadb/client.go

fix(db): fix javadb downloading error handling

---

docs/docs/configuration/reporting.md

SARIF is not only for GitHub.
- added link to SARIF 2.1.0 spec
- added link to SonarQube import
- see #7644

docs(report): Improve SARIF reporting doc

---

.golangci.yaml
integration/registry_test.go
pkg/dependency/parser/java/pom/parse.go
pkg/iac/adapters/terraform/aws/apigateway/adapt_test.go
pkg/iac/adapters/terraform/aws/apigateway/apiv1_test.go

enable and fixes [usestdlibvars](https://golangci-lint.run/usage/linters/#usestdlibvars) linter

fix: enable usestdlibvars linter

---

docs/getting-started/installation.md

Windows install instructions are lacked. Please add Windows install instructions.

docs: add Windows install instructions

---

.github/workflows/test.yaml
.golangci.yaml
magefiles/magefile.go
pkg/fanal/walker/walk_test.go
pkg/plugin/index.go

chore: bump golangci-lint to v1.61.0

---

integration/integration_test.go

UIIC `spdx-spec` renamed branches for `2.3.X` and `3.X.Y` versions.
They use `support/2.X` format now - https://github.com/spdx/spdx-spec?tab=readme-ov-file#branch-structure

test: change branch in spdx schema link to check in integration tests

---

go.mod
go.sum

Bump up trivy-checks to v1.3.0

chore(deps): Bump up trivy-checks to v1.3.0

---

go.mod
go.sum

chore(deps): Upgrade trivy-checks

---

pkg/dependency/parser/nodejs/npm/parse.go
pkg/dependency/parser/nodejs/npm/parse_test.go
pkg/dependency/parser/nodejs/npm/parse_testcase.go
pkg/dependency/parser/nodejs/npm/testdata/package-lock_v3_with_peer.json

Respect peer dependencies for the dependency tree when the package manager lists them in its lock file.
- Close https://github.com/aquasecurity/trivy/issues/7988

feat(nodejs): respect peer dependencies for dependency tree

---

.vex/trivy.openvex.json

govulncheck confirmed it is not affected.
- Close https://github.com/aquasecurity/trivy/issues/8100

chore(vex): suppress CVE-2024-45337

---

.github/workflows/auto-update-labels.yaml
.github/workflows/reusable-release.yaml
.github/workflows/test.yaml
.golangci.yaml
Dockerfile.protoc
aqua.yaml
go.mod

chore: bump go to 1.23.4

---

pkg/fanal/analyzer/language/python/pipenv/pipenv.go
pkg/fanal/analyzer/os/amazonlinux/amazonlinux.go
pkg/fanal/analyzer/os/debian/debian.go
pkg/fanal/analyzer/os/redhatbase/alma.go
pkg/fanal/analyzer/os/redhatbase/centos.go
pkg/fanal/analyzer/os/redhatbase/fedora.go
pkg/fanal/analyzer/os/redhatbase/oracle.go
pkg/fanal/analyzer/os/redhatbase/redhatbase.go
pkg/fanal/analyzer/os/redhatbase/rocky.go
pkg/fanal/analyzer/pkg/rpm/rpm.go
pkg/fanal/utils/utils.go

refactor: use slices package instead of custom function

---

contrib/junit.tpl
docs/docs/configuration/reporting.md

Adding a section for "Secrets" when scanning with `trivy image --scanners secret <image>` and using the JUnit output format `--format template --template @contrib/junit.tpl`
For a default output:
```
localhost/vulnerable:latest (secrets)
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 1)
CRITICAL: GitLab (gitlab-pat)
═══════════════════════════════════════════════════════════════════════════════
GitLab Personal Access Token
────────────────────────────────────────────────────────
localhost/vulnerable:latest:298
────────────────────────────────────────────────────────
296     {
297     "created": "2024-12-03T16:24:59Z",
298 [ by": "|3 GITLAB_PRIVATE_TOKEN=************************** WA-
299     "comment": "FROM f43dd38a5350" …
```

chore(secret): add reported issues related to secrets in junit template

---

pkg/fanal/analyzer/analyzer_test.go
pkg/iac/adapters/terraform/aws/redshift/adapt_test.go

chore: remove debug prints

---

.golangci.yaml
magefiles/magefile.go

chore: remove mockery

---

docs/docs/supply-chain/vex/index.md

docs: update VEX documentation index page

---

go.mod
go.sum

remove missed replace of `trivy-db`

chore(deps): remove missed replace of `trivy-db`

---

go.mod
pkg/iac/providers/aws/ec2/instance.go

These methods were only used in Go checks, so they are no longer needed

refactor(misconf): remove unused methods for ec2.Instance

---

README.md

https://github.com/aquasecurity/trivy/discussions/8544

docs: fix a broken link

---

docs/docs/coverage/language/python.md

More detailed README for Python.

docs(python): Mention pip-compile

---

README.md
mkdocs.yml

since we don't monitor slack anymore, remove it from recommended resources. (but it remains active)
- #8524

docs: remove slack

---

pkg/iac/rego/store.go
pkg/iac/rego/store_test.go

fix(misconf): do not skip loading documents from subdirectories

---

docs/community/maintainer/release-flow.md

Adds info about helm charts release

docs: Add info about helm charts release

---

docs/community/maintainer/release-flow.md

Adds info about upgrading dependencies prior to releasing.

docs: Update maintainer docs

---

pkg/iac/scanners/terraform/parser/evaluator.go
pkg/iac/scanners/terraform/parser/parser.go
pkg/iac/scanners/terraform/parser/parser_test.go
pkg/iac/terraform/attribute.go
pkg/iac/terraform/presets.go

See issue description
- Close https://github.com/aquasecurity/trivy/issues/8685

fix(misconf): add missing variable as unknown

---

pkg/iac/scanners/terraform/parser/evaluator.go
pkg/iac/scanners/terraform/parser/parser_test.go

This PR is an extension of this https://github.com/aquasecurity/trivy/pull/8555 and adds correct context populating for module instances.

fix(misconf): populate context correctly for module instances

---

.golangci.yaml
pkg/fanal/image/daemon/podman_test.go
pkg/iac/adapters/arm/storage/adapt_test.go
pkg/iac/detection/detect_test.go
pkg/iac/scanners/azure/arm/parser/armjson/parse_array_test.go
pkg/iac/scanners/terraform/parser/parser_test.go
pkg/iac/scanners/terraform/parser/resolvers/registry_test.go
pkg/k8s/report/report_test.go
pkg/k8s/scanner/scanner_test.go

- fixes testifylint last issues

fix: testifylint last issues

---

pkg/iac/providers/google/dns/dns.go
pkg/iac/types/int.go
pkg/iac/types/string.go
pkg/iac/types/string_test.go

refactor(misconf): remove unused methods from iac types

---

.golangci.yaml
cmd/trivy/main.go
go.mod
magefiles/fixture.go
magefiles/magefile.go
pkg/dependency/parser/nodejs/pnpm/parse.go
pkg/fanal/secret/scanner.go
pkg/flag/options.go
pkg/iac/scanners/azure/arm/parser/armjson/unmarshal.go
pkg/iac/scanners/cloudformation/parser/property.go
pkg/iac/scanners/helm/scanner.go
pkg/parallel/pipeline.go
pkg/parallel/walk.go
pkg/report/table/licensing.go
pkg/report/table/misconfig.go
pkg/report/table/secret.go
pkg/report/table/summary.go
pkg/report/table/vulnerability.go

Enables more rules from revive:
-  [bool-literal-in-expr](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#bool-literal-in-expr)
-  [context-as-argument](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#context-as-argument)
-  [duplicated-imports](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#duplicated-imports)
-  [if-return](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#if-return)
-  [increment-decrement](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#increment-decrement)
-  [range](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#range)
-  [range-val-address](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#range-val-address)
- …

fix: more revive rules

---

pkg/k8s/scanner/scanner.go

By default, k8s cluster scans use the FS cache, which stores the data in bbolt. Trivy scans all artifacts in the cluster for misconfigurations at a time, which can result in a large `BlobInfo` size stored in the cache, and exceed the maximum size of ~256MB. This PR uses the in-memory cache when scanning for misconfigurations in the k8s cluster.
- Close https://github.com/aquasecurity/trivy/issues/8542
```bash
❯ trivy k8s kind-vuln-cluster --cache-dir $(pwd)/cache -d --timeout 2h --disable-node-collector --scanners=misconfig --report=all --format json --output report.json
2025-05-14T16:42:24+06:00       DEBUG   Default config file "file_path=trivy.yaml" not found, using built in values
2025-05-14T16:42:24+06:00       DEBUG   Cache dir …
```

fix(k8s): use in-memory cache backend during misconfig scanning

---

go.mod

This PR bumps up Go version to 1.24.4 to fix some vulnerabilities.
Before:
```sh
$ go build -o trivy ./cmd/trivy/main.go &&  docker build -f Dockerfile -t trivy:dev .
$ trivy i trivy:dev 
2025-06-12T12:37:31+06:00       INFO    [vuln] Vulnerability scanning is enabled
2025-06-12T12:37:31+06:00       INFO    [secret] Secret scanning is enabled
2025-06-12T12:37:31+06:00       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-06-12T12:37:31+06:00       INFO    [secret] Please see also https://trivy.dev/v0.63/docs/scanner/secret#recommendation for faster secret detection
2025-06-12T12:37:33+06:00       INFO    Detected OS     family="alpine" version="3.21.3"
2025-06-12T12:37:33+06:00       INFO    [alpine] Detecting vulnerabilities... …
```

chore: bump up Go version to 1.24.4

---

pkg/iac/adapters/arm/adaptertest/adaptertest.go
pkg/iac/adapters/arm/appservice/adapt_test.go
pkg/iac/adapters/arm/authorization/adapt_test.go
pkg/iac/adapters/arm/compute/adapt_test.go
pkg/iac/adapters/arm/database/adapt_test.go
pkg/iac/adapters/arm/database/firewall.go
pkg/iac/adapters/arm/database/mssql.go
pkg/iac/adapters/arm/datafactory/adapt.go
pkg/iac/adapters/arm/datafactory/adapt_test.go
pkg/iac/adapters/arm/datalake/adapt.go
pkg/iac/adapters/arm/datalake/adapt_test.go
pkg/iac/adapters/arm/keyvault/adapt_test.go
pkg/iac/adapters/arm/monitor/adapt.go
pkg/iac/adapters/arm/monitor/adapt_test.go
pkg/iac/adapters/arm/network/adapt_test.go
pkg/iac/adapters/arm/securitycenter/adapt.go
pkg/iac/adapters/arm/securitycenter/adapt_test.go
pkg/iac/adapters/arm/storage/adapt_test.go
pkg/iac/adapters/arm/synapse/adapt_test.go

This PR extends the test coverage of the `iac/adapters/arm` package without affecting the adaptation logic. TODOs have been added in some places for further refinement in future PRs.
Additionally, the testing approach has been changed for consistency with other packages: instead of manually creating `azure.Deployment` structures, ARM templates in JSON format are now used. These templates are parsed by the ARM parser and serve as input data for the tests. This approach improves test readability, simplifies maintenance, and enables more realistic testing using actual templates.

test: improve and extend tests for iac/adapters/arm

---

docs/docs/scanner/misconfiguration/custom/data.md

https://github.com/aquasecurity/trivy-checks/pull/391#issuecomment-3014149423

docs: add section on customizing default check data

---

pkg/iac/adapters/arm/storage/adapt.go
pkg/iac/adapters/arm/storage/adapt_test.go
pkg/iac/scanners/azure/value.go

- Close https://github.com/aquasecurity/trivy/issues/9137

fix(misconf): correctly adapt azure storage account

---

pkg/module/module.go
pkg/notification/response.go

fix some function names in comment
- Close #XXX

chore: fix some function names in comment

---

pkg/fanal/handler/sysfile/filter.go

make `NewSystemFileFilteringPostHandler` function exported.

refactor: export `systemFileFiltering` Post Handler

---

pkg/iac/scanners/terraform/parser/resolvers/remote.go

refactor(misconf): use atomic.Int32

---

pkg/commands/artifact/run.go

This PR improves secret scanner log messages: previously the recommendation to disable it for better performance was shown even when only the secret scanner was enabled; now it appears only if multiple scanners are enabled, and the suggested `--scanners` flag reflects the current set of scanners instead of always using `vuln`.
Before:
```bash
❯ trivy fs --scanners secret,vuln,misconf test
...
2025-08-29T17:06:28+06:00       INFO    [secret] Secret scanning is enabled
2025-08-29T17:06:28+06:00       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-08-29T17:06:28+06:00       INFO    [secret] Please see also https://trivy.dev/v0.65/docs/scanner/secret#recommendation for faster secret detection
❯ trivy fs --scanners secret test …
```

refactor(secret): clarify secret scanner messages

---

docs/docs/advanced/modules.md
pkg/module/serialize/types.go

A minor fix on the modules page.

docs: fix modules path and update code example

---

docs/docs/scanner/misconfiguration/custom/index.md
docs/docs/scanner/misconfiguration/index.md

Improves documentation for scanning raw IaC configurations by clarifying how checks are defined, scanner requirements, and report output.

docs: improve documentation for scanning raw IaC configurations
