aquasecurity/trivy

- cmd/remic/main.go
- pkg/remic/run.go
- pkg/scanner/library/scan.go
- pkg/scanner/scan.go
- exit-code
- skip-update
- ignore-unfixed
Supports file reading with relative path.
Add remic release option.
> Add options for remic

- pkg/scanner/scan.go
I think this is a forgot fix of the commit.
https://github.com/knqyf263/trivy/commit/9a67f0d1a77dd77ffdbe233a175572df2af018f1
Could you delete warn message, if --clear-cache option true.
> Fix warn message use latest-image 

- README.md
- go.mod
- go.sum
- pkg/scanner/library/node/advisory.go
- pkg/scanner/library/node/scan.go
- pkg/scanner/library/scan.go
- merge npm and yarn to node scanner
- support yarn.lock
```
2019-05-16T10:14:06.623+0900    INFO    Resetting DB...
2019-05-16T10:14:06.646+0900    WARN    You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2019-05-16T10:14:09.255+0900    INFO    Detecting Alpine vulnerabilities...
2019-05-16T10:14:09.256+0900    INFO    Updating yarn Security DB...
2019-05-16T10:14:11.209+0900    INFO    Detecting yarn vulnerabilities...
asia.gcr.io/bizvoice-app-stg/api-streaming:latest (alpine 3.9.0)
================================================================
yarn.lock
=========
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0) …
```
> check yarn.lock in node scanner

- cmd/trivy/main.go
- pkg/db/db.go
- pkg/run.go
- pkg/utils/utils.go
The flag cache-dir allows users to specify the cache directory the
database is stored in.  If the flag value is not set, try to use the users cache directory or a temp directory.
Fixes #10 
Signed-off-by: Ken Herner <kherner@navistone.com>
> Allow user specified cache directory

- README.md
So it is a bit cleaner and the main file is not that cluttered.
> Suggest putting the apt source in its own file

- pkg/scanner/ospkg/scan.go
show os.Family if an unsupported OS
```
FATAL   error in image scan: failed to scan image: unsupported os : fedora
```
> show scanned os.Family if unsupported

- pkg/run.go
- fix: quiet flag doesn't work when refreshing database.
- fix: show error message "try again with --refresh..."  if set refresh flag
> fix quiet bug

- README.md
- pkg/report/writer.go
Fix #16 
Example
```
[
{
"Target": "php-app/composer.lock",
"Vulnerabilities": null
},
{
"Target": "node-app/package-lock.json",
"Vulnerabilities": [
{
"VulnerabilityID": "CVE-2018-16487",
"PkgName": "lodash",
"InstalledVersion": "4.17.4",
"FixedVersion": "\u003e=4.17.11",
"Title": "lodash: Prototype pollution in utilities function",
"Description": "A prototype pollution vulnerability was found in lodash \u003c4.17.11 where the functions merge, mergeWith, and defaultsDeep can be tricked into adding or modifying properties of Object.prototype.",
"Severity": "HIGH",
"References": [
"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16487",
]
}
]
},
{
"Target": "trivy-ci-test (alpine 3.7.1)",
"Vulnerabilities": [
{
"VulnerabilityID": "CVE-2018-16840",
"PkgName": "curl", …
```
> Update JSON schema

- pkg/run.go
Now, If pass an unknown format, it will panic.
> fix: unknown format case

- pkg/run.go
- The cache does not work if an error occurs after the initial database update.
> fixed cache bug

- pkg/git/git.go
add --depth option to git clone.
before:
```
$ time git clone https://github.com/knqyf263/vuln-list
Cloning into 'vuln-list'...
remote: Enumerating objects: 32220, done.
remote: Counting objects: 100% (32220/32220), done.
remote: Compressing objects: 100% (20546/20546), done.
remote: Total 505602 (delta 29307), reused 12089 (delta 11664), pack-reused 473382
Receiving objects: 100% (505602/505602), 183.02 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (476710/476710), done.
Checking out files: 100% (270908/270908), done.
git clone https://github.com/knqyf263/vuln-list  38.15s user 59.75s system 46% cpu 3:29.36 total
```
after:
```
$ time git clone --depth=1 https://github.com/knqyf263/vuln-list
Cloning into 'vuln-list'...
remote: Enumerating objects: 275059, done.
remote: Counting objects: …
```
> feat: add --depth option to git clone

- README.md
You don't need to tap a repo to install from it with Homebrew it seems. Homebrew will automatically tap it with `brew install`:
```
❯ brew install knqyf263/trivy/trivy
Updating Homebrew...
....
Cloning into '/usr/local/Homebrew/Library/Taps/knqyf263/homebrew-trivy'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Tapped 1 formula (27 files, 23.5KB).
==> Installing trivy from knqyf263/trivy
```
> Simpler Homebrew install instructions

- README.md
- cmd/trivy/main.go
- pkg/run.go
- pkg/scanner/ospkg/alpine/alpine.go
- pkg/vulnsrc/vulnerability/const.go
- pkg/vulnsrc/vulnsrc.go
Added `--only-update` option. use this option, we can update vulnerability database only that we are specified distributions.
If we are creating an docker image based on one distribution (for example, use only alpine image), it is too much to update all DBs. therefore we necessary to wait to update for long time.
> Added --only-update option

- README.md
- go.mod
- go.sum
- pkg/scanner/scan.go
- pkg/types/dockerConf.go
This feature for CI jobs.
https://github.com/knqyf263/trivy/issues/45
- self-hosted registry test
```
$ docker run --rm --entrypoint htpasswd registry:latest -Bbn hoge hoge > /path/to/auth/htpasswd
$ docker run -d -p 80:80 -e REGISTRY_HTTP_ADDR=0.0.0.0:80 \
-e REGISTRY_AUTH=htpasswd \
-e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
-e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
-v /path/to/auth:/auth registry:latest
$ docker login localhost
Username: hoge
Password
```
> auth for private docker registry from ENV vars

- pkg/scanner/ospkg/debian/debian.go
- pkg/scanner/ospkg/redhat/redhat.go
- pkg/scanner/ospkg/ubuntu/ubuntu.go
```
09:18 $ trivy -f json -o scan.json -debug jcowey/vs-coder
2019-05-31T09:21:40.852+0100	DEBUG	cache dir:  /Users/jcowey/Library/Caches/trivy
2019-05-31T09:21:40.852+0100	DEBUG	db path: /Users/jcowey/Library/Caches/trivy/db/trivy.db
2019-05-31T09:21:40.861+0100	INFO	Updating vulnerability database...
2019-05-31T09:21:40.861+0100	DEBUG	git pull
2019-05-31T09:21:41.671+0100	DEBUG	total updated files: 1
2019-05-31T09:21:41.709+0100	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2019-05-31T09:21:51.016+0100	DEBUG	OS family: ubuntu, OS version: 18.04
2019-05-31T09:21:51.018+0100	DEBUG	the number of packages: 176
2019-05-31T09:21:51.018+0100	DEBUG	the number of packages from commands: 0 …
```
> Fix debug log

- pkg/scanner/library/bundler/advisory.go
- pkg/scanner/library/composer/advisory.go
Close https://github.com/knqyf263/trivy/issues/85
GHSA (new vulnerability ID): 
https://github.com/rubysec/ruby-advisory-db/blob/master/gems/yard/GHSA-xfhh-rx56-rxcr.yml
No CVE-ID:
https://github.com/FriendsOfPHP/security-advisories/blob/f8537ec2e4573a5be2154b31803e46fec1826668/ezsystems/ezplatform-admin-ui/CVE-2019-12139.yaml
> Support unusual YAML

- README.md
Added a `lsb_release -c` to [Installation](https://github.com/akerge/trivy#debianubuntu).
> Add code snippet reminder on how to print distribution codename

- Dockerfile
lzma looks better than the default compression algorithm
```
Step 8/13 : RUN upx --lzma --best /trivy
---> Running in 1f23fb026681
Ultimate Packer for eXecutables
Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018
File size         Ratio      Format      Name
--------------------   ------   -----------   -----------
26868298 ->  10301860   38.34%   linux/amd64   trivy
Packed 1 file.
```
close #95
> [docker] Compress binary using upx

- cmd/trivy/main.go
- pkg/log/logger.go
- pkg/run.go
- pkg/scanner/ospkg/alpine/alpine_test.go
- pkg/scanner/ospkg/debian/debian_test.go
- pkg/scanner/ospkg/redhat/redhat_test.go
- pkg/scanner/ospkg/ubuntu/ubnutu_test.go
- pkg/utils/utils_test.go
ref.) https://github.com/aquasecurity/trivy/issues/106
Disable log output when `--quiet` flag is on.
Also, add new flag `--no-progress` to disable only progress bar (same feature implemented as `--quiet` previously).
> Suppress log output when --quiet flag is on

- pkg/scanner/library/bundler/advisory.go
- pkg/scanner/library/cargo/advisory.go
- pkg/scanner/library/composer/advisory.go
- pkg/scanner/library/node/advisory.go
- pkg/scanner/library/python/advisory.go
The path of the cache directory used when detecting application vulnerabilities is the always current directory.
```
$ ls 
$ trivy -debug trivy-ci-test:1.0       
2019-08-23T16:37:14.705+0900	DEBUG	cache dir:  /Users/masahiro331/Library/Caches/trivy
2019-08-23T16:37:14.706+0900	DEBUG	db path: /Users/01025026/Library/Caches/trivy/db/trivy.db
2019-08-23T16:37:14.709+0900	INFO	Updating vulnerability database...
2019-08-23T16:37:14.709+0900	DEBUG	git pull
2019-08-23T16:37:15.758+0900	DEBUG	total updated files: 1
2019-08-23T16:37:15.951+0900	DEBUG	Vulnerability type:  [os library]
2019-08-23T16:37:16.061+0900	DEBUG	OS family: alpine, OS version: 3.7.1
2019-08-23T16:37:16.062+0900	DEBUG	the number of packages: 65
2019-08-23T16:37:16.659+0900	DEBUG	the number of packages from commands: 83 …
```
> Fix bug. always application vulnerabilities list make in current directory.

- Dockerfile
ADD doesn't save cache so it's better to use `COPY` except when you download something from URL.
> use COPY on dockerfile rather than add

- ci/deploy-rpm.sh
Close https://github.com/aquasecurity/trivy/issues/137
[trivy-repo](https://github.com/aquasecurity/trivy-repo) which provides rpm repository supports only RHEL/CentOS 6/7. This PR adds RHEL8 support to rpm repository.
> Add the RHEL8 support to rpm repository

- cmd/trivy/main.go
Hi.
Trivy cache dir is changed by `--cache-dir` option.
But image cache is not changed and stored in /path/to/cache/fanal ( /path/to/cache/ = os.UserCacheDir() ).
So, I changed `--cache-dir` option usage comment.
If we want to change image cache dir too, we need to fix [aquasecurity/fanal/utils/utils.go - CacheDir](https://github.com/aquasecurity/fanal/blob/master/utils/utils.go#L14).
> Modify cache-dir usage comment

- cmd/trivy/main.go
- pkg/report/writer.go
- pkg/run.go
Adds a new output format "template" with a new command line argument to specify a template for the report.
trivy -t "{{ range . }}{{ range .Vulnerabilities}}{{ println .Severity }}{{ end }}{{ end }}" -f json -q rabbitmq:3-management
> Add template writer

- Dockerfile
Trivy depends on `rpm` command, but the image doesn't contain `rpm`.
https://github.com/aquasecurity/trivy/issues/146
> Add rpm to the trivy image

- pkg/git/git.go
- pkg/scanner/library/bundler/advisory.go
- pkg/scanner/library/cargo/advisory.go
- pkg/scanner/library/composer/advisory.go
- pkg/scanner/library/node/advisory.go
- pkg/utils/utils.go
In several files, the error passed from `filepath.Walk` to `WalkFunc` is not checked (see issue #207). As the `info` argument to WalkFn is `nil` in case of an error, accessing `info` can cause a runtime panic.
This commit adds checks for errors passed to WalkFunc.
Other solutions, like checking `info` for `nil` might be possible, too, but `err` should be handled in some way.
> Check errors passed through by filepath.Walk

- cmd/trivy/main.go
- pkg/run.go
- pkg/vulnsrc/vulnerability/vulnerability.go
this changes handling of specify ignorefile
- I want to scan many container images on one working space
- my situation is want Trivy on 1 pod to scan some container images
- but, the whitelist(.trivyignore) of each container image was less common vulnerabilities to ignore
- In other words, each image has a different vulnerability that want Trivy to ignore.
- However, Trivy could not specify ignore file
- Add Flag "--ignorefile value" in main.go to use as specific ignorefile
- modify pkg/vulnsrc/vulnerability/vulnerability.go, FillAndFilter()
- pass specific ignorefile string to FillAndFilter() as argument
- modify pkg/vulnsrc/vulnerability/vulnerability.go, getIgnoreIDs()
- pass specific ignorefile to getIgnoredIDs() as argument only when specified ignorefile
- pass default(.trivyignore) …
> Changed to be able to specify IgnoreFile as whitelist

- pkg/db/db.go
- pkg/db/db_mock.go
- pkg/git/git.go
- pkg/run.go
- pkg/vulnsrc/vulnsrc_test.go
Trivy uses the app version as the database schema version. When the app version is updated, an entire update of the database is forced. This is for DB migration, but the DB schema hardly changes.
This PR separates the app version and the DB version. It makes it possible to update the app version without forcing the entire update of the database.
Before:
|     | version |
|-----|---------|
| app | v0.1.6  |
| db  | v0.1.6  |
After:
|     | version |
|-----|---------|
| app | v0.1.6  |
| db  | v1  |
> fix(db): introduce db schema version

- .circleci/config.yml
the CI step that runs gofmt doesn't echo out a string
so it causes the step to fail before emitting the "gofmt"
errors that need to be fixed
> add echo to CI gofmt step

- pkg/scanner/library/bundler/scan.go
- pkg/scanner/library/bundler/scan_test.go
the rubygems version includes "platform" within the version
and it gets pulled into version.Version as a pre-release
value.
this means that in the case of something like "ffi",
1.9.25-java is not counted correctly as matching
">= 1.9.25".
Closes #108
> massage rubygems version to handle platforms

- README.md
- pkg/app.go
- pkg/run.go
Many Continuous Integration systems in companies use ephemeral workers
that may run more than one Trivy job. In those cases, downloading the
vulnerability database from the beginning time and again is a waste of
resources.
With this flag, we can download the database on worker creation
offsetting most of the download time on each job. execution
References: #109
---
When the `--download-db-only` flag is supplied, we will just download
the vulnerability database and exit without performing any scans.
If a database had been downloaded before the present run, and
`--only-update` option has been specified, we will only update the
database for the selected distribution and exit.
Add section to README on usage limitations of the new flag.
> Add option to only download vulnerability database

- pkg/db/db.go
- pkg/db/db_test.go
- pkg/run.go
`--skip-update` cannot be specified:
- First run
- Old DB version
- Different DB type (full vs light)
> fix(skip-update): prohibit --skip-update in some situations

- README.md
- pkg/app.go
v0.2.0 changed an behavior of `--clear-cache`.
Close https://github.com/aquasecurity/trivy/issues/273
> chore(clear-cache): add an explanation

- internal/standalone/config/config.go
```
$ ./trivy　--download-db-only               
2019-12-09T14:10:05.246+0900    ERROR   trivy requires at least 1 argument or --input option
```
> Fix DonwloadDBOnly conduct strategy.

- pkg/report/writer.go
- pkg/report/writer_test.go
- pkg/scanner/scan.go
This would result in an empty query:
```./trivy -f template -t "{{ range . }} {{ .Target }} {{ end }}" -q alpine:3.10```
instead of showing
```alpine:3.10 (alpine 3.10.3)```
> fix(writer): Refactor results struct

- go.mod
- go.sum
- internal/app.go
- internal/client/inject.go
- internal/client/run.go
- internal/client/wire_gen.go
- internal/operation/operation.go
- internal/server/run.go
- internal/standalone/inject.go
- internal/standalone/run.go
- internal/standalone/wire_gen.go
- pkg/scanner/scan.go
This PR enables Trivy to specify a directory to store image cache. Also, this fixes the problem of deadlock in integration tests. BoltDB can't be opened from multiple processes, but the DB path is fixed now. The multiple tests access BoltDB in parallel, and it causes a deadlock. If we can specify different paths, it can be avoided.
Related: https://github.com/aquasecurity/fanal/pull/62
Close: https://github.com/aquasecurity/trivy/issues/157
> fix(cache): specify a directory to store image cache

- integration/docker_engine_test.go
Close https://github.com/aquasecurity/trivy/issues/351
> fix(integration-test): use a snapshot database for Docker mode

- goreleaser.yml
According to https://goreleaser.com/deprecations/#nfpms-name-template, the name_template field was deprecated.
> chore(goreleaser): change name_template to file_name_template

- README.md
I noticed that there is a typo in example of `.gitlab-ci.yml` on `README.md`, and fixed it.
> Fix typo in example of .gitlab-ci.yml

- contrib/gitlab.tpl
While a template for [GitLab Container Scanning Report](https://docs.gitlab.com/ee/user/application_security/container_scanning/) was introduced in #367, the template should be modified to comply with GitLab Container Scanning Report as of 2020-01 (GitLab EE 
12.7).
```
git checkout fix-template-for-gitlab-integration
trivy --format template --template "@contrib/gitlab.tpl" alpine:3.9
```
- https://gitlab.com/tnir/trivy-ci-test/-/jobs/414069581
🚀 🚀 🚀 
Successfully parsed by GitLab Container Scanning report parser
Closes #386
> Modify template for GitLab Container Scanning

- Dockerfile
- goreleaser.yml
If we use the docker image in the GitLab CI (and not download/install trivy in a GitLab Job), we have to download the template and integrate it into our repository. 
To simplify this, I modified the project to include the file into the `/@contrib` folder. So, the line from the GitLab example can be used to do a GitLab analysis with Trivy. 
```yaml
🔎 ui:
stage: 🔎 Security Analysis
image:
name: aquasec/trivy
entrypoint: [""]
script:
- trivy --exit-code 0 --no-progress --format template --template "@.ci/gitlab-trivy.tpl" -o gl-container-scanning-report.json podcastserver/ui:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
artifacts:
reports:
container_scanning: gl-container-scanning-report.json
```
This PR could be integrated into #376 & #387 
/cc @neonox31
> feat(): include GitLab template inside the docker container

- contrib/Trivy.gitlab-ci.yml
Adds GitLab CI template with deep integration with GitLab Container Scanning (report) (part of GitLab Security Product)
cf. https://gitlab.com/gitlab-org/gitlab/blob/f156adcec4c48d304128f2a4a8987f9ad6408591/lib/gitlab/ci/templates/Security/Container-Scanning.gitlab-ci.yml
> contrib: Add GitLab CI template to deeply integrated with GitLab Container Scanning

- internal/standalone/config/config.go
- internal/standalone/config/config_test.go
to avoid `--template` is silently ignored when `--format <table|json>` or no `--format` is passed.
Closes #390 #394
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> cli: append warning when --template option is ignored

- integration/testdata/centos-6.json.golden
- integration/testdata/centos-7-critical.json.golden
- integration/testdata/centos-7-ignore-unfixed.json.golden
- integration/testdata/centos-7.json.golden
- pkg/detector/ospkg/redhat/redhat.go
- pkg/detector/ospkg/redhat/redhat_test.go
Red Hat OVAL provides only binary package names having vulnerabilities. Trivy uses source package names to detect vulnerabilities. This is because Red Hat Security Data API provides only source package names having vulnerabilities. Now, Trivy uses both data source, so we need to use binary package names for OVAL and source package names for Security Data API. Most source package has the same name in binary packages like this.
- Source Package: openssl
- Binary Packages: 
- **openssl**
- openssl-debuginfo
- openssl-perl
- etc.
There is no problem in this case. But it sometimes doesn't have the same name.
- Source Package: vim
- Binary Packages: 
- vim-common
- vim-enhanced
- vim-minimal
- etc.
In this case, Trivy queries `vim` to OVAL DB to get security advisories, but DB doesn't have such …
> fix(redhat): use binary package name for OVAL

- contrib/gitlab.tpl
https://aquasecurity.gitlab.io/-/trivy-ci-test/-/jobs/440937099/artifacts/gl-container-scanning-report.json is not a valid JSON. This PR fixes the JSON template for GitLab security report.
Address the problem on https://github.com/aquasecurity/trivy-ci-test/pull/7#issuecomment-587354942
> fix(gitlab): fix json template on loop

- goreleaser.yml
`containers/storage` doesn't support FreeBSD and OpenBSD. It appears to be difficult to fix it shortly. Let me drop BSD support once. We don't have so many BSD users.
The following is binary names and download counts from GitHub Releases.
```
curl https://api.github.com/repos/aquasecurity/trivy/releases | jq -c '.[].assets[] | .name, .download_count' | xargs -n 2 | grep -i bsd
trivy_0.4.4_FreeBSD-32bit.tar.gz 0
trivy_0.4.4_FreeBSD-64bit.tar.gz 0
trivy_0.4.4_FreeBSD-ARM.tar.gz 0
trivy_0.4.4_OpenBSD-32bit.tar.gz 0
trivy_0.4.4_OpenBSD-64bit.tar.gz 0
trivy_0.4.4_OpenBSD-ARM.tar.gz 0
trivy_0.4.3_FreeBSD-32bit.tar.gz 0
trivy_0.4.3_FreeBSD-64bit.tar.gz 0
trivy_0.4.3_FreeBSD-ARM.tar.gz 0
trivy_0.4.3_OpenBSD-32bit.tar.gz 0
trivy_0.4.3_OpenBSD-64bit.tar.gz 1
trivy_0.4.3_OpenBSD-ARM.tar.gz 0
...
```
> chore(goreleaser): drop BSD support temporarily

- go.mod
- go.sum
Close https://github.com/aquasecurity/trivy/issues/426
> fix(rpm): make it possible to scan non-RHEL images without rpm

- ci/Dockerfile
- ci/deploy-deb.sh
This PR makes it possible to fetch all supported versions automatically using `debian-distro-info` and `ubuntu-distro-info`
Close https://github.com/aquasecurity/trivy/issues/444
Related: https://github.com/aquasecurity/trivy-repo/pull/3
> feat(release): fetch all supported versions automatically

- README.md
After trying to run trivy using CircleCI based on the sample configuration and failing, I want to suggest the following updates:
* `docker:18.09-git` no longer exists and causes workflow to fail, replaced with `stable-git` instead.
* added  `setup_remote_docker` or else the docker commands fail in the rest of the execution, as per https://circleci.com/docs/2.0/building-docker-images/#overview
> Fix CircleCI example in README.md

- .circleci/config.yml
Fixes: https://github.com/aquasecurity/trivy/issues/457
The Docker documentation recommends piping the registry password through STDIN when logging in with `docker login` non-interactively. This is for security reasons:
> To run the docker login command non-interactively, you can set the --password-stdin flag to provide a password through STDIN. Using STDIN prevents the password from ending up in the shell’s history, or log-files.
Source: [Provide a password using STDIN](https://docs.docker.com/engine/reference/commandline/login/#provide-a-password-using-stdin)
However, the trivy CI doesn't make use of this yet:
https://github.com/aquasecurity/trivy/blob/e5ff5ec89542bda37b744f4cbc24bc267e72fccd/.circleci/config.yml#L45-L47
This PR changes the `docker login` command.
> improve: using STDIN for docker login command

- integration/client_server_test.go
- integration/testdata/alpine-310.gitlab.golden
- internal/standalone/run.go
- pkg/report/writer.go
Currently client/server mode is broken for using custom templates. 
This adds a test and fixes the issue.
> rpc: Fix output to use templates when in client server mode.

- .circleci/config.yml
- .github/workflows/test.yaml
- go.mod
- go.sum
- integration/client_server_test.go
- integration/docker_engine_test.go
- integration/standalone_test.go
- internal/standalone/run.go
- pkg/rpc/server/server_test.go
`gunzipDB` copies a database file to the temporal directory every time. It consumes a lot of disk spaces even if the file is removed by `defer os.RemoveAll(cacheDir)`. This is because the test process is still running, so the removed file can't be seen, but exists until the test process finishes.
ref. https://access.redhat.com/solutions/2316
After all, it reaches the capacity of disk and returns the error "no space left on device". This PR changed tests so that the database file can be copied only once.
> chore(ci): move integration tests to GitHub Actions

- README.md
`</details>` was in the wrong place.
> chore(doc): update README

- go.mod
- go.sum
- integration/client_server_test.go
- internal/app.go
- internal/client/config/config.go
- internal/client/config/config_test.go
- internal/client/run.go
- internal/server/config/config.go
- internal/server/config/config_test.go
- internal/server/run.go
- internal/standalone/config/config.go
- internal/standalone/config/config_test.go
- internal/standalone/run.go
bump up github.com/urfave/cli to v2
> chore: bump up urfave/cli to v2

- README.md
Add GitHub Actions and AWS CodePipeline to CI section of Readme
Correct a broken link to "Data sources"
> docs: add more CI options to README

- contrib/junit.tpl
- pkg/report/writer.go
- pkg/report/writer_test.go
[Issue](https://github.com/aquasecurity/trivy/issues/549)
* Failure and Title should be escaped before exporting to template
> Added function to escape string in failure message title and descriptions

- Dockerfile
- goreleaser.yml
Adding junit.tpl to docker image for easy of use during CI/CD pipelines
> Adding contrib/junit.tpl to docker image

- pkg/report/writer.go
When `--format` is set to something different than `template` trivy is printing a warning:
`WARN	--template is ignored because --format json is specified. Use --template option with --format template option.`
But after report is generated it fails with error:
`FATAL	unable to write results: Error retrieving template from path: open contrib/junit.tpl: no such file or directory`
Seems that checking for `outputTemplate` is happening too soon and should only be done when `--format` is `template`
> Fixing `Error retrieving template from path` when --format is not template but template is provided

- Dockerfile
- README.md
- contrib/sarif.tpl
- integration/client_server_test.go
- integration/testdata/alpine-310.sarif.golden
- pkg/report/writer.go
- pkg/report/writer_test.go
[Issue](https://github.com/aquasecurity/trivy/issues/547)
> Added sarif template

- go.mod
- go.sum
- pkg/detector/library/bundler/advisory.go
- pkg/detector/library/bundler/advisory_test.go
- pkg/detector/library/cargo/advisory.go
- pkg/detector/library/composer/advisory.go
- pkg/detector/library/detect.go
- pkg/detector/library/driver.go
- pkg/detector/library/ghsa/advisory.go
- pkg/detector/library/node/advisory.go
- pkg/detector/library/python/advisory.go
- pkg/scanner/utils/utils.go
- pkg/scanner/utils/utils_test.go
[Issue](https://github.com/aquasecurity/trivy/issues/108)
* Improved version checking and added tests
> improve ruby comparison version check.

- pkg/scanner/utils/utils.go
- pkg/scanner/utils/utils_test.go
Tests added to cover scenarios when version contains pre-release in minor or patch version
> Fixed case when pre-release is in suffix

- internal/artifact/run.go
- internal/client/run.go
[Issue](https://github.com/aquasecurity/trivy/issues/568)
> Fix --timeout flag

- Dockerfile
[Issue](https://github.com/aquasecurity/trivy/issues/519)
> Run trivy docker image runs as a non root user 

- README.md
Homebrew can be used on Linux and Windows Subsystem for Linux (WSL)
https://docs.brew.sh/Homebrew-on-Linux
I didn't know, but GoReleaser already supports Homebrew on Linux as well as macOS. It means Trivy also supports it transparently.
https://github.com/aquasecurity/homebrew-trivy/blob/master/trivy.rb
> Mention Homebrew on Linux in README

- .circleci/codecov.yml
- .circleci/config.yml
- .gitignore
- Makefile
- README.md
This adds code coverage to each PR we create.
Addresses: https://github.com/aquasecurity/trivy/issues/563
> ci: Add code coverage

- contrib/sarif.tpl
- integration/testdata/alpine-310.sarif.golden
- pkg/report/writer.go
- pkg/report/writer_test.go
Unescaped strings like https://gist.github.com/simar7/da144ed1d9b6d53f5c9af1e9282a3e68#file-gistfile1-txt-L81-L84 in output SARIF results in invalid SARIF file, this PR will fix the case
> Added template fucntion to escape string before output

- README.md
> Fix comparison table to use words instead of symbols

- README.md
- internal/app.go
- internal/artifact/run.go
- internal/config/artifact.go
- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
- pkg/types/scanoptions.go
Fix https://github.com/aquasecurity/trivy/issues/282
Fix https://github.com/aquasecurity/trivy/issues/366
Fix https://github.com/aquasecurity/trivy/issues/244
```
$ trivy image --vuln-type library fluent/fluentd:edge
2020-08-11T11:26:26.939+0300    INFO     Detecting bundler vulnerabilities...
2020-08-11T11:26:26.942+0300    INFO     Detecting bundler vulnerabilities...
usr/lib/ruby/gems/2.5.0/gems/async-http-0.50.7/examples/fetch/Gemfile.lock
==========================================================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
+---------+------------------+----------+-------------------+---------------+--------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |             TITLE …
```
> feat: add --skip-directories option

- contrib/sarif.tpl
- pkg/report/writer_test.go
[Issue](https://github.com/aquasecurity/trivy/issues/604)
> Fix: fullDescription field in SARIF output is not correctly escaped

- Dockerfile
Before this change, only a subset of templates were included in the docker image.
Now all templates which are part of the git repo will be included when the docker image will be build, a future commit for every new template is not needed anymore
Fixes #618
> Add all templates to the docker image

- README.md
This improves the installation step in `.gitlab-ci.yml`. 
- Removes unnecessary installation and use of `curl` (replaces it with `wget`)
- Removes storing the intermediate file by using a pipe to `tar`
- Rename `VERSION` to `TRIVY_VERSION`, to circumvent ambiguities in case there's other version variables in the CI configuration
> Improve Gitlab CI installation step in README

- README.md
- Convert "Good" to "Not bad" (we converted △ to "Good" for clarification, but I originally meant "not so good, not so bad".)
- Remove MicroScanner
- Convert "Not present" to "Not good" in DockerHub
https://github.com/aquasecurity/trivy/pull/587#issuecomment-684447331
> chore(docs): update comparison table

- .circleci/config.yml
- goreleaser.yml
Docker has new rate limits on image pulls, so it is better to push our official image to GitHub Container Registry as well.
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/
https://github.blog/2020-09-01-introducing-github-container-registry/
https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images
> chore(image): push the official image to GitHub Container Registry as well

- goreleaser.yml
Fixes: https://github.com/aquasecurity/trivy/issues/631
> goreleaser.yml: Add all templates to archive

- internal/config/artifact.go
Before
```
$ trivy image
NAME:
trivy - A simple and comprehensive vulnerability scanner for containers
USAGE:
trivy command [command options] target
COMMANDS:
image, i          scan an image
filesystem, fs    scan local filesystem
repository, repo  scan remote repository
client, c         client mode
server, s         server mode
help, h           Shows a list of commands or help for one command
OPTIONS:
--quiet, -q        suppress progress bar and log output (default: false) [$TRIVY_QUIET]
--debug, -d        debug mode (default: false) [$TRIVY_DEBUG]
--cache-dir value  cache directory (default: "/Users/teppei/Library/Caches/trivy") [$TRIVY_CACHE_DIR]
--help, -h         show help (default: false)
--version, -v      print the version (default: false)
```
After
```
$ trivy image
NAME:
trivy …
```
> fix(cli): show help for subcommands

- pkg/rpc/server/listen.go
Closes #534
```shell
$ curl http://127.0.0.1:4954/healthz 
ok
$ curl http://127.0.0.1:4954/healthz -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 4954 (#0)
> GET /healthz HTTP/1.1
> Host: 127.0.0.1:4954
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 20 Sep 2020 03:11:57 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
ok
```
> Add health check endpoint to trivy server

- .github/workflows/test.yaml
- ci/Dockerfile
- go.mod
- goreleaser.yml
darwin/386 is no longer supported.
https://golang.org/doc/go1.15#darwin
> chore: bump up Go to 1.15

- README.md
Closes #406 
This MR includes links to the Trivy CI Test repo and Gitlab CI pipelines
> add link to Gitlab CI pipeline in README

- README.md
Updates readme's Q&A section to add about running trivy on multiple images in parallel taking same time as a series run. 
Fixes #650 .
> update readme for parallel run issue

- pkg/detector/ospkg/suse/suse.go
All synced with https://www.suse.com/lifecycle/ as of today
Signed-off-by: Dirk Mueller <dirk@dmllr.de>
Signed-off-by: Dirk Mueller <dmueller@suse.com>
> suse: update end of life dates for SLES service packs

- ci/deploy-deb.sh
The deploy script removes all packages once and adds new packages only for supported versions. `stretch` recently reached EOL and this script removed a package for `stretch`. We should keep packages even for EOL versions. This PR changes the script to remove only packages of supported versions.
Ref. https://github.com/aquasecurity/trivy/issues/689
> fix(ci/deb): do not remove old packages for EOL versions

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
In this template, for the sections, I suggest to use H2 instead of bold
Details: https://github.com/aquasecurity/trivy/issues/711
> Update BUG_REPORT.md using H2

- pkg/detector/ospkg/redhat/redhat.go
- pkg/detector/ospkg/redhat/redhat_test.go
This PR adds a capability of skipping specific RPM packages (RedHat or CentOS) during the scan based on pre-defined patterns.
Currently only the `remi` repository is listed as unsupported.
Resolves #649.
> Skip packages from unsupported repository (remi)

- contrib/install.sh
- goreleaser.yml
Add binary building for the ppc64le (Power) architecture.
> Add support for ppc64le architecture

- goreleaser.yml
Reverts 7fc94ad95c920289e35a2dcc9e3df289918055a4
Fixes https://github.com/aquasecurity/trivy/issues/725
`goreleaser release --skip-publish --skip-validate --rm-dist` ran successfully
Feel free to close if this needs to be run by a maintainer 
cc @knqyf263
> Add back support for FreeBSD & OpenBSD

- pkg/detector/ospkg/suse/suse.go
without that you get this arning:
WARN	This OS version is not on the EOL list: suse linux enterprise server 15.2
which is actually misleading because 15.2 is the most current release,
we just don't know when it ends. we can however assume that it runs
for at least another year.
Signed-off-by: Dirk Mueller <dirk@dmllr.de>
Signed-off-by: Dirk Mueller <dmueller@suse.com>
> Add suse sles 15.2 to the EOL list as well

- pkg/detector/ospkg/oracle/oracle.go
- pkg/detector/ospkg/oracle/oracle_test.go
- pkg/detector/ospkg/oracle/testdata/fixtures/invalid-type.yaml
- pkg/detector/ospkg/oracle/testdata/fixtures/oracle7.yaml
`ksplice` is for zero-downtime updates and it doesn't seem to be used in a container image.
https://ksplice.oracle.com/
There are two patches for the same vulnerability.
1. Normal patch
2. Zero-downtime patch
They have different versioning. You can see the following advisories. The first one is the normal patch, while the second one is the zero-downtime patch.
1. https://linux.oracle.com/errata/ELSA-2019-2304.html
2. https://linux.oracle.com/errata/ELSA-2019-4754.html
If a package is installed without `ksplice` patch, we should not use `ksplice` advisories for vulnerability detection because they have different versioning and it causes false positives. This PR skips `ksplice` advisories when the installed package is not a `ksplice` package. Also, if the package is a `ksplice` one, we …
> fix(oracle): handle ksplice advisories

- README.md
Since trivy is only in the unstable (rolling release) channels ([nix channels info](https://nixos.wiki/wiki/Nix_channels)) at the moment I don't mind waiting until the `21.03` release but since that will be in March 2021 that's quite a long time to wait.
If required I can also look at getting trivy backported into `20.09` but I think most nix users are used to using unstable for the odd package.
> chore(docs): add nix install

- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
You can now specify redis as caching as backend.
The default is still the filesystem.
In case redis is added as caching backend, the cache-dir is still
used for the vulnerability database.
Fixes #781
> Add redis cache backend configuration options

- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
> Added nodeSelector, affinity and tolerations to helm chart

- internal/operation/operation.go
As suggested by the go-redis client, parse the url to get the config.
This will fix problems, when the url contains a username and/or password.
Fixes #798
> Parse redis backend url

- pkg/github/github.go
Changed the output string to "Using your github token".
> #813 "Use your github token" output is confusing to the user

- go.mod
- go.sum
- pkg/detector/library/node/compare_test.go
- pkg/detector/library/python/advisory.go
- pkg/detector/library/python/advisory_test.go
- pkg/detector/library/python/compare.go
- pkg/detector/library/python/compare_test.go
Python defines a scheme for identifying versions of Python software distributions in PEP 440.
https://www.python.org/dev/peps/pep-0440/
This PR replaces go-version with [go-pep440-version](https://github.com/aquasecurity/go-pep440-version) so that Trivy can align with the definition.
> fix(python): follow PEP 440

- pkg/detector/ospkg/amazon/amazon.go
- pkg/detector/ospkg/amazon/amazon_test.go
- pkg/detector/ospkg/debian/debian.go
- pkg/detector/ospkg/debian/debian_test.go
- pkg/detector/ospkg/redhat/redhat.go
- pkg/detector/ospkg/redhat/redhat_test.go
- [Amazon Linux](https://aws.amazon.com/jp/blogs/aws/update-on-amazon-linux-ami-end-of-life/)
- [Debian](https://wiki.debian.org/LTS)
- [CentOS 8](https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule)
> fix(eol): update EOL dates

- README.md
- go.mod
- go.sum
This PR enables Trivy to scan images in Podman (>=2.0) running locally. The remote Podman is not supported.
The podman.sock systemd service must be enabled on a machine.
```
$ systemctl --user enable --now podman.socket
$ podman images
REPOSITORY                TAG     IMAGE ID      CREATED      SIZE
localhost/test            latest  ed1b0762d815  3 weeks ago  5.85 MB
$ trivy image localhost/test
```
https://github.com/aquasecurity/fanal/pull/149
> feat: support Podman

- README.md
Hi, I was adding `trivy` instead of a broken built in GitLab for my use case `clair`, and made it work a simpler way than you describe it in `README`. This job takes ~15 sec given the image is cached.
Please correct me if I'm wrong somewhere.
> README: add Gitlab job that uses a container with trivy

- contrib/junit.tpl
- pkg/report/writer_test.go
Jenkins xunit plugin expects compatibility to the [Surefire](http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd) or Ant XML schema, this provides the two missing attributes for Surefire.
> Fix compatibility for Jenkins xunit plugin

- README.md
Ubuntu releases the latest version every 6 months. If they are regular releases, they are supported only for 9 months. It's hard to manage supported versions in README. This PR obsoletes the specific version list.
> docs(README): update ubuntu versions

- .github/workflows/publish-chart.yaml
- .gitignore
- docs/installation.md
- helm/trivy/README.md
Related https://github.com/aquasecurity/trivy/issues/839, 
- GH action to publish helm chart in the aqua repository helm chart
Using the Aqua chart repository:
helm repo add aquasecurity https://aquasecurity.github.io/helm-charts/
helm repo update
helm search repo trivy
helm install my-trivy aquasecurity/trivy
> feat: publish helm repository

- .github/workflows/stale-issues.yaml
Bot for stale issues and PR that they doesn't have the labels awaiting-approval,work-in-progress,priority/*
- days-before-stale: 90
- days-before-close: 20. We have time to validate the bot results before close it.
- Use labels  'no-pr-activity',  'no-issue-activity'
> feat: gh-action for stale issues

- docs/examples/skip.md
- integration/standalone_tar_test.go
- pkg/commands/app.go
- pkg/commands/artifact/run.go
- pkg/commands/config/artifact.go
- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
- pkg/types/scanoptions.go
Close https://github.com/aquasecurity/trivy/pull/905
```
trivy image --skip-dirs "/usr/lib/ruby/gems,/etc" fluent/fluentd:edge
```
```
trivy image --skip-dirs /usr/lib/ruby/gems --skip-dirs "/etc" fluent/fluentd:edge
```
> break(cli): use StringSliceFlag for skip-dirs/files

- docs/installation.md
Removed `$` prefixes from code blocks to make them constant across the page and make the commands copypasta-able.
> Update install docs to make commands consistent

- contrib/sarif.tpl
- integration/testdata/alpine-310.sarif.golden
- pkg/report/writer.go
- pkg/report/writer_internal_test.go
- pkg/report/writer_test.go
Fixes #930
- Remove character 'v' from start of version string.
- Update rule name according to .Type value.
- Update rule id format, remove severity from id to convert to sarif level.
- Update result location Uri points to file.
- Add base Uri id.
- Remove region property for now.
Attached the sarif result generated with these changes: [report.zip](https://github.com/aquasecurity/trivy/files/6295273/report.zip)
> Update SARIF repot template

- pkg/commands/artifact/fs.go
- pkg/commands/artifact/image.go
- pkg/commands/artifact/repository.go
- pkg/commands/artifact/run.go
- pkg/commands/client/run.go
```
$ trivy image -timeout 1s sequenceiq/hadoop-docker:2.7.0
2021-04-27T20:35:06.245+0900    WARN    increase --timeout value
2021-04-27T20:35:06.245+0900    FATAL   scan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded
```
> feat: show a help message when the context's deadline passes

- pkg/report/writer.go
Before:
```
2021-04-30T02:24:46.045+0900    INFO    Detecting Alpine vulnerabilities...
2021-04-30T02:24:46.048+0900    INFO    Trivy skips scanning programming language libraries because no supported file was detected
```
After:
```
2021-04-30T02:24:02.354+0900    INFO    Detecting Alpine vulnerabilities...
2021-04-30T02:24:02.357+0900    INFO    Trivy skips scanning programming language libraries because no supported file was detected
alpine:3.11.11 (alpine 3.11.11)
===============================
```
> fix(table): skip zero vulnerabilities on java

- .github/workflows/release.yaml
GoReleaser fails due to trivy-repo.
```
⨯ release failed after 0.11s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
?? trivy-repo/
```
> chore(ci): clone trivy-repo after releasing binaries

- .github/workflows/release.yaml
GITHUB_TOKEN doesn't have the permission for aquasecurity/homebrew-trivy.
> chore(ci): replace GITHUB_TOKEN with ORG_GITHUB_TOKEN

- go.mod
- go.sum
- pkg/detector/library/driver.go
- pkg/scanner/local/scan.go
Ref. https://github.com/aquasecurity/fanal/pull/175
> feat(go): added support of gomod analyzer

- go.mod
- go.sum
https://github.com/aquasecurity/fanal/pull/179
> fix(image): disable go.sum scanning

- docs/integrations/gitlab-ci.md
Just saw this small error in the GitLab CI example while using it in an existing pipeline and wanted to clear up any confusion for new users looking at the examples.
> docs: Add HIGH severity to Trivy command in GitLab CI example to match comment

- .github/workflows/publish-chart.yaml
- .github/workflows/release.yaml
To authenticate to the GHCR within a GitHub Actions workflow, we can use the GITHUB_TOKEN now. 
https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry
Replace `secrets.ORG_GITHUB_TOKEN` with `secrets.GITHUB_TOKEN`.
Replace `secrets.ORG_GITHUB_TOKEN` with `secrets.ORG_REPO_TOKEN` having `repo` scope.
> chore(ci): change to more granular tokens

- pkg/plugin/plugin.go
https://github.com/aquasecurity/trivy/pull/1020 is based on `support_config` branch, but the change is independent of the feature of config scanning. This PR toward `main` branch replaces #1020. Once this PR gets merged, I'll merge this change into `support_config` branch.
> feat(plugin): add aqua plugin

- contrib/asff.tpl
- integration/testdata/alpine-310.asff.golden
Use of the `Normalized` and `Product` fields is deprecated in the [ASFF spec](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-attributes.html#asff-severity). Instead, we should just provide the severity as a `Label`, which simplifies the logic in this template quite a bit as well.
> Update ASFF template to use label for severity

- contrib/asff.tpl
Masterminds/sprig breaks compatibility. The builtin `slice` accepts string, while `slice` from sprig doesn't allow it.
https://github.com/Masterminds/sprig/pull/306
```
$ AWS_REGION=us-west-1 AWS_ACCOUNT_ID=123456789012 ./trivy image --format template --template "@contrib/asff.tpl" -o report.asff knqyf263/vuln-image
...
2021-06-10T11:42:17.722+0300    FATAL   unable to write results: failed to write results: failed to write with template: template: output template:17:24: executing "output template" at <slice $description 0 1021>: error calling slice: list should be type of slice or array but string
```
> fix(asff): replace slice with substr

- pkg/detector/ospkg/suse/suse.go
SLE 15.3 is about to be released and will be maintained until
6 months after 15.4. this allows us to guess the 15 SP2 EOL date,
so updating that as well.
> suse: mark sle 15.3 as maintained, add opensuse 15.3

- go.mod
- go.sum
Go has multiple prefixed data sources such as `go::GitLab Advisory Database` and `go::vulndb` in Trivy DB. If a package name like `github.com/kubernetes/client-go` is missing in either of those buckets, the other bucket is also skipped by mistake, even though the bucket has security advisories of the package.
https://github.com/aquasecurity/trivy-db/pull/118
> fix(db): multiple prefixed data sources

- go.mod
- go.sum
- pkg/report/writer.go
- pkg/scanner/scan.go
- pkg/scanner/scan_test.go
```
$ TRIVY_NEW_JSON_SCHEMA=true ./trivy image -f json alpine:3.12
{
"ArtifactName": "alpine:3.12",
"ArtifactID": "sha256:5049df74eab8db41c3d5992a298c331bbf4a2251d19aa790bed3f27f9a183207",
"ArtifactType": "container_image",
"Metadata": {
"OS": {
"Family": "alpine",
"Name": "3.12.7"
},
"RepoTags": [
"alpine:3.12"
],
"RepoDigests": [
"alpine@sha256:87703314048c40236c6d674424159ee862e2b96ce1c37c62d877e21ed27a387e"
]
},
"Results": [
{
"Target": "alpine:3.12 (alpine 3.12.7)",
"Type": "alpine"
}
]
}
```
- Close https://github.com/aquasecurity/trivy/issues/1066
- https://github.com/aquasecurity/fanal/pull/185
- https://github.com/aquasecurity/trivy/discussions/1050
> feat(report): add artifact metadata

- .github/workflows/release.yaml
use version `^v0` instead of `latest` to avoid breaking the build when cyclonedx-gomod introduces breaking changes in a new major version. See https://github.com/CycloneDX/gh-gomod-generate-sbom/releases/tag/v0.3.0
> update cyclonedx github action to v0.3.0

- docs/misconfiguration/custom/index.md
Fix typo for word `finish` in custom index.md
> Fix typo for word `finish` in custom index.md

- docs/advanced/integrations/gitlab-ci.md
This is a suggestion to use the native integration, which is a lot simpler than the custom configurations currently recommended in the [documentation](https://aquasecurity.github.io/trivy/v0.19.2/advanced/integrations/gitlab-ci/).
I considered removing them altogether but thought it was best to let a maintainer weight-in before doing so.
> GitLab CI integration documentation

- pkg/detector/ospkg/oracle/oracle.go
use a package name instead of SrcName for getting of advisories
about Oracle packages.
Fixes #1170
> fix(detector): change an argument for trivy-db getter

- pkg/commands/plugin/plugin.go
There is a closure inside a function for Action field: variable p always refers on the last plugin.
solution: redefine variable inside the for loop.
Fixes #1086
> fix(plugin): resolve a closure

- pkg/detector/ospkg/debian/debian.go
https://bits.debian.org/2021/08/bullseye-released.html
> feat(debian): update EOL of Debian 11

- docs/vulnerability/detection/data-source.md
Trivy no longer depends on OSVDB and can use "Ruby Advisory Database" for commercial usage.
Fixes #1208
> docs(ruby): allow commercial use of Ruby Advisory Database

- pkg/detector/ospkg/alpine/alpine.go
- pkg/detector/ospkg/alpine/alpine_test.go
- pkg/detector/ospkg/alpine/testdata/fixtures/alpine.yaml
Trivy DB doesn't insert security advisories for unfixed vulnerabilities, so Trivy cannot detect unfixed vulnerabilities at the moment. This PR is for the future.
- https://github.com/aquasecurity/vuln-list-update/pull/93
> feat(alpine): support unfixed vulnerabilities

- go.mod
- go.sum
- pkg/detector/ospkg/debian/debian.go
- pkg/detector/ospkg/debian/debian_test.go
- pkg/detector/ospkg/debian/testdata/fixtures/debian.yaml
- pkg/result/result.go
- pkg/result/result_test.go
- pkg/types/vulnerability.go
Trivy used to use [OVAL](https://www.debian.org/security/oval/) and [JSON API](https://security-tracker.debian.org/tracker/data/json) for Debian scanning, but this PR migrates to [Debian repository](https://salsa.debian.org/security-tracker-team/security-tracker). This is because JSON API will no longer return security advisories of EOSL versions. We want to keep supporting old versions as well. This PR allows it.
Need to merge the below PRs first
- https://github.com/aquasecurity/vuln-list-update/pull/95
- https://github.com/aquasecurity/trivy-db/pull/137
> feat(debian): support the versions that reached EOL

- go.mod
- go.sum
> fix(deps): fix CVE-2021-32760 for github.com/containerd/containerd

- goreleaser.yml
An error occurred while executing brew test command:
```shell
% brew test trivy
==> Testing aquasecurity/trivy/trivy
==> /usr/local/Cellar/trivy/0.19.2/bin/program --version
Last 15 lines from /Users/minchao/Library/Logs/Homebrew/trivy/test.01.program:
2021-09-26 21:25:13 +0800
/usr/local/Cellar/trivy/0.19.2/bin/program --version
Error: aquasecurity/trivy/trivy: failed
An exception occurred within a child process:
BuildError: Failed executing: /usr/local/Cellar/trivy/0.19.2/bin/program --version
/usr/local/Homebrew/Library/Homebrew/formula.rb:2297:in `block in system'
omit...
```
This fix will correct the `program`  to `trivy`.
> fix: brew test command

- integration/client_server_test.go
- integration/docker/docker.go
- integration/docker_engine_test.go
- integration/registry_test.go
- integration/standalone_tar_test.go
- pkg/commands/app_test.go
- pkg/db/db_test.go
- pkg/github/github_test.go
- pkg/report/template.go
- pkg/result/result.go
- pkg/rpc/server/listen.go
- pkg/rpc/server/listen_test.go
- pkg/utils/utils_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
No breaking changes.
> refactor: move from io/ioutil to io and os package

- pkg/commands/app.go
- pkg/commands/artifact/option.go
- pkg/commands/artifact/option_test.go
This PR removes the following options:
- `--only-update`
- `--refresh`
- `--auto-refresh`
These options were deprecated a while ago and the warning has been displayed.
```
2021-10-04T14:18:32.603+0300    WARN    --only-update, --refresh and --auto-refresh are unnecessary and ignored now. These commands will be removed in the next version.
```
This PR finally removed them.
> feat(commands): remove deprecated options

- go.mod
- go.sum
Fixes #1251 Fixes #1183 Fixes #1172
Update via `go get github.com/aquasecurity/fanal` and `go mod tidy`
```
$ ./trivy config . 
2021-10-04T21:36:54.543+0800    INFO    Detected config files: 21
...
$ ./trivy image quay.io/openshift/origin-logging-elasticsearch5:v3.11
2021-10-04T21:39:34.009+0800    INFO    Detected OS: centos
2021-10-04T21:39:34.011+0800    INFO    Detecting RHEL/CentOS vulnerabilities...
2021-10-04T21:39:34.052+0800    INFO    Number of language-specific files: 0
quay.io/openshift/origin-logging-elasticsearch5:v3.11 (centos 7.8.2003)
=======================================================================
Total: 939 (UNKNOWN: 0, LOW: 440, MEDIUM: 479, HIGH: 18, CRITICAL: 2)
...
```
> fix: update fanal to fixes #1251 #1183 #1172

- docs/advanced/container/embed-in-dockerfile.md
- docs/advanced/container/unpacked-filesystem.md
- docs/getting-started/cli/fs.md
- docs/getting-started/cli/rootfs.md
- docs/getting-started/overview.md
- docs/vulnerability/detection/language.md
- docs/vulnerability/scanning/filesystem.md
- docs/vulnerability/scanning/index.md
- docs/vulnerability/scanning/rootfs.md
- go.mod
- go.sum
- mkdocs.yml
- pkg/commands/app.go
- pkg/commands/artifact/config.go
- pkg/commands/artifact/fs.go
- pkg/commands/artifact/image.go
- pkg/commands/artifact/option.go
- pkg/commands/artifact/repository.go
- pkg/commands/artifact/run.go
- pkg/commands/client/option.go
- pkg/commands/client/run.go
`fs` subcommand currently has two main targets.
- Local project
- scan lock files such as Gemfile.lock
- Rootfs
- scan filesystem from inside containers
- https://aquasecurity.github.io/trivy/v0.19.2/advanced/container/embed-in-dockerfile/
- scan unpacked container image filesystem
- https://aquasecurity.github.io/trivy/v0.19.2/advanced/container/unpacked-filesystem/
Trivy recently introduced individual package scannings such as gemspec and egg/wheel. It should be enabled for the rootfs scanning but should be disabled for scanning local projects. After all, we decided to split `fs` subcommand into two subcommand, `fs` and `rootfs`.
- `fs` subcommand
- scan local projects
- `rootfs` subcommand
- scan filesystem from inside containers
- scan unpacked container image filesystem
Need to merge …
> feat(command): add rootfs command

- go.mod
- go.sum
- integration/testdata/dockerfile-custom-policies.json.golden
- integration/testdata/dockerfile.json.golden
- integration/testdata/nodejs.json.golden
- integration/testdata/pip.json.golden
- pkg/detector/library/detect.go
- pkg/detector/library/mock_operation.go
- pkg/rpc/convert.go
- pkg/rpc/convert_test.go
- pkg/rpc/server/server_test.go
- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
- pkg/scanner/scan.go
- pkg/scanner/scan_test.go
This PR adds package paths into the JSON report.
```
"Packages": [
{
"Name": "i18n",
"Version": "1.8.2",
"License": "MIT",
"Layer": {
"Digest": "sha256:a8877cad19f14a7044524a145ce33170085441a7922458017db1631dcd5f7602",
"DiffID": "sha256:75e43d55939745950bc3f8fad56c5834617c4339f0f54755e69a0dd5372624e9"
},
},
{
"Name": "kubeclient",
"Version": "4.6.0",
"License": "MIT",
"Layer": {
"Digest": "sha256:a8877cad19f14a7044524a145ce33170085441a7922458017db1631dcd5f7602",
"DiffID": "sha256:75e43d55939745950bc3f8fad56c5834617c4339f0f54755e69a0dd5372624e9"
},
},
]
```
```
"Packages": [
{
"Name": "i18n",
"Version": "1.8.2",
"License": "MIT",
"Layer": {
"Digest": "sha256:a8877cad19f14a7044524a145ce33170085441a7922458017db1631dcd5f7602",
"DiffID": …
```
> feat(report): add package path

- contrib/install.sh
The current install.sh script logs all messages to stderr via ```echoerr()``` function, including debug and info; debug and info should go to stdout.
Since godownloader was used to generate install.sh and that project is no longer maintained, it seems reasonable to update install.sh here and simply ```echo``` info and debug messages.
> chore: send debug and info logs to stdout in install.sh, not stderr.

- go.mod
- go.sum
Updating go-dep-parser dependency to include fix for issue https://github.com/aquasecurity/fanal/issues/323
> fix(python): fix parsing of requirements.txt with hash checking mode available in pip since version 8.0

- ci/deploy-deb.sh
`ubuntu-distro-info --supported` returns only versions: `bionic`, `focal`, `hirsute`, `impish` and `jammy`.
`ubuntu-distro-info --supported-esm` returns another versions: `trusty`, `xenial`, `bionic`, `focal` and `jammy`.
we should use the union of these sets for the release script .
Fixes #1194
> chore(release): add ubuntu older versions to deploy script

- go.mod
- go.sum
Update fanal with cfsec version update
- new version of cfsec brought in with latest fanal
- fixes issue where cfsec treats files as CloudFormation when they aren't
- fixes issue where invalid content errors are surfaced to Trivy
- Gets addition of service and provider on the IaC results - this is not  visible to others
Resolves #1420
> fix(cloudformation): Update Fanal with less aggressive Cfsec

- docs/vulnerability/scanning/git-repository.md
Update instructions on how to scan private git repositories, as according to https://github.com/aquasecurity/fanal/pull/253 .
> [doc] Update git-repository.md with instruction about scanning private repos

- docs/advanced/private-registries/gcr.md
I found setting up and using the GCR difficult to figure out the exact credentials needed and the expected file format. Part this was confusion caused ISSUE #783 which wasn't what I needed to know. Hopefully this saves someone else a lot of time.
> docs: provide more information on scanning Google's GCR

- helm/trivy/Chart.yaml
- helm/trivy/templates/configmap.yaml
- helm/trivy/templates/secret.yaml
- helm/trivy/templates/statefulset.yaml
Asa mentioned in #1343, This is about storing environment variables into the right k8s resources : ConfigMap & Secret if it's sensitive data.
Once environment variables are stored in these resources, the pod definition can load these env vars with `spec.containers.envFrom` instead of putting directly the env vars with `spec.containers.env`.
This design has many benefits:
1. Meet k8s standards
2. distributed configuration
3. keeping pod template definition more stable as maintenance of env vars are shifted to configmap or/and secret template definition
4. Help to secure reading env vars with k8s RBAC ( .i.e restrict access to Secret resources, and pod exec verb )
> fix(helm): externalize env vars to configMap

- pkg/commands/app.go
- pkg/commands/plugin/plugin.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
Update existing plugins to the latest version
```bash
./trivy plugin update aqua
2021-12-13T09:12:54.577Z        INFO    Updating plugin 'aqua'
2021-12-13T09:12:54.577Z        INFO    Installing the plugin from github.com/aquasecurity/trivy-plugin-aqua...
2021-12-13T09:12:56.503Z        INFO    Loading the plugin metadata...
2021-12-13T09:12:58.535Z        INFO    Updated 'aqua' from v0.7.0 to v0.7.2
```
```bash
./trivy plugin update aqua
2021-12-13T09:14:36.535Z        INFO    Updating plugin 'aqua'
2021-12-13T09:14:36.535Z        INFO    Installing the plugin from github.com/aquasecurity/trivy-plugin-aqua...
2021-12-13T09:14:38.373Z        INFO    Loading the plugin metadata...
2021-12-13T09:14:39.497Z        INFO    The aqua plugin is the latest version. [v0.7.2]
```
```bash
./trivy …
```
> feat(plugin): Add option to update plugin

- contrib/html.tpl
- integration/testdata/alpine-310.html.golden
Trivi there is only tables of vulnerabilities for the html.tpl config.
For example.:
```
➜ ls
Dockerfile
➜  trivy config .
2021-12-09T10:45:09.460+0600	INFO	Detected config files: 1
Dockerfile (dockerfile)
=======================
Tests: 23 (SUCCESSES: 22, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | root user |   HIGH   | Specify at least 1 USER                  |
| …
```
> feat: added misconfiguration field for html.tpl

- go.mod
- go.sum
RPM databases can be either in BerkeleyDB format or optionally in the newer "native" NDB format. there are linux distributions that switched their implementation of the rpm database away from BerkeleyDB out of concerns about the future levels of maintenance after its license change.
See https://rpm.org/wiki/Releases/4.14.0
See also https://fedoraproject.org/wiki/Changes/NewRpmDBFormat
This PR supports NDB format reading.
We can test this PR with `registry.suse.com/suse/sle15:15.3`.
> feat(rpm): support NDB

- go.mod
- go.sum
The individual packages of Node.js, Python and Ruby show the file path, but JAR doesn't. This PR adds it.
Close https://github.com/aquasecurity/trivy/issues/1291
- Need to update go.mod after it gets merged
> feat(jar): add file path

- pkg/scanner/local/scan.go
This is for the plugin to get the richer information
- Add missing IacMetdata for service and provider information
> feat(config): add missing iac metadata

- go.mod
- go.sum
Scanning images including large executable files or JAR files consume a large amount of memory. This PR reduces memory usage.
Before
```
Showing nodes accounting for 1787.11MB, 99.50% of 1796.01MB total
```
After
```
Showing nodes accounting for 29068.50kB, 86.05% of 33779.92kB total
```
Close https://github.com/aquasecurity/trivy/issues/1295
Close https://github.com/aquasecurity/trivy/issues/1284
> fix: improve memory usage

- docs/vulnerability/detection/language.md
- go.mod
- go.sum
Trivy looks for JAR files even in filesystem and repository scanning, though it should be only in container image scanning. It is no longer necessary as `pom.xml` is supported now.
Before:
- JAR scanning
- image
- filesystem
- root filesystem
- repository
After
- JAR scanning
- image
- root filesystem
- pom.xml scanning
- filesystem
- repository
- Need to update `go.mod` after this PR gets merged.
JAR scanning is disabled here.
- https://github.com/aquasecurity/trivy/blob/1c9ccb5e03b2b84f12aee0b96042e873fafcc64c/pkg/commands/artifact/fs.go#L34
- https://github.com/aquasecurity/trivy/blob/1c9ccb5e03b2b84f12aee0b96042e873fafcc64c/pkg/commands/artifact/repository.go#L38
> BREAKING: disable JAR detection in fs/repo scanning

- pkg/commands/app.go
See https://github.com/aquasecurity/trivy/discussions/1515
```
$ trivy alpine:3.10.7
2021-12-24T22:39:01.192+0200    WARN    The root command will be removed. Please migrate to 'trivy image' command. See https://github.com/aquasecurity/trivy/discussions/1515
2021-12-24T22:39:03.878+0200    INFO    Detected OS: alpine
2021-12-24T22:39:03.878+0200    INFO    Detecting Alpine vulnerabilities...
...
```
> feat(cli): warning for root command

- go.mod
- go.sum
Trivy currently supports only the first two requirements in pom.xml. Other requirements should be skipped at the moment.
✅ 1.0: Soft requirement for 1.0
✅ [1.0]: Hard requirement for 1.0
❌ (,1.0]: Hard requirement for any version <= 1.0.
❌ [1.2,1.3]: Hard requirement for any version between 1.2 and 1.3 inclusive.
❌ [1.0,2.0): 1.0 <= x < 2.0; Hard requirement for any version between 1.0 inclusive and 2.0 exclusive.
❌ [1.5,): Hard requirement for any version greater than or equal to 1.5.
❌ (,1.0],[1.2,): Hard requirement for any version less than or equal to 1.0 than or greater than or equal to 1.2, but not 1.1. Multiple requirements are separated by commas.
❌ (,1.1),(1.1,): Hard requirement for any version except 1.1; for example because 1.1 has a critical vulnerability.
```
<dependency> …
```
> fix(java/pom): ignore unsupported requirements

- docs/vulnerability/examples/report.md
When Trivy is installed using rpm then default templates are present at location /usr/local/share/trivy/templates.
In this change, I've updated documentation so users know location where to find it and also added example command for html template.
> added note about default template path when Trivy installed using rpm

- docs/advanced/integrations/gitlab-ci.md
The GitLab CI yml alernative does not work.
- yml invalid: `artifacts:paths` is a list and a `-` is missing
- `--template` option: there is no `contrib/gitlab-codeclimate.tpl` file, you meant `contrib/gitlab-codequality.tpl` instead
And I did not suggest a change, but I had to change the docker images from 'docker:stable' and 'docker:dind' respectively to 'docker:19-stable' and 'docker:19-dind'. This is probably due to my gitlab-runner configuration, but a note could help some others in my situation.
> fix(doc): gitlab integration

- go.mod
- go.sum
- pkg/types/docker_conf.go
This PR removes `Timeout` in `DockerOption` which is no longer used. Also, it introduces the analyzer group to fanal, but there is no impact on Trivy.
> refactor: remove unused field

- docs/advanced/integrations/gitlab-ci.md
With the command change of `trivy` to `trivy image` in v0.23.0 issue #1515. I've updated the document for GitLab CI integration as it was throwing a warning to update the command in my pipeline.
> docs: updated integration document for gitlab ci

- docs/vulnerability/detection/language.md
It seems that there is no description of Rust (Cargo.lock) in [Language-specific Packages](https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/detection/language/), so I added it.
> docs: add Rust to Language-specific Packages Table

- pkg/commands/artifact/run.go
Resolves #927
Following https://github.com/aquasecurity/fanal/pull/335
Pass the `--quiet` flag to the `NewArtifact` function when initializing a scanner.
<details>
<summary>Before: (the `--quite` flag doesn't suppress the git clone output)</summary>
```sh
./trivy --quiet repo https://github.com/aquasecurity/vuln-list-update
Enumerating objects: 435, done.
Counting objects: 100% (435/435), done.
Compressing objects: 100% (293/293), done.
Total 435 (delta 78), reused 356 (delta 61), pack-reused 0
go.sum (gomod)
==============
Total: 8 (UNKNOWN: 4, LOW: 0, MEDIUM: 1, HIGH: 3, CRITICAL: 0)
+-----------------------------------+------------------+----------+--------------------+--------------------------------------+---------------------------------------+
|              LIBRARY              | …
```
> feat(repo): supress git clone output

- helm/trivy/README.md
- helm/trivy/templates/secret.yaml
- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
Fixes #1568
2 options to set these credentials implemented.
Either directly in the values.yaml file or via an existing Secret.
> Add the ability to set dockerhub credentials in the helm chart

- README.md
- docs/getting-started/overview.md
- docs/vulnerability/detection/data-source.md
- docs/vulnerability/detection/os.md
- go.mod
- go.sum
- integration/client_server_test.go
- integration/docker_engine_test.go
- integration/standalone_tar_test.go
- integration/testdata/almalinux-8.json.golden
- integration/testdata/fixtures/db/rockylinux.yaml
- integration/testdata/fixtures/db/vulnerability.yaml
- integration/testdata/rockylinux-8.json.golden
- pkg/detector/ospkg/detect.go
- pkg/detector/ospkg/rocky/rocky.go
- pkg/detector/ospkg/rocky/rocky_test.go
- pkg/detector/ospkg/rocky/testdata/fixtures/invalid.yaml
- pkg/detector/ospkg/rocky/testdata/fixtures/modular.yaml
- pkg/detector/ospkg/rocky/testdata/fixtures/rocky.yaml
- pkg/result/result.go
fixes. https://github.com/aquasecurity/trivy/issues/1053
Add Rocky Linux to Trivy's supported operating systems.
```console
$ trivy --cache-dir ~/.cache/trivy/ image rockylinux:8
2022-01-12T06:52:53.227+0900	INFO	Detected OS: rocky
2022-01-12T06:52:53.227+0900	INFO	Detecting Rocky Linux vulnerabilities...
2022-01-12T06:52:53.227+0900	INFO	Number of language-specific files: 0
rockylinux:8 (rocky 8.5)
========================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
+--------------+------------------+----------+-------------------+------------------+--------------------------------------+
|   LIBRARY    | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 | …
```
> feat(rocky): support Rocky Linux

- .github/pull_request_template.md
URLs don't work when creating a new PR. Created static URLs.
> fix(contribution): change links in pull_request_template to static URLs

- docs/getting-started/overview.md
Trivy DB v2+ is now available for commercial use.
- Close https://github.com/aquasecurity/trivy/issues/491
> docs: commercial use available

- pkg/report/writer.go
There is a mistake in the warning message about `sarif.tpl` template for backward compatibility.
> fix(sarif): fix the warning message

- pkg/commands/option/db.go
- pkg/report/writer.go
Add a link to GitHub Discussions
```
$ trivy image --light alpine:3.11
2022-01-31T14:18:37.618+0200    WARN    '--light' option is deprecated and will be removed
```
```
$ trivy image --light alpine:3.11
2022-01-31T14:18:37.618+0200    WARN    '--light' option is deprecated and will be removed. See also: https://github.com/aquasecurity/trivy/discussions/1649
```
> feat(option): show a link to GitHub Discussions for --light deprecation

- contrib/example_policy/advanced.rego
- contrib/example_policy/basic.rego
- docs/vulnerability/examples/filter.md
This request contains a fix to the example `--ignore-policy` files to make them work with the current structure of the `output` variable that they process.  It also updates the documentation to fix a broken file path and to reflect the updated command output.
For more details see #1627.
I have not added a test for this, nor run the test suite.  I am not proficient in go and I don't think the files that have been changed are covered by tests.  To confirm that the fix works, run the following scan from the issue and notice the vulnerability in `passwd` is no longer included.
```
trivy image --ignore-policy contrib/example_policy/basic.rego python:3.6-slim
```
I added the RedHat vector to the tests in the policy as I found that sometimes contained information where the NVD vector didn't.
- …
> fix: update example Rego files and docs

- docs/getting-started/cli/repo.md
- go.mod
- go.sum
- pkg/commands/app.go
- pkg/commands/artifact/run.go
`--no-progress` with the `repo` subcommand doesn't work properly. This PR fixes the bug.
Before:
```
$ trivy repo --no-progress github.com/aquasecurity/trivy-ci-test
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Compressing objects: 100% (5/5), done.
Total 6 (delta 0), reused 3 (delta 0), pack-reused 0
2022-02-02T12:51:31.689+0200	INFO	Number of language-specific files: 1
2022-02-02T12:51:31.689+0200	INFO	Detecting cargo vulnerabilities...
```
After:
```
$ trivy repo --no-progress github.com/aquasecurity/trivy-ci-test
bash-3.2$ trivy repo --no-progress --severity CRITICAL github.com/aquasecurity/rust-app
2022-02-02T13:04:15.114+0200	INFO	Number of language-specific files: 1
2022-02-02T13:04:15.114+0200	INFO	Detecting cargo vulnerabilities...
```
Remove this section if …
> fix(repo): --no-progress suppresses git output

- docs/vulnerability/scanning/image.md
The current documentation for container image scanning uses a ruby image, where the tag is no longer present on Docker Hub (`ruby:2.3.0-alpine3.9`).
This change just updates the command and output to a currently supported tag. Also adds a line to pull the image before using Docker save, so it's local on the host.
> docs(image): Update image tag to one present on Docker Hub

- integration/integration_test.go
- pkg/commands/artifact/run.go
- pkg/commands/client/run.go
- pkg/report/json.go
- pkg/report/json_test.go
- pkg/report/sarif.go
- pkg/report/sarif_test.go
- pkg/report/table.go
- pkg/report/table_test.go
- pkg/report/template.go
- pkg/report/template_test.go
- pkg/report/writer.go
- pkg/report/writer_test.go
- pkg/result/result.go
- pkg/result/result_test.go
- pkg/rpc/client/client.go
- pkg/rpc/client/client_test.go
- pkg/rpc/convert.go
- pkg/rpc/convert_test.go
- pkg/rpc/server/server_test.go
- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
- pkg/scanner/mock_driver.go
- pkg/scanner/scan.go
- pkg/scanner/scan_test.go
- pkg/types/report.go
Move all structs under the `report` package under `types` package
> refactor: move result structs under types

- .github/dependabot.yml
Set Dependabot to run monthly.
> chore(dependabot): enable gomod monthly

- helm/trivy/README.md
- helm/trivy/templates/serviceaccount.yaml
- helm/trivy/values.yaml
Allow customisation of ServiceAccount annotations in helm chart.
- Close #1676
> feat(helm): Parameterise ServiceAccount annotations

- contrib/junit.tpl
Junit report for misconfigurations was missing 
Usage example:
`trivy  fs  --security-checks config,vuln --format template --template "@junit.tpl" -o junit-report.xml {folder}`
> feat(template) Add misconfigurations to junit report

- goreleaser.yml
Signed-off-by: skuethe <56306041+skuethe@users.noreply.github.com>
This PR adds `s390x` arch container image builds and adds them to the multi arch container manifests.
- Close #1725
> build: add s390x container images

- .github/workflows/scan.yaml
- go.mod
- go.sum
`github.com/satori/go.uuid` was replaced to the latest version, because `github.com/satori/go.uuid@v1.2.0` contains CVE-2021-3538. **note**: this library uses only for tests.
Also `examples` folder was excluded from Scan Workflow.
> chore(deps): replace `satori` version and skipping examples folder 

- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
Add custom labels to the pod and the statefulset. This can be be useful for a number of reasons but for example using MSI in Azure.
- Close #1766 
N/A
> feat(helm): Add support for custom labels

- docs/getting-started/installation.md
Adds a missing `image` in the command to run trivy from the official docker image with `docker run`.
Without `image`, the image name itself is interpreted as a command (whereas the command we want to run here is `image`), and results in a failure with `No help topic for <IMAGE NAME>`.
> doc(docker): Fix command to run trivy with docker on linux

- .gitignore
- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/secret.yaml
- helm/trivy/values.yaml
Add support to the Helm chart for specifying `TRIVY_TOKEN`. Use `trivy.serverToken` to align with the Starboard chart.
> feat(helm): Add support for server token

- contrib/asff.tpl
- integration/testdata/alpine-310.asff.golden
Fix asff template to produce an array within an object instead of just an array so as to match asff schema
Signed-off-by: Amndeep Singh Mann <amann@mitre.org>
- Close #1684 
> fix: ASFF template to match ASFF schema

- Makefile
Find the `*.proto` files and run in a `for loop` to run `protoc`
for each file in a separated command. If fail, `|| exit` will exit
with the returned error.
The POSIX standard specifies that the return status of `find` is 0
unless an error occurred while traversing the directories;
the return status of executed commands doesn't enter into it.
To overcome this limitation, the `-exec ... +` pattern could be used
From the docs (https://man7.org/linux/man-pages/man1/find.1.html):
"If any invocation with the `+' form returns a non-zero
value as exit status, then find returns a non-zero exit
status."
But as well, "This variant of the -exec action runs the specified command
on the selected files, but the command line is built by appending each selected
file name at the end;"
Unfortunately, at …
> build: Replace `make protoc` with `for loop` to return an error

- helm/trivy/templates/serviceaccount.yaml
Fixes an issue with #1677 where the ServiceAccount annotations are indented incorrectly, rendering this invalid YAML.
- Close #1794
- #1677 (Original feature implementation)
> fix(helm): Indentation for ServiceAccount annotations

- goreleaser.yml
The Label Schema Convention has been deprecated in favor of the [OCI image spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema).
Update the gorelease config to use the new replacement fields.
This is not considered a breaking change, as it only touches metadata and the Label Schema Convention is deprecated for almost three years (March 2019).
Most fields only need to be renamed. 
`org.label-schema.schema-version` could be removed without replacement.
`org.opencontainers.image.documentation` was added to link to the Github page documentation in the exact version.
`org.opencontainers.image.url` was added pointing to the Aqua Security product page of trivy.
Further labels were considered but not added (unclear purpose or value): …
> feat(docker): Label images based on OCI image spec

- docs/getting-started/installation.md
* Add missing `image` argument in the Installation docs->Docker section for MacOS.
> docs: Fix Installation documentation

- go.mod
- go.sum
- integration/registry_test.go
- Bumps [github.com/testcontainers/testcontainers-go](https://github.com/testcontainers/testcontainers-go) from 0.11.1 to 0.12.0.
- The **TestRegistry** integration test has changed because [key and value of BindMounts are swapped ](https://github.com/testcontainers/testcontainers-go/pull/354).
> chore(deps): bump github.com/testcontainers/testcontainers-go from 0.11.1 to 0.12.0

- helm/trivy/README.md
- helm/trivy/templates/service.yaml
- helm/trivy/values.yaml
Makes the Service name used for Trivy configurable in `values.yaml`.
(Also some whitespace cleanup for readability)
- Closes https://github.com/aquasecurity/trivy/issues/1824
> feat(helm): Make Trivy service name configurable

- go.mod
- go.sum
if a tag is skipped, `trivy` will get an image with a default tag (`latest`).
- Close #1848
- https://github.com/aquasecurity/fanal/pull/425
> fix(docker): getting images without a tag

- docs/misconfiguration/policy/builtin.md
The current URL for the tfsec-checks is 404, so changing it in-line with what we've got for cfsec, which is just the base site URL.
> docs: change URL for tfsec-checks

- go.mod
- pkg/commands/app.go
- pkg/commands/artifact/option_test.go
- pkg/commands/option/remote.go
`tokenHeader` flag was initialized by default value (not empty), so warning message was always shown.
> fix(option): hide false warning about remote options

- go.mod
- go.sum
`Trivy-db` has `golang.org/x/vuln` library with critical vulnerabilities. This library [has been updated](https://github.com/aquasecurity/trivy-db/pull/198) in `Trivy-db`.
In this PR, `Trivy-db` dependency has been updated for `Trivy`.
- Close #1846
- Close #1847
> fix(vulnerabilities): fixed trivy-db vulns

- pkg/commands/app.go
Fixed error when Trivy try download DB in `server` mode.
- Close #1940
> fix(downloadDB): fixed download trivy-db in server mode 

- helm/trivy/Chart.yaml
Signed-off-by: Dennis Irsigler <dennis.irsigler@metro-markets.de>
Bump the Trivy version in the Helm Chart to 0.25.0.
- Close #1928
> chore: update Trivy version in HelmChart to 0.25.0

- pkg/commands/app.go
`--db-repository` is missing in `sbom` subcommand.
> fix(sbom): add --db-repository

- .github/pull_request_template.md
Move CONTRIBUTING.md to our docs
> chore: fix URLs in the PR template

- docs/docs/vulnerability/languages/golang.md
- go.mod
- go.sum
- mkdocs.yml
Go 1.17+ adds indirect dependencies to `go.mod`. This PR parses `go.mod` as well as `go.sum` and merges them according to the Go version in `go.mod`. 
- Go 1.17+
- it takes only `go.mod` and ignores `go.sum`.
- Go 1.16 or less
- it takes direct dependencies in `go.mod` and indirect dependencies in `go.sum`.
It reduces unused dependencies as shown below.
```
$ ./fanal fs --skip-dirs analyzer --skip-dirs artifact --skip-dirs config .
...
gomod (go.sum): 697
```
```
$ ./fanal fs --skip-dirs analyzer --skip-dirs artifact --skip-dirs config .
...
gomod (go.mod): 164
```
- Close https://github.com/aquasecurity/trivy/issues/1973
> feat(go): support go.mod in Go 1.17+

- pkg/detector/library/driver.go
Go started using `go.mod` and `go.sum` for checks, so this driver type calls `gomod` now.
> fix(go): set correct go modules type

- go.mod
- go.sum
Fixed panic when `*.egg` archive doesn't contain required information files.
- Close #1930
> fix(python): fixed panic when scan .egg archive

- go.mod
- go.sum
Replaced `github.com/containerd/containerd` from `v1.5.9` to `v1.5.10` for fixing CVE-2022-23648.
> chore(deps): replace `containerd/containerd` version to fix CVE-2022-23648

- pkg/report/writer.go
If a customer sets a template `@sarif.tpl`, `filepath.Base(option.OutputTemplate)` will return `@sarif.tpl`, so Trivy will use this file, instead of embedded sarif template.
> fix(report): correct check of old sarif template files

- go.mod
- go.sum
Scanning of some cloudformation files caused panic due to out of range.
it was fixed in defsec: https://github.com/aquasecurity/defsec/pull/516/files
- Close #1954
> fix(cloudformation): correct margin removal for empty lines

- contrib/asff.tpl
- integration/testdata/alpine-310.asff.golden
there was an error for large descriptions:
```sh
$ cat result.asff | jq '.Findings'
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line ...
```
so there was truncated a description before escaping.
also the description size is also checked as half of the allowable.
> fix(report): truncate a description before escaping in ASFF template

- pkg/cache/remote.go
- pkg/rpc/client/client.go
> feat(server): re-add proxy support for client/server communications

- integration/testdata/fixtures/fs/gomod/submod2/go.mod
Using an incorrect module name was breaking some IDE.
Now we use correct module names for integration tests.
> test(deps): using a correct module inside go.mod for integration tests

- go.mod
- go.sum
We should not fail on permission errors and warn it instead.
```
$ trivy --cache-dir /tmp fs /
2022-04-21T08:42:23.598Z        FATAL   scan error:
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout
/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:94
- image scan failed:
github.com/aquasecurity/trivy/pkg/commands/artifact.scan
/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:259
- failed analysis:
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
/home/runner/work/trivy/trivy/pkg/scanner/scan.go:111
- walk filesystem:
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect
/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/local/fs.go:105
- walk error: …
```
> fix(fs): ignore permission errors

- .github/workflows/publish-chart.yaml
Publish the helm chart only when it's pushed a release tag
> chore: gh publish only with push the tag release

- go.mod
- go.sum
See aquasecurity/go-dep-parser#97
- Close #2024
> fix(go): fixed panic to scanning gomod without version

- docs/getting-started/installation.md
This isn't very user friendly, and breaks the "copy" functionality. So I am proposing we remove the dollar signs and tee the yum repo into the file, preserving sudo.
> docs: Update installation.md

- go.mod
- go.sum
https://github.com/aquasecurity/trivy/issues/2049#issuecomment-1109542569
- Close https://github.com/aquasecurity/trivy/issues/2049
> feat(secret): truncate long line

- pkg/commands/artifact/fs.go
- pkg/commands/artifact/image.go
- pkg/commands/artifact/repository.go
- pkg/commands/artifact/run.go
To allow Trivy plugins create InitializeScanner signature scanner options need to be public
- Close #XXX
> refactor: scanner options

- docs/docs/secret/configuration.md
In secret custom rules documentation, the rule's path is an array. While actually, it's a single value.
- None, docs fix
> docs(secret): fix rule path in docs

- go.mod
- go.sum
- pkg/commands/artifact/run.go
Trivy always finds configuration files for all commands, but Trivy has no rules for parsing these files.
This is why Trivy can be slow.
We should only scan config files only for [config](https://aquasecurity.github.io/trivy/v0.27.1/docs/misconfiguration/iac/) command or [--security-checks config](https://aquasecurity.github.io/trivy/v0.27.1/docs/misconfiguration/filesystem/) flag.
- Close #2017
> fix(misconf): added to skip conf files if their scanning is not enabled

- go.mod
- go.sum
- integration/testdata/alpine-distroless.json.golden
Added OS version detection from OS release file for some dist:
- Alpine Linux
- openSUSE
- SLES
- Photon OS
> chore(os): more general support for os-release files

- Makefile
Fixing make lint version to be the same as workflow:
https://github.com/aquasecurity/trivy/blob/fbb83c42d9ffcefa9ffab4df25da0bb0b4f9fafd/.github/workflows/test.yaml#L29
> chore: fix make lint version

- docs/docs/kubernetes/scanning.md
The default report doesn't return json anymore.
> docs: fix k8s doc

- docs/docs/kubernetes/scanning.md
- go.mod
- go.sum
- pkg/commands/app.go
- pkg/k8s/json.go
- pkg/k8s/report.go
- pkg/k8s/run.go
- pkg/k8s/scanner.go
- pkg/k8s/table.go
- Add support to kubernetes single resource scanning
- Add support to format (table or json) and report (summary or all).
```
trivy k8s -n default --format table --report all deploy/orion 
trivy k8s -n default --format table --report summary deploy/orion 
trivy k8s -n default --format json --report all deploy/orion 
trivy k8s -n default --format json --report summary deploy/orion 
trivy k8s -n default --format json --report summary
trivy k8s -n default --format json --report all
...
```
When report `all` is chosen for table, the output table report for each resource (image or config) is the same as if you called those subcommands directly for 1 resource.
- Depends on -> https://github.com/aquasecurity/trivy/pull/2116
> feat: k8s resource scanning

- pkg/k8s/summary.go
- pkg/report/table.go
I'm trying to add support for WASM plugin, but some dependencies are not TinyGo-friendly, especially `github.com/faith/color`. I needed to remove this import from the type definition in trivy-db since it is imported by WASM and fails the build by TinyGo. We may want to move to `github.com/liamg/tml` later though.
> refactor(report): move colorization function from trivy-db

- docs/docs/references/cli/image.md
The default value for the `--security-checks` option is incorrect in the docs.
See https://github.com/aquasecurity/trivy/issues/2104
- Close #2104 
> docs(secret): Fix default value of --security-checks in docs

- .github/workflows/semantic-pr.yaml
added `k8s` scope to semantic PR
> ci: added k8s scope to semantic pr

- pkg/commands/app.go
- pkg/k8s/scanner.go
Fixes security-checks flag.
```
trivy k8s deploy/orion
trivy k8s --security-checks=config deploy/orion
trivy k8s --security-checks=vuln deploy/orion
```
> fix(k8s): security-checks panic

- docs/getting-started/installation.md
If there is no `distroverpkg` value in `/etc/yum.conf` file, then `$releasever` is `{version number}Client/Server`(e.g. `7Server`).
`os-release` file is used to correctly determine RHEL/CentOS version.
Also added backslash to `$basearch` yum variable. 
- Close #2099
> docs: fixed installation instruction for rhel/centos

- docs/docs/misconfiguration/custom/index.md
- docs/docs/misconfiguration/custom/testing.md
- docs/docs/misconfiguration/options/policy.md
- docs/docs/misconfiguration/policy/builtin.md
- examples/misconf/namespace-exception/README.md
- examples/misconf/namespace-exception/policy/k8s_exception.rego
- examples/misconf/rule-exception/policy/ksv006_exception.rego
See https://github.com/aquasecurity/trivy/issues/2141
> docs(misconf): Update further examples and docs to refer to builtin/defsec instead of appshield

- go.mod
- go.sum
Optimises scanning of very large files for misconfigurations. Large files containing many issues cause the file to be read once for each issue, and subsequently syntax highlighted, analysed and built into a result. By caching each file containing issues while building the results, things run much faster and with much less memory required.
For example, scanning [this large file](https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml):
Before:
```shell
217.86s user 2.05s system 119% cpu 3:03.90 total
```
After:
```shell
12.58s user 0.85s system 189% cpu 7.099 total
```
- Close #2141
> perf(misconf): Improve performance when scanning very large files

- go.mod
- go.sum
See https://github.com/aquasecurity/fanal/pull/533 and https://github.com/aquasecurity/defsec/pull/612
> chore(deps): Update fanal to get defsec v0.58.2 (fixes false positives in KSV038)

- pkg/k8s/json.go
- pkg/k8s/report.go
- pkg/k8s/report_test.go
- pkg/k8s/table.go
**Before**:
```
trivy k8s --security-checks=vuln --report summary  deploy app
┌───────────┬──────────┬───────────────────┬───────────────────┬───────────────────┐
│ Namespace │ Resource │  Vulnerabilities  │ Misconfigurations │      Secrets      │
│           │          ├───┬───┬───┬───┬───┼───┬───┬───┬───┬───┼───┬───┬───┬───┬───┤
│           │          │ C │ H │ M │ L │ U │ C │ H │ M │ L │ U │ C │ H │ M │ L │ U │
└───────────┴──────────┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┘
Severities: C=CRITICAL H=HIGH M=MEDIUM L=LOW U=UNKNOWN
```
and
```
┌───────────┬────────────────────┬──────────────────────┬────────────────────┬───────────────────┐
│ Namespace │      Resource      │   Vulnerabilities    │ …
```
> fix(k8s): summary report when when only vulns exit

- docs/docs/kubernetes/operator/installation/helm.md
- docs/docs/kubernetes/operator/installation/kubectl.md
- mkdocs.yml
Fixes the version in the trivy-operator docs. Don't use git.tag, use the `var.operator_version`
> docs: fix the operator version

- docs/docs/integrations/gitlab-ci.md
In GitLab 15.0, the integration with Trivy was moved to the free tier. Include this information in the Trivy docs so that users can benefit from a simpler, and GitLab-maintained, CI template.
- Related to https://github.com/aquasecurity/trivy/issues/1598
> docs(vuln): Include GitLab 15.0 integration

- go.mod
- go.sum
Update docker/distribution to allow building again.
The 2.8.1 release of docker/distribution was tagged to fix the issue linked below.
Release Notes: https://github.com/distribution/distribution/releases/tag/v2.8.1
- Close #2173
> fix(deps): update docker/distribution from 2.8.0 to 2.8.1

- contrib/gitlab-codequality.tpl
```
n:~/Documents/Repos/trivy-template$ ./trivy version
Version: 0.28.0
n:~/Documents/Repos/trivy-template$ ./trivy fs --security-checks config,vuln         --severity HIGH,CRITICAL --format template         --template "@contrib/gitlab-codequality.tpl"         --output raw-report.json .
2022-05-25T13:30:15.633+0100    FATAL   report error: unable to write results: failed to write results: failed to write with template: template: output template:65:34: executing "output template" at <.IacMetadata.StartLine>: can't evaluate field IacMetadata in type types.DetectedMisconfiguration
```
v0.28 updates the report output format specifically  IACMetadata -> CauseMetadata, update template to match
> fix(report): misconfig start line for code quality tpl

- pkg/detector/ospkg/redhat/redhat.go
RedHat may have several advisories for package.
We should always use advisory with fixed version if there is one.
- Close #2085
> fix(redhat): always use vulns with fixed version if there is one

- pkg/report/table.go
If Trivy found misconf, but they were removed in filter(e.g. by severity), then this is a panic.
For example:
```
➜  trivy -d config ./secrets.tf 
2022-05-27T17:55:32.479+0600	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-05-27T17:55:32.479+0600	DEBUG	cache dir:  /home/dmitriy/.cache/trivy
2022-05-27T17:55:32.479+0600	DEBUG	Vulnerability type:  []
2022-05-27T17:55:32.534+0600	DEBUG	OS is not detected.
2022-05-27T17:55:32.534+0600	INFO	Detected config files: 1
2022-05-27T17:55:32.534+0600	DEBUG	Scanned config file: secrets.tf
secrets.tf (terraform)
Tests: 1 (SUCCESSES: 0, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
LOW: Secret explicitly uses the default key.
═════════════════════════════════════════════════════════════════════════ …
```
> fix(report): fixed panic if all misconf reports were removed in filter

- go.mod
- go.sum
- integration/registry_test.go
testcontainers [has been updated](https://github.com/aquasecurity/fanal/pull/502) from v0.12.0 to v0.13.0 in `fanal`.
`BindMounts` map changed to `Mount`
Fixed integration tests about this.
> test: fixed integration tests after updating testcontainers to v0.13.0

- go.mod
- go.sum
Asymmetric private key can be obtained from any function.
For example([phpseclib/Crypt/RSA.php](https://github.com/phpseclib/phpseclib/blob/2.0.32/phpseclib/Crypt/RSA.php#L881-L883)):
```
...
return "-----BEGIN OPENSSH PRIVATE KEY-----\r\n" .
chunk_split(base64_encode($key), 70) .
"-----END OPENSSH PRIVATE KEY-----";
...
```
Only base64 characters (with `=`) should be used to avoid false positives.
- Close #2190
> fix(secret): asymmetric private keys use only base64 characters

- pkg/k8s/run.go
- pkg/k8s/scanner.go
- fixes log enable/disable after scanning
- fixes timeout warn
before:
after:
- Close https://github.com/aquasecurity/trivy/issues/2169
> fix(k8s): timeout error logging

- docs/docs/kubernetes/cli/scanning.md
- docs/docs/kubernetes/operator/getting-started.md
- docs/docs/kubernetes/operator/troubleshooting.md
- docs/docs/kubernetes/operator/vulnerability-scanning/index.md
- mkdocs.yml
Updated some of the descriptions, referenced namespaces, links in the docs on trivy k8s and removed katacoda since they no longer support it
> docs: clarifying parts of the k8s docs and updating links

- docs/docs/vulnerability/detection/data-source.md
There are similar issues with questions about various vulnerabilities between trivy result and `GitHub database` or why Trivy doesn't get advisories from `GitHub` or `GitLab` databases.
Added information on how Trivy chooses advisory database for package.
> docs: added information about choosing advisory database

- pkg/report/cyclonedx/cyclonedx.go
- pkg/report/cyclonedx/cyclonedx_test.go
For CycloneDX output requires a special  `date-time` format: https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times
Also fixed cases where `cwes == null` in output.
- Close #2026
> fix: fixed incorrect CycloneDX output format

- pkg/commands/operation/operation.go
- pkg/commands/option/cache.go
- pkg/commands/option/cache_test.go
This PR masks the redis credentials when logging here https://github.com/aquasecurity/trivy/blob/b7ec64257279b5f9c47ac02063e12c5305f5af8a/pkg/commands/operation/operation.go#L36
- Close #2081
> fix: mask redis credentials when logging

- helm/trivy/README.md
- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
:wave: this PR adds support for pod annotations in the helm chart
- Close #1889
> feat(helm): support pod annotations

- go.mod
- go.sum
- pkg/report/misconfig_test.go
see here: https://github.com/aquasecurity/fanal/pull/537
> refactor: do not import defsec in fanal types package

- docs/getting-started/installation.md
- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
Before this PR, the only way to grant AWS Permission is by using IAM Role for ServiceAccount.
After this PR, we are able to grant permission with kube2iam or kiam role.
- Close #1889
Just saw the similar PR #2265
> feat(helm): add pod annotations

- integration/client_server_test.go
`client` subcommand is deprecated now. 
so we should update the integration tests and use `image --server`.
> test: replace deprecated subcommand `client` in integration tests

- pkg/log/logger.go
Redirecting all log messages to stderr allows to process output with tools like jq.
A work-around is to pass `--quiet` but then you lose all messages.
Before:
```
trivy sbom --artifact-type fs . | jq .vulnerabilities | head
parse error: Invalid numeric literal at line 1, column 14
```
After:
```
trivy sbom --artifact-type fs . | jq .vulnerabilities | head
2022-06-08T17:44:12.504+0200    INFO    Number of language-specific files: 1
2022-06-08T17:44:12.504+0200    INFO    Detecting gomod vulnerabilities...
[]
```
- Close #381
> feat(cli): use stderr for all log messages

- docs/docs/vulnerability/detection/os.md
- pkg/detector/ospkg/alpine/alpine.go
- pkg/detector/ospkg/redhat/redhat.go
- pkg/detector/ospkg/suse/suse.go
- pkg/detector/ospkg/ubuntu/ubuntu.go
add Alpine Linux 3.16.
https://alpinelinux.org/posts/Alpine-3.16.0-released.html
- before
```console
$ trivy image vuln-alpine:3.16
2022-06-14T23:19:11.654+0900	INFO	Detected OS: alpine
2022-06-14T23:19:11.654+0900	INFO	This OS version is not on the EOL list: alpine 3.16
2022-06-14T23:19:11.654+0900	INFO	Detecting Alpine vulnerabilities...
2022-06-14T23:19:11.658+0900	INFO	Number of language-specific files: 0
vuln-alpine:3.16 (alpine 3.16.0)
```
- after
```console
$ trivy image vuln-alpine:3.16
2022-06-14T23:18:59.406+0900	INFO	Detected OS: alpine
2022-06-14T23:18:59.406+0900	INFO	Detecting Alpine vulnerabilities...
2022-06-14T23:18:59.407+0900	INFO	Number of language-specific files: 0
vuln-alpine:3.16 (alpine 3.16.0)
Total: …
```
> feat(alpine): add Alpine Linux 3.16

- docs/docs/references/cli/client.md
- pkg/commands/app.go
Removes the `--clear-cache` flag from the client mode.
I think this is enough, but let me know if something else is missing
- Close #1860
> fix(flag): remove --clear-cache flag client mode

- pkg/detector/ospkg/alma/alma.go
- pkg/detector/ospkg/alma/alma_test.go
- pkg/detector/ospkg/alma/testdata/fixtures/modular.yaml
As verified by this comment, the appropriate %{MODULARITYLABEL} is set in the modular package for AlmaLinux 8.6 (`module_el8.6` in %{RELEASE}).
https://github.com/aquasecurity/trivy/issues/2342#issuecomment-1158459628
Therefore, the previous skip was done for all modular packages, but now skip is done only when there is a `module_el` in %{RELEASE}, but %{MODULARITYLABEL}=="".
- Close #2342
> feat(alma): support for scanning of modular packages for AlmaLinux

- README.md
Link to installation documentation shows 404:
https://aquasecurity.github.io/trivy/latest/docs/getting-started/installation/
correct link:
https://aquasecurity.github.io/trivy/latest/getting-started/installation/
- Close #XXX
> docs(repo): Link to installation documentation in readme shows 404

- contrib/asff.tpl
This change omits the `Recommendation` field if the `PrimaryURL` is empty, since the Security Hub API fails import if the `Recommendation.Remediation.Url` field is empty.  Please see the related issue for more context. 
Testing: 
The existing integration test case doesn't exercise this change, and I didn't see a simple way to update the `PrimaryURL` of the test image in order to do so (I'm open to feedback on this point).  However, I have tested this change manually by:
- running Trivy and generating ASFF that has an empty `PrimaryURL` (using a local copy of the template)
- encountering the ASFF import error with the Security Hub API
- updating the local copy of the template with this change
- seeing the ASFF import succeed
- [Close …
> fix: Omit Remediation if PrimaryURL is empty

- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/configmap.yaml
- helm/trivy/values.yaml
This adds Helm support for the `dbRepository` flag introduced in https://github.com/aquasecurity/trivy/pull/1873.
- Close #2344 
> feat(helm): add support for trivy dbRepository

- .gitignore
`git` tries to commit `.vscode` folder.
it seems we should ignore it.
> chore: skip Visual Studio Code project folder

- go.mod
- go.sum
- pkg/fanal/artifact/local/testdata/misconfig/cloudformation/passed/src/main.yaml
CloudFormation detection was not strict enough. Now we ensure the `Resources` property in json/yaml is of the correct type before passing the detection test.
Additionally, we ignore invalid json/yaml CF files when parsing a complete filesystem.
- Close #2382
> fix(misconf): Update defsec to v0.68.4 to resolve CF detection bug

- .github/workflows/test.yaml
- go.mod
- go.sum
Trivy fails to parse `Gemfile.lock` dependencies when the platform details are appended to the version string.
For example, run Trivy on this Rails [Gemfile.lock](https://github.com/rails/rails/blob/7f93661551b4e0bfa5296671e5eaf70efb21af0e/Gemfile.lock):
```
$ trivy fs Gemfile.lock
...
2022-06-22T14:50:44.264-0400	WARN	RubyGems version error (1.13.3-x86_64-darwin): invalid gem version
2022-06-22T14:50:44.264-0400	WARN	RubyGems version error (1.13.3-x86_64-linux): invalid gem version
...
```
As a result, checks are skipped from for those dependencies.
This update to [go-dep-parser](https://github.com/aquasecurity/go-dep-parser) drops the platform string that is appended to versions, so version checks and comparisons can be performed.
e.g. `1.13.3-x86_64-darwin` -> `1.13.3`
(This is …
> feat(ruby): drop platform strings from dependency versions bundled with bundler v2

- helm/trivy/Chart.yaml
But Helm chart appVersion to the latest trivy release.
If the Helm chart is published with releases of trivy, I would expect some automation to ensure the appVersion is kept up-to-date? Is this apparently not working because that automation is not implemented yet, or is there a bug somewhere? @krol3
> chore(helm): bump appVersion to latest release

- pkg/commands/server/run.go
- pkg/rpc/server/listen.go
A new db client in server mode didn't set up a custom repository, but we should do it for hot updates.
https://github.com/aquasecurity/trivy/blob/57ed5774590434acc8becfb131338f5889cab749/pkg/rpc/server/listen.go#L53
- Close #2376
> fix(server): hot update the db from a custom repository

- pkg/detector/ospkg/suse/suse.go
SUSE SLES 15.4 and OpenSUSE 15.4 were released, so this PR updates its EOL dates and also for SLES 15.3.
- Close https://github.com/aquasecurity/trivy/issues/2402
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
> chore(suse): update EOL dates for SUSE SLES 15.3, 15.4 and OpenSUSE 15.4

- docs/docs/index.md
- docs/docs/vulnerability/detection/language.md
- docs/getting-started/overview.md
This PR completes the PR #2414 adding references to the support of pnpm in the documentation.
I think this is all that is needed to reflect pnpm support, if I should update something else in the documentation let me know.
> docs(nodejs): add docs about pnpm support

- pkg/commands/artifact/run.go
Looks like we were prefixing the version string with an extra `v` at some point.
This removes it 😄 
Before:
After:
> fix(cli): fix version string in docs link when secret scanning is enabled

- pkg/fanal/secret/builtin-rules.go
Remove spaces from regex for asymmetric private key
- Close #2427
> fix(secret): remove spaces from asymmetric private key

- ci/deploy-rpm.sh
`Red Hat UBI 9` released.
Add RHEL 9 to rpm deploy.
Tested in fork:
- https://github.com/DmitriyLewen/trivy/runs/7148839349?check_suite_focus=true
- https://github.com/DmitriyLewen/trivy-repo/tree/main/rpm/releases/9/x86_64
- Close #2426
> ci: add rhel 9 to rpm deploy

- docs/docs/kubernetes/operator/index.md
- docs/index.md
the content about `trivy-operator` was removed #2372, but there are some links.
some links to `kubernetes.io` didn't build correctly.
also PR #2110 removed some gifs, but there is mention on the home page.
- Close #2417
> docs: remove links to removed content

- go.mod
- go.sum
- pkg/module/module.go
Updates to latest wazero and also removes redundant close already done by the runtime.
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [n/a] I've added usage information (if the PR introduces new options)
- [n/a] I've included a "before" and "after" example to the description (if the PR is a user interface change).
> chore(deps): bump wazero to latest main

- pkg/flag/remote_flags.go
`tokenHeader` was always empty by default. 
also there was a wrong warning for `server` mode:
```sh
$ trivy server --token testtoken
2022-07-06T16:14:08.866+0600    WARN    "--token" can be used only with "--server"
2022-07-06T16:14:08.870+0600    INFO    Listening localhost:4954...
```
> fix: update initialisation of remote options

- pkg/flag/remote_flags.go
it seems we should check a length of custom headers after getting it from `viper`:
https://github.com/aquasecurity/trivy/blob/27c5227e1c9aba223ada086d2da13d36b59e9739/pkg/flag/remote_flags.go#L85-L93
> fix: check of custom headers length after `viper`

- pkg/flag/remote_flags.go
We shouldn't show warnings about a token and headers for `server` subcommand too.
> fix: don't show warnings for server mode

- pkg/commands/app.go
show help on using the command when an invalid flag is encountered. For example:
```
➜  ./trivy image --invalid-flag 
scan a container image
Usage:
trivy image [flags] IMAGE_NAME
Aliases:
image, i
Flags:
--cache-backend string        cache backend (e.g. redis://localhost:6379) (default "fs")
--cache-ttl duration          cache TTL when using redis as cache backend
--clear-cache                 clear image caches without scanning
--config-data strings         specify paths from which data for the Rego policies will be recursively loaded
--config-policy strings       specify paths to the Rego policy files directory, applying config files
--custom-headers strings      custom headers in client mode
--db-repository string        OCI repository to retrieve trivy-db from" (default …
```
> feat(cli): add usage info for invalid command flag

- pkg/commands/artifact/run.go
disable db download for `--reset` and `--clear-cache` flags
> fix(cli): disable db download for reset and clear-cache flags

- pkg/commands/app.go
- pkg/flag/cache_flags.go
- pkg/flag/db_flags.go
- pkg/flag/image_flags.go
- pkg/flag/kubernetes_flags.go
- pkg/flag/misconf_flags.go
- pkg/flag/options.go
- pkg/flag/remote_flags.go
- pkg/flag/report_flags.go
- pkg/flag/report_flags_test.go
- pkg/flag/sbom_flags.go
- pkg/flag/scan_flags.go
- pkg/flag/scan_flags_test.go
- pkg/flag/secret_flags.go
- pkg/flag/vulnerability_flags.go
- pkg/flag/vulnerability_flags_test.go
Improve usage messages by grouping flags.
As it is not yet implemented in cobra, this PR implemented flag groups on Trivy's end.
https://github.com/spf13/cobra/issues/1327
```
$ trivy image -h
...
Flags:
--cache-backend string        cache backend (e.g. redis://localhost:6379) (default "fs")
--cache-ttl duration          cache TTL when using redis as cache backend
--clear-cache                 clear image caches without scanning
--config-data strings         specify paths from which data for the Rego policies will be recursively loaded
--config-policy strings       specify paths to the Rego policy files directory, applying config files
--custom-headers strings      custom headers in client mode
--db-repository string        OCI repository to retrieve trivy-db from" (default …
```
> feat: add support for flag groups

- docs/docs/references/cli/client.md
- docs/docs/references/cli/config.md
- docs/docs/references/cli/fs.md
- docs/docs/references/cli/image.md
- docs/docs/references/cli/index.md
- docs/docs/references/cli/module.md
- docs/docs/references/cli/plugin.md
- docs/docs/references/cli/repo.md
- docs/docs/references/cli/rootfs.md
- docs/docs/references/cli/sbom.md
- docs/docs/references/cli/server.md
- docs/docs/references/customization/config-file.md
- docs/docs/references/customization/envs.md
- examples/trivy-conf/trivy.yaml
- mkdocs.yml
- pkg/commands/app.go
- pkg/flag/global_flags.go
- pkg/flag/misconf_flags.go
Add a description and an example of `trivy.yaml`.
> docs: add config file and update CLI references

- docs/docs/vulnerability/detection/data-source.md
- docs/docs/vulnerability/detection/os.md
- pkg/detector/ospkg/amazon/amazon.go
- pkg/detector/ospkg/amazon/amazon_test.go
- pkg/detector/ospkg/amazon/testdata/fixtures/amazon.yaml
- pkg/detector/ospkg/amazon/testdata/fixtures/data-source.yaml
- pkg/fanal/analyzer/os/amazonlinux/amazonlinux.go
- pkg/fanal/analyzer/os/amazonlinux/amazonlinux_test.go
add support for Amazon Linux 2022
```
➜ trivy image --severity HIGH public.ecr.aws/amazonlinux/amazonlinux:2022.0.20220308.1
2022-06-30T17:37:25.120+0600    INFO    Vulnerability scanning is enabled
2022-06-30T17:37:25.120+0600    INFO    Secret scanning is enabled
2022-06-30T17:37:25.120+0600    INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-06-30T17:37:25.120+0600    INFO    Please see also https://aquasecurity.github.io/trivy/dev/docs/secret/scanning/#recommendation for faster secret detection
2022-06-30T17:37:26.855+0600    INFO    Detected OS: amazon
2022-06-30T17:37:26.855+0600    INFO    Detecting Amazon Linux vulnerabilities...
2022-06-30T17:37:26.857+0600    INFO    Number of language-specific files: 0 …
```
> feat(amazon): add support for 2022 version

- docs/docs/vulnerability/examples/report.md
- pkg/commands/app.go
- pkg/flag/report_flags.go
- pkg/report/writer.go
`--dependency-tree` flag is currently only supported by `fs` or `repo` commands. Also, only `package-lock.json` files are currently supported.
- Remove `--dependency-tree` flag for `image` and `sbom` subcommand.
- Update docs(add info about supported subcommands)
- Add info message when using `--dependency-tree` flag.
- Close #2491
> fix: remove dependency-tree flag for image subcommand

- pkg/fanal/walker/walk.go
- pkg/licensing/normalize.go
Currently `vendor` dir is skipped, but some dependencies and licenses are stored in `vendor`.
> fix: scan vendor dir

- pkg/k8s/commands/cluster.go
- pkg/k8s/commands/namespace.go
- pkg/k8s/commands/resource.go
- pkg/k8s/commands/run.go
- pkg/k8s/report/report.go
This change hides summary reports when scanning single resources only. I didn't make it a flag, because a flag would have to be consistent cross command, and the idea is that when you doing a scan for specific resource you see only the report you care about. Eg:
if you scanning, only roles, you only see rbac assesment:
```
trivy k8s clusterrole trivy-operator --report=summary -n kube-system
1 / 1 [----------------------------------------------------------------------------------------------------------] 100.00% ? p/s
┌───────────┬────────────────────────────┬───────────────────┐
│ Namespace │          Resource          │  RBAC Assessment  │
│           │                            ├───┬───┬───┬───┬───┤
│ …
```
> fix: hide empty report when scanning resource

- pkg/commands/app.go
before:
```sh
$ trivy plugin Uninstall demo-trivy-plgn
```
after
```sh
$ trivy plugin uninstall demo-trivy-plgn
```
> fix: change a capital letter for `plugin uninstall` subcommand

- pkg/commands/app.go
We bind flags and environment variables manually, so we don't need to use viper.AutomaticEnv.
- Close a part of #2525
> fix(cli): remove auto configure environment variables via viper

- pkg/flag/scan_flags.go
the initial values for `--skip-dirs` and `--skip-files` were `string` instead of `[]string`
- Close #2529
> fix(flag): change a value type for `--skip-dirs` and `--skip-files`

- go.mod
- go.sum
- integration/fs_test.go
- integration/testdata/fixtures/fs/helm_badname/Chart.yaml
- integration/testdata/helm_badname.json.golden
No longer assumes the name attribute of the Chart.yaml is going to be a string
Added a test to support
- Close #2459
> fix: yaml files with non-string chart name

- docs/index.md
The demo videos in [v0.30.0](https://aquasecurity.github.io/trivy/v0.30.0/) do not play automatically because the video tag lacks some attributes for autoplay.
I have added the following attributes:
- [autoplay](https://www.w3schools.com/tags/tag_video.asp): play video automatically 
- [muted](https://www.w3schools.com/tags/att_video_muted.asp): some browsers require this attribute for autoplay ([ref](https://www.w3schools.com/tags/att_video_autoplay.asp))
- [loop](https://www.w3schools.com/tags/att_video_loop.asp): play the video again when finished 
- [controls](https://www.w3schools.com/tags/att_video_controls.asp): display control buttons such as a play/pause button
I built the mkdocs server locally and checked that the demo video played automatically with chrome and firefox.
> docs: add attributes to the video tag to autoplay demo videos

- pkg/detector/ospkg/rocky/rocky.go
Rocky Linux 9.0 is now GA and EOL is set.
https://rockylinux.org/news/rocky-linux-9-0-ga-release/
> feat(rocky): set Rocky Linux 9 EOL

- pkg/fanal/analyzer/licensing/license.go
- pkg/fanal/analyzer/pkg/dpkg/copyright.go
- pkg/licensing/classifier.go
- pkg/licensing/classifier_test.go
Loading license classifiers are expensive. It should be done only when license scanning is needed.
- Close #2525
> fix(license): lazy loading of classifiers

- pkg/flag/options.go
Trivy env variables currently include "-"  instead of "_". 
Added replacement for these envs.
- Close #2559
> fix(cli): replace '-' to '_' for env vars

- docs/docs/attestation/sbom.md
Improve SBOM attestation documentation by better output file names.
> docs(sbom): improve sbom attestation documentation

- pkg/k8s/commands/run.go
- pkg/k8s/report/report.go
- pkg/k8s/scanner/scanner.go
Enabling logs for k8s mode and increasing log level for the failed image scans from debug to warning. Should it be even error?
@josedonizetti mentioned that logging was disabled to not mess the output of report. But it looks like logs are printed before the reports, so looks fine for me. Please let me know if I'm missing anything.
```
❯ ./trivy k8s -n prod --security-checks vuln deployment/<deployment name>
1 / 1 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 2 p/s
```
```
❯ ./trivy k8s -n prod --security-checks vuln deployment/<deployment name>
2022-07-15T10:15:50.115+0300	INFO	Vulnerability scanning is enabled
1 / 1 …
```
> fix(k8s): no error logged if trivy can't get docker image in kubernetes mode

- .github/workflows/test.yaml
- pkg/module/module.go
When we use tinygo in the latest version 0.24.0, unit tests fail because tinygo uses some new features(https://github.com/tinygo-org/tinygo/pull/2911) and the runtime needs to enable these features.
We got the following error message when we executed a wasm binary built by tinygo 0.24.0 on Trivy's wasm runtime.
```
invalid function[11]: memory.copy invalid as feature "bulk-memory-operations" is disabled
```
This PR enables required features when using tinygo 0.24.0.
I checked I could pass the unit tests with tinygo 0.24.0. I also checked the tinygo 0.23.0 for backward compatibility, and it was fine.
- Close https://github.com/aquasecurity/trivy/issues/2570
> fix: enable some features of the wasm runtime

- pkg/fanal/analyzer/const.go
Added missing types from TypeOSes and TypeLanguages in analyzer.
> fix: add missing types in TypeOSes and TypeLanguages in analyzer

- cmd/trivy/main.go
- pkg/commands/app.go
- pkg/plugin/plugin.go
After cobra migration, it shows the following error.
```
$ TRIVY_RUN_AS_PLUGIN='aqua' ./trivy fs .
Error: unknown command "fs" for "trivy"
Usage:
trivy [global flags] command [flags] target
Examples:
$ trivy image python:3.4-alpine
$ trivy image --input ruby-3.1.tar
$ trivy fs .
$ trivy server
Flags:
--cache-dir string          cache directory (default "/Users/teppei/Library/Caches/trivy")
-c, --config string             config path (default "trivy.yaml")
-d, --debug                     debug mode
-f, --format string             version format (json)
--generate-default-config   write the default config to trivy-default.yaml
-h, --help                      help for trivy
--insecure                  allow insecure server connections when using TLS
-q, --quiet                     suppress …
```
> fix: allow subcommands with TRIVY_RUN_AS_PLUGIN

- pkg/flag/report_flags.go
- pkg/flag/report_flags_test.go
`--severity` flag doesn't accept lowercase strings:
```sh
$ trivy image --severity high alpine:3.15.1
2022-07-21T19:41:18.737+0600	WARN	unknown severity option: unknown severity: high
```
fixed.
> fix(flag): severity flag accepts lowercase

- pkg/types/report.go
Currently the license check ignores the configured exit code; this fix add the license check
- Close #2562
> feat(report): export exitcode for license checks

- docs/build/Dockerfile
- docs/build/requirements.txt
- docs/docs/advanced/air-gap.md
- docs/docs/vulnerability/examples/report.md
- mkdocs.yml
In `oras v0.13.0` the `-a/--allow-all` behavior is set by default and these flags have been removed(https://github.com/oras-project/oras/pull/387).
Also `grouping code blocks` was used:
e.g.:
- Close #2580
> docs: split commands to download db for different versions of oras

- docs/docs/advanced/air-gap.md
User can use `--download-db-only` flag to download `trivy-db` to use in Air-Gapped Environment.
Added command for this.
> docs: add trivy with download-db-only flag to Air-Gapped Environment

- contrib/gitlab.tpl
- docs/docs/integrations/gitlab-ci.md
- integration/testdata/alpine-310.gitlab.golden
- Upgrade to schema 14.0.6 (https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/v14.0.6/dist/container-scanning-report-format.json).
- Drop unsupported `confidence` property. Currently optional and will be removed by GitLab in schema 15-0-0.
I've generated a test report using:
```
trivy image --exit-code 0 --security-checks vuln --format template --template "@contrib/gitlab.tpl" -o gl-container-scanning-report.json webgoat/webgoat-8.0:latest
```
And I've [validated locally](https://docs.gitlab.com/ee/development/integrations/secure.html#validate-locally):
```
Thiagos-MacBook-Pro:tmp thiago$ ruby validate.rb container-scanning-report-format_14-0-6.json ~/repos/aquasecurity/trivy/gl-container-scanning-report.json
property '/vulnerabilities/8/identifiers/0/url' …
```
> fix(vuln): GitLab report template

- cmd/trivy/main.go
Remove the first argument if TRIVY_RUN_AS_PLUGIN is set.
> fix: remove the first arg when running as a plugin

- docs/docs/vulnerability/distributions.md
Add example with `fs` subcommand.
Use `cbl-mariner 2.0` in examples.
> docs(mariner): use v2.0 in examples

- integration/fs_test.go
- integration/testdata/dockerfile_file_pattern.json.golden
- integration/testdata/fixtures/fs/dockerfile_file_pattern/Customfile
- pkg/fanal/handler/misconf/misconf.go
Resolves #2608
Fixes use of the `--file-patterns` flag. Defsec detection is now overridden when a custom file pattern is provided for the file type.
- Close #2608
> fix: Fix --file-patterns flag

- docs/docs/references/cli/client.md
- docs/docs/references/cli/fs.md
- docs/docs/references/cli/image.md
- docs/docs/references/cli/repo.md
- docs/docs/references/cli/rootfs.md
- docs/docs/references/cli/sbom.md
- docs/docs/references/cli/server.md
- pkg/flag/db_flags.go
`--db-repository` option contained extra double quotation marks, which were making [the cli reference](https://aquasecurity.github.io/trivy/v0.30.4/docs/references/cli/server/) look bad.
So this PR has removed unnecessary double quotations.
> docs: remove unnecessary double quotation marks

- docs/docs/vulnerability/distributions.md
`yum` is deprecated, and not available in Mariner
certificates do not exist, used `ca-certificates`
> docs(mariner): use tdnf in fs usage example

- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/secret.yaml
- helm/trivy/templates/statefulset.yaml
- helm/trivy/values.yaml
Signed-off-by: cebidhem <cebidhem@pm.me>
This will allow the users of the Helm chart to define an existing secret containing the env variables `GITHUB_TOKEN` `TRIVY_TOKEN` `TRIVY_USERNAME` `TRIVY_PASSWORD` as it is quite common for us to use external tools for creating secrets (could be external-secret or something else).
This would allow us to avoid putting tokens in a git repo.
I haven't seen a helm doc generator - but it's my very first PR here so I may have missed it - but I added it manually in the README.md of the chart.
I bumped the `appVersion` as it was quite old. Let me know if you'd rather do it in a separate PR.
I also bumped the Chart `version`, because I haven't seen a job under ci/ doing it. Let me know if it was wrong.
I tested locally with `helm template`, again let me …
> feat(helm): allows users to define an existing secret for tokens

- docs/docs/advanced/air-gap.md
> docs: improve formatting

- pkg/detector/ospkg/oracle/oracle.go
Set Oracle Linux 9 EOL
ATTENTION! merge only after adding advisories to `trivy-db`
> feat(oracle): set Oracle Linux 9 EOL

- go.mod
- go.sum
- integration/testdata/helm.json.golden
- integration/testdata/helm_testchart.json.golden
- pkg/fanal/handler/misconf/misconf.go
Resolves #2622
Regular expression for WORKDIR used in the rego rule in defsec did not allow quotes - now it does.
- Close #2622
> fix(misconf): Allow quotes in Dockerfile WORKDIR when detecting relative dirs

- docs/docs/kubernetes/cli/scanning.md
- go.mod
- go.sum
- pkg/flag/kubernetes_flags.go
- pkg/k8s/commands/run.go
> feat(kubernetes): add option to specify kubeconfig file path

- docs/docs/secret/configuration.md
- docs/docs/secret/scanning.md
- Fixed missing and broken links in secret scanning docs
- Change ref to trivy repo instead of archived fanal repo
Before:
After:
> docs(secret): fix missing and broken links

- pkg/sbom/cyclonedx/testdata/happy/empty-metadata-component-bom.json
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/sbom/cyclonedx/unmarshal_test.go
Add nil check for "metadata.component"
- Close #2654
> fix(cyclonedx): add nil check to metadata.component

- contrib/junit.tpl
Add explicit name="trivy" in the first testsuite element
- Close #2678
> fix(report): Update junit.tpl

- pkg/fanal/walker/tar.go
`symlinks` and `hardlinks` have no content in tar reader.
Skip them.
> chore(image): skip symlinks and hardlinks from tar scan

- docs/docs/misconfiguration/options/values.md
- docs/docs/references/customization/config-file.md
- go.mod
- go.sum
- integration/fs_test.go
- integration/testdata/fixtures/fs/helm_values/values.yaml
- integration/testdata/helm_testchart.overridden.json.golden
- mkdocs.yml
- pkg/commands/artifact/run.go
- pkg/fanal/analyzer/config/config.go
- pkg/fanal/handler/misconf/misconf.go
- pkg/flag/misconf_flags.go
Add support for passing variable files for configuration scanning
**Terraform**
Pass `--tf-vars` to override default terraform values
**Helm**
Support standard helm install flags (with the `helm` prefix)
`--helm-set`
`--helm-values`
`--helm-set-string`
`--helm-set-file`
- Close #2276
> feat: Support passing value overrides for configuration checks

- pkg/rpc/convert.go
The server ftypes scan result when converted to RPC response using method ConvertToRPCScanResponse(), were dropping customerResources in conversion. This commit fixes the method to consider customResources as well
> fix(server): scanResponse rpc conversion for custom resources

- docs/docs/attestation/sbom.md
- docs/docs/sbom/index.md
I've improved SBOM docs by adding a description for scanning SBOM attestation.
> docs(sbom): improve SBOM docs by adding a description for scanning SBOM attestation

- docs/docs/attestation/vuln.md
Specify the type when verifying an attestation because Cosign command will fail without the type option.
> docs: specify the type when verifying an attestation

- Makefile
- docs/docs/vulnerability/distributions.md
- go.mod
- go.sum
- goreleaser-canary.yml
- goreleaser.yml
- pkg/commands/artifact/run.go
Fixes the URL in the logs of the scanner
- Close #2606
```bash
2022-07-27T18:57:49.498+0530	INFO	Vulnerability scanning is enabled
2022-07-27T18:57:49.498+0530	INFO	Secret scanning is enabled
2022-07-27T18:57:49.498+0530	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-27T18:57:49.498+0530	INFO	Please see also https://aquasecurity.github.io/trivy/0.30.4/docs/secret/scanning/#recommendation for faster secret detection
```
```bash
2022-07-27T18:57:49.498+0530	INFO	Vulnerability scanning is enabled
2022-07-27T18:57:49.498+0530	INFO	Secret scanning is enabled
2022-07-27T18:57:49.498+0530	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-27T18:57:49.498+0530	INFO	Please see also …
```
> fix(cli): secret scanning perf link fix

- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
When the first application has no vulnerability, it exits from the scanning function and returns no vulnerability even though other applications have vulnerabilities.
> fix(vuln): continue scanning when no vuln found in the first application

- pkg/flag/options.go
- pkg/flag/scan_flags.go
- pkg/flag/scan_flags_test.go
Trivy doesn't stop scan if `--security-checks` flag has only unsupported values.
We need to return error when parsing the flags.
Before: 
```
➜ trivy -d image --security-checks conf alpine:3.14.3           
2022-08-16T10:41:50.312+0600    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-08-16T10:41:50.312+0600    WARN    unknown security check: conf
2022-08-16T10:41:50.315+0600    DEBUG   cache dir:  /home/dmitriy/.cache/trivy
2022-08-16T10:41:50.316+0600    DEBUG   Module dir: /home/dmitriy/.trivy/modules
2022-08-16T10:41:52.786+0600    DEBUG   Image ID: sha256:0a97eee8041e2b6c0e65abb2700b0705d0da5525ca69060b9e0bde8a3d17afdb
2022-08-16T10:41:52.786+0600    DEBUG   Diff IDs: [sha256:1a058d5342cc722ad5439cacae4b2b4eedde51d8fe8800fcf28444302355c16d] …
```
> feat(flag): add error when there are no supported security checks

- go.mod
- go.sum
- pkg/cloud/aws/commands/run.go
Update to [v0.71.8](https://github.com/aquasecurity/defsec/releases/tag/v0.71.8) to fix handling of 403s etc. in AWS API.
Resolves #2725 
Resolves #2728
> fix: Correctly handle recoverable AWS scanning errors

- README.md
- docs/getting-started/installation.md
`trivy` is also available via [MacPorts](https://www.macports.org) on macOS.  This PR adds information on how to install it that way.
> docs: add MacPorts install instructions

- Dockerfile
- Dockerfile.canary
Upgrade Alpine to 3.16.2 to fix the zlib security issue
> chore(deps): Upgrade Alpine to 3.16.2 to fix zlib issue

- integration/testdata/dockerfile-rule-exception.json.golden
- integration/testdata/dockerfile.json.golden
- integration/testdata/dockerfile_file_pattern.json.golden
- integration/testdata/helm.json.golden
- integration/testdata/helm_testchart.json.golden
- integration/testdata/helm_testchart.overridden.json.golden
- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/handler/misconf/misconf.go
- pkg/fanal/types/misconf.go
- pkg/result/filter.go
- pkg/scanner/local/scan.go
- pkg/types/misconfiguration.go
`Trivy` can skip misconfigurations only by ID from rego files. 
but the customer may not know this ID #2711, because [avd.aquasec.com](https://avd.aquasec.com/) contains only `AVD ID`.
so `Trivy` should skip misconfigurations by `AVD ID` too.
> feat(misconf): skipping misconfigurations by AVD ID

- pkg/commands/artifact/run.go
```
trivy k8s --security-checks=rbac --report=summary cluster
178 / 178 [--------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 4 p/s
┌──────────────┬─────────────────────────────────────────────────────────────────┬───────────────────┐
│  Namespace   │                            Resource                             │  RBAC Assessment  │
│              │                                                                 ├───┬───┬───┬───┬───┤
│              │                                                                 │ C │ H │ M │ L │ U │
├──────────────┼───────────────────────────────────────────────────────── …
```
> fix: fix k8s rbac filter

- go.mod
- go.sum
- pkg/fanal/analyzer/language/rust/binary/binary_test.go
See [#116](https://github.com/aquasecurity/go-dep-parser/pull/116)
- Close #2430
> fix(java): check depManagement from upper pom's

- pkg/k8s/report/summary.go
only vuln:
```
trivy k8s -n kube-system --security-checks=vuln --report=summary Pod/kube-apiserver-minikube
1 / 1 [----------------------------------------------------------------------------------------------------------------------] 100.00% 0 p/s
┌───────────┬──────────┬───────────────────┐
│ Namespace │ Resource │  Vulnerabilities  │
│           │          ├───┬───┬───┬───┬───┤
│           │          │ C │ H │ M │ L │ U │
└───────────┴──────────┴───┴───┴───┴───┴───┘
Severities: C=CRITICAL H=HIGH M=MEDIUM L=LOW U=UNKNOWN
```
only config:
```
trivy k8s -n kube-system --security-checks=config --report=summary Pod/kube-apiserver-minikube
1 / 1 [-------------------------------------------------------------------- …
```
> fix: fix k8s summary report

- pkg/fanal/image/daemon/image.go
- pkg/fanal/image/daemon/image_test.go
Added logic to detect empty layers.
Logic is taken from [buildkit](https://github.com/moby/buildkit/blob/2942d13ff489a2a49082c99e6104517e357e53ad/frontend/dockerfile/dockerfile2llb/convert.go).
> fix(image): add logic to detect empty layers

- go.mod
- go.sum
- pkg/module/module.go
This updates [wazero](https://wazero.io) to 1.0.0-pre.1
A new pre-release will happen at least once each month until 1.0 in February 2023.
Note: [Release notes](https://github.com/tetratelabs/wazero/releases) will be posted in the next day or two.
Meanwhile, we've also opened a [gophers slack](https://gophers.slack.com/) `#wazero` channel for support, updates and conversation! Note: You may need an [invite](https://invite.slack.golangbridge.org/) to join gophers.
> build: updates wazero to 1.0.0-pre.1

- docs/docs/integrations/azure-devops.md
- mkdocs.yml
> chore: improve doc about azure devops

- .github/workflows/test.yaml
- goreleaser.yml
The current goreleaser configuration leverages cosign to sign the
goreleaser container manifests using public sigstore infrastructure.
This is great!
This PR also signs the rest of the releaser artifacts (binaries, sbom
file, etc), so we can verify them using the aforementioned public
infrastructure. This is very useful for folks consuming the binaries
from the public GitHub releases.
Note that this assumes that the OIDC issuer is GitHub, and thus ties
this signature to be triggered a GitHub action.
- Closes #2788
> build(): Sign releaser artifacts, not only container manifests

- helm/trivy/README.md
- helm/trivy/templates/configmap.yaml
- helm/trivy/values.yaml
Enables users to configure the cache TTL with a new helm value.
- Close #2797 
Signed-off-by: elchenberg <elchenberg@users.noreply.github.com>
> feat(helm): make cache TTL configurable

- contrib/asff.tpl
- docs/docs/integrations/aws-security-hub.md
- Close https://github.com/aquasecurity/trivy/issues/2781
> fix: update ProductArn with account id

- go.mod
- go.sum
- pkg/commands/artifact/run.go
- pkg/fanal/analyzer/all/import.go
- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/analyzer_test.go
- pkg/fanal/analyzer/secret/secret.go
- pkg/fanal/analyzer/secret/secret_test.go
- pkg/fanal/artifact/artifact.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/image_test.go
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/artifact/remote/git_test.go
- pkg/fanal/secret/scanner.go
- pkg/fanal/secret/scanner_test.go
- pkg/module/module_test.go
Add a new interface for initializing analyzers
- Close https://github.com/aquasecurity/trivy/issues/2834
> refactor: add a new interface for initializing analyzers

- .github/workflows/publish-chart.yaml
- helm/trivy/values.yaml
- Update versions in the publish-chart gh
- Update the ingress test flag in publish-chart gh
- Disabled the PodSecurtyPolicy by default
> chore(helm): helm test with ingress

- go.mod
- go.sum
Helm scanning was not correctly unpacking dependencies tars to the right place. This is fixed in defsec
Signed-off-by: Owen Rumney <owen.rumney@aquasec.com>
- Resolves #2850
> fix: Scan tarred helm dependencies

- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
- .golangci.yaml
- Dockerfile.protoc
- Makefile
- go.mod
- pkg/fanal/analyzer/pkg/rpm/rpm.go
- pkg/fanal/artifact/sbom/sbom.go
- pkg/fanal/test/integration/library_test.go
- pkg/fanal/test/integration/testdata/goldens/packages/opensuse-leap-151.json.golden
- pkg/fanal/test/integration/testdata/goldens/packages/suse-15.3_ndb.json.golden
- pkg/flag/cache_flags.go
- pkg/flag/misconf_flags.go
- pkg/flag/options.go
- pkg/flag/report_flags.go
- pkg/k8s/commands/run.go
- pkg/sbom/cyclonedx/unmarshal.go
> chore: bump Go to 1.19

- .github/workflows/reusable-release.yaml
The source code needs to be checked out before setting up Go as `go-version-file` refers to `go.mod`.
The above PR introduced the issue.
> build: checkout before setting up Go

- docs/docs/integrations/aws-security-hub.md
This doesn't really solve anything but points out issue and proposes work around. If someone has an actual fix I would really appreciate it
- Close #2849
> docs: batch-import-findings limit

- contrib/asff.tpl
- docs/docs/integrations/aws-security-hub.md
This PR fixes the issues introduced in #2782. My understanding was that it was required to use the default ARN. This turns out not to be true. The PR fixes those issues and adds documentation for said issue as well as the required use of [enable-import-findings-for-product](https://docs.aws.amazon.com/cli/latest/reference/securityhub/enable-import-findings-for-product.html)
> fix: revert asff arn and add documentation

- README.md
- docs/getting-started/installation.md
Since have a trivy on archlinux official communtiy repository, why not recommend to install using pacman?
```bash
docker run -it --rm archlinux bash -c "pacman -Sy && pacman -Sy --noconfirm trivy"
```
- Close #XXX
> docs: update archlinux commands

- go.mod
- go.sum
Bumps github.com/aquasecurity/go-dep-parser to match the current tip of the main branch.
- n/a
> fix(c): support revisions in Conan parser

- go.mod
- go.sum
- integration/testdata/helm.json.golden
- integration/testdata/helm_testchart.json.golden
- integration/testdata/helm_testchart.overridden.json.golden
bump defsec v0.75.3 supprting outdated-api
output example:
```console
$ trivy fs ./scanjob.yaml
scanjob.yaml (kubernetes)
Tests: 79 (SUCCESSES: 66, FAILURES: 13, EXCEPTIONS: 0)
Failures: 13 (UNKNOWN: 0, LOW: 10, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
HIGH: apiVersion 'batch/v1beta1' and kind ‘CronJob' should be replaced with the new API ‘batch.v1.CronJob'
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
apiVersion 'batch/v1beta1' and kind 'CronJob' has been deprecated on: 'v1.21' and planned for removal on:'v1.25'
See …
```
> feat(k8s): support outdated-api

- pkg/commands/artifact/run.go
- pkg/commands/artifact/run_test.go
Now Trivy omits patch versions in the docs now, so we should change the link.
there was added a little test to clarify logic and check casting `Part` to `int`.
> fix: remove a patch number from the recommendation link

- .github/CODEOWNERS
@liamg and @owenrumney are owners on `pkg/flag`, which is why reviews for irrelevant PRs are requested from them. Narrowing the scope to aws_flags.go and misconf_flags.go could be more relevant.
> chore: narrow the owner scope

- docs/docs/attestation/rekor.md
- docs/docs/attestation/sbom.md
- docs/tutorials/kubernetes/kyverno.md
- mkdocs.yml
- pkg/flag/scan_flags.go
Add Rekor SBOM attestation scanning
> docs: add Rekor SBOM attestation scanning

- pkg/commands/app.go
Add `--file-patterns` flag for `config` subcommand after [moving](https://github.com/aquasecurity/trivy/pull/2539) it to `scan` flags.
- Close #2923
> fix(flag): add file-patterns flag for config subcommand

- pkg/flag/options.go
- pkg/flag/options_test.go
- pkg/flag/scan_flags_test.go
- pkg/flag/vulnerability_flags.go
`Viper` always [returns a string](https://github.com/spf13/viper/blob/419fd86e49ef061d0d33f4d1d56d5e2a480df5bb/viper.go#L545-L553) for ENVs.
And it [uses](https://github.com/spf13/cast/blob/2b0eb0f724e320b655240e331aef36d1175986c2/caste.go#L1275-L1276) `strings.Field` to separate values (by space only).
Added separation of env values with ','.
- Close #2922
> fix(cli): split env values with ',' for slice flags

- README.md
Fixed broken link to `integrations section`.
- Close #2913
> docs: fix broken link in readme.md

- pkg/purl/purl.go
- pkg/purl/purl_test.go
- pkg/sbom/cyclonedx/testdata/happy/bom.json
- pkg/sbom/cyclonedx/unmarshal_test.go
`Gradle` package name uses the ":" separator like `Maven`.
- Close #2886
> fix(sbom): fix package name separation for gradle

- pkg/module/module.go
This removes an accidental assignment of memory to the host module. This api has never been used correctly and will be removed from the next wazero release. The actual memory used by host functions is that defined by the guest (%.wasm file).
> fix: Removes accidentally exported wasm memory

- go.mod
- go.sum
See [#136](https://github.com/aquasecurity/go-dep-parser/pull/136)
- Close #2935
> fix(java): use fields of dependency from dependencyManagement from upper pom.xml to parse deps

- pkg/cloud/report/report.go
Signed-off-by: Salvador Cavadini <salvadorcavadini+github@gmail.com>
fix #2966 by using the right slice indexes in the return expression of the Less function passed to sort.Slice
- Close #2966
> fix(go): Less function for slice sorting always returns `false`

- go.mod
- go.sum
- pkg/module/module.go
This updates [wazero](https://wazero.io/) to [1.0.0-pre.2](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.2).
Notably, this simplifies syntax for some common cases.
> chore(go): updates wazero to 1.0.0-pre.2

- pkg/commands/app_test.go
- rpc/cache/service.twirp.go
- rpc/scanner/service.twirp.go
go formatter chaged some files:
```sh
$ go fmt ./...
pkg/commands/app_test.go
rpc/cache/service.twirp.go
rpc/scanner/service.twirp.go
```
> chore: run `go fmt`

- docs/docs/references/troubleshooting.md
Adds a troubleshooting section for choosing a different directory other than `/tmp` when cloning a remote Git repository for scanning.
This is how it looks like in MkDocs:
- Close #2921
> docs(repo): troubleshooting $TMPDIR customization

- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
`serialNumber` field is optional: https://cyclonedx.org/docs/1.4/json/#serialNumber
Changed ref generation if serialNumber is empty when input is cyclonedx file.
- Close #2998
> fix(sbom): ref generation if serialNumber is empty when input is cyclonedx file

- integration/testdata/alpine-310.sarif.golden
- pkg/report/sarif.go
- pkg/report/sarif_test.go
SARIF allows a "message" to be provided for a location and that can have more useful information. See:
https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317675
It would be helpful to set this property so SARIF consumers can display better information. It would be particularly nice if Trivy includes the file and the package name and version (ex, `pom.xml:org.yaml:snakeyaml@1.30`).
- Close #3002
> feat(report): add location.message to SARIF output (#3002)

- docs/docs/misconfiguration/custom/index.md
- docs/docs/misconfiguration/options/values.md
Fix a minor typo and remove extra brank.
> docs(misconf): fix typo

- pkg/fanal/analyzer/pkg/rpm/rpm.go
Manually ran tests before/after this little chage:
```sh
% go test .  -v
=== RUN   TestParseRpmInfo
=== RUN   TestParseRpmInfo/Valid
=== RUN   TestParseRpmInfo/ValidBig
=== RUN   TestParseRpmInfo/ValidWithModularitylabel
--- PASS: TestParseRpmInfo (0.17s)
--- PASS: TestParseRpmInfo/Valid (0.03s)
--- PASS: TestParseRpmInfo/ValidBig (0.05s)
--- PASS: TestParseRpmInfo/ValidWithModularitylabel (0.09s)
=== RUN   Test_splitFileName
=== RUN   Test_splitFileName/valid_name
=== RUN   Test_splitFileName/invalid_name
--- PASS: Test_splitFileName (0.00s)
--- PASS: Test_splitFileName/valid_name (0.00s)
--- PASS: Test_splitFileName/invalid_name (0.00s)
=== RUN   TestParseMarinerDistrolessManifest
=== RUN   TestParseMarinerDistrolessManifest/happy_path
=== RUN …
```
> refactor: use strings.TrimSuffix instead of strings.HasSuffix

- docs/getting-started/installation.md
When running:
```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /root/.cache:/root/.cache docker.io/aquasec/trivy:0.32.1 node:18
```
I get the following error message:
```bash
Error: unknown command "node:18" for "trivy"
```
This will add the 'image' subcommand to the documentation.
(this will include some other 'nits and picks', but I can remove revert them in order to keep the PR changes clean if necessary)
> docs: fix missing 'image' subcommand

- docs/docs/references/cli/rootfs.md
- docs/docs/references/modes/client-server.md
- docs/docs/vulnerability/scanning/rootfs.md
- pkg/commands/app.go
This PR adds support for client/server mode for the `trivy rootfs` command.
Before:
```
Scan rootfs
Usage:
trivy rootfs [flags] ROOTDIR
Examples:
$ docker export $(docker create alpine:3.10.2) | tar -C /tmp/rootfs -xvf -
$ trivy rootfs /tmp/rootfs
$ docker run --rm -it alpine:3.11
/ # curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
/ # trivy rootfs /
Scan Flags
--file-patterns strings     specify config file patterns
--offline-scan              do not issue API requests to identify dependencies
--rekor-url string          [EXPERIMENTAL] address of rekor STL server (default "https://rekor.sigstore.dev")
--sbom-sources strings      [EXPERIMENTAL] try to retrieve SBOM from the specified sources (rekor)
--security-checks …
```
> feat(server): Add support for client/server mode to rootfs command

- pkg/fanal/test/integration/containerd_test.go
Disable [containerd fanal integration tests](https://github.com/aquasecurity/trivy/blob/9b0e9794cb94a2292c506afbff2bcd8695170558/pkg/fanal/test/integration/containerd_test.go) for non-amd64 arch.
> test: disable containerd fanal integration tests for non-amd64 arch

- pkg/detector/ospkg/alpine/alpine.go
- pkg/detector/ospkg/alpine/alpine_test.go
In few images like automation.azurecr.io/alpine_exploit:v1 we have no **o:** in **lib/apk/db/installed** path therefore analyzer is not sending SrcName. 
But since SrcName is not available we are not getting advisories. 
So I have modified code to check with Name for fetching advisories. I have also added a test case without SrcName for alpine.
> fix: In alpine use Name to fetch advisories

- docs/docs/advanced/container/containerd.md
- pkg/fanal/image/daemon/containerd.go
- pkg/fanal/test/integration/containerd_test.go
Containerd allows you to specify a namespace for queries, pulls, storage, etc. Trivy currently only scans local images in the `default` containerd namespace. This PR enables trivy to scan other namespaces within the containerd store.
An excellent use case is scanning the containerd store on kubernetes clusters; by default, images used by kubernetes are pulled to the `k8s.io` namespace.
- Close #3059
> feat: Allow override of containerd namespace

- pkg/commands/artifact/run.go
- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/pkg/dpkg/copyright.go
- pkg/fanal/artifact/artifact.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/image_test.go
- pkg/fanal/artifact/local/fs.go
Initializing license classifiers and performing license classification is expensive and it is disabled by default. However, it is used only when scanning Debian because Debian licenses are not stored in a machine-readable format. In other words, scanning Debian activates the license classification and leads to high CPU/memory utilization.
This PR changes it to try to detect licenses without license classifiers by default and enable classifies only when `--license-full` is specified.
> perf(license): enable license classifier only with "--license-full"

- pkg/commands/app.go
Example from `image` help contains wrong `--security-checks none` flag.
Fix this.
Before:
```
➜  trivy image --help
Scan a container image
Usage:
trivy image [flags] IMAGE_NAME
...
$ trivy image --format cyclonedx --output result.cdx --security-checks none alpine:3.15
```
After:
```
➜  trivy git:(fix/cyclonedx-example) ✗ ./trivy image --help
Scan a container image
Usage:
trivy image [flags] IMAGE_NAME
...
$ trivy image --format cyclonedx --output result.cdx alpine:3.15
```
- Close #3153
> fix: remove `--security-checks none` from image help

- pkg/commands/app.go
exclude --compliance flag from non relevant sub-commands
- Close #3157
- Related #2919
> fix: exclude --compliance flag from non supported sub-commands

- docs/docs/licenses/scanning.md
Fix typo inside the license scanning quick start.
> docs(license): fix typo inside quick start

- go.mod
- go.sum
- pkg/module/module.go
This updates [wazero](https://wazero.io/) to [1.0.0-pre.3](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.3). This is the last release that will build with Go 1.17.
Notably, this improves performance and changes host function syntax.
> chore(go): updates wazero to 1.0.0-pre.3

- docs/docs/references/customization/config-file.md
In #2994, some configuration flags were moved from the `misconfiguration` namespace setting into a new `rego` namespace setting.
This reflects the new configuration namespace.
> docs(flag): add "rego" configuration file options

- Makefile
`GOPATH` variable can be composed of several paths.
Fix:
Extract and use first path from `GOPATH`.
- Close #3091
> chore: handle GOPATH with several paths in make file

- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
- pkg/sbom/spdx/testdata/happy/bom.json
There is mistake in `DESCRIBES` field in SPDX.
https://spdx.github.io/spdx-spec/relationships-between-SPDX-elements/#1111-description
- Close #3100
> fix(spdx): rename describes field in spdx

- .github/workflows/semantic-pr.yaml
amannn/action-semantic-pull-request v5 broke our workflow. This PR is a hotfix.
> chore: use newline for semantic pr

- pkg/fanal/walker/walk.go
Perform filepath.Clean first and then filepath.ToSlash for skipFile/skipDirs settings
- Close #3143
> fix: Perform filepath.Clean first and then filepath.ToSlash for skipFile/skipDirs settings

- docs/docs/misconfiguration/policy/builtin.md
The rego policies were moved to a different directory in the defsec project. See https://github.com/aquasecurity/defsec/pull/995. This caused a few of the links on https://aquasecurity.github.io/trivy/v0.34/docs/misconfiguration/policy/builtin/ to be broken. This PR updates the URLs and also fixes the misnamed link for `rbac`.
none
none
_Links that are relevant to this PR:_
| Config type | Hyperlink |
| --- | --- |
| Kubernetes | https://github.com/aquasecurity/defsec/tree/master/internal/rules/rbac |
| Dockerfile, Containerfile | https://github.com/aquasecurity/defsec/tree/master/internal/rules/docker |
| RBAC | https://github.com/aquasecurity/defsec |
Notice that `[rbac]` no longer appears in the last row in the table.
_Links that are relevant to this PR:_
| Config type | Hyperlink |
| …
> docs: fix links on Built-in Policies page

- docs/docs/kubernetes/cli/compliance.md
- docs/docs/vulnerability/scanning/git-repository.md
- docs/getting-started/installation.md
- docs/tutorials/kubernetes/kyverno.md
> docs: fix some typo

- docs/docs/secret/configuration.md
- docs/docs/secret/scanning.md
The documentation had a few mentions of `enable-builin-rules` which should have been `enable-builtin-rules`
> docs: fix typo in enable-builin-rules mentions

- pkg/fanal/image/daemon/image.go
- pkg/fanal/image/daemon/image_test.go
WORKDIR command in docker file is actually empty layer. tested with podman and buildkit
> fix: workdir command as empty layer

- contrib/asff.tpl
- integration/testdata/alpine-310.asff.golden
This PR adds the package name that contains the vulnerability to the title of the finding. This way the finding is different from other findings with the same CVE but with a different package. This is important because AWS Security Hub just updates and overrides an existing finding instead of creating a new one. More information can be found in the related issue
```json
"Title": "Trivy found a vulnerability to CVE-2019-1549 in container testdata/fixtures/images/alpine-310.tar.gz (alpine 3.10.2)",
```
```json
"Title": "Trivy found a vulnerability to CVE-2019-1549 in container testdata/fixtures/images/alpine-310.tar.gz (alpine 3.10.2), related to libcrypto1.1",
```
The related PR is old and this is just so I don't have to manually pull changes to add tests
- Close #2774
> fix(vuln): add package name to title

- pkg/fanal/image/daemon/containerd.go
- pkg/fanal/test/integration/containerd_test.go
There are many ways to reference a container image. Because of the
history of the terms `reference`, `name`, `repo`, `tag`, I will refer to
any way of uniquely identifying an image as a `handle`. A handle can be
in any of the following formats:
```
repo.io/name:tag
repo.io/xyz/name:tag
name:tag
compound/name:tag
sha256:4dca0fd5f424a31b03ab807cbae77eb32bf2d089eed1cee154b3afed458de0dc
name@sha256:4dca0fd5f424a31b03ab807cbae77eb32bf2d089eed1cee154b3afed458de0dc
repo.io/name@4dca0fd5f424a31b03ab807cbae77eb32bf2d089eed1cee154b3afed458de0dc
```
To complicate matters, given Docker's conventions it is often customary
to prefix a "familiar name" (i.e a name with no registry component, in
the above example the familiar name of `name:tag` would be `name`) with
`docker.io/library/`. Following that …
> feat(containerd): scan image by digest

- docs/docs/references/troubleshooting.md
Troubleshoot space issues while scanning large images or with small /tmp.
/tmp initialisation: https://github.com/aquasecurity/trivy/blob/cb5744dcaf914fca954dc0f9327b093991c4ee42/pkg/fanal/image/daemon/docker.go#L45
- https://github.com/aquasecurity/trivy/issues/1796
- https://github.com/aquasecurity/trivy/issues/1834
> docs(image): space issues during image scan

- integration/testdata/fixtures/db/opensuse.yaml
- pkg/detector/ospkg/suse/suse.go
`SUSE cvrt` contains advisories for package names, not for source names.
False positive example(used actual Trivy version):
```
➜ trivy -q image registry.suse.com/suse/sles/15.4/virt-launcher:0.54.0-150400.3.5.1     
registry.suse.com/suse/sles/15.4/virt-launcher:0.54.0-150400.3.5.1 (suse linux enterprise server 15.4)
Total: 18 (UNKNOWN: 1, LOW: 0, MEDIUM: 8, HIGH: 7, CRITICAL: 2)
...
├───────────────────────┼─────────────────────┼──────────┼─────────────────────────────────┼─────────────────────────┼──────────────────────────────────────────────────────────────┤
│ qemu-ipxe             │ SUSE-SU-2022:2260-1 │ HIGH     │ 1.0.0+-150400.37.8.2            │ 6.2.0-150400.37.5.3     │ Security update for qemu                                     │
│ …
```
> fix(suse): use package name to get advisories

- docs/docs/kubernetes/cli/compliance.md
- pkg/compliance/spec/compliance.go
- pkg/flag/report_flags.go
- pkg/k8s/commands/run.go
Load compliance report from file system
- Related #2919
> fix: load compliance report from file system

- pkg/fanal/walker/walk.go
there is a mistake in `slowSizeThreshold`. it's equal `defaultSizeThreshold`.
> fix: `slowSizeThreshold` should be less than `defaultSizeThreshold`

- go.mod
- go.sum
update go-xfs-filesystem.
change commit: https://github.com/masahiro331/go-xfs-filesystem/commit/051c25f1becd4b2f26cffb76a9b74cc3991740dc
> fix(vm): turn warning message into debug message

- helm/trivy/README.md
- helm/trivy/templates/configmap.yaml
- helm/trivy/values.yaml
fix #3206 
with the following values.yaml
```
trivy:
extraEnvVars:
FOO: bar
TOTO: |
titi
multi
line
``` 
the chart has the following diff in the configmap: 
``` 
@@ -47,6 +47,11 @@
TRIVY_DEBUG: "false"
TRIVY_SKIP_UPDATE: "false"
TRIVY_DB_REPOSITORY: "ghcr.io/aquasecurity/trivy-db"
+  FOO: bar
+  TOTO: |
+    titi
+    multi
+    line
``` 
- [] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x ] I've added usage information (if the PR introduces new options)
> feat(helm): pass arbitrary env vars to trivy

- docs/ecosystem/ide.md
Mention trivy pre-commit hook https://github.com/mxab/pre-commit-trivy
- Relates to #1858
> docs: add pre-commit hook to community tools

- docs/docs/vulnerability/examples/report.md
- go.mod
- go.sum
- integration/testdata/fixtures/fs/nuget/packages.lock.json
- integration/testdata/nuget.json.golden
- pkg/fanal/analyzer/language/dotnet/nuget/nuget_test.go
- pkg/fanal/analyzer/language/dotnet/nuget/testdata/packages.lock.json
Add dependency parsing for nuget lock files
> feat(dotnet): add dependency parsing for nuget lock files

- pkg/flag/report_flags.go
- pkg/report/sarif.go
- pkg/report/sarif_test.go
- pkg/report/writer.go
We start support dependency locations for some languages (e.g. #3016, #3032...).
Use correct locations for these languages.
Before:
After:
> feat(report): add dependency locations to sarif format

- go.mod
- go.sum
- pkg/module/module.go
This updates [wazero](https://wazero.io/) to [1.0.0-pre.4](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.4).
Notably, v1.0.0-pre.4:
* improves module initialization speed
* supports listeners in the compiler engine
* supports WASI `fd_pread`, `fd_readdir` and `path_filestat_get`
* breaks GoModuleFunc API
> chore(go): updates wazero to 1.0.0-pre.4

- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
* Changed to avoid duplicate dependsOn.
* Changed to create Application Component with RustBinary and GoBinary.
- Close #3260
> fix(sbom): duplicate dependson

- README.md
Fix link to Ecosystem page in Trivy docs.
> docs: fix broken "ecosystem" link in readme

- pkg/fanal/artifact/vm/vm_test.go
`vm_test.go` imports all the analyzers now, and the expected digests will be changed every time analyzers are added/removed/modified since the digest is calculated by those versions. This PR changes it to import relevant analyzers only.
> test(vm): import relevant analyzers

- .github/workflows/semantic-pr.yaml
- docs/community/contribute/pr.md
- pkg/purl/purl.go
- pkg/purl/purl_test.go
It currently uses constants for analyzers, but it should be constants for result types.
> fix(sbom): use proper constants

- pkg/vulnerability/testdata/fixtures/vulnerability.yaml
- pkg/vulnerability/vulnerability.go
- pkg/vulnerability/vulnerability_test.go
Vulnerabilities from `govuln` and `GHSA-xxx` will get severity from github first (if github has no severity then from NVD)
> fix: change severity vendor priority for ghsa-ids and vulns from govuln

- pkg/result/filter.go
- pkg/result/filter_test.go
- pkg/types/vulnerability.go
DetectedVulnerability objects with identical VulnerabilityID, PkgName and InstalledVersion properties' values will only be included once in the final report of trivy, regardless of whether their respective PkgPath property values are different, due to the current [deduplication logic](https://github.com/aquasecurity/trivy/blob/7a6cf5a27c661f61a54669af7935c1389fef8453/pkg/result/filter.go#L56) for filtering unique DetectedVulnerability objects produced by different data sources. Thus, the final report is incomplete regarding the root cause of the corresponding vulnerability (i.e. which dependency files introduce it).
In order to mitigate this, our PR adds vuln.PkgPath to the [key](https://github.com/aquasecurity/trivy/blob/7a6cf5a27c661f61a54669af7935c1389fef8453/pkg/result/filter.go#L77) …
> fix(vuln): include duplicate vulnerabilities with different package paths in the final report

- pkg/module/memfs.go
- pkg/module/memfs_test.go
- pkg/module/module.go
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
Previously, wazero introduced context-based FS (https://github.com/tetratelabs/wazero/pull/571) and used in Trivy to change the underlying file system anytime it calls Analyze API. But it came with the runtime overhead and there's actually an easy way to achieve the same thing without that experimental API.
This PR, hence, removes the usage of the experimental API by introducing the wrapper over memfs.FS which can change the underlying file system in response to the Analyze calls.
> chore(go): remove experimental FS API usage in Wasm

- docs/docs/secret/examples.md
- pkg/result/filter.go
- pkg/result/filter_test.go
- pkg/result/testdata/.trivyignore
This allows the filtering of secret scan results by RuleID using .trivyignore as it's possible for Misconfiguration or Vulnerability.
- Close #3311
> feat(secret): Use .trivyignore for filtering secret scanning result

- pkg/sbom/sbom.go
Add support for the detection of old CycloneDX predicate type.
I tested scanning sbom attestation created by Cosign v1.13.1, which has cyclonedx attestation with the old predicate type( `https://cyclonedx.org/schema` ).
before
```bash
$ trivy image --format cyclonedx -o sbom.cdx.json otms61/my-alpine:latest
$ cosign verify-attestation --key cosign.pub --type cyclonedx otms61/my-alpine:latest > sbom.cdx.intoto.jsonl
Verification for otms61/my-alpine:latest --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- Existence of the claims in the transparency log was verified offline
- The signatures were verified against the specified public key
$ cat sbom.cdx.intoto.jsonl | jq '.payload | @base64d | fromjson | .predicateType' …
```
> fix(sbom): support for the detection of old CycloneDX predicate type

- integration/fs_test.go
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/walker/fs.go
- pkg/fanal/walker/walk.go
Change logic to build relative paths for skip-dirs and skip-files
> fix: change logic to build relative paths for skip-dirs and skip-files

- docs/docs/cloud/aws/compliance.md
- docs/docs/compliance/compliance.md
- docs/docs/kubernetes/cli/compliance.md
Added most of the general description to the compliance page, including custom compliance docs. 
the k8s and aws pages repeated the same content, so I restructured them (note that I've removed the table with all the checks because it made it hard to read the page, if we need it it should probably be in avd). This change will also help when we add compliance in the fs command
- related https://github.com/aquasecurity/trivy/issues/3339
> docs: improve compliance docs

- go.mod
- go.sum
- pkg/module/memfs.go
- pkg/module/module.go
This updates to wazero v1.0.0-pre.7 which fixes a `GOARCH=386` compilation problem in v1.0.0-pre.6.
[wazero](https://wazero.io/) [1.0.0-pre.6](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.6) includes the following notable changes:
* improves module compilation and initialization performance
The following features are new and not currently used in Trivy, but might be relevant for future work:
* adds `writefs.NewDirFS` which lets you add new files.
* `path_open` `O_CREAT` flags, `path_remove_directory` `path_rename` `path_unlink_file`
* adds `NewFilesystemLoggingListenerFactory` with dramatically improved logging.
This also includes changes described in [1.0.0-pre.5](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.5). Notably, context param was removed from …
> chore(go): updates wazero to 1.0.0-pre.7

- docs/docs/vulnerability/examples/report.md
- docs/tutorials/integrations/aws-security-hub.md
Fix broken links for Amazon Security Hub:
- In `report.md`, link to ASFF  / Security Hub tutorial
- In `aws-security-hub.md` tutorial, fix image link and resizing thanks to `attr_list`
- In `aws-security-hub.md` tutorial, make link to AWS blog clickable
Before:
After:
- Not applicable: simple doc fix.
> docs(aws): fix broken links

- pkg/flag/report_flags.go
- pkg/report/writer.go
This PR will make trivy fail earlier when the format is wrong.
- Close #3244
Before:
```
$ ./trivy image alpine:latest --format foo
2023-01-02T19:00:26.902+0800    INFO    Vulnerability scanning is enabled
2023-01-02T19:00:26.902+0800    INFO    Secret scanning is enabled
2023-01-02T19:00:26.902+0800    INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2023-01-02T19:00:26.902+0800    INFO    Please see also https://aquasecurity.github.io/trivy/v0.35/docs/secret/scanning/#recommendation for faster secret detection
2023-01-02T19:00:29.062+0800    INFO    Detected OS: alpine
2023-01-02T19:00:29.062+0800    INFO    This OS version is not on the EOL list: alpine 3.17
2023-01-02T19:00:29.062+0800    INFO    Detecting Alpine vulnerabilities... …
```
> feat(flag): early fail when the format is invalid

- README.md
- docs/index.md
Homebrew currently maintains the Trivy formula. It is better to use it rather than our formula.
https://github.com/Porkepix/homebrew-core/blob/master/Formula/trivy.rb
Homebrew didn't use to have `trivy` and we needed to maintain our tap. We no longer have to maintain that, but keep it for compatibility.
- Close https://github.com/aquasecurity/trivy/issues/3388
- Close https://github.com/aquasecurity/trivy/issues/3387
> docs: use the formula maintained by Homebrew

- .github/workflows/test-docs.yaml
- .github/workflows/test.yaml
we don't need all the tests to run on every docs PR
> chore: test docs separately from code

- go.mod
- go.sum
Address some vulnerabilities in helm
- Close https://github.com/aquasecurity/trivy/issues/3352
> chore(deps): bump defsec to address helm vulnerabilities

- pkg/rpc/server/server.go
Log rpc errors in warn level on server.
- Close #3310
Open two terminals and run the following commands (please turn off redis server for testing purpose):
```bash
trivy server --cache-backend redis://localhost:6379 --cache-ttl 1h --listen localhost:4954 --debug
trivy image --server http://localhost:4954 busybox:latest --debug
```
Output on the server-side:
```
2023-01-08T12:46:49.683+0800	INFO	Redis cache: redis://localhost:6379
2023-01-08T12:46:49.683+0800	DEBUG	cache dir:  /home/lin/.cache/trivy
2023-01-08T12:46:49.683+0800	DEBUG	DB update was skipped because the local DB is the latest
2023-01-08T12:46:49.683+0800	DEBUG	DB Schema: 2, UpdatedAt: 2023-01-08 00:11:47.038838827 +0000 UTC, NextUpdate: 2023-01-08 06:11:47.038838527 +0000 UTC, DownloadedAt: 2023-01-08 04:46:15.748637321 +0000 …
```
> feat(server): log errors on server side

- pkg/licensing/normalize.go
Fix mistake when GPL-3+-WITH-BISON-EXCEPTION normalize to GPL-2.0-with-bison-exception
- Close #3404
> fix(license): change normalize for GPL-3+-WITH-BISON-EXCEPTION

- pkg/fanal/image/remote.go
fix parsePlatform is failing with UNAUTHORIZED error by Plugging in the **auth** to the **parsePlatform**
- Close #3304
> fix(image): parsePlatform is failing with UNAUTHORIZED error

- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/remote_sbom_test.go
- pkg/fanal/image/archive.go
- pkg/fanal/image/daemon.go
- pkg/fanal/image/daemon/image.go
- pkg/fanal/image/image_test.go
- pkg/fanal/image/remote.go
- pkg/fanal/types/image.go
Trivy needs to determine which layers are empty because the history API of container engines doesn't return the `emptyLayer` field. However, we recently found out that the implementation of `emptyLayer` differs depending on container engine. It seems to be challenging to handle all edge cases where empty layers cannot be properly determined.
This PR implements fallback into `docker save` in that case. It falls back only when empty layer detection is wrong as `docker save` is expensive.
> fix(image): handle wrong empty layer detection

- pkg/commands/server/run.go
- pkg/rpc/server/listen.go
- pkg/rpc/server/listen_test.go
add support of `skip-db-update` flag for hot db update in server mode
- #3408
> feat(server): add support of `skip-db-update` flag for hot db update

- ci/deploy-rpm.sh
[aquasecurity/trivy-repo](https://github.com/aquasecurity/trivy-repo) has a large size - more than 4.5Gb.
It leads to timeout aborting in deploy Github Pages, ex: https://github.com/aquasecurity/trivy-repo/actions/runs/3360429639
the reason is that rpm folder contains all built rpm releases, it's about 4.37 Gb. for comparison, deb folder has about 237 Mb.
Now Trivy RPM repository stores only a link to Github Release.
- Close https://github.com/aquasecurity/trivy-repo/issues/21
> ci: store URLs to Github Releases in RPM repository

- .github/workflows/test.yaml
- go.mod
setup-go added support for `stable` and `oldstable` - https://github.com/actions/setup-go#using-stableoldstable-aliases
use `stable` and `oldstable` go versions for unit tests
> ci: downgrade Go to 1.18 and use stable and oldstable go versions for unit tests

- pkg/oci/artifact.go
When we download DB with `insecure` flag - we don't check proxy settings.
Fix this.
- Close #3396
> fix(db): check proxy settings when using insecure flag

- go.mod
- go.sum
Update go-dep-parser, which contains more ignore protocols in yarn parser.
- Close #3428 
- https://github.com/aquasecurity/go-dep-parser/pull/163
> fix(deps): add ignore protocols to yarn parser

- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/analyzer_test.go
- pkg/fanal/analyzer/command/apk/apk.go
- pkg/fanal/analyzer/command/apk/apk_test.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/cache/fs_test.go
- pkg/fanal/types/artifact.go
- pkg/fanal/types/const.go
We're planning to migrate [Dockle](https://github.com/goodwithtech/dockle) into Trivy. It detects misconfiguration in container image config. This PR extends the image config analyzer interface for the subsequent PRs.
- https://github.com/aquasecurity/trivy/issues/2676
> refactor(image): extend image config analyzer

- docs/docs/secret/examples.md
Typo in docs -> secret/examples
before - 
"`--skip-fles` also works similarly."
after - 
"`--skip-files` also works similarly."
Fix screenshot -
> docs(secret): typo in --skip-files

- .github/workflows/vm-test.yaml
The VM test is triggered by all PRs now. This PR changes it to trigger the test only when needed.
> ci: set paths triggering VM tests in PR

- docs/tutorials/kubernetes/gitops.md
Fixes tabs FluxCD yaml example, updates example to auto create the namespace, bumps version to current and gives example for setting values to be more in line with the "normal" helm install docs.
> docs: yaml tabs to spaces, auto create namespace

- docs/docs/references/troubleshooting.md
- pkg/db/db.go
The expired GHCR token configured locally like `docker login ghcr.io` leads to the following error.
```
2023-01-23T14:50:36.108+0200    FATAL   init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: GET https://ghcr.io/token?scope=repository%3Aaquasecurity%2Ftrivy-db%3Apull&service=ghcr.io: DENIED: denied
```
- Close https://github.com/aquasecurity/trivy/issues/3472
> chore: display the troubleshooting URL for the DB denial error

- go.mod
- go.sum
Add `implementationVendor` and `specificationVendor` fields to detect GroupID from MANIFEST.MF.
- #3427
> feat(java): add implementationVendor and specificationVendor fields to detect GroupID from MANIFEST.MF

- go.mod
- pkg/flag/db_flags.go
- pkg/flag/kubernetes_flags.go
- pkg/flag/options.go
- pkg/flag/rego_flags.go
- pkg/flag/scan_flags.go
This PR adds support for aliases in CLI flag, env and config. Currently, CLI flag is only supported, but others are not. Also, it shows deprecation messages for deprecated aliases.
```
$ trivy image --security-checks vuln alpine:3.17
2023-01-24T11:57:47.570Z        INFO    Vulnerability scanning is enabled
```
```
$ trivy image --security-checks vuln alpine:3.17
2023-01-24T11:57:47.570Z        WARN    '--security-checks' is deprecated. Use '--scanners' instead.
2023-01-24T11:57:47.570Z        INFO    Vulnerability scanning is enabled
```
```
$ TRIVY_SECURITY_CHECKS=vuln trivy image alpine:3.17
2023-01-25T11:30:12.090+0200    WARN    'TRIVY_SECURITY_CHECKS' is deprecated. Use 'TRIVY_SCANNERS' instead.
```
```
$ trivy image alpine:3.17
2023-01-25T11:30:46.062+0200    INFO    Loaded …
```
> feat: support aliases in CLI flag, env and config

- helm/trivy/Chart.yaml
Updates the Trivy version used in the Helm chart from 0.30.4 to 0.36.1.
- Close #XXX
> chore(helm): update Trivy from v0.30.4 to v0.36.1

- docs/docs/compliance/compliance.md
- go.mod
- go.sum
- pkg/cloud/aws/commands/run.go
- pkg/cloud/aws/commands/run_test.go
- pkg/cloud/aws/scanner/scanner.go
- pkg/commands/app.go
- pkg/commands/artifact/run.go
- pkg/compliance/report/summary.go
- pkg/compliance/report/table.go
- pkg/compliance/report/testdata/table_summary.txt
- pkg/compliance/spec/compliance.go
- pkg/flag/report_flags.go
- pkg/flag/report_flags_test.go
- pkg/flag/testdata/example-spec.yaml
- pkg/k8s/commands/run.go
- pkg/report/writer.go
- pkg/types/report.go
This PR adds support for [Docker CIS Benchmark](https://www.aquasec.com/cloud-native-academy/docker-container/docker-cis-benchmark/).
Docker CIS Benchmark has checks for vulnerabilities, misconfigurations and secrets. This PR supports only misconfigurations. Vulnerabilities and secrets will be supported later.
I'll update the documentation in another PR since we need to restructure the doc.
```
$ trivy image --compliance docker-cis my-image
2023-01-30T16:59:31.454+0900    INFO    Container image config scanners: ["config"]
2023-01-30T16:59:31.454+0900    INFO    Misconfiguration scanning is enabled
2023-01-30T16:59:31.511+0900    INFO    Detected config files: 1
Summary Report for compliance: CIS Docker Community Edition Benchmark v1.1.0 …
```
> feat(image): add support for Docker CIS Benchmark

- go.mod
- go.sum
bumps defsec to latest version
> chore(deps): bump defsec to v0.82.9

- docs/docs/vulnerability/detection/os.md
Trivy supports `AlmaLinux 9` and `Rocky Linux 9`, but there is no information about this in the documentation.
- Close #2520
> docs: add AlmaLinux 9 and Rocky Linux 9 to supported OS

- go.mod
- go.sum
- pkg/module/module.go
This updates [wazero](https://wazero.io/) to [1.0.0-pre.8](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.8) which notably
* Obviates Namespace in favor of cheaper Runtimes sharing a CompilationCache
Other notable changes (unrelated to this PR)
* Better supports WASI including third-party integrated tests
* Adds support for writeable filesystems via FSConfig
* Improves observability with LogScopes, e.g. filesystem.
Signed-off-by: Edoardo Vacchi <evacchi@users.noreply.github.com>
> chore(deps): updates wazero to 1.0.0-pre.8

- docs/docs/attestation/rekor.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
This PR aims to add information about the limitation in Rekor about the attestation size.
- Close #XXX
https://github.com/sigstore/rekor/pull/1313
https://github.com/aquasecurity/trivy-plugin-attest/pull/6
> docs: add note about the limitation in Rekor

- ci/deploy-rpm.sh
`deploy-rpm.sh` calculated `TRIVY_VERSION` from the main folder, not from `trivy-repo` 
so path `../dist/` was wrong and `TRIVY_VERSION` was empty
> ci: fix path to dist folder

- pkg/misconf/scanner.go
- pkg/misconf/scanner_test.go
We shouldn't trim out dot prefixes as they are valid usable directories.
- Close https://github.com/aquasecurity/trivy/issues/3549
> fix(misconf): handle dot files better

- helm/trivy/Chart.yaml
Updates the Trivy version used in the Helm chart from 0.36.1 to 0.37.1.
> chore(helm): update Trivy from v0.36.1 to v0.37.2

- docs/docs/references/cli/client.md
- docs/docs/references/cli/fs.md
- docs/docs/references/cli/image.md
- docs/docs/references/cli/repo.md
- docs/docs/references/cli/rootfs.md
- docs/docs/references/cli/sbom.md
- docs/docs/references/customization/config-file.md
- docs/docs/vulnerability/examples/db.md
- pkg/commands/artifact/run.go
- pkg/fanal/analyzer/language/java/jar/jar_test.go
- pkg/flag/db_flags.go
- pkg/javadb/client.go
This implements an additional `--java-db-repository` option to allow users to specify a custom Java DB repository. This is useful for users who want to use a custom Java DB repository, such as a private repository mirror like Artifactory or other private registries. It will also print the Java DB repository - even if it's the default - to make it clear to the user which Java DB repository is being used.
I've updated the documentation to reflect this new option, as well as the existing tests for the JAR file scanner.
Scanning an image containing JAR files will print the following:
```bash
$ trivy image tomcat:9.0.71-jdk8        
2023-02-11T15:12:30.064+0100    INFO    Need to update DB
2023-02-11T15:12:30.064+0100    INFO    DB Repository: ghcr.io/aquasecurity/trivy-db …
```
> fix(cli): make java db repository configurable

- pkg/cloud/aws/scanner/scanner.go
Fixes a bug where update-cache flag is not being properly applied.
- Close #3618
> fix(aws): Adding a fix for update-cache flag that is not applied on AWS scans.

- go.mod
- go.sum
This updates [wazero](https://wazero.io/) to [1.0.0-pre.9][1]. Notably:
* This release includes our last breaking changes before 1.0.0 final:
* Requires at least Go 1.8
* This release also integrates Go context to limit execution time.
More details on the [Release Notes][1]
* We are now passing third-party integration test suites: wasi-testsuite,
TinyGo's, Zig's.
[1]: https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.9
Signed-off-by: Edoardo Vacchi <evacchi@users.noreply.github.com>
> chore(deps): updates wazero to 1.0.0-pre.9

- pkg/mapfs/file.go
- pkg/mapfs/fs.go
- pkg/mapfs/fs_test.go
This PR adds support for virtual files in `mapfs`.
> feat: add support for virtual files in mapfs

- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
Use empty array with cyclonedx components and ratings. 
- Close #3623 
- Close #3646  
> fix(cyclonedx): fix array empty value, null to []

- docs/docs/vulnerability/languages/golang.md
- integration/module_test.go
- pkg/commands/artifact/run.go
- pkg/commands/operation/operation.go
- pkg/commands/server/run.go
- pkg/fanal/analyzer/language/golang/mod/mod.go
- pkg/fanal/analyzer/language/golang/mod/mod_test.go
- pkg/fanal/analyzer/language/golang/mod/testdata/pkg/mod/github.com/!burnt!sushi/toml@v0.3.1/COPYING
- pkg/fanal/analyzer/language/golang/mod/testdata/pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20220406074731-71021a481237/LICENSE
- pkg/flag/global_flags.go
- pkg/module/module.go
- pkg/module/module_test.go
- pkg/oci/artifact_test.go
- pkg/plugin/plugin.go
- pkg/rpc/server/listen.go
- pkg/rpc/server/listen_test.go
- pkg/utils/fsutils/fs.go
- pkg/utils/fsutils/fs_test.go
Add license support for Go
In the following example, license fields are filled.
```
$ trivy fs --scanners vuln -f json --list-all-pkgs ./go.mod
{
"SchemaVersion": 2,
"ArtifactName": "go.mod",
"ArtifactType": "filesystem",
"Results": [
{
"Target": "go.mod",
"Class": "lang-pkgs",
"Type": "gomod",
"Packages": [
{
"Name": "cloud.google.com/go",
"Version": "0.105.0",
"Licenses": [
"Apache-2.0"
],
"Indirect": true,
"Layer": {}
},
{
"Name": "cloud.google.com/go/compute",
"Version": "1.14.0",
"Licenses": [
"Apache-2.0"
],
"Indirect": true,
"Layer": {}
},
```
- Close https://github.com/aquasecurity/trivy/issues/1949
> feat(go): license support

- docs/docs/advanced/air-gap.md
Downloaded file name is `javadb.tar.gz` rather than `db.tar.gz`. Also `--skip-update` is deprecated in favor of `--skip-db-update` and `--skip-java-db-update`.
> docs: java-db air-gap doc tweaks

- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- Close https://github.com/aquasecurity/trivy/issues/3663
> fix(sbom): export empty dependencies in CycloneDX

- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
Change CreationInfo timestamp format.
Before: Use RFC3336Nano format
After: Use RFC3336 format
Ref: https://spdx.github.io/spdx-spec/v2.2.2/document-creation-information/#69-created-field
- Close #3600 
> fix(spdx): change CreationInfo timestamp format RFC3336Nano to RFC3336

- helm/trivy/Chart.yaml
- helm/trivy/README.md
- helm/trivy/templates/configmap.yaml
- helm/trivy/values.yaml
Use `TRIVY_SKIP_DB_UPDATE` instead of `TRIVY_SKIP_UPDATE`.
- Close #3656
```
2023-02-20T16:59:57.928Z        WARN    'TRIVY_SKIP_UPDATE' is deprecated. Use 'TRIVY_SKIP_DB_UPDATE' instead.
2023-02-20T16:59:57.931Z        INFO    Listening 0.0.0.0:4954...
```
```
2023-02-20T16:59:57.931Z        INFO    Listening 0.0.0.0:4954...
```
> chore(helm): update skip-db-update environment variable

- docs/docs/references/cli/client.md
- docs/docs/references/cli/image.md
- docs/docs/references/customization/config-file.md
- docs/docs/vulnerability/examples/others.md
- pkg/commands/app.go
- pkg/commands/artifact/run.go
- pkg/flag/report_flags.go
- pkg/flag/report_flags_test.go
Change `--exit-on-eol` from boolean to integer. Also, renamed `exit-on-eosl` to `exit-on-eol` as EOL could be more used than EOSL.
```
$ trivy image --exit-code 1 --exit-on-eosl alpine:3.10
```
```
$ trivy image --exit-on-eol 1 alpine:3.10
```
- https://github.com/aquasecurity/trivy/pull/3423
> fix(cli): pass integer to exit-on-eol

- docs/docs/sbom/spdx.md
- integration/testdata/conda-spdx.json.golden
- integration/testdata/fixtures/sbom/centos-7-spdx.json
- integration/testdata/fixtures/sbom/centos-7-spdx.txt
- pkg/report/spdx/spdx.go
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
- pkg/sbom/spdx/testdata/happy/bom.json
- pkg/sbom/spdx/testdata/happy/empty-bom.json
- pkg/sbom/spdx/testdata/happy/os-only-bom.json
- pkg/sbom/spdx/testdata/happy/unrelated-bom.json
- pkg/sbom/spdx/testdata/sad/invalid-source-info.json
`Creator.Tool` field should contain `Trivy` version: https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#68-creator-field.
before:
```
Creator: Organization: aquasecurity
Creator: Tool: trivy
```
after:
```
Creator: Organization: aquasecurity
Creator: Tool: trivy-0.38.1
```
before:
``` json
"creationInfo": {
"created": "2023-03-03T04:46:04.859719101Z",
"creators": [
"Tool: trivy",
"Organization: aquasecurity"
]
},
```
after:
```json
"creationInfo": {
"created": "2023-03-03T04:45:57Z",
"creators": [
"Tool: trivy-0.38.1",
"Organization: aquasecurity"
]
},
```
- Close #3707
> fix(sbom): add trivy version to spdx creators tool field

- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/language/java/jar/jar.go
There are cases when dir has same name as required file.
e.g.
```
➜  docker run -it --rm  --entrypoint /bin/bash docker.io/consensys/teku:develop-jdk16
teku@6636da39406f:~$ ls -hl ./licenses/
total 604K
drwxr-xr-x 3 teku teku 4.0K Mar  6 05:43 apiguardian-api-1.1.2.jar
drwxr-xr-x 3 teku teku 4.0K Mar  6 05:43 attoparser-2.0.6.RELEASE.jar
drwxr-xr-x 3 teku teku 4.0K Mar  6 05:43 byte-buddy-1.12.21.jar
...
```
We should skip these dirs.
- Close #3760
> fix: skip checking dirs for required post-analyzers

- pkg/commands/artifact/run.go
- pkg/fanal/analyzer/const.go
We don't need to parse jar files if we don't analyze vulnerabilities or use sbom format
- Close #3699
> fix(license): disable jar analyzer for licence scan only

- docs/docs/target/git-repository.md
Just adding the link to generate a GH personal access token to perform private repo scans
> docs: adding link to gh token generation

- README.md
Add canary build info to `README.md`
- Close #3782
> docs: add canary build info to README.md

- pkg/commands/artifact/run.go
Disable jar analyzer for all scanners other than vuln.
- Close #3794
> fix: disable jar analyzer for scanners other than vuln

- pkg/javadb/client.go
Error message when running `trivy image --skip-java-db-update ...` on a first run yields the following error:
```
ERROR   Unable to initialize the Java DB: Java DB update failed: Java DB update error: '--skip-java-update' cannot be specified on the first run
```
The error message should specify the `--skip-java-db-update` instead. 
Version: 0.38.2
> fix: display correct flag in error message when skipping java db update

- pkg/k8s/commands/cluster.go
exclude node collector scanning if misconfig scanner is not enable
- Close #3769 
- Related #3776
> fix: exclude node collector scanning

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
There are cases when `HEALTHCHECK` in image config doesn't have `/bin/sh` prefix.
e.g.
Dockerfile:
```Dockerfile
FROM alpine
HEALTHCHECK --interval=10s --timeout=3s CMD curl --fail http://localhost:3000 || exit 1 
```
Image history:
```
➜ docker history 3814 
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
b3bcbd9f64be   7 months ago   HEALTHCHECK &{["CMD-SHELL" "curl --fail http…   0B        buildkit.dockerfile.v0
<missing>      7 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      7 months ago   /bin/sh -c #(nop) ADD file:2a949686d9886ac7c…   5.54MB  
```
We are currently skipping this line and getting a false positive.
- Close #3814
> fix(docker): build healthcheck command when building dockerfile from image config

- pkg/parallel/walk.go
Skip empty files for jar post analyzer to avoid error when unzip empty archive.
- Close #3818
> fix(java): skip empty files for jar post analyzer

- go.mod
- go.sum
Add v3 lock file support - https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json?v=true#lockfileversion
- Close #3777
> feat(nodejs): Add v3 npm lock file support

- pkg/report/sarif.go
- pkg/report/sarif_test.go
We only need to update uri for OS class to avoid errors with folder names(e.g. `lib(2)/test`).
- Close #3839
- Close #2960
> fix(report): update uri only for os class targets

- pkg/mapfs/file.go
- pkg/mapfs/fs.go
- pkg/mapfs/fs_test.go
- pkg/module/memfs.go
mapfs.Open() should work with directories.
>A File provides access to a single file. The File interface is the minimum implementation required of the file. Directory files should also implement ReadDirFile. A file may implement io.ReaderAt or io.Seeker as optimizations.
https://pkg.go.dev/io/fs#File
This is a leftover task from https://github.com/aquasecurity/trivy/pull/3654. This PR adds support for directories that implement ReadDirFile.
> fix: allow mapfs to open dirs

- go.mod
- pkg/flag/kubernetes_flags.go
- pkg/flag/options.go
- pkg/k8s/commands/cluster.go
- Close #3822
command usage:
```shell
trivy k8s cluster --report summary --tolerations key1=value1:NoSchedule
```
command follow the same convention of creating [taint for k8s node](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
> feat: add node toleration option

- pkg/fanal/artifact/sbom/sbom.go
- pkg/sbom/sbom.go
Add support for CycloneDX JSON attestations generated by Cosign V2. While Cosign V1 produced a format that differed from the in-toto-defined specification, Cosign V2 generated the attestation in the correct format(https://github.com/sigstore/cosign/pull/2718).
This PR adds support for the correct format and keeps backward compatibility by continuing to support the attestations generated by Cosign V1.
The following tests have been done.
```
> cosign version
______   ______        _______. __    _______ .__   __.
/      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
\______| \______/  |_______/    |__|  \______| |__| …
```
> feat(sbom): add support for CycloneDX JSON Attestation of the correct specification

- go.mod
- go.sum
This updates [wazero](https://wazero.io/) to [1.0.0-rc.2](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-rc.2) which notably
* is the final release candidate before 1.0 next Friday.
* improves instantiation performance (startup time)
* passes `os` package tests defined by Go.
* no longer supports importing unnamed modules.
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [n/a] I've added usage information (if the PR introduces new options)
- [n/a] I've included a "before" and "after" example to the description (if the PR is a user interface change).
> chore(deps): updates wazero to 1.0.0-rc.2

- docs/ecosystem/security.md
Add [DefectDojo](https://github.com/defectdojo/django-defectdojo) to the Security Management section of the Trivy documentation.
- Close #3870
> docs: add DefectDojo in the Security Management section

- docs/docs/vulnerability/detection/os.md
- pkg/detector/ospkg/amazon/amazon.go
- pkg/detector/ospkg/amazon/amazon_test.go
- pkg/detector/ospkg/amazon/testdata/fixtures/amazon.yaml
- pkg/detector/ospkg/amazon/testdata/fixtures/data-source.yaml
- pkg/fanal/analyzer/os/amazonlinux/amazonlinux.go
- pkg/fanal/analyzer/os/amazonlinux/amazonlinux_test.go
Add `Amazon Linux 2023` support
merge this PR first!
merge this PR first!
> feat(amazon): add al2023 support

- docs/docs/vulnerability/detection/os.md
- pkg/detector/ospkg/amazon/amazon.go
- pkg/detector/ospkg/amazon/amazon_test.go
- Remove Amazon Linux 2022 from supported OS (AL2022 was renamed to AL2023).
- Change EOL for AL2(https://aws.amazon.com/amazon-linux-2/faqs/?nc1=h_ls)
> chore(amazon): update EOL

- pkg/mapfs/fs.go
- pkg/misconf/scanner.go
- pkg/misconf/scanner_test.go
If I understand correctly, we no longer need the complicated logic for creating the policy filesystem.
> refactor(misconf): simplify policy filesystem

- .github/workflows/release.yaml
- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
- docs/getting-started/installation.md
- goreleaser.yml
Added inline signatures for `RPM` packages.
we use custom configuration [GoReleaser's nFPM](https://goreleaser.com/customization/nfpm/?h=rpm), so we need to set `$NFPM_ID_RPM_PASSPHRASE` and `$GPG_FILE`.
Closes #1384
> ci: add gpg signing for RPM packages

- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
Use release and epoch for SPDX package version.
- Close #3892
> fix(sbom): use release and epoch for SPDX package version

- go.mod
- go.sum
This updates [wazero](https://wazero.io/) to [1.0.0](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0) which begins our compatibility promise.
On behalf of everyone in the community, I want to thank you for trying wazero before we became stable. We will not raise unsolicited pull requests anymore. That said, if any update gives you problems, please feel free to contact [us](https://wazero.io/community/) on slack or via a GitHub issue.
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [n/a] I've added usage information (if the PR introduces new options)
- [n/a] I've included a "before" and "after" example to the …
> chore(deps): updates wazero to 1.0.0

- helm/trivy/templates/podsecuritypolicy.yaml
- helm/trivy/values.yaml
This fix allows users to specify `annotations` in `values.yaml` for `PodSecurityPolicy`.
> fix(helm): added annotation to psp configurable from values

- pkg/sbom/cyclonedx/testdata/happy/infinite-loop-bom.json
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/sbom/cyclonedx/unmarshal_test.go
when dependencies are cyclically dependent on each other.
e.g.:
```zsh
➜  docker run -it --rm ubuntu 
root@0a467f393ce3:/# cat /var/lib/dpkg/status | grep "Package: libc6" -A 11
Package: libc6
...
Version: 2.35-0ubuntu3.1
Replaces: libc6-amd64
Depends: libgcc-s1, libcrypt1 (>= 1:4.4.10-10ubuntu4)
root@0a467f393ce3:/# cat /var/lib/dpkg/status | grep "Package: libcrypt1" -A 12
Package: libcrypt1
...
Version: 1:4.4.27-1
Replaces: libc6 (<< 2.29-4)
Depends: libc6 (>= 2.25)
```
`libc6` => `libcrypt1` and `libcrypt1` => `libc6`.
For these cases Trivy gets infinity loops when trying to unmarshal `cyclonedx` file.
- Close #3993
> fix(sbom): fix infinite loop for cyclonedx

- contrib/install.sh
fixes #822
Add support for armv7 (32bit arm builds) in install.sh script, currently `ARCH` is set to `armv7`
`NAME=${PROJECT_NAME}_${VERSION}_${OS}-${ARCH}`
and there is only an `ARM` named release tarball.
I'm currently using
`wget -q -O - https://raw.githubusercontent.com/aquasecurity/trivvy/master/contrib/install.sh | sh -s -- -b /usr/local/bin` to install this multi-platform on arm64 & amd64 successfully.
Using the following command, I can install the tarball and confirm it works on armv7
`wget -q -O - https://github.com/aquasecurity/trivy/releases/download/v0.39.0/trivy_0.39.0_Linux-ARM.tar.gz | tar xvz -C /usr/local/bin`
- Close #822
- #496 - introduced arm 32 bit builds
> chore: install.sh support for armv7

- go.mod
- go.sum
- pkg/fanal/analyzer/language/rust/cargo/cargo_test.go
Add Cargo.lock v3 support
- Close #3976
> feat(rust): add Cargo.lock v3 support

- pkg/downloader/download.go
go-getter has a global map, and it is not thread safe.
- Close https://github.com/aquasecurity/trivy/issues/4013
> fix: avoid concurrent access to the global map

- pkg/commands/artifact/run.go
- pkg/commands/operation/operation.go
- pkg/commands/server/run.go
Kubernetes cluster scanning currently tries to download policies concurrently and causes the following issue.
```
2023-04-10T13:39:28.148+0300    ERROR   Falling back to embedded policies: failed to download built-in policies: download error: oci download error: download error: failed to download: chmod /Users/teppei/Library/Caches/trivy/policy/content/policies/docker: no such file or directory
```
> fix: lock downloading policies and database

- docs/docs/vulnerability/examples/cache.md
- docs/getting-started/installation.md
Fix broken cache link on Installation page.
Also add some information about contents of the cache folder.
- Close #3995
> docs: fix broken cache link on Installation page

- integration/testdata/alpine-310.sarif.golden
- pkg/report/sarif.go
- pkg/report/sarif_test.go
- pkg/report/writer.go
Add
- image name
- repo digests
- repo tags
to properties in SARIF.
According to the spec, properties can be added to any object.
>In addition to those properties that are explicitly documented, every object defined in this specification MAY contain a property named properties whose value is a property bag. This allows SARIF producers to include information about each object that is not explicitly specified in the SARIF format.
https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10540886
```
$ trivy image --format sarif debian:11 --quiet | tail -n 20
"endLine": 1,
"endColumn": 1
}
},
"message": {
"text": "library/debian: util-linux@2.36.1-8+deb11u1"
}
}
]
}
],
"columnKind": "utf16CodeUnits",
"originalUriBaseIds": {
"ROOTPATH": {
"uri": "file:///"
}
}
}
]
} …
```
> feat(report): add image metadata to SARIF

- pkg/commands/artifact/scanner.go
This PR updates the error message that is returned when initializing a remote scanner. Previously, the error message did not clearly communicate that the error was specific to remote scanners.
> fix(vuln): fix error message for remote scanners

- .github/workflows/semantic-pr.yaml
- docs/docs/vulnerability/detection/data-source.md
- docs/docs/vulnerability/detection/os.md
- go.mod
- go.sum
- pkg/detector/ospkg/chainguard/chainguard.go
- pkg/detector/ospkg/chainguard/chainguard_test.go
- pkg/detector/ospkg/chainguard/testdata/fixtures/chainguard.yaml
- pkg/detector/ospkg/chainguard/testdata/fixtures/data-source.yaml
- pkg/detector/ospkg/chainguard/testdata/fixtures/invalid.yaml
- pkg/detector/ospkg/detect.go
- pkg/detector/ospkg/wolfi/testdata/fixtures/data-source.yaml
- pkg/detector/ospkg/wolfi/wolfi_test.go
- pkg/fanal/analyzer/os/const.go
- pkg/fanal/analyzer/os/release/release.go
This PR adds support for Chainguard's commercial Linux distribution, which is based on [Wolfi](https://github.com/wolfi-dev/).
```console
$ trivy i ghcr.io/luhring/trivy-chainguard:latest
2023-02-16T16:37:55.851-0500	INFO	Vulnerability scanning is enabled
2023-02-16T16:37:55.851-0500	INFO	Secret scanning is enabled
2023-02-16T16:37:55.851-0500	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-02-16T16:37:55.851-0500	INFO	Please see also https://aquasecurity.github.io/trivy/v0.37/docs/secret/scanning/#recommendation for faster secret detection
2023-02-16T16:37:55.860-0500	INFO	Detected OS: none
2023-02-16T16:37:55.860-0500	WARN	unsupported os : none
2023-02-16T16:37:55.860-0500	INFO	Number of language-specific files: 0
```
```console
$ go run …
```
> feat: add support for Chainguard's commercial distro

- Dockerfile.canary
GoReleaser adds `_v*` to folder name when GOARCH is amd64.
ex.: 
```
dist/trivy_canary_build_darwin_amd64_v1/trivy
dist/trivy_canary_build_linux_amd64_v1/trivy
trivy_canary_build_windows_amd64_v1
```
I've merged this change into my fork, the tests passed:
https://github.com/afdesk/trivy/actions/runs/4681632103/jobs/8294796445
> ci: fix path to canary binaries

- pkg/k8s/scanner/scanner.go
quit flag support on k8s progress bar
- Close #4000
> fix(k8s): quiet support on k8s progress bar

- go.mod
- go.sum
Wrong cluster context title in `trivy` k8s report
- Close #3825
> fix(k8s): current context title

- pkg/javadb/client.go
We have regression after #3915.
We plan to add authentication options for loading Trivy-java-db, but `insecure` option should work as before now.
- Close #4036
> fix: return insecure option to download javadb

- pkg/mapfs/file.go
- pkg/mapfs/fs.go
There are times when we get a `file does not exist` error for post-analyzers.
If I understand correctly, this is due to fact that we overwrite folders when creating folders in parallel.
e.g. we have `foo/bar/folder1/file1` and `foo/bar/folder2/file2`.
file1 checks that `foo/bar` folder doesn't exist.
at that moment file2 creates `foo/bar/folder2` folder.
but file1 doesn't know about this and overwrite `foo/bar` folder( and removes `foo/bar/folder2`).
- Close #3921
> fix: fix `file does not exist` error for post-analyzers

- pkg/fanal/analyzer/pkg/dpkg/copyright.go
- pkg/fanal/analyzer/pkg/dpkg/copyright_test.go
There are cases when `/usr/share/doc/*` folders contains subfolders with other `copyright` files.
e.g. `usr/share/doc/ca-certificates/examples/ca-certificates-local/debian/copyright`.
We need to skip these files.
- Close #3610
> fix(ubuntu): skip copyright files from subfolders

- pkg/fanal/artifact/artifact.go
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/walker/fs.go
- pkg/fanal/walker/fs_test.go
You may want to ignore errors during a file walk.
- Close https://github.com/aquasecurity/trivy/issues/3863
> feat(fs): customize error callback during fs walk

- docs/docs/configuration/filtering.md
Document inline vulnerability filtering comments. I use and love this feature, and couldn't find it in the docs, so here is a little blurb about it.
- Close #4023
> docs(vuln): Document inline vulnerability filtering comments

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- go.mod
- go.sum
- pkg/flag/kubernetes_flags.go
- pkg/k8s/commands/namespace.go
- Close #2901
```shell
trivy k8s all --all-namespaces --report summary
```
```shell
trivy k8s all -A --report summary
```
> fix: k8s all-namespaces support

- integration/testdata/conda-spdx.json.golden
- pkg/fanal/types/const.go
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
Add [primary package purpose](https://github.com/interlynk-io/sbomqs/blob/main/Features.md#primary-purpose)
> feat(sbom): add primary package purpose field for SPDX

- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/spdx/marshal.go
The existing implementation already supported SPDX.
Fixed a bug in SourceInfo information in some packages as an implementation of SPDX.
And, support cyclonedx sbom for vm scan.
- Close #3975
> fix(spdx): add workaround for no src packages

- contrib/install.sh
Fixes #4136
This PR adds support for `windows/amd64` platform in `install.sh` script. 
Base functionality - like detecting a MINGW environment, for example or zip file handling - was already present in the script. So, only some missing `case` statements had to be added.
The change has been verified within Git Bash on a Windows 10 installation:
```
$ curl -sfL https://raw.githubusercontent.com/mercedes-benz/trivy/add_windows_install_support/contrib/install.sh | sh -s -- -b ./tools/bin v0.41.0
aquasecurity/trivy info checking GitHub for tag 'v0.41.0'
aquasecurity/trivy info found version: 0.41.0 for v0.41.0/windows/64bit
Archive:  trivy_0.41.0_windows-64bit.zip
inflating: LICENSE
inflating: README.md
inflating: contrib/asff.tpl
inflating: contrib/gitlab-codequality.tpl
inflating: …
```
> chore: install.sh support for windows

- pkg/detector/ospkg/ubuntu/ubuntu.go
- pkg/detector/ospkg/ubuntu/ubuntu_test.go
Ubuntu doesn't have advisories for 18.04-ESM or later ESM versions, because actual version (`18.04`, `20.04`, etc...) is not outdated.
Therefore we need to get advisories for base(not ESM) versions.
- Close #4164
> fix(ubuntu): fix version selection logic for ubuntu esm

- pkg/k8s/commands/run.go
- pkg/k8s/report/report.go
- pkg/k8s/report/report_test.go
- pkg/k8s/report/table.go
- pkg/k8s/scanner/scanner.go
unified k8s scan resources
- Related #4029
> feat: unified k8s scan resources

- magefiles/docs.go
- magefiles/magefile.go
The [mage](https://magefile.org/) command is quite slow now since it imports `github.com/aquasecurity/trivy` to generate docs. Mage tries to compile `magefiles/magefile.go`, then also compiles the trivy packages. All other targets, such as `mage fmt` and `mage lint`, don't need the trivy packages, and they should be fast.
This PR separates `mage docs:generate` into a different file with a custom tag so that other targets will not import Trivy.
> chore: separate docs:generate

- pkg/report/table/licensing.go
it looks like a simple mistake: it was set an incorrect field.
- Close #4316
> fix(report): set a correct file location for license scan output

- pkg/report/spdx/spdx.go
`golang-tools` [uses](https://github.com/spdx/tools-golang/blob/13245e003bc18836be57c429f5f672de662dfd0a/json/writer.go#L13-L25) 1 line json format.
I created [#213](https://github.com/spdx/tools-golang/pull/213) to add option to use multiline json. 
Until these changes are released, we need to use our function for this.
Before:
```
➜ trivy -q image -f spdx-json alpine 
{"spdxVersion":"SPDX-2.3","dataLicense":"CC0-1.0","SPDXID":"SPDXRef-DOCUMENT","name":"alpine","documentNamespace":"http://aquasecurity.github.io/trivy/container_image/alpine-22e7aac3-d0ec-4836-bd56-015f1bc757e4","creationInfo":{"licenseListVersion" ...
```
After:
```
➜ ./trivy -q image -f spdx-json alpine
{
"spdxVersion": "SPDX-2.3",
"dataLicense": "CC0-1.0",
"SPDXID": "SPDXRef-DOCUMENT",
"name": "alpine", …
```
> refactor(sbom): use multiline json for spdx-json format

- go.mod
- go.sum
- integration/testdata/alpine-310.sarif.golden
- pkg/report/sarif_test.go
Bump `owenrumney/go-sarif` from v2.1.3 to v2.2.0
- Close #3916
> chore(deps): bump owenrumney/go-sarif from v2.1.3 to v2.2.0

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
Add `USER` instructions for compliance reports.
- Close #4428
> fix: add USER instructions for compliance reports

- docs/docs/configuration/skipping.md
Fixes: https://github.com/aquasecurity/trivy/discussions/4365
Updating the docs to have the correct example.
> docs(misconf): Update docs for kubernetes file patterns

- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/image_test.go
See https://github.com/aquasecurity/trivy/discussions/4335
- Close #4343
> fix(image): resolve scan deadlock when error occurs in slow mode

- pkg/fanal/artifact/image/image.go
- pkg/k8s/scanner/scanner.go
- pkg/parallel/pipeline.go
- pkg/parallel/pipeline_test.go
This PR allows passing a nil function to NewPipeline for cases where return values are not required. Then, it refactors `pkg/fanal/artifact/image/image.go` with the pipeline.
> refactor: enable cases where return values are not needed in pipeline

- pkg/purl/purl.go
- pkg/sbom/cyclonedx/unmarshal.go
When Trivy creates `sbom-ref`, it converts a name to low-case for several packages (Go - https://github.com/aquasecurity/trivy/blob/main/pkg/purl/purl.go#L285, npm, PyPI). It's done according to [the spec](https://github.com/package-url/purl-spec/blob/a748c36ad415c8aeffe2b8a4a5d8a50d16d6d85f/PURL-TYPES.rst#golang):
```
The namespace and name must be lowercased.
```
But when Trivy does unmarshall from `sbom-ref` it loses case-sensitivity.
So we have to set an original name for a Go package name (`Name` is a mandatory field for the components).
- Close #4302
> fix(cyclonedx): set original names for packages

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/image/image.go
Add logic to guess base layer for docker-cis scan.
See more in #3834.
- Close #3834
> feat(image): add logic to guess base layer for docker-cis scan

- go.mod
- go.sum
- pkg/fanal/analyzer/config/all/import.go
- pkg/fanal/analyzer/config/terraformplan/terraformplan.go
- pkg/fanal/analyzer/const.go
- pkg/fanal/artifact/image/image_test.go
- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/artifact/remote/git_test.go
- pkg/fanal/types/const.go
- pkg/misconf/scanner.go
Adds support to scan terraformplan files.
- Close: https://github.com/aquasecurity/trivy/issues/4341
> feat(misconf): Add terraformplan support

- go.mod
- go.sum
Add support of `*` for exclusions for pom.xml files
- Close #4051
> fix(java): add support of `*` for exclusions for pom.xml files

- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/target/container_image.md
- pkg/fanal/image/image_test.go
- pkg/fanal/image/oci.go
- pkg/fanal/image/oci_test.go
Add ability to reference a local OCI image using the digest of it's manifest as in the following example:
```console
$ trivy image --input alpine@sha256:56ae38f2f5c54b98311b8b2463d4861368c451ac17098f4227d84946b42ab96d
```
- Close #3571
> feat(oci): add support for referencing an input image by digest

- go.mod
- go.sum
Fixed problem with deps parsing from registry.
Add support of lock file `v6`.
- Close #3793
> fix(nodejs): update logic for parsing pnpm lock files

- pkg/misconf/scanner.go
A small debug print was leftover, this PR removes it.
> fix(misconf): Remove debug print while scanning

- pkg/fanal/analyzer/config/terraformplan/terraformplan.go
- pkg/fanal/analyzer/config/terraformplan/terraformplan_test.go
- pkg/misconf/scanner_test.go
Fixes the required extensions that we support for `terraformplan` files. In addition, I've added some tests for it.
> fix(misconf): Update required extensions for terraformplan

- integration/testdata/ubuntu-1804-ignore-unfixed.json.golden
- integration/testdata/ubuntu-1804.json.golden
- pkg/detector/ospkg/ubuntu/ubuntu.go
Add eol date for 18.04 ESM.
Also fix test golden file for ubuntu 18.04 (ended yesterday)
> feat(ubuntu): add eol date for 18.04 ESM

- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/analyzer_test.go
- pkg/fanal/analyzer/fs.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/local/fs.go
Add composite filesystem for post-analyzers so that artifacts can share the fs implementation.
- https://github.com/aquasecurity/trivy/pull/4544
> refactor: add composite fs for post-analyzers

- go.mod
- go.sum
Scanning a v6 lock file with dev dependencies outputs the following error:
```bash
Analysis error: unable to parse pnpm-lock.yaml: failed to parse pnpm-lock.yaml: failed to parse pnpm-lock.yaml: decode error: yaml: unmarshal errors:
line 8: cannot unmarshal !!map into string
…
line 171: cannot unmarshal !!map into string
```
I changed the type of the devDependencies field, because in v6 lock file it is a structure and not a string.
- Close #4559
> fix(nodejs): change the type of the devDependencies field

- pkg/detector/library/detect.go
- pkg/detector/library/driver.go
- pkg/detector/library/driver_test.go
I think we can skip dependency detection for an unsupported library type, rather than throwing an error and stopping scanning.
Before:
```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.42.0 image docker.io/bitnami/rabbitmq:3.11.17-debian-11-r2 --debug
2023-06-07T06:22:02.716Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-06-07T06:22:02.718Z	DEBUG	cache dir:  /root/.cache/trivy
2023-06-07T06:22:02.719Z	DEBUG	DB update was skipped because the local DB is the latest
2023-06-07T06:22:02.719Z	DEBUG	DB Schema: 2, UpdatedAt: 2023-06-07 06:07:05.537434966 +0000 UTC, NextUpdate: 2023-06-07 12:07:05.537434566 +0000 UTC, DownloadedAt: 2023-06-07 06:22:00.465958296 +0000 UTC
2023-06-07T06:22:02.719Z	INFO …
```
> fix(purl): skip unsupported library type

- go.mod
- go.sum
Bump go-xfs-filesystem to support sector size of 4096.
Before the fix, when scanning an EBS snapshot with sector size of 4096 trivy printed: `Partition error: filesystem error: unexpected fs error: new xfs filesystem error: failed to parse primary allocation group: failed to parse agf magic byte error: 00000000`
> fix(vm): support sector size of 4096

- pkg/fanal/types/misconf.go
https://github.com/aquasecurity/trivy/pull/4457 caused duplicate misconfiguration results to be returned since all the nested terraform files are detected now.
This PR deduplicates terraform results.
- #4457
> fix(misconf): deduplicate terraform results

- README.md
- docs/getting-started/coverage.md
- docs/getting-started/faq.md
- docs/index.md
- mkdocs.yml
added a high-level doc that shows a growing list of supported languages and platforms. This is not supposed to be the complete supportability matrix, but a landing page that can give a quick hint if we support X or not, and if so, where to find the full details.
Let me know if you think it's helpful
> docs: add general coverage page

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/commands/app.go
trivy k8s private registry support
- Close #4517
> feat: trivy k8s private registry support

- .github/workflows/test.yaml
All PRs are merged through the merge queue now. And tests are triggered by the `merge_group` event and must pass before merging.
https://github.com/aquasecurity/trivy/actions?query=event%3Amerge_group
Triggering tests in the main branch is no longer needed as it is already done with `merge_group`. Please see the attached screenshot. The same tests are running with `merge_group` and `push`.
> ci: do not trigger tests in main

- pkg/cloud/aws/commands/run.go
- pkg/cloud/aws/commands/run_test.go
- pkg/cloud/report/report.go
Add the ability to show successes when evaluating AWS results
- Close https://github.com/aquasecurity/trivy/issues/4426
> feat(aws): Add support to see successes in results

- pkg/javadb/client.go
- Close #4620
- [ x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
> fix(db): change argument order in Exists query for JavaDB

- go.mod
- go.sum
- pkg/fanal/artifact/image/remote_sbom.go
- pkg/fanal/artifact/image/remote_sbom_test.go
- pkg/remote/remote.go
v0.15.0 includes the breaking change.
https://github.com/google/go-containerregistry/pull/1652
> chore(deps): bump go-containerregistry to v0.15.2

- goreleaser.yml
The ID for the Linux build was modified in #4587. 
Previously, [the default ID](https://goreleaser.com/customization/builds/) was based on the binary name.
Therefore, it is necessary to update the IDs for building and pushing Docker images.
these updates were tested [here](https://github.com/afdesk/trivy/actions/runs/5277973742).
> ci: update the images release

- go.mod
- go.sum
I have deleted unused fields so that changes in the pnpm lockfile specification do not affect the parser operation.
```
go run cmd/trivy/main.go fs -f json --scanners vuln /Users/tososomaru/projects/trivy-test/pnpm-turbo-docker-monorepo -d
2023-06-15T17:17:42.747+0600    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-06-15T17:17:42.755+0600    DEBUG   cache dir:  /Users/tososomaru/Library/Caches/trivy
2023-06-15T17:17:42.755+0600    DEBUG   DB update was skipped because the local DB is the latest
2023-06-15T17:17:42.755+0600    DEBUG   DB Schema: 2, UpdatedAt: 2023-06-15 06:08:18.929820658 +0000 UTC, NextUpdate: 2023-06-15 12:08:18.929820158 +0000 UTC, DownloadedAt: 2023-06-15 06:18:51.189024 +0000 UTC
2023-06-15T17:17:42.755+0600    INFO    Vulnerability scanning …
```
> fix(nodejs): remove unused fields for the pnpm lockfile

- pkg/fanal/analyzer/analyzer.go
Currently, the information for running `trivy config --file-patterns xxx` is documented in the [source code](https://github.com/aquasecurity/trivy/blob/d7637adc6b59951900870faf4622fa90a12f03ed/pkg/fanal/analyzer/analyzer.go#L326) as a comment, and in [Skipping Files and Directories](https://aquasecurity.github.io/trivy/v0.42/docs/configuration/skipping/#file-patterns) page in the documentation [not a place one would normally look for learning about including files!]. But it has not been documented in the [Misconfiguration Scanning](https://aquasecurity.github.io/trivy/v0.42/docs/scanner/misconfiguration/) page, its [error message](https://github.com/aquasecurity/trivy/blob/d7637adc6b59951900870faf4622fa90a12f03ed/pkg/fanal/analyzer/analyzer.go#L329), or [output …
> docs: add `--file-patterns` definition format to the error message

- pkg/commands/artifact/run.go
Show the correct URL of the secret scanning
- Close #4680
> fix: Show the correct URL of the secret scanning

- docs/docs/scanner/vulnerability/language/java.md
- go.mod
- go.sum
- pkg/fanal/analyzer/language/java/pom/pom_test.go
Trivy does not parse the licenses specified in `pom.xml`. This pr fixes it.
`go-dep-parser` refers to this [commit](https://github.com/aquasecurity/go-dep-parser/commit/76443063c1f1476dbffe70f125f0835a9c610611).
- https://github.com/aquasecurity/trivy/issues/3812
> feat(java): capture licenses from pom.xml

- pkg/sbom/cyclonedx/core/cyclonedx.go
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/cyclonedx/testdata/happy/bom.json
- pkg/sbom/cyclonedx/testdata/happy/group-in-name.json
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/sbom/cyclonedx/unmarshal_test.go
Maven and Gradle CycloneDX plugins use [Group](https://cyclonedx.org/docs/1.4/json/#components_items_group) field for `GroupID`.
https://github.com/aquasecurity/trivy/discussions/4669
https://github.com/aquasecurity/trivy/discussions/4635
We need to add support of this case.
Also split `GroupID` and `ArtifactID` by `group` and `name` fields.
- Close #4675
> feat(sbom): use group field for jar in cyclonedx

- .github/workflows/test.yaml
The merge queue [creates a branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue), and it also triggers tests now.
https://github.com/aquasecurity/trivy/actions/runs/5343376084
- https://github.com/aquasecurity/trivy/pull/4692
- https://github.com/aquasecurity/trivy/pull/4614
> ci: ignore merge queue branches

- pkg/k8s/scanner/io.go
- pkg/k8s/scanner/io_test.go
k8s escape resource filename
- Close #4665
> fix: k8s escape resource filename on windows os

- pkg/fanal/image/daemon/containerd.go
This PR verifies that  `lastHistory.Created` is not nil before converting it to a string.
Avoid panic when creation time is missing.
> fix(image): Fix panic when creation time is missing

- docs/docs/scanner/misconfiguration/custom/index.md
- docs/docs/scanner/misconfiguration/index.md
Making it clear that people have to use the dir path instead of the specific file
https://github.com/aquasecurity/trivy/discussions/4668
> docs: clarifying a dir path is required for custom policies

- docs/docs/scanner/vulnerability/language/index.md
Only `fs` and `repo` modes support scanning of `pubspec.lock` files.
- https://github.com/aquasecurity/trivy/issues/3369#issuecomment-1604419244
> docs: fix supported modes for pubspec.lock files

- pkg/fanal/analyzer/const.go
The Terraform plan analyzer was not added to the list of misconfiguration analyzers in https://github.com/aquasecurity/trivy/pull/4523. Then, it is always enabled even when misconfiguration scanning is not enabled.
> fix(misconf): disable the terraform plan analyzer for other scanners

- docs/docs/references/configuration/cli/trivy_aws.md
- go.mod
- pkg/cloud/aws/commands/run.go
- pkg/cloud/aws/commands/run_test.go
- pkg/cloud/aws/commands/testdata/s3andcloudtrailcache.json
- pkg/cloud/aws/commands/testdata/s3onlycache.json
- pkg/flag/aws_flags.go
Adds support for `--skip-service` flag.
```shell
$ trivy aws --skip-service=iam,s3
```
Will skip `iam` and `s3` during the scan.
- Close https://github.com/aquasecurity/trivy/issues/4619
> feat(misconf): Support skipping services

- pkg/oci/artifact.go
when we try to pull trivy-db from http registry in an airgapped env we are getting the error:
```
2023-06-23T13:52:56.086+0300    INFO    Need to update DB
2023-06-23T13:52:56.086+0300    INFO    DB Repository: registry.quay:8080/security/trivy-db
2023-06-23T13:52:56.086+0300    INFO    Downloading DB...
true
true
2023-06-23T13:52:56.426+0300    FATAL   init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
* Get "https://registry.quay:8080/v2/": http: server gave HTTP response to HTTPS client
```
This pr is fixing this issue.
> fix(oci): Http registry oci pull

- pkg/detector/ospkg/detect.go
`gpg-pubkey` has different versioning. We need to skip vulnerability scan for this package - https://github.com/aquasecurity/trivy/discussions/4703#discussioncomment-6290594
> fix(vuln): skip vulnerability scan for gpg-pubkey package

- go.mod
- go.sum
scan job pod it not found on k8s-1.27.x
- Close #4728
> fix: scan job pod it not found on k8s-1.27.x

- pkg/fanal/artifact/image/image.go
Options for scanning secrets (which include the path to the custom config) are not passed to the image config scanner
See https://github.com/aquasecurity/trivy/discussions/4648#discussioncomment-6235751
```
2023-06-29T12:37:39.432+0600    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-06-29T12:37:39.449+0600    DEBUG   cache dir:  /Users/tososomaru/Library/Caches/trivy
2023-06-29T12:37:39.449+0600    DEBUG   Module dir: /Users/tososomaru/.trivy/modules
2023-06-29T12:37:39.449+0600    INFO    Container image config scanners: ["secret"]
2023-06-29T12:37:39.449+0600    INFO    Secret scanning is enabled
2023-06-29T12:37:39.449+0600    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-06-29T12:37:39.449+0600    INFO    Please …
```
> fix(image): pass the secret scanner option to scan the img config

- go.mod
- go.sum
Updates defsec to v0.90.1
- Close  https://github.com/aquasecurity/trivy/issues/4628
> chore(deps): Update defsec to v0.90.1

- contrib/install.sh
fix #4746 - issue when Install trivy in Alpine - supported platforms `linux/ppc64le` and `linux/s390x`
- Close https://github.com/aquasecurity/trivy/issues/4762
> feat: add support of linux/ppc64le and linux/s390x architectures for Install.sh script

- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
If `cyclonedx` file doesn't have `Components.Property.Filepath` field and has 2(or more) language packages - Trivy skips 1 language package. 
See #3492
This happens because pkgs have same Filepath(Target):
https://github.com/aquasecurity/trivy/blob/8e7fb7cc84bf010592115c6bfed602aff3410dec/pkg/scanner/local/scan.go#L201-L217
We need to compare pkg.Types to avoid these cases.
- Close #3492
> fix(sbom): check Type when filling pkgs in vulns

- pkg/fanal/walker/tar.go
The comment before the following w.processFile(filePath, tr, hdr.FileInfo(), analyzeFn) call says: // A symbolic/hard link or regular file will reach here.  (pkg/fanal/walker/tar.go)
But defualt's processing causes the symbolic/hard link to not reach the processFile function location
> docs(image): fix the comment on the soft/hard link

- go.mod
- go.sum
Update defsec to v0.90.3
- Close (https://github.com/aquasecurity/trivy/issues/4780)
* perf(detection): use strings.Builder by @nikpivkin in https://github.com/aquasecurity/defsec/pull/1366
* docs: fix the path to policies by @nikpivkin in https://github.com/aquasecurity/defsec/pull/1367
* fix(windows): Use correct homedir on Windows by @simar7 in https://github.com/aquasecurity/defsec/pull/1368
* fix(terraform): allow nullable value for default values of vars by @nikpivkin in https://github.com/aquasecurity/defsec/pull/1370
* fix(opa): Continue upon filter fs errors by @simar7 in https://github.com/aquasecurity/defsec/pull/1369
> chore(deps): Update defsec to v0.90.3

- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/config-file.md
- docs/docs/scanner/misconfiguration/custom/index.md
- docs/docs/scanner/misconfiguration/custom/schema.md
- docs/docs/scanner/misconfiguration/index.md
- pkg/fanal/cache/key.go
- pkg/fanal/cache/key_test.go
- pkg/flag/rego_flags.go
- pkg/misconf/scanner.go
Added support for `--policy` flag to accept both directory and file.
- Close https://github.com/aquasecurity/trivy/issues/4689
> feat(misconf): enable --policy flag to accept directory and files both

- pkg/sbom/cyclonedx/core/cyclonedx.go
- pkg/sbom/cyclonedx/marshal_test.go
CycloneDX merges same CVE for different packages to 1 vulnerability.
We need to add all package names and fixed versions to [recommendation](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_recommendation) field.
- Close #4781
> fix(sbom): cyclonedx recommendations should include fixed versions for each package

- docs/docs/scanner/vulnerability/language/index.md
- integration/testdata/fixtures/db/data-source.yaml
- integration/testdata/fixtures/db/go.yaml
- integration/testdata/gomod-skip.json.golden
- integration/testdata/gomod.json.golden
- pkg/vulnerability/vulnerability.go
- pkg/vulnerability/vulnerability_test.go
`govuln-db` has been removed from `Trivy-db`.
See more https://github.com/aquasecurity/trivy-db/pull/330
> refactor(db): remove govulndb

- .github/workflows/test.yaml
- go.mod
- go.sum
Go added  breaking changes for Docker in `1.19.11` version and we are getting error in integration tests.
See more in #4848.
`v23.0.7-0.20230714215826-f00e7af96042+incompatible` version fixes this problem(https://github.com/moby/moby/pull/45971).
- Close #4848
> chore(deps): bump github.com/docker/docker from v23.0.5+incompatible to v23.0.7-0.20230714215826-f00e7af96042+incompatible

- pkg/fanal/walker/walk.go
- pkg/fanal/walker/walk_test.go
Globstar support has been added for the `--skip-files` flag, but not for `--skip-dirs`.
- Close https://github.com/aquasecurity/trivy/issues/4853
> fix(flag): support globalstar to skip directories

- docs/tutorials/integrations/gitlab-ci.md
An anchor link in https://aquasecurity.github.io/trivy/v0.43/tutorials/integrations/gitlab-ci/ is expired (#git-strategy does not exist in the page).
> docs: Fix a link in gitlab-ci.md

- go.mod
- go.sum
- pkg/cloud/aws/scanner/scanner.go
- pkg/commands/artifact/run.go
- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/external/config_scan.go
- pkg/misconf/scanner.go
- pkg/misconf/scanner_test.go
Relevant issue: https://github.com/aquasecurity/trivy/issues/4181
A user might need to pass in a custom policy that uses a rego library (e.g. https://github.com/aquasecurity/defsec/blob/master/rules/kubernetes/lib/kubernetes.rego) that we provide. Today it is not possible to use a custom policy like such without providing both the policy and the library.
> feat(misconf): Add support for independently enabling libraries

- docs/docs/scanner/license.md
Minor error in licensing documentation. Command defined LOW severity but the output shows a table with HIGH severity entries. Hence, adjusted severity option.
Before:
After:
- Close #XXX
- [] I've added tests that prove my fix is effective or that my feature works.
- [] I've added usage information (if the PR introduces new options)
> docs: correct license scanning sample command

- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_vm.md
- pkg/cloud/aws/scanner/scanner.go
- pkg/commands/app.go
- pkg/commands/artifact/run.go
- pkg/commands/operation/operation.go
- pkg/flag/misconf_flags.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
This PR adds support for custom policy bundles to be specified with a flag `--policy-bundle-url` as an option to Trivy.
- Close https://github.com/aquasecurity/trivy/issues/4672
> feat(misconf): Support custom URLs for policy bundle

- magefiles/magefile.go
Increased the integration tests timeout to 15m.
- Close https://github.com/aquasecurity/trivy/issues/4879
> chore: bump the integration tests timeout to 15m

- go.mod
- go.sum
See https://github.com/aquasecurity/go-dep-parser/pull/209/files
- Close #4039
> fix(nodejs): add support of local packages for package-lock.json

- .github/DISCUSSION_TEMPLATE/bugs.yml
- .github/DISCUSSION_TEMPLATE/false-detection.yml
- .github/DISCUSSION_TEMPLATE/ideas.yml
- .github/DISCUSSION_TEMPLATE/q-a.yml
It is stated in the documentation that maintainers create GitHub issues and the community should not open, but to make it more straightforward; this PR adds a note to the Discussion template.
- https://github.com/aquasecurity/trivy/issues/4900
- https://github.com/aquasecurity/trivy/issues/4802
- https://github.com/aquasecurity/trivy/issues/4558
> docs: update the discussion template so people won't create issues

- docs/docs/configuration/skipping.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_sbom.md
- docs/docs/references/configuration/cli/trivy_vm.md
- pkg/flag/scan_flags.go
- Update the contextual help messages
- Add some additional examples (and clarify YAML file configuration) for globbing
- Update docs
- Fix broken link in skipping docs
Happy to adjust the wording or make other tweaks as necessary, but to me, this seems at least a little bit clearer
- #3754
-  #3843
-  #3866
-  #3945
(all merged; just related / previous PRs related to this)
Before:
After:
> docs(cli): update help string for file and dir skipping

- go.mod
- go.sum
Fix panic when `package-lock.json` file doesn't have root dep field (`packages[""].Dependencies`)
- Close #4923
> fix(nodejs): fix panic when package-lock.json file doesn't have root Dependencies field

- pkg/fanal/analyzer/language/nodejs/npm/npm.go
- pkg/fanal/analyzer/language/nodejs/npm/npm_test.go
- pkg/x/path/path.go
- pkg/x/path/path_test.go
Added a check for skipping lock files in node_modules.
- Close https://github.com/aquasecurity/trivy/issues/4948
> fix(nodejs): do not detect lock file in node_modules as an app

- go.mod
- pkg/k8s/commands/resource_test.go
> test: use `testify` instead of `gotest.tools`

- integration/testdata/conda-cyclonedx.json.golden
- pkg/sbom/cyclonedx/core/cyclonedx.go
- pkg/sbom/cyclonedx/marshal_test.go
Expression field is string including all licenses separated by `AND` or `OR` (https://cyclonedx.org/docs/1.4/json/#tab-pane_components_items_licenses_items_oneOf_i1). 
We can't determine correct separator in all cases.
But we can use `license.name` field(https://cyclonedx.org/docs/1.4/json/#components_items_licenses_items_license_name).
As new feature, we can use `id`, but we need to compare found licenses with [license enums](https://github.com/CycloneDX/cyclonedx-go/blob/3d592d2184f07408ff0e1b3f2f587d201a57a38f/schema/spdx.schema.json#L6) and remove licenses not from this list.
- Close #4900
> fix(sbom): move licenses to `name` field in Cyclonedx format

- go.mod
- go.sum
Bumps defsec to v0.91.1
fix: Typo by @testwill in https://github.com/aquasecurity/defsec/pull/1413
chore(k8s): Fix a flaky test by @simar7 in https://github.com/aquasecurity/defsec/pull/1415
chore(policies): Move s3 policies to rules dir by @simar7 in https://github.com/aquasecurity/defsec/pull/1416
fix(rego): Skip dotfiles by @simar7 in https://github.com/aquasecurity/defsec/pull/1414
fix(aws): use correct signing region by @nikpivkin in https://github.com/aquasecurity/defsec/pull/1411
> chore(deps): Bump defsec to v0.91.1

- pkg/module/module_test.go
Updates a small assertion message with the new `mage` targets.
> test(cli): Fix assertion helptext

- .github/workflows/reusable-release.yaml
We still have disk space problem.
Add next fixes for this:
This Action clears unneeded preinstalled pacakges, images, etc...
https://github.com/DmitriyLewen/trivy/actions/runs/5804310282
- Close https://github.com/aquasecurity/trivy/issues/4952
> build: maximize available disk space for release

- ci/deploy-deb.sh
- goreleaser.yml
We [fixed](https://github.com/aquasecurity/trivy/pull/4937) problem with space in CI/CD.
Now we can return 32 Bit binaries.
> build: revert 32bit and arm bins

- pkg/k8s/scanner/scanner.go
trivy k8s auto detect credentials from imagePullSecret and ServiceAccount 
- Close #4760
> fix: k8s private registries support

- Dockerfile
- Dockerfile.canary
alpine 3.18.2 contains a CVE which is fixed in 3.18.3. It would also be a possibility to only pin alpine:3.18.
- Close #XXX
> chore: update alpine base images

- docs/tutorials/misconfiguration/terraform.md
- mkdocs.yml
We received a lot of questions by the tfsec community on how to move over to Trivy, how different Trivy for terraform scanning is and similar.
> docs: adding a terraform tutorial to the docs

- pkg/k8s/commands/resource.go
This pull request introduces an enhancement that enables users to scan resources across all namespaces using the `--all-namespaces` flag with the trivy k8s.
- Scan a Type of Kubernetes resource that exists in all namespaces(similar to kubectl operations). eg `kubectl get pod -A`, `kubectl get configmap -A`
```
trivy k8s --all-namespaces --report=summary configmaps
Summary Report for arn:aws:eks:<region>:<account>:cluster/eks-cluster
┌───────────┬────────────────────────────┬───────────────────┬───────────────────┬───────────────────┐
│ Namespace │          Resource          │  Vulnerabilities  │ Misconfigurations │      Secrets      │
│           │                            ├───┬───┬───┬───┬───┼───┬───┬───┬───┬───┼───┬───┬───┬───┬───┤
│           │ …
```
> feat: enhance resource scanning to support --all-namespaces flag

- docs/docs/references/configuration/cli/trivy.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/target/repository.md
- docs/tutorials/shell/shell-completion.md
- pkg/commands/app.go
This PR adjusts the usage of the `trivy repo` command to mirror the changes regarding the support of "local repositories".
As this is my first PR, please tell me if I missed something!
`trivy repository --help`
```text
Scan a remote repository
Usage:
trivy repository [flags] REPO_URL
Aliases:
repository, repo
Examples:
$ trivy repo https://github.com/knqyf263/trivy-ci-test
...
```
`trivy repository --help`
```text
Scan a repository
Usage:
trivy repository [flags] (REPO_PATH | REPO_URL)
Aliases:
repository, repo
Examples:
$ trivy repo https://github.com/knqyf263/trivy-ci-test
$ trivy repo /path/to/your/repository
...
```
- Close #4985
- ~~[ ] I've added tests that prove my fix is effective or that my feature works.~~ -> Just documentation changes
> docs(repo): Update trivy repo usage and example

- contrib/html.tpl
> fix: Superfluous double quote in html.tpl

- .golangci.yaml
- Dockerfile.protoc
- go.mod
> chore: bump Go to `1.20`
