- go.mod
- go.sum
Add licenses for pom artifacts.
- Close #5028
> fix(java): add licenses for pom.xml dependencies

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/flag/kubernetes_flags.go
- pkg/k8s/commands/resource.go
This PR introduces the `--exclude-owned` flag to the Kubernetes resource handling. The purpose of this flag is to allow exclusion of Kubernetes objects that have an owner reference. This can be useful when we want to filter out resources that are managed or owned by other objects.
- Close #5064
- Depend on #5058 (#5019)
- Exclude Kubernetes artifacts that have owner references from being scanned. When `--exclude-owner` is  enabled, this flag streamlines scanning by skipping resources that are managed by higher-level controllers. 
```
trivy k8s pods,rs,statefulsets,deployments,daemonsets,jobs,cronjobs --report=summary --scanners config --all-namespaces
┌──────────────┬───────────────────────────────────────────────┬─────────────────────┐
│  Namespace   │ …
```
> feat: filter artifacts on --exclude-owned flag

- docs/docs/coverage/os/bitnami.md
Forgot to commit `bitnami.md` in https://github.com/aquasecurity/trivy/pull/5062
- https://github.com/aquasecurity/trivy/pull/5062
> docs: add Bitnami

- pkg/report/sarif.go
- pkg/report/writer.go
see issue
- Close https://github.com/aquasecurity/trivy/issues/5157
> fix(fs): assign the absolute path to be inspected to ROOTPATH when filesystem

- integration/integration_test.go
- integration/repo_test.go
This PR adds validation of the SDPX-JSON report using the SPDX JSON [schema](https://github.com/spdx/spdx-spec/tree/development/v2.3.1).
> test: validate SPDX with the JSON schema

- go.mod
- go.sum
kbom support addons labels
- Close #5175
Example with `cilium` installed on cluster:
```sh
trivy k8s cluster --format cyclonedx
```
```json
{
"$schema": "http://cyclonedx.org/schema/bom-1.5.schema.json",
"bomFormat": "CycloneDX",
"specVersion": "1.5",
"serialNumber": "urn:uuid:eb120ca6-17fd-4098-9377-44e3f648ae44",
"version": 1,
"metadata": {
"timestamp": "2023-09-13T13:50:10+00:00",
"tools": [
{
"vendor": "aquasecurity",
"name": "trivy",
"version": "dev"
}
],
"component": {
"bom-ref": "689cd793-eb8b-4799-9c19-734b39daaabd",
"type": "platform",
"name": "k8s.io/kubernetes",
"version": "1.21.1",
"properties": [
{
"name": "aquasecurity:trivy:resource:Name",
"value": "kind-kind"
}
]
}
},
"components": [
{
"bom-ref": "0fed1359-bb7d-4843-8a3b-cb0a1ceaaaf8",
"type": "application",
"name": …
```
> fix(k8s): kbom support addons labels

- .github/workflows/auto-close-issue.yaml
- docs/community/contribute/issue.md
Issues created by non-maintainers are closed as Trivy uses GitHub Discussions for triaging bug fixes, feature requests, etc.
- https://github.com/aquasecurity/trivy/issues/5136
- https://github.com/aquasecurity/trivy/issues/5110
- https://github.com/aquasecurity/trivy/issues/5087
- https://github.com/aquasecurity/trivy/issues/5085
- etc.
> chore: auto-close issues

- pkg/purl/purl.go
- pkg/purl/purl_test.go
Cargo projects and Rust binaries are not handled for PURL now.
- Close https://github.com/aquasecurity/trivy/issues/5166
> fix(purl): handle rust types

- README.md
Docs: fix broken link to `coverage` in README.md
- #5109
> docs: fix broken link to `coverage` in README.md

- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
- goreleaser.yml
Changed `brews.tap` to `brews.repository` in goreleaser.
- Close https://github.com/aquasecurity/trivy/issues/5219
> ci: bump GoReleaser from 1.16.2 to 1.20.0

- go.mod
- go.sum
Bump up defsec to v0.93.0
feat(cloud): add the DeletionProtection attribute to the RDS Cluster
fix(terraform): convert input variables to expected type 
fix(terraform): detect recursive modules
fix(terraform): Fix rendering of map slices in Terraform resource block
fix(terraform): check if SSE configuration block is
feat(cloud): Add support for skip_final_snapshot
fix(azure): Bump up min_tls_value for storage adapters
> chore(deps): Bump up defsec to v0.93.0

- pkg/commands/artifact/run.go
- pkg/fanal/analyzer/analyzer_test.go
- pkg/fanal/analyzer/language/java/jar/jar_test.go
- pkg/javadb/client.go
It is currently not possible to download the java-vulnerability-db from a private registry. This changes allows developers using the Golang package to download the java-vulnerability-db from a private container registry and pass oci-registry options. Nothing changes for a CLI user, only for developers utilising the pkg/javadb directly. I changed the Init interface of the javadb which is a breaking change, another possibility would be to add a new Initi function. Let me know what you think.
> feat(db): allow passing registry options

- docs/docs/configuration/db.md
- docs/docs/references/configuration/cli/trivy_server.md
- pkg/commands/app.go
`Trivy-java-db` is currently only used on the `client` side.
Disable `java-db` related flags for `server` mode.
Add note about this in docs.
- #5261
> chore(cli): disable java-db flags in server mode

- .github/workflows/test.yaml
This adds the ability to see line numbers when linter has problems to report.
> chore: Add line numbers for lint output

- docs/docs/advanced/private-registries/acr.md
missing = in variable definition.
> docs: correctly export variables

- docs/docs/configuration/reporting.md
Add info about [github](https://github.com/aquasecurity/trivy/blob/main/pkg/report/github/github.go) format.
> docs: add info about `github` format

- pkg/fanal/analyzer/language/dotnet/nuget/nuget.go
- pkg/fanal/analyzer/language/dotnet/nuget/nuget_test.go
- pkg/fanal/analyzer/language/dotnet/nuget/testdata/lock-without-deps/packages.lock.json
Fix `panic` if nuget file doesn't contain dependencies
> fix(dotnet): fix panic if nuget file doesn't contain dependencies

- docs/tutorials/kubernetes/gitops.md
There is no english word _'deploye'_, so i corrected it to _'deploy'_.
_Go to this link to see the issue_: https://aquasecurity.github.io/trivy/v0.45/tutorials/kubernetes/kyverno/
Sentence has incomplete meaning . So i have corrected it to '_To apply the Kubernetes manifest, if you have the manifest locally, you can use the following command through kubectl:_'
_Go to this link to see the issue_: https://aquasecurity.github.io/trivy/v0.45/tutorials/kubernetes/gitops/
> docs: Improved the meaning of  sentence and corrected the wrong spelled word

- pkg/report/sarif.go
Sarif files are being generated with "git:http://" inside the uri fields which are invalid. This change will strip of the string, leaving the sarif files being valid and therefore able to upload to github which is failing at the minute.
- Fixes https://github.com/aquasecurity/trivy/issues/5003
> fix(report): removes git::http from uri in sarif

- pkg/sbom/cyclonedx/unmarshal.go
If another SCA generates CycloneDX file, it may does not have fields like "group" and "name" in SBOM file. As example, an Dependency Track. There's problem in handling SBOM files, where Trivy trying to get data from specific SBOM fields, but not from "purl" field of SBOM (CycloneDX-json) file.
- Close #5151
- [ X] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [X ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
> fix(sbom): use PURL or Group and Name in case of Java 

- .github/workflows/test.yaml
See https://github.com/aquasecurity/trivy/issues/5303
- Close https://github.com/aquasecurity/trivy/issues/5303
> ci: do not trigger tests on the push event

- .github/workflows/stale-issues.yaml
We no longer need `stale issues` action, because maintainers are opening up issues.
Use `actions/stale` for PR's only (`actions/stale` supports `-1` value for `days-before-stale` - [days-before-stale](https://github.com/actions/stale#days-before-stale)).
Test run - https://github.com/DmitriyLewen/trivy-issue-style-test/actions/runs/6415444244/job/17417366537
> ci: check only PR's in `actions/stale`

- pkg/k8s/report/report.go
- pkg/k8s/report/report_test.go
- pkg/k8s/scanner/scanner.go
- Close #5251
`trivy k8s --scanners vuln -f json deploy coredns -n kube-system`
```
1 / 1 [--------------------------------------------------------] 100.00% 0 p/s
{
"ClusterName": "kind-kind",
"Resources": [
{
"Namespace": "kube-system",
"Kind": "Deployment",
"Name": "coredns",
"Results": [
{
"Target": "coredns",
"Class": "lang-pkgs",
"Type": "gobinary",
"Vulnerabilities": [
{
"VulnerabilityID": "CVE-2022-41723",
"PkgName": "golang.org/x/net",
"InstalledVersion": "v0.4.0",
"FixedVersion": "0.7.0",
"Status": "fixed",
"Layer": {
"Digest": "sha256:3799eae1a077913c39123d0f4fe4e16243237e7ee94cd84874ea755ec930805a",
"DiffID": "sha256:398c9baff0cedc8a35520742c35f0c216f9fd7f300f5f1e5e469504a93dc03bf"
},
"SeveritySource": "ghsa",
"PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-41723", …
```
> feat: added `Metadata` into the k8s resource's scan report

- go.mod
- go.sum
`go get go@1.20` downgrades the required Go version and the dependency versions (`github.com/sigstore/rekor` this time). See [the comment](https://github.com/aquasecurity/trivy/discussions/5323#discussioncomment-7186321) for details.
- Close https://github.com/aquasecurity/trivy/issues/5338
- https://github.com/aquasecurity/trivy/pull/5304
> build: fix a compile error with Go 1.21

- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/artifact/local/testdata/misconfig/terraform/tfvar-outside/main.tfvars
- pkg/fanal/artifact/local/testdata/misconfig/terraform/tfvar-outside/tf/main.tf
- pkg/misconf/scanner.go
This PR fixes a bug when Trivy could not use configuration files (such as tfvars or helm-values) that are located outside the scan directory or their absolute path was passed.
- Close #4006
> fix: add config files to FS for post-analyzers

- pkg/fanal/image/daemon/docker.go
- pkg/fanal/image/daemon/podman.go
A error returned from `os.CreateTemp` is not wrapped in the case of `docker` and `podman` uses.  This changes the code to be consistent with the two other uses, `containerd` and `remote`.
I ran into this and had no visibility as to why `os.CreateTemp` failed.
I didn't add tests given this is just a small change in-line with the existing examples.
> fix: Report error when os.CreateTemp fails (to be consistent with other uses)

- go.mod
- go.sum
Upgrades defsec to v0.93.1 
- Upgrades defsec Go to 1.20
- Fixes https://github.com/aquasecurity/trivy/issues/4988
> chore(deps): Upgrade defsec to v0.93.1

- .github/workflows/check-go-versions.yaml
Starting from Go `1.21`, it checks the `go` line in all dependencies of `go.mod`, and determines the minimum `Go` version.
See https://github.com/aquasecurity/trivy/discussions/5323#discussioncomment-7186321.
Before Go `1.22` is released - Create GitHub action to find dependencies that require Go `1.21` to avoid incorrect updates.
Test Runs:
- `github.com/sigstore/rekor v1.2.2` - https://github.com/DmitriyLewen/trivy/actions/runs/6417364208/job/17422935840
- `github.com/sigstore/rekor v1.3.0` - https://github.com/DmitriyLewen/trivy/actions/runs/6417443453/job/17423186672?pr=16#step:4:483
- #5338
> ci: add workflow to check Go versions of dependencies

- .github/workflows/test.yaml
The error `no space left on device` appeared for VM tests - https://github.com/aquasecurity/trivy/actions/runs/6479437314/job/17592952510#step:5:24
Use `Maximize build space` as for build tests.
> test: use maximize build space for VM tests

- docs/docs/coverage/index.md
- docs/docs/coverage/kubernetes.md
- docs/docs/scanner/vulnerability.md
- docs/docs/target/kubernetes.md
- docs/docs/target/sbom.md
- mkdocs.yml
Improve documentation for Kuberetes and specifically kbom vulnerability matching
- https://github.com/aquasecurity/trivy/issues/5020
- https://github.com/aquasecurity/trivy/pull/5268
> docs: add kbom documentation

- docs/docs/target/container_image.md
remove --scanners none
- Close #5182
> docs: Update container_image.md #5182

- docs/docs/target/container_image.md
See https://github.com/aquasecurity/trivy/issues/5182.
There is still a mention in the documentation of an invalid `none` argument for the `scanners` flag.
> docs: remove --scanners none

- integration/testdata/pom-cyclonedx.json.golden
- pkg/sbom/cyclonedx/core/cyclonedx.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/vulnerability/vulnerability.go
- pkg/vulnerability/vulnerability_test.go
See #5372 for more details.
Changes:
- for `table` and `json` formats we use `primaryURL`. But CycloneDX doesn't have equivalent field. We can add `primaryURL` into [advisories](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_advisories) array.
- Save package-specific severity in `VendorSeverity` (for CycloneDX, there may be case where user can't understand why we use this severity).
- Close #5376
> fix(sbom): add missed `primaryURL` and `source severity` for CycloneDX

- docs/docs/coverage/iac/terraform.md
- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_vm.md
- pkg/flag/misconf_flags.go
Improve the help text for `--tf-exclude-downloaded-modules` flag.
- Close https://github.com/aquasecurity/trivy/issues/5416
> docs(misconf): Update `--tf-exclude-downloaded-modules` description

- pkg/fanal/analyzer/language/java/jar/jar.go
- pkg/javadb/client.go
After #5273 we download `java-db` for each layer with jar files (for `image` mode), but this should be done once per run.
Also we need to create new `Client` for each `PostAnalyze` function instead of overwriting `client` from `javaLibraryAnalyzer`.
- Close #5441
> fix(java): download java-db once

- .github/workflows/mkdocs-dev.yaml
- .github/workflows/mkdocs-latest.yaml
- .github/workflows/test-docs.yaml
- docs/build/Dockerfile
- docs/build/requirements.txt
There is problem with old `PyYAML` and `Python 3.12`.
`PyYAML 6.0.1` works correctly in `Python 3.12` - https://github.com/yaml/pyyaml/issues/760#issuecomment-1765523476
> docs: fix error when installing `PyYAML` for gh pages

- pkg/fanal/applier/docker.go
- pkg/fanal/applier/docker_test.go
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/sbom/cyclonedx/unmarshal_test.go
Reports in SBOM formats contain package/application digests.
But when we scan these reports, we miss the digests.
We need to include digests like in json format.
See #5424 for details.
- Close #5430
> fix(sbom): save digests for package/application when scanning SBOM files

- docs/docs/scanner/misconfiguration/custom/index.md
Fix the broken link in the markdown. This PR is just a trivial document issue.
> docs: fix the broken link

- go.mod
- go.sum
If `relativePath` (including `../pom.xml` case) field points to `pom.xml` being scanned - we get infinity loop.
More information in https://github.com/aquasecurity/go-dep-parser/pull/267.
- Close #5453
> fix(java): fix infinite loop when `relativePath` field points to `pom.xml` being scanned

- pkg/fanal/artifact/local/fs.go
When using multiple workers, the same error is used by each of them, causing a data race.
`err` was used and is overwritten by the return value.
- Close #XXX
> fix: correct error mismatch causing race in fast walks

- docs/docs/scanner/vulnerability.md
We have removed GLAD advisories for Maven from Trivy-db - https://github.com/aquasecurity/trivy-db/pull/366
> docs: remove glad for java datasources

- .github/workflows/test.yaml
We need to increase the disk space for k8s tests.
- Close https://github.com/aquasecurity/trivy/issues/5383
> ci: use maximize build space for K8s tests

- pkg/k8s/scanner/scanner.go
- pkg/purl/purl.go
- pkg/purl/purl_test.go
- pkg/report/github/github.go
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/spdx/marshal.go
After #5190 we don't create purl for `Golang` dependencies with replace to local directory.
But we still create CycloneDX component, but `BomRef` and `purl` for these packages are incorrect.
See more in #5434 
We should skip wrong `purl` and use `UUID` for `BomRef` for these components.
- Close #5449
> fix(sbom): Use UUID as BomRef for packages with empty purl

- docs/docs/coverage/kubernetes.md
this should render correctly on website; website's .md renderer is stricter than GitHub's
> docs(k8s): fix whitespace in list syntax

- integration/testdata/helm.json.golden
- integration/testdata/helm_testchart.json.golden
- integration/testdata/helm_testchart.overridden.json.golden
- pkg/types/report.go
We need to save `Highlighted` field in `json` format to retain option to display colored text in `convert` mode.
See more in #5514.
- Close #5530
> refactor(misconf): don't remove Highlighted in json format

- go.mod
- go.sum
parse ecri mage with arn
- Close #5429
- Related https://github.com/aquasecurity/trivy-kubernetes/pull/243
> fix: trivy k8s parse ecr image with arn

- pkg/fanal/secret/builtin-rules.go
Currently the secret scanning does not detect JWT tokens, which are used for example by Artifactory as Authentication mechanism. 
For example, if a user builds an OCI image and installs dependencies from a private Artifactory repository during build-time and has passed those credentials in an insecure manner to the builder (for example using ARG statements), trivy needs to detect this leak.
The regex I added to the built-in rules is the same as used by gitleaks to detect JWT tokens:
https://github.com/gitleaks/gitleaks/blob/master/cmd/generate/config/rules/jwt.go
* [feat(secret): detect JWT tokens in secret scanning.](https://github.com/aquasecurity/trivy/discussions/5479)
> feat(secret): add built-in rule for JWT tokens

- go.mod
- go.sum
- integration/testdata/conda-spdx.json.golden
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
In SPDX 2.3 we can't use `FilesAnalyzed == false` for packages with `Files` - `If false, the package shall not contain any files.` - https://spdx.github.io/spdx-spec/v2.3/package-information/#781-description
So we need to use `FilesAnalyzed == true` and fill `PackageVerificationCode` field for these packages.
> fix(sbom): add `FilesAnalyzed` and `PackageVerificationCode` fields for SPDX

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/commands/app.go
We need to overwrite allowed `scanners` for `k8s` target:
- remove `license` scanner
- add `rbac` scanner
- Close #5538
> fix(cli): set correct `scanners` for `k8s` target

- pkg/flag/kubernetes_flags.go
- pkg/flag/kubernetes_flags_test.go
no schedule toleration should not include tolerationSeconds
- Close #5349
> fix: no schedule toleration

- magefiles/docs.go
If a plugin is installed locally, `mage docs:genarete` also generates references for the plugin subcommand. This PR sets a dummy XDG_DATA_HOME so that the plugin is not loaded.
> chore: not load plugins for auto-generating docs

- docs/docs/references/configuration/cli/trivy_aws.md
- pkg/commands/app.go
`trivy aws --help` shows a list of supported services, and it is also shown in the document.
https://aquasecurity.github.io/trivy/v0.47/docs/references/configuration/cli/trivy_aws/
The order is not consistent, and `mage docs:geneate` can generate some differences. This PR sorts supported services for the consistent document.
> chore: sort supported AWS services

- pkg/cloud/aws/commands/run_test.go
- pkg/cloud/report/report.go
- pkg/cloud/report/resource_test.go
- pkg/cloud/report/result_test.go
- pkg/cloud/report/service_test.go
- pkg/flag/options.go
- pkg/k8s/commands/run.go
- pkg/report/table/table.go
- pkg/report/writer.go
- pkg/x/io/io.go
See https://github.com/aquasecurity/trivy/issues/5560
- Close https://github.com/aquasecurity/trivy/issues/5560
> refactor: reintroduce output writer

- README.md
- docs/docs/configuration/others.md
- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_vm.md
- docs/docs/references/configuration/config-file.md
- docs/docs/scanner/misconfiguration/index.md
- docs/docs/target/container_image.md
- docs/docs/target/filesystem.md
- docs/docs/target/repository.md
- docs/docs/target/vm.md
- docs/index.md
- docs/tutorials/integrations/gitlab-ci.md
- docs/tutorials/misconfiguration/terraform.md
- integration/repo_test.go
- pkg/commands/app.go
- pkg/flag/misconf_flags.go
- pkg/flag/options.go
- pkg/flag/options_test.go
- pkg/flag/scan_flags.go
- pkg/flag/scan_flags_test.go
- pkg/flag/value.go
- pkg/types/target.go
This PR updates the allowed values of `--scanners` from `config` to `misconfig`. It also adds aliases for backward compatibility and spelling discrepancies.
- `misconfig` also allows
- `config`
- `misconf`
- `misconfiguration`
- `vuln` also allows
- `vulnerability`
```
$ trivy repo --scanners config .
```
NOTE: It remains working.
```
$ trivy repo --scanners misconfig .
```
- https://github.com/aquasecurity/trivy/issues/5557
- https://github.com/aquasecurity/trivy/pull/4990
> feat: add aliases to '--scanners'

- pkg/flag/scan_flags.go
It shows a warning message to encourage users to migrate to `--scanners misconfig`.
```
$ trivy repo --scanners config .
2023-11-15T11:35:57.027+0900    WARN    '--scanner config' is deprecated. Use '--scanner misconfig' instead. See https://github.com/aquasecurity/trivy/discussions/5586 for the detail.
2023-11-15T11:35:57.036+0900    INFO    Misconfiguration scanning is enabled
```
- https://github.com/aquasecurity/trivy/pull/5558
> chore: show a deprecation notice for `--scanners config`

- integration/testdata/alpine-310.sarif.golden
- pkg/report/sarif.go
- pkg/report/sarif_test.go
> fix(report): add escaping for Sarif format

- pkg/cloud/aws/scanner/scanner.go
- pkg/commands/artifact/run.go
- pkg/log/logger.go
- pkg/misconf/scanner.go
Exposes useful informational debug logs from the misconf engine when the existing `--debug` option is passed.
```shell
./trivy --debug config  /Users/repos/trivy-issues/5395    
2023-11-09T18:21:57.612-0700    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-11-09T18:21:57.624-0700    DEBUG   cache dir:  /Users/simarpreetsingh/Library/Caches/trivy
2023-11-09T18:21:57.625-0700    INFO    Misconfiguration scanning is enabled
2023-11-09T18:21:57.625-0700    DEBUG   Policies successfully loaded from disk
2023-11-09T18:21:57.649-0700    DEBUG   The nuget packages directory couldn't be found. License search disabled
2023-11-09T18:21:57.650-0700    DEBUG   Walk the file tree rooted at '/Users/simarpreetsingh/repos/trivy-issues/5395' in parallel
<snip> …
```
> feat(misconf): Expose misconf engine debug logs with `--debug` option

- pkg/k8s/commands/run.go
fix: k8s friendly error messages kbom non cluster scans
- Close #5264
Usage:  
```sh
trivy k8s all --format cyclonedx
2023-11-15T14:43:48.113+0200	INFO	"k8s with --format cyclonedx" disable security scanning
2023-11-15T14:43:48.120+0200	FATAL	Error: KBOM with CycloneDX format is not supported for all namespace scans
```
```sh
trivy k8s --format cyclonedx  -n kube-system pods/coredns-558bd4d5db-h22jb
2023-11-15T14:46:02.809+0200	INFO	"k8s with --format cyclonedx" disable security scanning
2023-11-15T14:46:02.816+0200	FATAL	Error: KBOM with CycloneDX format is not supported for resource scans
```
> fix: k8s friendly error messages kbom non cluster scans

- docs/ecosystem/cicd.md
Adds a Dagger integration section and cleans up a couple of minor things on the  Ecosystem CICD docs page.
There is a Dagger integration for Trivy that we want to share through the docs page, so I made an update. In the course of updating the page, I noticed that the Azure DevOps content was stuck in the middle of the GitHub Actions content, so I moved that out to stand alone. I also noticed that integrations were using H2 (##) markdown, but the Buildkite entry was using H3 (###), so I fixed that to make things consistent.
- I tried to open an issue, but got routed to created a discussion: https://github.com/aquasecurity/trivy/discussions/5607 (discussion)
- none other than this one 😄 
- n/a ~I've added tests that prove my fix is …
> docs: Add Dagger integration section and cleanup Ecosystem CICD docs page

- pkg/commands/artifact/inject.go
- pkg/commands/artifact/scanner.go
- pkg/commands/artifact/wire_gen.go
- pkg/fanal/image/image.go
Show more friendly errors from image sources.
```
$ trivy image foo
...
2023-11-16T15:21:08.107+0900    FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
* unable to inspect the image (foo): Error response from daemon: No such image: foo:latest
* containerd socket not found: /run/containerd/containerd.sock
* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
* GET https://index.docker.io/v2/library/foo/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/foo Type:repository]]
```
```
$ trivy image foo
...
2023-11-16T15:19:48.658+0900    FATAL   image scan error: scan error: unable to initialize a scanner: unable …
```
> chore: add prefix to image errors

- docs/getting-started/installation.md
The old package URL returns 404 now, and the old source URL is now archive-only.
> docs: Update Arch Linux package URL in installation.md

- docs/tutorials/misconfiguration/terraform.md
Updates broken links on [Scanning Terraform files with Trivy](https://aquasecurity.github.io/trivy/v0.47/tutorials/misconfiguration/terraform/) to point to the correct locations.
- Close #5660
> docs: terraform tutorial links updated to point to correct loc

- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_vm.md
- docs/docs/references/configuration/config-file.md
- docs/docs/scanner/misconfiguration/index.md
- pkg/commands/app.go
- pkg/commands/artifact/run.go
- pkg/flag/misconf_flags.go
Adds the `--misconfig-scanners` option to enable a subset of misconfiguration scanners.
- Close https://github.com/aquasecurity/trivy/issues/4901
> feat(misconf): Add `--misconfig-scanners` option

- docs/docs/advanced/modules.md
In the build section, the file name of the last build was `spring4shell.wasm`, so this has been corrected.
https://aquasecurity.github.io/trivy/dev/docs/advanced/modules/
> docs: typo in modules.md

- pkg/detector/library/driver.go
- pkg/detector/library/driver_test.go
- pkg/detector/library/testdata/fixtures/data-source.yaml
- pkg/detector/library/testdata/fixtures/pip.yaml
Sometime, the Fixed Version column may contains the same versions repeatedly:
```
Python (python-pkg)
===================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 1)
┌───────────────────────┬────────────────┬──────────┬────────┬───────────────────┬──────────────────────────────────────────────┬──────────────────────────────────────────────────────────────┐
│        Library        │ Vulnerability  │ Severity │ Status │ Installed Version │                Fixed Version                 │                            Title                             │
├───────────────────────┼────────────────┼──────────┼────────┼───────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ Django (METADATA)     │ …
```
> feat(vuln): remove duplicates in Fixed Version

- pkg/fanal/secret/builtin-rules.go
- pkg/fanal/secret/scanner_test.go
- pkg/fanal/secret/testdata/docker-secrets.txt
Issue: https://github.com/aquasecurity/trivy/issues/5669
added support of Docker registry credentials
- Close #5669
> feat(secret): added support of Docker registry credentials

- pkg/scanner/local/scan.go
- pkg/scanner/local/scan_test.go
When adding misconfigurations to the result, we need to check that the image configuration scanner has been enabled.
- Close https://github.com/aquasecurity/trivy/issues/5728
> fix(misconf): add an image misconf to result

- contrib/junit.tpl
See #5766 
Before:
```xml 
<?xml version="1.0" ?>
<testsuites name="trivy">
<testsuite tests="0" failures="0" name="Dockerfile" errors="0" skipped="0" time="">
<properties>
<property name="type" value="dockerfile"></property>
</properties>
</testsuite>
<testsuite tests="26" failures="26" name="Dockerfile" errors="0" skipped="0" time="">
<properties>
<property name="type" value="dockerfile"></property>
</properties>
<testcase classname="Dockerfile Security Check" name="[MEDIUM] DS001" time="">
<failure message="&#39;:latest&#39; tag used" type="description">When using a &#39;FROM&#39; statement you should use a specific tag to avoid uncontrolled behavior when the image is updated.</failure>
</testcase>
<testcase classname="Dockerfile Security Check" name="[HIGH] DS002" time="">
<failure …
```
> fix(report): don't mark misconfig passed tests as failed in junit.tpl

- contrib/junit.tpl
- integration/client_server_test.go
- integration/testdata/alpine-310.junit.golden
After #5767 Trivy returns error if misconfigs are empty:
```
- template: output template:17:44: executing "output template" at <.MisconfSummary.Successes>: nil pointer evaluating *types.MisconfSummary.Successes
```
`.MisconfSummary` is pointer. Therefore we need to add check to number of misconfigs.
> fix(report): fix error if miconfigs are empty

- integration/testdata/alpine-310.gsbom.golden
- pkg/report/github/github.go
- pkg/report/github/github_test.go
OS package purl should contains OS name and `distro` field
e.g. for `deb` - https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#deb
before: `pkg:apk/alpine-baselayout@3.1.2-r0`
after: ` pkg:apk/alpine/alpine-baselayout@3.1.2-r0?arch=x86_64\u0026distro=3.10.2`
> fix(report): use OS information for OS packages purl in `github` template

- pkg/purl/purl.go
- pkg/purl/purl_test.go
`package-url` added `pub` to purl types - https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#pub
> refactor(purl): use `pub` from `package-url`

- integration/testdata/fluentd-multiple-lockfiles.cdx.json.golden
- pkg/k8s/report/cyclonedx.go
- pkg/report/cyclonedx/cyclonedx.go
Disable HTML escaping for CycloneDX.
Purl has already escaped all the necessary characters:
https://github.com/package-url/packageurl-go/blob/fe183c1943ec36f257fae7143e160978217104b6/packageurl.go#L369-L394
- Close #5763
> refactor(sbom): disable html escaping for CycloneDX

- go.mod
- go.sum
aws-sdk-go v1.23.0 [contained](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md#L671) a breaking change, so the `ec2` package needs to be [updated](https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1814903382):
>Please upgrade ALL of your dependencies under the github.com/aws/aws-sdk-go-v2 namespace to the latest tags from yesterday's release, that should resolve the issue. Please chime in with the results if you can.
I tested the `aws` command and didn't notice any problems with other services.
- Close https://github.com/aquasecurity/trivy/issues/5821
> chore(deps): bump github.com/aws/aws-sdk-go-v2/service/ec2 from v1.116.0 to v1.134.0

- go.mod
- go.sum
Update go-ext4-filesystem
- https://github.com/masahiro331/go-ext4-filesystem/pull/11
- https://github.com/masahiro331/go-ext4-filesystem/pull/10
> fix(vm): update ext4-filesystem fix reading groupdescriptor in 32bit mode

- docs/ecosystem/miscellaneous.md
- docs/ecosystem/security.md
I have created this as per our discussion with @knqyf263 and @DmitriyLewen on https://github.com/aquasecurity/trivy/discussions/5388
> docs: add_scan2html_to_trivy_ecosystem

- integration/testdata/alpine-310.sarif.golden
- pkg/report/sarif.go
- pkg/report/sarif_test.go
We [added](https://github.com/aquasecurity/trivy/pull/5568) escaping for sarif report.
But after #5804, recheck docs and [discuss](https://github.com/orgs/community/discussions/80935#discussioncomment-8062555) this with GitHub team, we understand that we don't need to escape newlines for text and markdown properties.
> revert(report): don't escape new line characters for sarif format

- docs/docs/configuration/filtering.md
A little addition to the doc which can be helpful to users.
.
> docs(misconf): multiple ignores in comment

- integration/testdata/pom-cyclonedx.json.golden
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/cyclonedx/testdata/happy/bom.json
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/sbom/cyclonedx/unmarshal_test.go
We separate `GroupID` and `ArtifactID` to `group` and `name` fields for jar files - #4674
But we need to use same logic for all Java files.
Also we need to store nodejs `scopes` to `group` fields (see #5908).
- Close #5908
> fix(sbom): use `group` field for pom.xml and nodejs files for CycloneDX reports

- pkg/fanal/analyzer/language/nodejs/npm/npm.go
- pkg/fanal/analyzer/language/nodejs/npm/npm_test.go
- pkg/fanal/analyzer/language/nodejs/npm/testdata/happy/node_modules/@babel/parser/package.json
- pkg/fanal/analyzer/language/nodejs/npm/testdata/happy/package-lock.json
We don't need to skip `package.json` files (when searching for licenses for `package-lock.json` files) if package name contains slash (e.g. `node_modules/@babel/parser/package.json`)
- Close #5835
> fix(nodejs): find licenses for packages with slash

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/flag/kubernetes_flags.go
- pkg/k8s/commands/run.go
This aims to allow users to adjust K8S Client QPS and Burst value.
> feat: allow end-users to adjust K8S client QPS and burst

- pkg/fanal/analyzer/pkg/rpm/rpm.go
- pkg/fanal/analyzer/pkg/rpm/rpm_test.go
> fix(amazon): save system files for pkgs containing `amzn` in src

- docs/docs/supply-chain/sbom.md
- go.mod
- go.sum
- integration/testdata/conda-cyclonedx.json.golden
- integration/testdata/fluentd-multiple-lockfiles.cdx.json.golden
- integration/testdata/pom-cyclonedx.json.golden
- pkg/fanal/analyzer/sbom/testdata/cdx.json
- pkg/fanal/artifact/sbom/testdata/bom.json
- pkg/fanal/artifact/sbom/testdata/os-only-bom.json
- pkg/rekortest/server.go
- pkg/sbom/cyclonedx/core/cyclonedx.go
- pkg/sbom/cyclonedx/core/cyclonedx_test.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/cyclonedx/testdata/happy/bom.json
- pkg/sbom/cyclonedx/testdata/happy/empty-metadata-component-bom.json
- pkg/sbom/cyclonedx/testdata/happy/group-in-name.json
- pkg/sbom/cyclonedx/testdata/happy/independent-library-bom.json
- pkg/sbom/cyclonedx/testdata/happy/infinite-loop-bom.json
- pkg/sbom/cyclonedx/testdata/happy/kbom.json
- pkg/sbom/cyclonedx/testdata/happy/os-only-bom.json
- pkg/sbom/cyclonedx/testdata/happy/unrelated-bom.json
- pkg/sbom/cyclonedx/testdata/sad/invalid-purl.json
1) Bump `github.com/CycloneDX/cyclonedx-go` to add support for [metadata.tools.components](https://cyclonedx.org/docs/1.5/json/#metadata_tools_oneOf_i0_components) (https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.8.0)
2) Use [metadata.tools.components](https://cyclonedx.org/docs/1.5/json/#metadata_tools_oneOf_i0_components) to save information about Trivy app.
3) Add support for both `metadata.tools` formats to save backward compatibility.
Go to github.com/CycloneDX/cycledx-go to add support for metadata.tools.comComponents.
Use Metadata.tools.comComponents to save information about the Trivy application.
Add support for both Metadata.tools formats to maintain backward compatibility.
Before:
```json
{
"$schema": "http://cyclonedx.org/schema/bom-1.5.schema.json",
"bomFormat": …
```
> refactor(sbom): use new `metadata.tools` struct for CycloneDX

- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_vm.md
- docs/docs/supply-chain/vex.md
- pkg/flag/sbom_flags.go
- pkg/flag/vulnerability_flags.go
`--vex` is currently available only in SBOM scanning (`trivy sbom`). https://github.com/aquasecurity/trivy/pull/5439 has changed to always generate PURLs, except when generating SBOMs. It is easy to extend VEX support to other targets like container images.
```
$ trivy image debian:11 --vex debian11.vex.csaf
```
- Close https://github.com/aquasecurity/trivy/issues/4767
- https://github.com/aquasecurity/trivy/pull/5439
> feat(vuln): enable `--vex` for all targets

- pkg/fanal/analyzer/pkg/apk/apk_test.go
> fix: check returned error before deferring f.Close()

- contrib/asff.tpl
- integration/testdata/secrets.asff.golden
Use `AWS_REGION` env (https://aquasecurity.github.io/trivy/v0.48/tutorials/integrations/aws-security-hub/) for secrets in `asff` template.
- Close #6010
> fix(report): use `AWS_REGION` env for secrets in `asff` template

- integration/docker_engine_test.go
We need to close `ImageLoad` response to avoid a resource leak - https://github.com/moby/moby/blob/71fa3ab079ec13d17257f86fa92db8d7f24802f1/api/types/client.go#L198
We get flaky errors when try to remove image after finish each `TestDockerEngine` testcase:
https://github.com/aquasecurity/trivy/actions/runs/7743024958/job/21113470515?pr=6047#step:5:652
Looks like we don't need to check this error.
> test: fix flaky `TestDockerEngine`

- go.mod
- go.sum
- pkg/fanal/cache/redis.go
See https://github.com/aquasecurity/trivy/pull/6045#discussion_r1475865219
> fix: fix cursor usage in Redis Clear function

- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
Size of GitHub action ubuntu image has been reduce:
before:
```
Filesystem Size Used Avail Use% Mounted on 
/dev/root 84G 53G 31G 64% /
```
now:
```
Filesystem Size Used Avail Use% Mounted on 
/dev/root 73G 53G 21G 73% /
```
So we can't get [35840MB](https://github.com/aquasecurity/trivy/blob/fc20dfdd804389f82f397707fe641dcf26e2dc98/.github/workflows/test.yaml#L94C28-L94C33) - https://github.com/aquasecurity/trivy/actions/runs/7779351592/job/21210359409
So we need to reduce `root-reserve-mb` value.
Also i [played](https://github.com/DmitriyLewen/trivy/pull/24) with root-reserve-mb. Size equal 32GB doesn't return error.
> ci: reduce `root-reserve-mb` size for `maximize-build-space`

- pkg/fanal/types/artifact.go
- pkg/vex/testdata/cyclonedx.json
- pkg/vex/vex_test.go
When [parsing BomLink]((https://github.com/CycloneDX/cyclonedx-go/blob/master/link.go#L136)), we get an unescaped BomRef.
But we use purl for `BomRef`. So in some cases we may see escaped characters (e.g. `pkg:deb/ubuntu/libstdc%2B%2B6@12.3.0-1ubuntu1~22.04`).
To avoid cases when we don't match refs - we need to compare escaped and unespected BomRef with ref from BomLink.
- Close #6023
> fix: check unescaped `BomRef` when matching `PkgIdentifier`

- docs/index.md
Trivial documentation issue.
Fixes a broken link: "pronunciation" in the docs.
> docs: Fix broken link to "pronunciation"

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
Possible cases when `History` doesn't contain information about user.
`Config.User` can contain user information:
```bash
➜  ~ docker image inspect alpine | jq '.[].Config.User'
""
➜  ~ docker history alpine          
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
5053b247d78b   7 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      7 months ago   /bin/sh -c #(nop) ADD file:289c2fac17119508c…   7.66MB    
➜  ~ docker run --user 1003 alpine
➜  ~ docker ps -a          
CONTAINER ID   IMAGE     COMMAND     CREATED          STATUS                      PORTS     NAMES
bcbf97a115a5   alpine    "/bin/sh"   28 seconds ago   Exited (0) 27 seconds ago             focused_fermat
➜  ~ docker commit bcbf97a115a5 …
```
> fix(misconf): get `user` from `Config.User`

- docs/docs/coverage/language/java.md
- go.mod
- go.sum
- integration/testdata/gradle.json.golden
- pkg/fanal/analyzer/language/java/gradle/lockfile_test.go
Add dependency location support for `gradle` files.
- Close #5948
> feat(java): add dependency location support for `gradle` files

- pkg/fanal/analyzer/pkg/apk/apk.go
- pkg/fanal/analyzer/pkg/apk/apk_test.go
- pkg/fanal/analyzer/pkg/apk/testdata/apk
After parsing line of apk package, we can get empty licenses.
e.g.:
```json
"Licenses": [
"",
"Apache-2.0",
"MIT",
"",
"MPL-2.0"
],
```
- Close #6128
> fix(alpine): exclude empty licenses for apk packages

- docs/ecosystem/cicd.md
- docs/ecosystem/reporting.md
SecObserve is an open source vulnerability management system that can import and show results of Trivy and has it's own set of GitHub actions and GitLab templates. This shall be shown on the ecosystem pages for CI/CD and reporting.
> docs: add SecObserve in CI/CD and reporting

- pkg/fanal/types/sbom.go
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/cyclonedx/unmarshal.go
In cases when input and output files use `CycloneDX` format - Trivy misses [rootComponent](https://cyclonedx.org/docs/1.5/json/#metadata_component) information in output file.
See more in #6095
- Close #6111
> fix(cyclonedx): move root component from scanned cyclonedx file to output cyclonedx file

- docs/docs/configuration/filtering.md
We currently doesn't support using `path` field in `.trivyignore.yaml` file to filter package licenses.
More information - #6117.
> docs(report): add remark about `path` to filter licenses using `.trivyignore.yaml` file

- pkg/commands/artifact/run.go
Fixed to skip executable analysis if Rekor is not the specified SBOM source.
**before**
Even if only `oci` is specified in the SBOM source, trivy performs a lot of searches for rekor.
```
> trivy version
Version: 0.49.1
Vulnerability DB:
Version: 2
UpdatedAt: 2024-02-20 00:16:01.804708429 +0000 UTC
NextUpdate: 2024-02-20 06:16:01.804708139 +0000 UTC
DownloadedAt: 2024-02-20 01:34:32.831729 +0000 UTC
Java DB:
Version: 1
UpdatedAt: 2024-02-18 00:44:32.669835578 +0000 UTC
NextUpdate: 2024-02-21 00:44:32.669835368 +0000 UTC
DownloadedAt: 2024-02-19 16:39:27.048401 +0000 UTC
> trivy -d image --timeout 30m --scanners vuln --severity CRITICAL,HIGH --sbom-sources oci apicurio/apicurio-registry-sql:2.2.5.Final
2024-02-20T12:08:19.513+0900	DEBUG	Severities: ["CRITICAL" "HIGH"] …
```
> fix(sbom): skip executable file analysis if Rekor isn't a specified SBOM source

- pkg/dependency/parser/java/jar/parse.go
Add only valid libs from `pom.properties` files from `jars`.
- #6148
> fix(java): add only valid libs from `pom.properties` files from `jars`

- pkg/iac/scanners/terraform/parser/load_module.go
- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/resolvers/local.go
- pkg/iac/scanners/terraform/scanner.go
Trivy creates a virtual filesystem for post-analysers, so path handling should not depend on the OS.
> fix(terraform): ensure consistent path handling across OS

- pkg/dependency/parser/swift/swift/parse.go
- pkg/dependency/parser/swift/swift/parse_test.go
- pkg/dependency/parser/swift/swift/testdata/happy-v2-Package.resolved
- pkg/dependency/parser/swift/swift/types.go
> fix(swift): try to use branch to resolve version

- go.mod
- go.sum
- pkg/k8s/scanner/scanner.go
- pkg/k8s/scanner/scanner_test.go
- pkg/purl/purl.go
k8s scan rancher rke2 version support
- Close #5987
- Related https://github.com/aquasecurity/trivy-kubernetes/pull/292
> feat(k8s): rancher rke2 version support

- pkg/report/github/github.go
- pkg/report/github/github_test.go
Relates to https://github.com/aquasecurity/trivy/discussions/5998
Fixes https://github.com/aquasecurity/trivy/issues/6008
The goal is to change the `source_location` of the `manifest` in SBOM report so it provides useful information when displayed in Github Dependency.
The current solution is to use `<image_registry>/<image_name>:<tag>@sha256:<image_hash>` format.
As you can see instead of specifying the image scanned, it only show `Python`.
The report now shows the image name and tag as the `source_location` for all packages.
```
"manifests": {
"Python": {
"name": "python-pkg",
"file": {
"source_location": "redacted_registry/accesspod:latest"
},
```
> refactor(report): Replacing `source_location` in `github` report when scanning an image

- docs/docs/configuration/filtering.md
- pkg/result/filter.go
- pkg/result/filter_test.go
- pkg/result/ignore.go
- pkg/result/testdata/.trivyignore.yaml
Add PURL support for `.trivyignore.yaml`.
```
vulnerabilities:
- id: CVE-2022-40897
paths:
- "usr/local/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/METADATA"
statement: Accept the risk
- id: CVE-2023-3817
purls:
- "pkg:deb/debian/libssl1.1"
```
- Close https://github.com/aquasecurity/trivy/issues/6119
> feat(vuln): ignore vulnerabilities by PURL

- pkg/dependency/parser/java/pom/pom.go
Return text of error when can't parse `<dependency> element` for `pom.xml files.
> fix: Printf format err

- pkg/k8s/report/table.go
add context to Target (`namespace/kind/name`) finding on k8s table view
- Close #6098
example:
```
k8s.io/apiserver (kubernetes)
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 0, CRITICAL: 0)
┌──────────────────┬───────────────┬──────────┬────────┬───────────────────┬──────────────────────────────────┬───────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability │ Severity │ Status │ Installed Version │          Fixed Version           │                           Title                           │
├──────────────────┼───────────────┼──────────┼────────┼───────────────────┼──────────────────────────────────┼───────────────────────────────────────────────────────────┤
│ k8s.io/apiserver │ CVE-2022-3162 │ MEDIUM   │ fixed  │ 1.21.1            │ 1.22.16, …
```
> fix: add context to target finding on k8s table view

- pkg/k8s/report/report.go
- pkg/k8s/report/report_test.go
- pkg/k8s/report/summary.go
- pkg/k8s/report/summary_test.go
- pkg/k8s/report/table.go
- pkg/k8s/writer_test.go
k8s summary separate infra and user finding results
- Close #6121
Usage:
- Install [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) cluster
- run : `trivy k8s cluster --report summary`
```
Summary Report for kind-kind
┌────────────────────┬────────────────────────────────────────────────┬───────────────────────┬───────────────────┬───────────────────┐
│     Namespace      │                    Resource                    │    Vulnerabilities    │ Misconfigurations │      Secrets      │
│                    │                                                ├────┬────┬────┬────┬───┼───┬───┬───┬───┬───┼───┬───┬───┬───┬───┤
│                    │                                                │ C  │ H  │ M  │ L  │ U │ C │ H │ M │ L │ U │ C │ H │ M │ L │ U │ …
```
> fix: k8s summary separate infra and user finding results

- docs/ecosystem/reporting.md
Add the following project to our ecosystem page https://github.com/dbsystel/trivy-vulnerability-explorer
* I also reordered this section in alphabetical order
> docs: update ecosystem page reporting with db app

- .github/workflows/test.yaml
We received `no space left on device` errors for [golangci-lint from GH Test action](https://github.com/aquasecurity/trivy/blob/1dfece89d0c7c8dec73b6e3be8e7fabf1fca4a39/.github/workflows/test.yaml#L34-L41)
Add `maximize-build-space` for `Test` job to get more free space.
> ci: add maximize-build-space for `Test` job

- integration/k8s_test.go
We use trivy-db from default cache dir for [k8s integration tests](https://github.com/aquasecurity/trivy/blob/main/integration/k8s_test.go#L23).
To avoid downloading trivy-db each run of CI/CD - we need to use test db.
> test(k8s): use test-db for k8s integration tests

- pkg/fanal/analyzer/language/analyze.go
- pkg/scanner/local/scan.go
By default, we suppress `Dev` dependencies (npm, yarn is currently support only). 
We need to show info about it.
> feat: add info log message about dev deps suppression

- pkg/dependency/parser/java/pom/parse.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/testdata/happy/pom.xml
We don't need to ignore runtime scope for `pom.xml` files.
See more in #6207
- Close #6207
> fix(java): don't ignore runtime scope for pom.xml files

- pkg/iac/adapters/cloudformation/aws/s3/bucket.go
- pkg/iac/adapters/cloudformation/aws/s3/s3_test.go
- Close https://github.com/aquasecurity/trivy/issues/6024
> fix(cloudformation): support of all SSE algorithms for s3

- pkg/iac/scanners/terraform/module_test.go
- pkg/iac/scanners/terraform/options.go
- pkg/iac/scanners/terraform/parser/evaluator.go
- pkg/iac/scanners/terraform/scanner_integration_test.go
- pkg/iac/scanners/terraformplan/snapshot/scanner_test.go
Skipping cached modules will avoid fluky tests. See https://github.com/aquasecurity/trivy/pull/6176#discussion_r1510860391
> test(terraform): skip cached modules

- docs/docs/coverage/language/java.md
- pkg/fanal/analyzer/language/java/pom/pom.go
- pkg/fanal/analyzer/language/java/pom/pom_test.go
- pkg/fanal/analyzer/language/java/pom/testdata/mark-as-dev/src/it/example/pom.xml
Mark dependencies from `maven-invoker-plugin` integration tests pom.xml files as `Dev`.
This is necessary to add an option to skip/show these dependencies using `--include-dev-deps` flag.
See more in #5787
> feat(java): mark dependencies from `maven-invoker-plugin` integration tests pom.xml files as `Dev`

- go.mod
- go.sum
- pkg/module/memfs.go
- pkg/module/memfs_test.go
This updated wazero to the latest stable version.
Since wazero 1.3.0 the virtual file system supports socket file descriptors, this also ensures that the memory file system is recognized as a directory.
> chore(deps): bump wazero from 1.2.1 to 1.6.0

- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/config-file.md
- docs/docs/target/container_image.md
- pkg/commands/artifact/run.go
- pkg/fanal/image/daemon.go
- pkg/fanal/image/daemon/image_test.go
- pkg/fanal/image/daemon/podman.go
- pkg/fanal/image/daemon/podman_test.go
- pkg/fanal/types/image.go
- pkg/flag/image_flags.go
This pull request adds a new feature option `--podman-host` to the image command. This option allows users to specify a custom Podman host.
command output before introducing this feature
```sh
$ trivy image --image-src podman nginx:latest
2024-03-02T16:49:02.943Z	INFO	Need to update DB
2024-03-02T16:49:02.944Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2024-03-02T16:49:02.944Z	INFO	Downloading DB...
43.58 MiB / 43.58 MiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 7.43 MiB p/s 6.1s
2024-03-02T16:49:10.272Z	INFO	Vulnerability scanning is enabled
2024-03-02T16:49:10.272Z	INFO	Secret scanning is enabled
2024-03-02T16:49:10.272Z	INFO	If your scanning is …
```
> feat(image): customer podman host or socket option

- pkg/dependency/parser/nodejs/packagejson/parse.go
- pkg/dependency/parser/nodejs/packagejson/parse_test.go
- pkg/dependency/parser/nodejs/packagejson/testdata/invalid_name.json
Npm uses some rules for package names - https://docs.npmjs.com/cli/v10/configuring-npm/package-json
We need to reproduce `npm` logic and return error for invalid package names.
- https://github.com/aquasecurity/trivy/discussions/6259#discussioncomment-8666078.
> fix(nodejs): add name validation for package name from `package.json` 

- docs/docs/configuration/db.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_sbom.md
- docs/docs/references/configuration/cli/trivy_server.md
- docs/docs/references/configuration/cli/trivy_vm.md
- pkg/db/db.go
- pkg/flag/db_flags.go
- pkg/javadb/client.go
We add schema version as tag only for all registries (both default and external).
To avoid limiting users, we only need to do this for the default registries (`ghcr.io/aquasecurity/trivy-db` and `ghcr.io/aquasecurity/trivy-java-db`).
- Close #6218
> fix(db): use schema version as tag only for `trivy-db` and `trivy-java-db` registries by default

- pkg/detector/ospkg/amazon/amazon.go
- pkg/detector/ospkg/amazon/amazon_test.go
`system-release` can contain minor and patch version(e.g. `2023.3.20240304`).
But we need to check only major version to get list of advisories for found OS.
- Close #6294
- https://github.com/aquasecurity/trivy-db/issues/390
> fix(amazon): check only major version of AL to find advisories

- pkg/iac/scanners/terraform/parser/load_module.go
Removed custom `moduleLoadError` error which is not used anywhere else
> refactor(terraform): remove unused custom error

- pkg/iac/adapters/terraform/aws/iam/convert.go
- pkg/iac/adapters/terraform/aws/iam/policies_test.go
- pkg/iac/adapters/terraform/aws/iam/roles_test.go
If a policy, such as `aws_iam_policy` or `aws_iam_policy_document`, uses a for-each loop to reference policy document resources, those resources are not detected. In the case where a policy references document resources in a condition, only the first resource was selected. It is necessary to search for policy document resources by identifiers (id) rather than by references to fix this.
- Close https://github.com/aquasecurity/trivy/issues/5686
> fix(terraform): fix policy document retrieval

- docs/docs/scanner/misconfiguration/index.md
The documentation lacked information on all the options for filtering by inline comments
> docs(terraform): improve documentation for filtering by inline comments

- integration/testdata/conda-spdx.json.golden
- integration/testdata/fluentd-multiple-lockfiles.cdx.json.golden
- pkg/fanal/analyzer/sbom/sbom_test.go
- pkg/fanal/applier/docker.go
- pkg/fanal/types/const.go
- pkg/k8s/scanner/scanner.go
- pkg/k8s/scanner/scanner_test.go
- pkg/report/spdx/spdx.go
- pkg/sbom/core/bom.go
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/sbom/io/decode.go
- pkg/sbom/io/encode.go
- pkg/sbom/io/encode_test.go
- pkg/sbom/sbom.go
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
- pkg/sbom/spdx/testdata/sad/invalid-purl.json
- pkg/sbom/spdx/unmarshal.go
- pkg/sbom/spdx/unmarshal_test.go
This PR is leftover from #6240. It changes to use intermediate representation (core.BOM) introduced in #6240 for SPDX as well as CycloneDX.
> refactor(sbom): use intermediate representation for SPDX

- go.mod
- go.sum
This will update [wazero](https://wazero.io/) to v1.7.0. The v1.7.0. release marks a milestone in the wazero project, replacing our old compiler architecture with a [new optimizing compiler backend.][docs]. It also introduces experimental support to the thread spec.
We will officially announce the final v1.7.0 release in just a few days, during [Wasm I/O](https://wasmio.tech/), after which we will undraft this PR and update it to the latest tag.
~Let me know if you'd rather merge this PR before the official release. This draft PR is intended to let your CI checks run and verify everything is in order before our final release.~
[docs]: https://wazero.io/docs/how_the_optimizing_compiler_works/
- [na] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with …
> chore: updates wazero to v1.7.0

- pkg/fanal/analyzer/pkg/dpkg/scanner.go
There are cases when package data (from dpkg status file) may exceed default buffer size.
Increase the buffer [default size](https://github.com/golang/go/blob/78755f6b8c5f18b0014e9dcac383898047ff14fe/src/bufio/scan.go#L82) by 2 times.
- Close #6297
> fix: increase the default buffer size for scanning dpkg status files by 2 times

- contrib/gitlab.tpl
Empty strings in `.vulnerabilities[].identifiers[].url` is not valid value:
- https://gitlab.com/gitlab-org/gitlab/-/issues/443531#note_1803834238
- https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/e3d280d7f0862ca66a1555ea8b24016a004bb914/dist/container-scanning-report-format.json#L157-179 
- Close #6347
> fix(report): don't include empty strings in `.vulnerabilities[].identifiers[].url` when `gitlab.tpl` is used

- pkg/sbom/spdx/unmarshal.go
We get panic if `CreationInfo` doesn't exist (see #6344).
add check for `CreationInfo` to nil when detecting SPDX created using Trivy.
- Close #6344
> fix(sbom): add check for `CreationInfo` to nil when detecting SPDX created using Trivy

- pkg/dependency/parser/java/pom/parse.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/testdata/modules-infinity-loop/module-1/module-2/pom.xml
- pkg/dependency/parser/java/pom/testdata/modules-infinity-loop/module-1/pom.xml
- pkg/dependency/parser/java/pom/testdata/modules-infinity-loop/pom.xml
Possible cases when, when parsing modules, we get an infinite loop.
See examples in https://github.com/aquasecurity/go-dep-parser/issues/297.
To avoid this - we need to parse modules once.
- Close aquasecurity/go-dep-parser/issues/297
> fix(java): parse modules from `pom.xml` files once

- pkg/fanal/analyzer/fs.go
Use `0600` perms for tmp files for post analyzers to avoid errors when file use wrong perms.
e.g.:
- #6373
- https://github.com/goharbor/harbor/issues/18824
- https://github.com/goharbor/harbor/issues/19405
- Close #6373
> fix: use `0600` perms for tmp files for post analyzers

- docs/docs/scanner/license.md
Trivy supports license detection for some lock files.
e.g.:
```
➜  trivy -q fs --scanners license ./integration/testdata/fixtures/repo/yarn
yarn.lock (license)
Total: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
┌─────────┬─────────┬────────────────┬──────────┐
│ Package │ License │ Classification │ Severity │
├─────────┼─────────┼────────────────┼──────────┤
│ jquery  │ MIT     │ Notice         │ LOW      │
└─────────┴─────────┴────────────────┴──────────┘
```
> docs: add info about support for package license detection in `fs`/`repo` modes

- pkg/dependency/parser/golang/mod/testdata/replaced-with-local-path-and-version-mismatch/go.sum
- pkg/dependency/parser/nodejs/npm/parse.go
- pkg/dependency/parser/nodejs/npm/parse_test.go
- pkg/dependency/parser/nodejs/npm/parse_testcase.go
- pkg/dependency/parser/nodejs/npm/testdata/package-lock_v3_with-same-dev-and-non-dev.json
There are times when `package-lock.json` contains 2 (or more) identical dependencies, but
- only one of these dependencies is `Dev`.
- only one of these dependencies is `Indirect`.
We need to combine these dependencies correctly.
Also we need to merge ExternalReferences rather than overwrite them.
- Close #5139
> fix(nodejs): merge `Indirect`, `Dev`, `ExternalReferences` fields for same deps from `package-lock.json` files v2 or later

- pkg/sbom/core/bom.go
- pkg/sbom/spdx/testdata/happy/with-file-as-relationship-parent.json
- pkg/sbom/spdx/unmarshal.go
- pkg/sbom/spdx/unmarshal_test.go
When parent from Relationship is not package (e.g. File) - Trivy returns error. (see #6391)
e.g.:
```json
{
"relationshipType": "DESCRIBED_BY",
"relatedSpdxElement": "SPDXRef-DOCUMENT",
"spdxElementId": "SPDXRef-File--Modules-Microsoft.PowerShell.PSResourceGet--manifest-spdx-2.2-manifest.spdx.json-2B9FB98F5CA97DC84FD382A8F8E68F663C003362"
}
```
We only need to add to [BOM Relationships](https://github.com/aquasecurity/trivy/blob/f148eb10f25b4daaf97b38ef523e6f16e9b118a1/pkg/sbom/core/bom.go#L63) relationships between packages 
- Close #6391
> fix(sbom): fix error when parent of SPDX Relationships is not a package.

- pkg/iac/scanners/cloudformation/cftypes/types.go
- pkg/iac/scanners/cloudformation/parser/fn_find_in_map_test.go
- pkg/iac/scanners/cloudformation/parser/intrinsics.go
- pkg/iac/scanners/cloudformation/parser/property.go
- pkg/iac/scanners/cloudformation/parser/resource.go
- pkg/iac/scanners/cloudformation/parser/util.go
We need to infer the type after resolving the function because the property with the function is of type `string`.
- Close https://github.com/aquasecurity/trivy/issues/6404
> fix(cloudformation): infer type after resolving a function

- pkg/report/sarif.go
- pkg/report/sarif_test.go
Ref:
- https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127618
- https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#specifying-the-root-for-source-files
- Close https://github.com/aquasecurity/trivy/issues/5003
> fix(misconf): clear location URI for SARIF

- pkg/cloud/aws/commands/run.go
- pkg/cloud/aws/scanner/progress.go
- pkg/cloud/aws/scanner/scanner.go
Output:
```bash
go run ./cmd/trivy aws --endpoint http://localhost:4566 --region us-east-1 --service s3 --update-cache -d -q -o test
```
- Close https://github.com/aquasecurity/trivy/issues/5551
> feat(aws): quiet flag support

- pkg/iac/scanners/helm/parser/parser.go
- pkg/iac/scanners/helm/test/parser_test.go
Instead of copying files to a temporary folder, we can pass virutal files to helm, which improves performance.
```bash
benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/aquasecurity/trivy/pkg/iac/scanners/helm/test
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
_RenderChartFiles-8   2138.1µ ± 2%   978.3µ ± 3%  -54.24% (p=0.000 n=10)
│   old.txt    │               new.txt               │
│     B/op     │     B/op      vs base               │
_RenderChartFiles-8   570.4Ki ± 0%   532.8Ki ± 0%  -6.59% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│  allocs/op  │  allocs/op   vs base               │
_RenderChartFiles-8   7.714k ± 0%   7.476k ± 0%  -3.09% (p=0.000 n=10)
```
> perf(helm): load in-memory files

- pkg/cloud/aws/scanner/scanner.go
- pkg/commands/artifact/run.go
- pkg/commands/operation/operation.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
This proposed change allows the policy bundle repository specified with `--policy-bundle-repository` to be pulled from a private registry using [specified username and password](https://aquasecurity.github.io/trivy/v0.49/docs/advanced/private-registries/).
- Close #6266
> feat(misconf): Support private registries for misconf check bundle

- pkg/commands/operation/operation.go
- pkg/db/db.go
- pkg/fanal/analyzer/analyzer_test.go
- pkg/fanal/analyzer/language/java/jar/jar_test.go
- pkg/flag/db_flags.go
- pkg/flag/db_flags_test.go
- pkg/javadb/client.go
- pkg/rpc/server/listen.go
We add tag (schema version) to trivy-db and trivy-java-db repositories (#6219).
But url can contain `:` not in image name.
In this case we will not add tag.
See example in #6409.
So we need to check schema version for image name only.
- Close #6409
> fix(db): check schema version for image name only

- pkg/iac/adapters/cloudformation/aws/eks/cluster.go
- pkg/iac/adapters/cloudformation/aws/eks/eks_test.go
- Close https://github.com/aquasecurity/trivy/issues/6421
- Close https://github.com/aquasecurity/trivy/issues/6422
> feat(cloudformation): add support for logging and endpoint access for EKS

- docs/docs/scanner/misconfiguration/index.md
- pkg/iac/ignore/rule.go
- pkg/iac/ignore/rule_test.go
- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/ignore_test.go
Added wildcard support for `id` and `workspace` sections.
- Close https://github.com/aquasecurity/trivy/issues/5120
> feat(misconf): add support for wildcard ignores

- pkg/dependency/parser/golang/mod/testdata/replaced-with-local-path-and-version-mismatch/go.sum
- pkg/iac/scanners/terraformplan/tfjson/scanner_test.go
- pkg/iac/scanners/terraformplan/tfjson/test/parser_test.go
- pkg/iac/scanners/terraformplan/tfjson/test/testdata/plan_with_template.json
- pkg/iac/terraform/resource_block.go
Escape templates correctly.
- Close https://github.com/aquasecurity/trivy/issues/6291
> fix(misconf): Escape template value correctly

- docs/docs/advanced/air-gap.md
- docs/docs/scanner/misconfiguration/custom/index.md
- docs/docs/scanner/misconfiguration/custom/schema.md
> docs: fix links to OPA docs

- pkg/log/handler.go
Some log messages (debug, warning, etc.) may contain error message.
We use red for these errors. But decoding updates color symbols and disrupts the coloration.
Before:
After:
> fix: add color for error inside of log message

- pkg/iac/rego/build.go
- pkg/iac/rego/embed_test.go
- pkg/iac/rego/load_test.go
- pkg/iac/scanners/dockerfile/scanner_test.go
- pkg/iac/scanners/terraform/scanner_integration_test.go
A non-valid REGO schema passed by the user can cause panic.
> fix(misconf): avoid panic if the scheme is not valid

- pkg/cloud/report/convert.go
- pkg/commands/artifact/run.go
- pkg/iac/rego/embed.go
- pkg/iac/rego/load.go
- pkg/iac/rego/load_test.go
- pkg/iac/rego/metadata.go
- pkg/iac/rego/scanner.go
- pkg/iac/rego/testdata/embedded/bad-check.rego
- pkg/iac/rego/testdata/embedded/my-check1.rego
- pkg/iac/rego/testdata/embedded/my-policy1.rego
- pkg/scanner/local/scan.go
This PR adds functionality to fallback to embedded checks if an error occurs compiling an built-in check from a bundle. 
`main.tf`
```tf
resource "aws_s3_bucket" "test" {
bucket = "test"
}
resource "aws_s3_bucket" "log_bucket" {
bucket = "log_bucket"
}
resource "aws_s3_bucket_logging" "test" {
bucket = aws_s3_bucket.test.id
target_bucket = aws_s3_bucket.log_bucket.id
target_prefix   = "log/"
}
```
1. `rm -rf ~/Library/Caches/trivy/policy`
2. `go run ./cmd/trivy conf main.tf -d --policy-bundle-repository ghcr.io/nikpivkin/trivy-policies:test`
```bash
2024-04-16T17:50:24+07:00       DEBUG   [misconf] 50:24.188902000 terraform.scanner.rego           Error occurred while parsing: Users/nikita/Library/Caches/trivy/policy/content/policies/cloud/policies/aws/s3/enable_logging.rego, …
```
> feat(misconf): loading embedded checks as a fallback

- pkg/iac/rego/metadata.go
Annotations can be retrieved directly from the Rego module.
> refactor(misconf): simplify the retrieval of module annotations

- .github/workflows/reusable-release.yaml
`GoReleaser` uses `TMPDIR` during operation.
But we moved all free space to Trivy directory and got error - https://github.com/aquasecurity/trivy/actions/runs/8781316705/job/24095365717#step:14:47
So we also need to move the `GoReleaser` temp directory to Trivy directory.
Test run - https://github.com/DmitriyLewen/trivy/actions/runs/8782979882/job/24098204231#step:14:78
> ci: use tmp dir inside Trivy repo dir for GoReleaser

- pkg/iac/rego/scanner.go
- pkg/iac/rego/scanner_test.go
This PR ensures that Rego checks continue to run even if an error is encountered in one of them, avoiding halting the entire process.
> refactor(misconf): improve error handling in the Rego scanner

- pkg/iac/scanners/terraform/parser/funcs/filesystem.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/attribute.go
* `fileset` function now uses `fs.Stat` instead of `os.Stat` and works more often
* `Attribute.DecodeVarType` now handles the `list` and `map` shortcuts for `list(any)` and `map(any)`
* `Attribute.GetRawValue` now returns data from `set` values
- Close #XXX
> fix(terraform): Attribute and fileset fixes

- pkg/detector/library/detect.go
- pkg/scanner/langpkg/scan.go
- pkg/scanner/local/scan.go
It currently shows warnings on empty versions.
```
$ trivy sbom /tmp/sbom-k8s-cluster.json
2024-04-23T13:53:05+04:00       INFO    Vulnerability scanning is enabled
2024-04-23T13:53:05+04:00       INFO    Detected SBOM format    format="cyclonedx-json"
...
2024-04-23T13:53:05+04:00       INFO    [kubernetes] Detecting vulnerabilities...
2024-04-23T13:53:05+04:00       WARN    Version matching error  err="version error (): malformed version: "
2024-04-23T13:53:05+04:00       WARN    Version matching error  err="version error (): malformed version: "
2024-04-23T13:53:05+04:00       WARN    Version matching error  err="version error (): malformed version: "
2024-04-23T13:53:05+04:00       WARN    Version matching error  err="version error (): malformed version: "
```
This PR changed it to …
> fix(vuln): skip empty versions

- docs/getting-started/installation.md
When adding repo configuration to /etc/yum.repos.d/trivy.repo, RELEASE_VERSION should not be added to repo baseurl.
This is also documented in: https://aquasecurity.github.io/trivy-repo/.
> docs: remove RELEASE_VERSION from trivy.repo

- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/config-file.md
- pkg/flag/cloud_flags.go
- pkg/flag/kubernetes_flags.go
- pkg/flag/scan_flags.go
[config file page](https://aquasecurity.github.io/trivy/v0.50/docs/references/configuration/config-file/) missed some flags and contains mistakes.
Update this page.
- #6529
> docs: update info about config file

- pkg/fanal/analyzer/pkg/dpkg/dpkg.go
- pkg/fanal/analyzer/pkg/dpkg/dpkg_test.go
Discussed in https://github.com/aquasecurity/trivy/discussions/6543
- Close #6548
> fix(debian): sort dpkg info before parsing due to exclude directories

- docs/docs/configuration/filtering.md
- Close https://github.com/aquasecurity/trivy/issues/6494
> docs: mention `--show-suppressed` is available in table

- .github/workflows/reusable-release.yaml
Size of Go cache, Trivy binary, GoReleaser temp files, etc. are getting larger.
We recently started getting an error in `Post Go Setup` step - https://github.com/aquasecurity/trivy/actions/runs/8816024192.
To avoid errors and get stable release run - we disable `Go` cache for `reusable-release.yaml`
Test run - https://github.com/DmitriyLewen/trivy/actions/runs/8845727149
> ci: disable `Go` cache for `reusable-release.yaml`

- pkg/dependency/parser/golang/mod/parse.go
- pkg/dependency/parser/golang/mod/parse_testcase.go
- pkg/fanal/analyzer/language/golang/mod/mod_test.go
Extract the main module from go.mod. As far as I know, it should not be possible to get the version, but it is programmatically possible to get it (`Module.Mod` has the version field), so I try to get it just in case.
> feat(go): add main module

- docs/getting-started/installation.md
- Add basic documentation to install trivy tool using asdf and mise tool
> docs: add asdf and mise installation method

- cmd/trivy/main.go
- pkg/cloud/aws/commands/run.go
- pkg/commands/app.go
- pkg/commands/artifact/run.go
- pkg/commands/convert/run.go
- pkg/commands/operation/operation.go
- pkg/k8s/commands/run.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- pkg/types/error.go
Trivy doesn't respect exit codes from plugins now and always exits with 1 if the plugin fails. This PR adds support for it.
The `testplugin` always exits with 2.
```
$ trivy testplugin; echo $?
Error: plugin error: plugin exec: exit status 2
Usage:
trivy testplugin [flags]
Flags:
-h, --help   help for testplugin
Global Flags:
--cache-dir string          cache directory (default "/Users/teppei/Library/Caches/trivy")
-c, --config string             config path (default "trivy.yaml")
-d, --debug                     debug mode
--generate-default-config   write the default config to trivy-default.yaml
--insecure                  allow insecure server connections
-q, --quiet                     suppress progress bar and log output
--timeout duration          timeout (default 5m0s)
-v, --version …
```
> feat: respect custom exit code from plugin

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/flag/kubernetes_flags.go
- pkg/flag/options.go
- pkg/k8s/commands/cluster.go
- pkg/k8s/commands/run.go
- pkg/k8s/report/report.go
- pkg/k8s/report/report_test.go
- pkg/k8s/report/summary.go
- pkg/k8s/report/summary_test.go
- pkg/k8s/writer.go
- pkg/k8s/writer_test.go
Add support for k8s intrusive flag
- Close #6194
> BREAKING: add support for k8s `disable-node-collector` flag

- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/flag/kubernetes_flags.go
- pkg/k8s/scanner/scanner.go
support skip-deep scanning flag
- Close #6193
> feat: support `--skip-images` scanning flag

- docs/getting-started/installation.md
Use `generic` link from `trivy-repo`.
See more in https://github.com/aquasecurity/trivy-repo/pull/37.
> docs: use `generic` link from `trivy-repo`

- docs/tutorials/integrations/gitlab-ci.md
This PR removes the mention of GitLab Gold in the `gitlab-ci` docs because GitLab renamed their SaaS offerings to match the names of the on-prem offerings.
There is no issue because this only fixes a trivial documentation issue.
~~- [ ] I've added tests that prove my fix is effective or that my feature works.~~
> docs: remove mention of GitLab Gold because it doesn't exist anymore

- docs/docs/target/kubernetes.md
docs: trivy-k8s new experiance remove un-used section
- Related #6199
> docs: trivy-k8s new experiance remove un-used section

- pkg/iac/scan/code.go
- pkg/misconf/scanner.go
We only need to get the offending cause if the result is a failure.
Today we end up getting a cause for every single result type, which results in unnecessary compute being done. 
As a side note, I also verified that the JSON output (when including the `--include-non-failures` flag) also does not contain any info on cause (for code excerpts) for results that are a `PASS`. 
- Close https://github.com/aquasecurity/trivy/issues/6557
> perf(misconf): Improve cause performance

- pkg/commands/app_test.go
- pkg/commands/artifact/run.go
- pkg/flag/options.go
when using compliance reports, we init some options before configuring the scanners (e.g. init trivy-db).
To avoid panic, we need to set up scanners when parsing flags.
- Close #6613
> refactor: move setting scanners when using compliance reports to flag parsing

- pkg/iac/scanners/terraform/parser/parser_integration_test.go
- pkg/iac/scanners/terraform/parser/resolvers/registry.go
Terraform does [not use](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraints) semantic module versioning, so we must use the `github.com/aquasecurity/go-version/pkg/version` package to parsing module versions.
- Close https://github.com/aquasecurity/trivy/issues/6537
> fix(misconf): do not use semver for parsing tf module versions

- pkg/fanal/analyzer/config/terraform/terraform_test.go
- pkg/iac/detection/detect.go
- pkg/iac/scanners/terraform/parser/load_module_metadata.go
- pkg/iac/scanners/terraform/parser/modules.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/scanners/terraform/parser/testdata/cached-modules/.terraform/modules/modules.json
- pkg/iac/scanners/terraform/parser/testdata/cached-modules/.terraform/modules/s3-bucket/main.tf
- pkg/iac/scanners/terraform/parser/testdata/cached-modules/main.tf
```sh
cat main.tf
module "s3_bucket" {
source = "terraform-aws-modules/s3-bucket/aws"
bucket = "my-s3-bucket"
acl    = "private"
control_object_ownership = true
object_ownership         = "ObjectWriter"
versioning = {
enabled = true
}
}%
```
```bash
go run ./cmd/trivy conf ~/projects/trivy-test/issue-6603
2024-05-03T10:50:00+06:00       INFO    Detected config files   num=2
2024-05-03T10:50:00+06:00       DEBUG   Scanned config file     path="."
2024-05-03T10:50:00+06:00       DEBUG   Scanned config file     path="terraform-aws-modules/s3-bucket/aws/.terraform/modules/s3_bucket/main.tf"
terraform-aws-modules/s3-bucket/aws/.terraform/modules/s3_bucket/main.tf (terraform)
Tests: 10 (SUCCESSES: 7, FAILURES: 3, EXCEPTIONS: 0)
Failures: 3 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 2, CRITICAL: 0) …
```
> fix(misconf): load cached tf modules

- pkg/fanal/walker/fs.go
There are two problems. First, `d.Info()` could return an error on system files, like `/proc`. It is currently called before skipping dirs. File walking exits before processing skipping dirs. Second, user-specified skipping dirs are pre-processed, but the default skipping dirs are also processed by mistake. This PR fixes these two problems.
- Close https://github.com/aquasecurity/trivy/issues/6627
> fix(fs): handle default skip dirs properly

- .github/workflows/scan.yaml
We use old Trivy in [Scan vulnerabilities](https://github.com/aquasecurity/trivy/actions/workflows/scan.yaml) and get errors - https://github.com/aquasecurity/trivy/actions/runs/8962160517/job/24610643339
Bump `knqyf263/trivy-issue-action` to v0.0.6
Test run - https://github.com/DmitriyLewen/trivy/actions/runs/8964744455/job/24617010006
> chore(deps): bump `knqyf263/trivy-issue-action` to v0.0.6

- pkg/cloud/aws/commands/run.go
- pkg/commands/artifact/run.go
- pkg/k8s/commands/run.go
Should these warnings only mention the CLI flag? How about instead linking to a docs page 1 level higher, so that users who encounter these warnings can then pick the relevant way to set their higher timeout?
- https://github.com/aquasecurity/trivy/issues/2054
- https://github.com/aquasecurity/trivy/issues/3421
- The exact strings don't seem to be tested for, so is this needed?
- … double-checking locally …
- [~] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [~] I've added usage information (if the PR introduces new options)
- [~] I've included a "before" and "after" example to the description (if the PR is a user interface change).
> docs: link warning to both timeout config options

- ci/deploy-deb.sh
Add `generic` dir to deb deploy script.
Test:
- https://github.com/DmitriyLewen/trivy/actions/runs/8965411083/job/24620153662
- https://github.com/DmitriyLewen/trivy-repo/tree/main/deb/dists/generic
> ci: add `generic` dir to deb deploy script

- pkg/iac/rego/load.go
We have to skip errors without locations.
https://github.com/aquasecurity/trivy/pull/6502#discussion_r1591042149
> fix(misconf): skip Rego errors with a nil location

- go.mod
- go.sum
Use of specified context to obtain cluster name
- Close #6643
- Related https://github.com/aquasecurity/trivy-kubernetes/pull/339
> fix: use of specified context to obtain cluster name

- docs/docs/references/configuration/cli/trivy_aws.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- go.mod
- go.sum
- pkg/commands/artifact/run.go
- pkg/flag/rego_flags.go
- pkg/iac/rego/scanner.go
- pkg/iac/rego/scanner_test.go
- pkg/iac/scanners/azure/arm/scanner.go
- pkg/iac/scanners/cloudformation/scanner.go
- pkg/iac/scanners/dockerfile/scanner.go
- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/json/scanner.go
- pkg/iac/scanners/kubernetes/scanner.go
- pkg/iac/scanners/options/scanner.go
- pkg/iac/scanners/terraform/scanner.go
- pkg/iac/scanners/terraformplan/tfjson/scanner.go
- pkg/iac/scanners/toml/scanner.go
- pkg/iac/scanners/yaml/scanner.go
- pkg/misconf/scanner.go
Adds support for `--include-deprecated-checks`. This is a stacked PR on https://github.com/aquasecurity/trivy/pull/6664
- Closes https://github.com/aquasecurity/trivy/issues/6665
> feat(misconf): Add support for `--include-deprecated-checks`

- pkg/result/filter.go
- pkg/result/filter_test.go
- pkg/result/testdata/test-ignore-policy-licenses-and-secrets.rego
In #6004 rego policy was extended to allow filtering Licenses and Filters, but I somehow overlooked that there’s ModifiedFindings available now, so with this PR I’m trying to fix this and include them, just like it currently includes misconfigurations and vulnerabilities. I’ve updated tests accordingly, and also made them reuse predefined license and secret examples.
> feat(report): Include licenses and secrets filtered by rego to ModifiedFindings

- go.mod
- pkg/cache/remote_test.go
- pkg/rpc/client/client_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
use `google.golang.org/protobuf/types/known` instead of `github.com/golang/protobuf/ptypes`
this also removes `github.com/golang/protobuf` from the list of direct dependencies to use the recommanded `google.golang.org/protobuf`
> chore(deps): use `google.golang.org/protobuf/types/known` instead of `github.com/golang/protobuf/ptypes`

- pkg/dependency/parser/golang/binary/parse.go
- pkg/dependency/parser/golang/binary/parse_test.go
Add only non-empty root modules for `gobinaries`.
See #6709
- Close #6709
> fix(go): add only non-empty root modules for `gobinaries`

- pkg/dependency/parser/golang/binary/parse.go
- pkg/dependency/parser/golang/binary/parse_test.go
There are cases when ldflags contain `version` with prefix (e.g. `github.com/argoproj/argo-cd/v2/common.kubectlVersion=v0.26.11`).
We don't need to take these versions.
- Close #6702
> fix(go): include only `.version`|`.ver` (no prefixes) ldflags for `gobinaries`

- .github/workflows/test.yaml
- .golangci.yaml
- pkg/fanal/analyzer/buildinfo/dockerfile_test.go
- pkg/fanal/analyzer/language/nodejs/license/license_test.go
- pkg/flag/kubernetes_flags_test.go
- pkg/iac/adapters/arm/storage/adapt_test.go
- pkg/iac/adapters/terraform/aws/s3/adapt_test.go
- pkg/iac/adapters/terraform/aws/s3/bucket_test.go
- pkg/iac/rego/scanner_test.go
- pkg/iac/rules/register_test.go
- pkg/iac/scanners/dockerfile/parser/parser_test.go
- pkg/iac/scanners/helm/test/scanner_test.go
- pkg/iac/scanners/kubernetes/scanner_test.go
- pkg/iac/scanners/terraform/block_test.go
- pkg/iac/scanners/terraform/count_test.go
- pkg/iac/scanners/terraform/parser/load_vars_test.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/k8s/report/summary_test.go
- pkg/licensing/expression/parser_test.go
- pkg/misconf/scanner_test.go
- pkg/module/module_test.go
- pkg/scanner/post/post_scan_test.go
- pkg/utils/fsutils/fs_test.go
Update golangci-lint-action to v6.0.1 which doesn’t cache go package dependencies anymore 
Move the timeout configuration in the config file so it is mutualise for any use case.
enable [testifylint](https://github.com/Antonboom/testifylint) linter on integration/*
It helps applying the best practices with testify use
It applies `bool-compare`, `expected-actual` and `len` rules. 
The `integration/*` has been removed from `exclude-files`.
> ci(deps): update golangci-lint-action and enable testifylint linter on "integration/*"

- magefiles/magefile.go
Install golangci-lint if the installed version doesn't match.
- https://github.com/aquasecurity/trivy/pull/6639
> chore: enforce golangci-lint version

- pkg/iac/ignore/parse.go
- pkg/iac/ignore/rule.go
- pkg/iac/ignore/rule_test.go
This PR prevents a range shift for a rule that is on the same line as the code.
- Close https://github.com/aquasecurity/trivy/issues/6686
> fix(misconf): don't shift ignore rule related to code

- .github/workflows/auto-update-labels.yaml
- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
The following change will help to solve an issue of auto-bump golang patch versions.
up to now that auto-bump golang patch versions was using the:
```
- uses: actions/setup-go@v5
with:
go-version-file: 'go.mod'
```
This setting assumes that the go.mod file of Trivy is configured with a partial Go version `<major>.<minor>` for instance, `go 1.22`.
It has been observed that if a go.mod file includes a dependency like `github.com/aquasecurity/trivy-kubernetes`, and that dependency's go.mod file specifies a full Go version `<major>.<minor>.<patch>` such as `go 1.22.0`, then the Go version of this dependency will replace the Go version specified in trivy go.mod file.
therefore the above `actions/setup-go` cannot be used with `go-version-file: 'go.mod'` param.
The workaround will be to use the …
> chore: auto-bump golang patch versions

- magefiles/magefile.go
https://github.com/aquasecurity/trivy/pull/6706 added the timeout value to `.golangci.yaml`, but the `--timeout` flag is specified in magefile. To respect the value in `.golangci.yaml`, this PR deletes the flag in magefile.
- https://github.com/aquasecurity/trivy/pull/6706
> chore: respect timeout value in .golangci.yaml

- docs/docs/coverage/language/python.md
- integration/testdata/pip.json.golden
- pkg/dependency/parser/python/pip/parse.go
- pkg/dependency/parser/python/pip/parse_testcase.go
- pkg/fanal/analyzer/language/python/pip/pip_test.go
- pkg/fanal/artifact/local/fs_test.go
Add line number support for `requirement.txt` files
- Close #6701
> feat(python): add line number support for `requirement.txt` files

- integration/testdata/conda-spdx.json.golden
- integration/testdata/julia-spdx.json.golden
- pkg/fanal/applier/applier_test.go
- pkg/result/filter.go
- pkg/result/filter_test.go
- pkg/sbom/core/bom.go
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/io/encode.go
- pkg/vex/csaf.go
- pkg/vex/openvex.go
- pkg/vex/testdata/openvex-nested.json
- pkg/vex/vex.go
- pkg/vex/vex_test.go
Currently, Trivy uses VEX statements with `fixed` and `not_affected` statuses to filter out vulnerabilities.
In [this PR](https://github.com/aquasecurity/trivy/pull/6313), we added limited support for OpenVEX subcomponents. With this change, VEX can be applied to scans when the product is the root component and the subcomponent is the leaf component, i.e., the component with the vulnerability. For container image scans, if the product ID is the scan subject, the PURL of the image, the VEX is applicable as the image is a root component.
However, it does not work with VEX for non-root components within that container image. In the following example, a VEX document for Application B doesn't work since it is a non-root component.
This PR extends that functionality to allow VEX with non-root …
> feat(vex): support non-root components for products in OpenVEX

- .github/dependabot.yml
`Dependabot` PRs [grouping](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-updates-into-one-pull-request):
- GH actions
- Docker files
- `github.com/docker/*` from `go.mod`.
- `github.com/aws/*` from `go.mod`.
- `github.com/testcontainers-go/*` from `go.mod`.
- others
Example:
> ci: add groups for `dependabot`

- .golangci.yaml
- pkg/dependency/parser/java/pom/artifact_test.go
- pkg/fanal/image/daemon/podman_test.go
- pkg/iac/rego/scanner_test.go
- pkg/report/template_test.go
Fixes tenv linter issues in ".*_test.go$"
> ci(deps): fix tenv in ".*_test.go$"

- pkg/iac/scanners/terraform/parser/module_retrieval.go
- pkg/iac/scanners/terraform/parser/resolvers/registry.go
- pkg/iac/scanners/terraform/parser/resolvers/registry_integration_test.go
Ref:
- https://opentofu.org/docs/internals/module-registry-protocol/#download-source-code-for-a-specific-module-version
- Close https://github.com/aquasecurity/trivy/issues/6744
> feat(misconf): resolve tf module from OpenTofu compatible registry

- goreleaser.yml
Our release binaries don't include the main module information now, and our gobinary analyzer doesn't work on them.
```
$ docker run --rm -it --entrypoint "sh" ghcr.io/aquasecurity/trivy:0.51.2 -c "apk add go && go version -m /usr/local/bin/trivy" | grep "/usr/local/bin/trivy" -A 5
/usr/local/bin/trivy: go1.22.3
path    command-line-arguments
dep     cloud.google.com/go     v0.112.1        h1:uJSeirPke5UNZHIb4SxfZklVSiWWVqW4oXlETwZziwM=
dep     cloud.google.com/go/compute/metadata    v0.2.3  h1:mg4jlk7mCAj6xXp9UJ4fjI9VUI5rubuGBW5aJ7UnBMY=
dep     cloud.google.com/go/iam v1.1.6  h1:bEa06k05IO4f4uJonbB5iAgKTPpABy1ayxaIZV/GHVc=
dep     cloud.google.com/go/storage     v1.39.1 h1:MvraqHKhogCOTXTlct/9C3K3+Uy2jBmFYb3/Sp6dVtY=
```
A binary built by Mage includes it.
```
$ mage build && go version …
```
> build: use main package instead of main.go

- docs/docs/configuration/reporting.md
- mkdocs.yml
> docs(plugin): add missed `plugin` section

- docs/docs/coverage/os/index.md
- pkg/detector/ospkg/alpine/alpine.go
Add eol date for Alpine 3.20.
`trivy-db` already contains vulns for `3.20`.
```bash
➜ trivy image alpine 
...
2024-05-28T13:19:53+06:00       INFO    Detected OS     family="alpine" version="3.20.0"
2024-05-28T13:19:53+06:00       INFO    [alpine] Detecting vulnerabilities...   os_version="3.20" repository="3.20" pkg_num=14
```
> chore(alpine): add eol date for Alpine 3.20

- pkg/dependency/parser/python/pip/parse.go
- pkg/dependency/parser/python/pip/parse_test.go
- pkg/dependency/parser/python/pip/testdata/requirements_with_templating_engine.txt
Add package name and version validation for `requirements.txt` files.
- Close #6750
> fix(python): add package name and version validation for `requirements.txt` files.

- .golangci.yaml
Sort linter-settings alphabetically.
Enable misspell in test.go
Remove unused exclusions
> fix: clean up golangci lint configuration

- go.mod
- go.sum
- pkg/fanal/image/image_test.go
- pkg/rpc/retry.go
use modules instead of incompatible version
> ci(deps): use modules instead of incompatible version

- pkg/sbom/io/encode.go
- pkg/sbom/io/encode_test.go
> fix(sbom): fix panic for `convert` mode when scanning json file derived from sbom file

- pkg/fanal/image/image.go
The current error message, "unable to initialize a scanner", when Trivy doesn't find the passed image, confuses users.
```
2024-05-30T10:25:06+04:00       FATAL   Fatal error     image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: 4 errors occurred:
```
This PR improves the error message.
```
$ trivy image --scanners vuln fooooo
2024-05-30T10:30:16+04:00       INFO    Vulnerability scanning is enabled
2024-05-30T10:30:19+04:00       FATAL   Fatal error     image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: 4 errors occurred:
* docker error: unable to inspect the image (fooooo): Error response from daemon: No such image: fooooo:latest
* containerd error: containerd socket not found: …
```
> chore: improve error message for image not found

- docs/docs/references/troubleshooting.md
Add several workarounds besides `$TMPDIR` with a large capacity,
> docs: add more workarounds for out-of-disk

- docs/docs/coverage/language/julia.md
Add a missing table of supported scanners.
- https://github.com/aquasecurity/trivy/pull/5635
> docs(julia): add scanner table

- pkg/log/logger.go
`--quiet` currently suppresses even fatal errors.
```
$ trivy image unknown --quiet 
```
```
$ trivy image unknown --quiet
2024-05-30T16:16:14+04:00        FATAL   Fatal error     image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "unknown" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
* docker error: unable to inspect the image (unknown): Error response from daemon: No such image: unknown:latest
* containerd error: containerd socket not found: /run/containerd/containerd.sock
* podman error: unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
* remote error: GET https://index.docker.io/v2/library/unknown/manifests/latest: …
```
> fix(cli): always output fatal errors to stderr

- cmd/trivy/main.go
- pkg/commands/app.go
- pkg/plugin/manager.go
Need to initialize a logger before running a plugin. Also, renamed `RunWithURL` with `Run` as it also takes a plugin name as an argument now.
> fix(plugin): initialize logger

- pkg/iac/rego/convert/struct.go
- pkg/iac/rego/convert/struct_test.go
- pkg/iac/rego/schemas/builder.go
- pkg/iac/rego/schemas/cloud.json
The schema was missing a metadata type.
- https://github.com/aquasecurity/trivy-checks/pull/131
> feat(misconf): add metadata to Cloud schema

- pkg/iac/scanners/terraform/parser/module_retrieval.go
- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_integration_test.go
- pkg/iac/scanners/terraform/parser/resolvers/cache.go
- pkg/iac/scanners/terraform/parser/resolvers/cache_integration_test.go
- pkg/iac/scanners/terraform/parser/resolvers/options.go
- pkg/iac/scanners/terraform/parser/resolvers/registry.go
- pkg/iac/scanners/terraform/parser/resolvers/remote.go
- pkg/iac/scanners/terraform/parser/resolvers/source.go
- pkg/iac/scanners/terraform/parser/resolvers/source_test.go
Modules are saved and retrieved from the cache by a key, which is built from the module source and version. But when caching a module from a package subdirectory, the relative path of that module is added to the key, which is not taken into account when loading the module from the cache. This leads to two problems:
- The cache is bloated because a separate directory is created for each module in the package that contains the entire package. For example, two directories would be created for `terraform-aws-modules/s3-bucket/aws//modules/object` and `terraform-aws-modules/s3-bucket/aws//modules/object`, each containing a `terraform-aws-modules/s3-bucket/aws` module.
- Trivy does not load modules from the cache that are in subdirectories, such as …
> fix(misconf): fix caching of modules in subdirectories

- pkg/iac/scanners/cloudformation/parser/intrinsics.go
- pkg/iac/scanners/cloudformation/parser/parameter.go
- pkg/iac/scanners/cloudformation/parser/parser_test.go
- pkg/iac/scanners/cloudformation/parser/util.go
`jfather` parses Number without fractional part as int64, but in our types we use int, which causes type casting error.
```json
{
"AWSTemplateFormatVersion": "2010-09-09",
"Parameters": {
"ContainerMemory": {
"Type": "Number",
"Default": 512
}
},
"Resources": {
"TaskDefinition": {
"Type": "AWS::ECS::TaskDefinition",
"Properties": {
"ContainerDefinitions": [
{
"Memory": {
"Ref": "ContainerMemory"
}
}
]
}
}
}
}
```
```sh
trivy conf -d /Users/nikita/projects/aws-cloudformation-templates/ECS/FargateLaunchType/services/private-subnet-private-service.json
2024-05-31T22:01:39+07:00       DEBUG   Parsed severities       severities=[UNKNOWN LOW MEDIUM HIGH CRITICAL]
2024-05-31T22:01:39+07:00       DEBUG   Cache dir       dir="/Users/nikita/Library/Caches/trivy"
2024-05-31T22:01:39+07:00       INFO …
```
> fix(misconf): parsing numbers without fraction as int

- pkg/dependency/parser/nodejs/pnpm/parse.go
- pkg/dependency/parser/nodejs/pnpm/parse_test.go
- pkg/dependency/parser/nodejs/pnpm/parse_testcase.go
- pkg/dependency/parser/nodejs/pnpm/testdata/pnpm-lock_v9_cyclic_import.yaml
`pnpm` allows cyclic imports with peer dependencies.
e.g.:
```yaml
snapshots:
browserslist@4.23.0:
dependencies:
caniuse-lite: 1.0.30001627
electron-to-chromium: 1.4.789
node-releases: 2.0.14
update-browserslist-db: 1.0.16(browserslist@4.23.0)
update-browserslist-db@1.0.16(browserslist@4.23.0):
dependencies:
browserslist: 4.23.0
escalade: 3.1.2
picocolors: 1.0.1
```
See more in #6848
In these cases you should not end up with an infinite loop.
- Close #6848
> fix(nodejs): fix infinity loops for `pnpm` with cyclic imports

- pkg/dependency/parser/python/poetry/parse.go
- pkg/fanal/analyzer/language/python/poetry/poetry.go
- pkg/fanal/analyzer/language/python/poetry/testdata/happy/pyproject.toml
There are cases where package names from `poetry.lock` and `pyproject.toml` use different case.
e.g. `pyproject.toml` uses `Flask`, but `poetry.lock` uses `flask`
So we need to compare lowercase package names.
- Close #6817
> fix(python): compare pkg names from `poetry.lock` and `pyproject.toml` in lowercase

- .github/workflows/release-please.yaml
Automatically create a release branch `release/vX.Y` when `vX.Y.0` is released. This branch is for patch versions, such as `vX.Y.1` and `vX.Y.2`.
- https://github.com/aquasecurity/trivy/pull/6781
> ci: create release branch

- docs/docs/supply-chain/vex.md
Better describe how VEX is applied in the dependency tree
- https://github.com/aquasecurity/trivy/pull/6728
- https://github.com/aquasecurity/trivy/pull/6735
> docs: explain how VEX is applied

- .github/workflows/backport.yaml
Due to organization visibility, the `author_association` field is always NONE for maintainers  - https://github.com/orgs/community/discussions/18690
Therefore, we need to check the permissions of the comment author to run `backport`.
Test runs:
https://github.com/aquasecurity/trivy-backport-test/pull/5#issuecomment-2153893422 + https://github.com/aquasecurity/trivy-backport-test/actions/runs/9411582941
https://github.com/aquasecurity/trivy-backport-test/pull/5#issuecomment-2153896517 + https://github.com/aquasecurity/trivy-backport-test/actions/runs/9411592649
> ci: use author permission check instead of `author_association` field for backport workflow

- pkg/sbom/io/decode.go
Trivy stores source information in `properties`.
So, we only need to overwrite the source information if `srcName` and `srcVersion` are not found (it means that we decoding  third-party SBOMs).
- Close #6865
> fix(sbom): don't overwrite `srcEpoch` when decoding SBOM files

- .github/workflows/release-please.yaml
add created release branch (please release worflow) to `rulesets` to enable merge queue
Test run - https://github.com/DmitriyLewen/trivy/actions/runs/9415815309/job/25937712229#step:2:1
> ci: add created release branch to `rulesets` to enable merge queue

- pkg/iac/adapters/cloudformation/aws/apigateway/apigateway.go
- pkg/iac/adapters/cloudformation/aws/apigateway/apigateway_test.go
- pkg/iac/adapters/cloudformation/aws/apigateway/apiv1.go
- pkg/iac/adapters/cloudformation/aws/apigateway/apiv2.go
- Close https://github.com/aquasecurity/trivy/issues/6863
> feat(misconf): API Gateway V1 support for CloudFormation

- pkg/dependency/parser/nodejs/npm/parse.go
- pkg/dependency/parser/nodejs/npm/parse_test.go
- pkg/dependency/parser/nodejs/npm/testdata/package-lock_v3_broken_link.json
This PR fixes 2 cases:
1. When `Packages[x].resolved` is empty for link - we don't need to resolve this link.
2. Don't overwrite `packages` map when resolving links to avoid cases when we updated package is parsed.
- Close #6854
> fix(nodejs): fix infinite loop when package link from `package-lock.json` file is broken

- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
- goreleaser-canary.yml
- goreleaser.yml
- Bump `goreleaser/goreleaser-action` to `v6`
- Bump `github.com/goreleaser/goreleaser` to `v2.0.0`
- Add `version` field to config files
config file validations:
```bash
➜  goreleaser check goreleaser.yml       
• checking                                 path=goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
➜  goreleaser check goreleaser-canary.yml
• checking                                 path=goreleaser-canary.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
- Close #6885
> ci: bump `github.com/goreleaser/goreleaser` to `v2.0.0`

- pkg/iac/adapters/cloudformation/aws/ec2/adapt_test.go
- pkg/iac/adapters/cloudformation/aws/ec2/security_group.go
Added support for `AWS::EC2::SecurityGroupIngress` and `AWS::EC2::SecurityGroupEgress` resources.
- Close https://github.com/aquasecurity/trivy/issues/6754
```sh
2024-05-23T17:28:41+06:00	INFO	Misconfiguration scanning is enabled
2024-05-23T17:29:09+06:00	INFO	Detected config files	num=1
templ.yaml (cloudformation)
Tests: 8 (SUCCESSES: 6, FAILURES: 2, EXCEPTIONS: 0)
Failures: 2 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 1)
CRITICAL: Security group rule allows ingress from public internet.
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Opening up ports to the public internet is generally to be avoided. You should restrict access to IP addresses or ranges that explicitly require it where possible.
See …
```
> feat(misconf): add support for AWS::EC2::SecurityGroupIngress/Egress

- .github/workflows/bypass-test.yaml
- .github/workflows/test.yaml
Release please PRs contain information only about created changes and don't affect source code.
To avoid running `tests` after every commit to `main` branch - we need to disable `tests` workflow for these PRs.
> ci: don't run `tests` for `release-please` PRs

- pkg/iac/providers/provider.go
- pkg/iac/rego/scanner.go
This will allow specifying selectors for all providers.
Fixes https://github.com/aquasecurity/trivy/issues/6911
For example:
```rego
package user.test001
import rego.v1
deny contains res if {
some instance in input.google.compute.instances
instance.name.value == "my-instance"
res := result.new("deny", instance.name)
}
```
> feat(misconf): support of selectors for all providers for Rego

- pkg/iac/ignore/parse.go
- pkg/iac/ignore/rule_test.go
- pkg/iac/scanners/cloudformation/parser/parser.go
- pkg/iac/scanners/terraform/ignore_test.go
- pkg/iac/scanners/terraform/parser/parser.go
- Close https://github.com/aquasecurity/trivy/issues/6941
> fix(misconf): handle source prefix to ignore

- pkg/fanal/image/daemon/image.go
`Created` field can be empty - https://github.com/moby/moby/blob/8e96db1c328d0467b015768e42a62c0f834970bb/api/types/types.go#L76-L77
We don't need to parse this empty field to avoid errors.
Error example - https://github.com/aquasecurity/trivy/discussions/6944
- Close #6947
> fix(image): parse `image.inspect.Created` field only for non-empty values

- docs/docs/coverage/language/c.md
- pkg/fanal/analyzer/language/c/conan/conan.go
- pkg/fanal/analyzer/language/c/conan/conan_test.go
- pkg/fanal/analyzer/language/c/conan/testdata/cacheDir_v2/p/opens464b5c427ce9d/e/conanfile.py
- pkg/fanal/analyzer/language/c/conan/testdata/cacheDir_v2/p/zlib41bd3946e7341/e/conanfile.py
- pkg/fanal/analyzer/language/c/conan/testdata/happy_v2/release.lock
This PR fixes detected issues for `conan.lock` files:
- scan `.conan2` fir (and `CONAN_HOME` env) to detect licenses
- don't skip files from [file-patterns](https://aquasecurity.github.io/trivy/v0.52/docs/configuration/skipping/#file-patterns)
- Close #6946
- Close #6931
> fix(c): don't skip conan files from `file-patterns` and scan `.conan2` cache dir

- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
trim non-URL info for [advisory.url](https://cyclonedx.org/docs/1.6/json/#vulnerabilities_items_advisories_items_url)
more info #6801
- Close #6801
> fix(cyclonedx): trim non-URL info for `advisory.url`

- integration/testdata/mariner-1.0.json.golden
- pkg/purl/purl.go
Use correct `purl` types for some OS pkgs (e.g. `pkg:cbl-mariner/bash@5.1.8-4.cm2` -> `pkg:rpm/cbl-mariner/bash@5.1.8-4.cm2`).
> fix(purl): add missed os types

- pkg/detector/ospkg/suse/suse.go
There are three changes here:
* openSUSE Leap 15.6 got released and will be maintained at least until end of Dec 2025.
* SLES 15.6 is going to be announced shortly and hence the overlapping lifecycle for 15.5 shortens its lifecycle to the end of calendar year 2024.
* SLES 15 got a lifecycle extension. General support got 3 more years post-initial release added, hence end of life moves from 2028 to 2031.
> fix(suse): Add SLES 15.6 and Leap 15.6

- go.mod
Go 1.22.0-1.22.3 has a bug. This PR bumps the toolchain version so developers will not face the problem.
https://github.com/golang/go/issues/66993
NOTE: the fix was backported to 1.22.4.
https://github.com/golang/go/issues/67527
> chore: bump Go toolchain version

- pkg/fanal/analyzer/sbom/sbom_test.go
- pkg/sbom/io/decode.go
> fix(sbom): use `purl` for `bitnami` pkg names

- .github/workflows/semantic-pr.yaml
- docs/community/contribute/pr.md
For clarity, we added the type `BREAKING` to the existing type of [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), but [Release Please](https://github.com/googleapis/release-please) recognizes only breaking changes indicated by the `! `.
>feat!:, or fix!:, refactor!:, etc., which represent a breaking change (indicated by the !) and will result in a SemVer major.
https://github.com/googleapis/release-please/blob/ace2bd5dc778f83c33ad5dee6807db5d0afdba36/README.md?plain=1#L52-L53
Now, it's better to follow Conventional Commits.
> chore: use `!` for breaking changes

- pkg/sbom/io/decode.go
See #7007
pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>example.groupId</groupId>
<artifactId>example-artifactId</artifactId>
<version>1.0.0</version>
<name>example-name</name>
<description>Example</description>
</project>
```
before:
```bash
➜  trivy -q sbom example.groupId_example-artifactId-1.0.0.spdx.json -f json --list-all-pkgs
{
...
"Results": [
{
"Target": "Java",
"Class": "lang-pkgs",
"Type": "jar",
"Packages": [
{
"ID": "example-name:1.0.0",
"Name": "example-name",
"Identifier": {
"PURL": "pkg:maven/example.groupId/example-artifactId@1.0.0",
"UID": …
```
> fix(sbom): take pkg name from `purl` for maven pkgs

- pkg/commands/app.go
- pkg/downloader/download.go
- pkg/downloader/downloader_test.go
- pkg/oci/artifact.go
- pkg/plugin/index.go
- pkg/plugin/index_test.go
- pkg/plugin/manager.go
- pkg/plugin/plugin.go
`--insecure` is not respected for plugin subcommands now.
- Close https://github.com/aquasecurity/trivy/issues/7021
> fix(plugin): respect `--insecure`

- docs/getting-started/installation.md
This PR changes installation docs as mentioned below:
* Add sudo on pacman
* Add sudo on sh -s
* Run chmod before mv
> docs: Add sudo on commands, chmod before mv on install docs

- .github/workflows/test.yaml
- .golangci.yaml
- pkg/iac/scanners/azure/arm/parser/armjson/parse_number_test.go
- pkg/iac/scanners/azure/arm/parser/armjson/parse_object_test.go
- pkg/iac/scanners/cloudformation/parser/parser_test.go
- pkg/iac/scanners/json/parser/parser_test.go
- pkg/parallel/pipeline_test.go
enable and fixes float-compare rule from testifylint
> chore: enable float-compare rule from testifylint

- pkg/flag/options.go
`trivy convert` shows the following message even though it doesn't have `--scanners` flag.
```
$ trivy convert -f cyclonedx /tmp/with_vulns.json -o /dev/null
2024-06-27T07:33:52+04:00       INFO    "--format cyclonedx" disables security scanning. Specify "--scanners vuln" explicitly if you want to include vulnerabilities in the CycloneDX report.
```
```
$ trivy convert -f cyclonedx /tmp/with_vulns.json -o /dev/null
```
- Discussion: https://github.com/aquasecurity/trivy/discussions/7016
> fix(cli): show info message only when --scanners is available

- pkg/cache/cache.go
- pkg/cache/client.go
- pkg/cache/client_test.go
- pkg/cache/fs.go
- pkg/cache/fs_test.go
- pkg/cache/redis.go
- pkg/cache/redis_test.go
- pkg/cache/remote.go
- pkg/cache/remote_test.go
- pkg/commands/artifact/inject.go
- pkg/commands/artifact/run.go
- pkg/commands/artifact/scanner.go
- pkg/commands/artifact/wire_gen.go
- pkg/commands/clean/run.go
- pkg/commands/clean/run_test.go
- pkg/commands/server/run.go
- pkg/flag/cache_flags.go
- pkg/flag/global_flags.go
- pkg/flag/options.go
- pkg/k8s/wire_gen.go
- pkg/rpc/server/wire_gen.go
- pkg/scanner/scan.go
This PR simplifies the cache initialization process in the artifact scanning. Previously, we [initialized](https://github.com/aquasecurity/trivy/blob/3d02a31b44924f9e2495aae087f7ca9de3314db4/pkg/commands/artifact/run.go#L338-L361) the `cache.Cache` instance within `pkg/commands/artifact/run.go` to support `--clear-cache` and `--reset` operations. However, these operations have been [moved to the `trivy clean` command](https://github.com/aquasecurity/trivy/pull/6993).
With this change, we can now generate the `cache.Cache` instance through [google/wire](https://github.com/google/wire), which is consistent with other instances in the project. 
- Remove the `initCache` function from `pkg/commands/artifact/run.go`
- Update the wire injection to include `cache.Cache` generation
- Adjust the …
> refactor: use google/wire for cache

- go.mod
- go.sum
fix: use embedded when command path not found
- #6602
- https://github.com/aquasecurity/trivy-kubernetes/pull/371
> fix: use embedded when command path not found

- docs/ecosystem/prod.md
This PR updates the docs/ecosystem/prod. documentation to include a new additional reference to a community-supported  tool to import Helm Charts and container images to OCI registries, with Security Scanning (trivy) and Copacetic (patching based on trivy reports)
- N/A
> docs: ✨ Updated ecosystem docs with reference to new community app

- docs/docs/configuration/cache.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_sbom.md
- docs/docs/references/configuration/cli/trivy_server.md
- docs/docs/references/configuration/cli/trivy_vm.md
- pkg/cache/client.go
- pkg/cache/memory.go
- pkg/cache/memory_test.go
- pkg/commands/app.go
- pkg/fanal/types/package.go
- pkg/flag/cache_flags.go
See https://github.com/aquasecurity/trivy/issues/7047 for details
For repository scans (and filesystem/SBOM), it's used by default now.
```
$ trivy repo my-repo
```
For container image scans, you can specify this if you don't need cache.
```
$ trivy image debian:11 --cache-backend memory
```
- Close https://github.com/aquasecurity/trivy/issues/7047
> feat: add memory cache backend

- docs/community/maintainer/release-flow.md
Update the release page at the end of a release so users will be redirected to the release highlights and summary.
e.g. https://github.com/aquasecurity/trivy/releases/tag/v0.52.0
> docs: navigate to the release highlights and summary

- go.mod
- go.sum
- integration/integration_test.go
- internal/dbtest/db.go
- pkg/commands/artifact/run.go
- pkg/commands/clean/run.go
- pkg/commands/operation/operation.go
- pkg/commands/server/run.go
- pkg/db/db.go
- pkg/db/db_test.go
- pkg/rpc/server/listen.go
- pkg/rpc/server/listen_test.go
- pkg/version/version.go
See https://github.com/aquasecurity/trivy-db/pull/412 for more details.
> refactor: pass DB dir to trivy-db

- pkg/fanal/analyzer/pkg/dpkg/scanner.go
This PR makes use of `bytes.Index` in `emptyLineSplit` instead of `strings.Index` to remove the extra allocation caused by the bytes to string cast.
- Close https://github.com/aquasecurity/trivy/discussions/7064
> perf(debian): use `bytes.Index` in `emptyLineSplit` to cut allocation

- .github/workflows/test.yaml
- internal/testutil/util.go
- magefiles/magefile.go
- pkg/downloader/downloader_test.go
- pkg/fanal/artifact/image/remote_sbom_test.go
- pkg/iac/scanners/terraform/scanner_test.go
- pkg/plugin/index_test.go
- pkg/plugin/manager_unix_test.go
- pkg/rekortest/server.go
> chore: bump golangci-lint from v1.58 to v1.59

- pkg/commands/app.go
- pkg/dependency/parser/java/jar/parse.go
- pkg/dependency/parser/java/pom/parse.go
- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/language/analyze.go
- pkg/fanal/analyzer/language/dart/pub/pubspec.go
- pkg/fanal/analyzer/language/java/gradle/pom.go
- pkg/fanal/analyzer/language/julia/pkg/pkg.go
- pkg/fanal/analyzer/language/nodejs/license/license.go
- pkg/fanal/analyzer/language/nodejs/yarn/yarn.go
- pkg/fanal/analyzer/language/php/composer/composer.go
- pkg/fanal/analyzer/language/python/pip/pip.go
- pkg/fanal/analyzer/language/python/poetry/poetry.go
- pkg/fanal/analyzer/language/rust/cargo/cargo.go
- pkg/fanal/analyzer/licensing/license.go
- pkg/fanal/analyzer/pkg/dpkg/dpkg.go
- pkg/fanal/handler/unpackaged/unpackaged.go
- pkg/log/handler.go
- pkg/module/module.go
- pkg/parallel/walk.go
- pkg/result/ignore.go
- pkg/scanner/langpkg/scan.go
- pkg/scanner/local/scan.go
- pkg/utils/fsutils/fs.go
We often use `log.String()` with `file/filepath/path/etc.` key for filepath.
Add log.FilePath() function to use a consistent key name.
> feat: add `log.FilePath()` function for logger

- pkg/fanal/analyzer/secret/secret.go
Show warnings about large files so users can skip them.
See https://github.com/aquasecurity/trivy/discussions/7078 for more details.
example:
```bash
2024-07-03T12:46:19+06:00       WARN    [secret] The size of the scanned file is too large. It is recommended to use `--skip-files` for this file to avoid high memory consumption.     file_path="fslibs-entry-point.sh" size (MB)=946
```
- Close #7078
> refactor(secret): add warning about large files

- go.mod
- go.sum
Ignore nodes when listing permission is not allowed
- Related #6692
- Related https://github.com/aquasecurity/trivy-kubernetes/pull/374
> fix: ignore nodes when listing permission is not allowed

- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/pom.go
- pkg/dependency/parser/java/pom/testdata/exclusions-parent-dependency-management/child/pom.xml
- pkg/dependency/parser/java/pom/testdata/exclusions-parent-dependency-management/pom.xml
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-exclusions/3.0.0/example-exclusions-3.0.0.pom
I noticed that if I have a child pom with a dependency with some exclusions, and a parent pom with a dependencyManagement section with the same dependency with different exclusions, then Trivy only uses the child exclusions.
This is not the behaviour that the maven command line uses, the mvn dependency:tree combines the set of exclusions in this case.
To reproduce unzip "trivy.zip" attached and run:
```
mvn dependency:tree | grep jettison
```
This will return nothing as jettison is excluded in the parent pom. Now run:
```
trivy fs . | grep jettison
```
and see it returns findings in jettison even though it's not on the classpath
> fix: Add dependencyManagement exclusions to the child exclusions

- integration/testdata/conan.json.golden
- integration/testdata/fixtures/db/vulnerability.yaml
- integration/testdata/spring4shell-jre11.json.golden
- integration/testdata/spring4shell-jre8.json.golden
[vulnerability.yaml](https://github.com/aquasecurity/trivy/blob/main/integration/testdata/fixtures/db/vulnerability.yaml) file contains extra commas.
This is why advisory details for `CVE-2020-14155` (and new details added after this CVE) doesn't exist in test db.
> test: add missing advisory details for integration tests database

- pkg/fanal/analyzer/secret/secret.go
Fix problem that we write warning every each binary  file larger than 10MB.
Before:
```bash
➜ ./trivy fs --scanners secret ./trivy 
2024-07-09T12:19:09+06:00       INFO    Secret scanning is enabled
2024-07-09T12:19:09+06:00       INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-07-09T12:19:09+06:00       INFO    Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret#recommendation for faster secret detection
2024-07-09T12:19:09+06:00       WARN    [secret] The size of the scanned file is too large. It is recommended to use `--skip-files` for this file to avoid high memory consumption.     file_path="trivy" size (MB)=240
```
After:
```bash
➜  ./trivy fs --scanners secret ./trivy
2024-07-09T12:21:13+06:00       INFO …
```
> refactor(secret): move warning about file size after `IsBinary` check

- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_test.go
If an error occurs while loading the configuration files, we must skip the evaluation.
- Close https://github.com/aquasecurity/trivy/issues/7084
> fix(misconf): do not evaluate TF when a load error occurs

- .vex/oci.openvex.json
Add OpenVEX file for OCI images
NOTE: In this case, I created it manually, but I feel like it's not a human task. I think we should generate VEX automatically from the image scan results and `.trivyignore.yaml`.
```
$ trivy image ghcr.io/aquasecurity/trivy:0.51.0 --vex .vex/oci.openvex.json --show-suppressed --pkg-types os
ghcr.io/aquasecurity/trivy:0.51.0 (alpine 3.19.1)
=================================================
Total: 17 (UNKNOWN: 0, LOW: 4, MEDIUM: 10, HIGH: 2, CRITICAL: 1)
┌────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                           │ …
```
> chore: add VEX for Trivy images

- docs/docs/coverage/iac/terraform.md
- Close https://github.com/aquasecurity/trivy/issues/7098
> docs(misconf): add info about limitations for terraform plan json

- docs/community/contribute/pr.md
Fix PR documentation page since non-maintainers cannot use GitHub issues in trivy project.
- None (basic documentation issue).
> docs: Fix PR documentation to use GitHub Discussions, not Issues

- pkg/fanal/image/docker.go
> fix: close file when failed to open gzip

- pkg/iac/types/compliance.go
The platform and type fields are present in the compliance specifications in trivy-checks, but missing in types.
> fix: add missing platform and type to spec

- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
Bump [goreleaser](https://github.com/goreleaser/goreleaser/) from `v2.0.0` to `v2.1.0`
First of all we need this update to fix the problem with creating the release discussion (https://github.com/goreleaser/goreleaser/commit/afd92ffe0fc1070081dcd7e0e49cf87f0749853f).
> chore(deps): bump goreleaser from `v2.0.0` to `v2.1.0`

- docs/docs/references/configuration/config-file.md
The documentation for the config file states that the yaml field `rego.skip-policy-update` skips the retrieval of policy checks which is outdated or incorrect because the actual field is `rego.skip-check-update`
> docs: updates config file

- .vex/oci.openvex.json
CVE-2023-42364 and other awk vulnerabilities are detected on `ssl_client` as it is a binary package of busybox. It must not be affected.
```
$ trivy image ghcr.io/aquasecurity/trivy:0.52.0 --vex .vex/oci.openvex.json
...
ghcr.io/aquasecurity/trivy:0.52.0 (alpine 3.20.0)
=================================================
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 6, HIGH: 0, CRITICAL: 0)
┌────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────┐
│  Library   │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                     Title                      │
├────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼────────────────────────────────────────────────┤
│ …
```
> chore(vex): update subcomponents for CVE-2023-42363/42364/42365/42366

- .github/workflows/bypass-test.yaml
- .github/workflows/test.yaml
Use `ubuntu-latest-m` only for `build tests` and `release` action, to avoid running this runner a lot.
> ci: use free runner for all tests except `build tests`

- pkg/fanal/secret/builtin-rules.go
`hugging-face-access-token` can contain 34-40 characters.
- Close #6823
> fix(secret): update length of `hugging-face-access-token`

- docs/docs/references/configuration/config-file.md
- mkdocs.yml
Show VEX cli pages (add them to docs config file) + update config file page for VEX flags.
> docs: show VEX cli pages + update config file page for VEX flags

- pkg/report/table/table_test.go
- pkg/report/table/vulnerability.go
This PR introduces a VEX (Vulnerability Exploitability eXchange) notice for OSS maintainers when Trivy is run in CI environments. The notice aims to encourage the use of VEX statements for more accurate vulnerability reporting.
1. Implement a VEX notice that displays after vulnerability scanning results.
2. Add logic to show the notice only in CI environments.
3. Provide an option to disable the notice via an environment variable (`TRIVY_DISABLE_VEX_NOTICE`).
```
$ CI=true ./trivy image alpine:3.20
...
For OSS Maintainers: VEX Notice
--------------------------------
If you're an OSS maintainer and Trivy has detected vulnerabilities in your project that you believe are not actually exploitable, consider issuing a VEX (Vulnerability Exploitability eXchange) statement.
VEX allows you to …
```
> chore: show VEX notice for OSS maintainers in CI environments

- pkg/flag/db_flags.go
Trivy doesn't support simultaneous use of the `--download-db-only` and `--download-java-db-only` flags.
So in this case we need to return an error.
Example:
```bash
➜ trivy image --download-db-only --download-java-db-only
2024-07-30T12:19:15+06:00       FATAL   Fatal error     flag error: db flag error: --download-db-only and --download-java-db-only options can not be specified both
```
- #7250
> refactor(flag): return error if both `--download-db-only` and `--download-java-db-only` are specified

- docs/docs/target/vm.md
- go.mod
- go.sum
Since I have implemented the Ext2/3 filesystems parser on the [go-ext4-filesystem](https://github.com/masahiro331/go-ext4-filesystem)  that trivy depends, upgraded the library on go.mod file.
- https://github.com/masahiro331/go-ext4-filesystem/pull/16
> feat(vm): support the Ext2/Ext3 filesystems

- pkg/downloader/download.go
```
$ trivy plugin install referrer
...
2024-07-31T14:51:48+04:00       FATAL   Fatal error     plugin install error: failed to install the plugin: unable to download the execution file (https://github.com/aquasecurity/trivy-plugin-referrer/releases/download/v0.3.1/trivy_plugin_referrer_0.3.1_macOS-ARM64.tar.gz): failed to download https://github.com/aquasecurity/trivy-plugin-referrer/releases/download/v0.3.1/trivy_plugin_referrer_0.3.1_macOS-ARM64.tar.gz: Get "https://github.com/aquasecurity/trivy-plugin-referrer/releases/download/v0.3.1/trivy_plugin_referrer_0.3.1_macOS-ARM64.tar.gz": failed to round trip: failed to get the file content: GET https://api.github.com/repos/aquasecurity/trivy-plugin-referrer/contents/releases/download/v0.3.1: 404 Not Found []
```
- Close …
> fix(plugin): do not call GitHub content API for releases and tags

- pkg/dependency/parser/java/pom/parse.go
On updating from 0.52.x to 0.54.0, Trivy is segfaulting when scanning a maven filesystem due to the changes in https://github.com/aquasecurity/trivy/commit/1f8fca1fc77b989bb4e3ba820b297464dbdd825f
"Nil" is returned for the error in remoteRepoRequest, and so in fetchPOMFromRemoteRepository it proceeds to client.Do with a null "req".
The fix just returns the error in remoteRepoRequest and so it's handled properly by the calling functions.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x69868fb]
goroutine 41 [running]:
net/http.(*Client).do(0xc000c76580?, 0x0)
/opt/hostedtoolcache/go/1.22.5/x64/src/net/http/client.go:599 +0xbb
net/http.(*Client).Do(...) …
```
> fix(java): Return error when trying to find a remote pom to avoid segfault

- pkg/flag/cache_flags.go
`ClearCache` should be initialized for correct message.
Before:
```sh
$ trivy image --clear-cache
Scan a container image
...
2024-07-31T18:13:26+06:00	FATAL	Fatal error	unknown flag: --clear-cache
```
After:
```sh
$ trivy image --clear-cache
2024-07-31T18:14:29+06:00	ERROR	"--clear-cache" was removed. Use "trivy clean --scan-cache" instead
2024-07-31T18:14:29+06:00	FATAL	Fatal error	flag error: cache flag error: unable to parse flag: removed flag ("--clear-cache")
```
> fix(flag): incorrect behavior for deprected flag `--clear-cache`

- pkg/iac/detection/detect.go
- pkg/iac/detection/detect_test.go
- pkg/iac/rego/scanner.go
- pkg/iac/scanners/azure/arm/parser/parser.go
- pkg/iac/scanners/azure/arm/parser/parser_test.go
- pkg/iac/scanners/azure/arm/scanner.go
- pkg/iac/scanners/cloudformation/parser/parser.go
- pkg/iac/scanners/cloudformation/scanner.go
- pkg/iac/scanners/dockerfile/parser/parser.go
- pkg/iac/scanners/dockerfile/scanner.go
- pkg/iac/scanners/helm/parser/parser.go
- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/json/parser/parser.go
- pkg/iac/scanners/json/scanner.go
- pkg/iac/scanners/kubernetes/parser/parser.go
- pkg/iac/scanners/kubernetes/scanner.go
- pkg/iac/scanners/options/parser.go
- pkg/iac/scanners/options/scanner.go
- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/scanner.go
- pkg/iac/scanners/terraformplan/tfjson/scanner.go
- pkg/iac/scanners/toml/parser/parser.go
- pkg/iac/scanners/toml/scanner.go
- pkg/iac/scanners/yaml/parser/parser.go
- pkg/iac/scanners/yaml/scanner.go
- pkg/misconf/scanner.go
This PR removes duplicate file filtering from the parsers, which was never done because a flag was always passed to disable it. Currently, the detection package is responsible for this, which filters files before scanning.
> refactor(misconf): remove file filtering from parsers

- pkg/iac/detection/detect.go
- pkg/iac/scanners/yaml/parser/parser.go
To work with bytes, it is better to use the bytes package instead of converting bytes to a string.
> perf(misconf): do not convert contents of a YAML file to string

- pkg/iac/detection/detect.go
Validity checking with `json.Valid` is faster and produces fewer allocations than validity checking via unmarshalling.
> perf(misconf): use json.Valid to check validity of JSON

- pkg/iac/adapters/terraform/aws/cloudfront/adapt.go
- pkg/iac/adapters/terraform/aws/cloudfront/adapt_test.go
The documentation does not say that the `default_cache_behavior` argument has a default values.
Refs:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#default_cache_behavior
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html
- Close https://github.com/aquasecurity/trivy/issues/7233
> fix(misconf): do not set default value for default_cache_behavior

- docs/docs/references/modes/client-server.md
- pkg/commands/artifact/run.go
Also added logging:
```bash
2024-07-31T18:16:37+07:00       WARN    Trivy runs in client/server mode, but misconfiguration and license scanning will be done on the client side, see https://aquasecurity.github.io/trivy/dev/docs/references/modes/client-server
```
- Close https://github.com/aquasecurity/trivy/issues/7177
> docs: update client/server docs for misconf and license scanning

- pkg/iac/scanners/terraform/parser/evaluator.go
- pkg/iac/terraform/block.go
- pkg/iac/terraform/context/context.go
- pkg/iac/terraform/context/context_test.go
- The `for_each` resource attribute is not added to the context because it cannot be accessed, but it can take up a lot of memory.
- If possible, use the `GetAttr` method to access `cty.Object` attributes, instead of converting the object to a map.
Unfortunately there is still the [mergeVars](https://github.com/aquasecurity/trivy/pull/6968/files#diff-8544850e0d901aac3f77abe4fb9e6e9430043f6f2dbadd5a66a79f25c4140db6L90) function, which cannot be optimised due to some limitations. Because of the [impossibility to modify](https://github.com/zclconf/go-cty/issues/57) `cty.Object` directly, it is necessary to convert `cty.Object` into a map, modify it and create the object from the map again. With a large number of resources, such actions generate a large number of objects and take a decent …
> perf(misconf): optimize work with context

- pkg/iac/adapters/arm/storage/adapt.go
- pkg/iac/adapters/arm/storage/adapt_test.go
- pkg/iac/adapters/terraform/azure/storage/adapt.go
Now the default minimum TLS value for storage account in Terraform is `TLS1_2`. But Azure ARM sets the default value depending on the deployment method. If the account is created via ARM, the MinimumTlsVersion property is not set by default and does not return a value until you explicitly set it.
Refs:
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#min_tls_version
- https://learn.microsoft.com/en-us/azure/storage/common/transport-layer-security-configure-minimum-version?tabs=azure-cli#configure-the-minimum-tls-version-for-a-storage-account
> fix(misconf): change default TLS values for the Azure storage account

- integration/testdata/helm_testchart.overridden.json.golden
- pkg/iac/scan/code.go
- pkg/iac/scan/code_test.go
- pkg/iac/scan/highlighting.go
- pkg/iac/types/range.go
This PR highlights only the affected code, not the entire file in which the misconfiguration is detected. The highlighting code has also been refactored.
> refactor(misconf): highlight only affected rows

- pkg/iac/adapters/arm/network/adapt.go
- pkg/iac/adapters/terraform/azure/network/adapt.go
- pkg/iac/adapters/terraform/azure/network/adapt_test.go
- pkg/iac/providers/azure/network/network.go
- pkg/iac/rego/schemas/cloud.json
`PortRange` is not exported to json for Rego because it is not wrapped in IaC types.
> fix(misconf): wrap Azure PortRange in iac types

- pkg/utils/fsutils/fs.go
- pkg/utils/fsutils/fs_test.go
The `DirExists` function call caused a panic if an error not related to the existence of the file was received when retrieving the file information
- Close https://github.com/aquasecurity/trivy/issues/7352
> fix: safely check if the directory exists

- docs/docs/references/configuration/config-file.md
- integration/client_server_test.go
- magefiles/docs.go
- pkg/cache/remote.go
- pkg/commands/artifact/run.go
- pkg/commands/server/run.go
- pkg/flag/options.go
- pkg/flag/remote_flags.go
- pkg/rpc/client/client.go
- pkg/rpc/server/listen.go
- pkg/rpc/server/listen_test.go
This PR introduces a new internal flag `--path-prefix` for client/server mode, allowing customization of the API endpoint prefix. This feature is currently intended for internal use only and will not be exposed in the CLI help output.
```
$ trivy server --path-prefix myprefix
```
```
$ trivy image --server http://localhost:4954 --path-prefix myprefix debian:11
```
- Add a new `--path-prefix` flag to customize the API endpoint prefix in server mode
- Implement logic to 
- apply the custom prefix to all server endpoints
- apply the custom prefix to all client requests
- Ensure the flag is hidden from CLI help output
- Hide deprecated/removed flags in the configuration document
- Add integration tests
This change is necessary for internal purposes, but we want to maintain flexibility for …
> feat(server): add internal `--path-prefix` flag for client/server mode

- go.mod
- go.sum
Now some Go checks use scanner from squealer package and analyze CIDR, but it is impossible to implement them on pure Rego, so built-in Rego functions were [added](https://github.com/aquasecurity/trivy-checks/pull/174).
An example of such checks:
- https://github.com/aquasecurity/trivy-checks/blob/main/checks/cloud/aws/ec2/no_sensitive_info.go#L42
- https://github.com/aquasecurity/trivy-checks/blob/main/checks/cloud/aws/ec2/no_public_egress_sgr.go#L45
> chore(deps): bump trivy-checks

- pkg/iac/rego/metadata.go
- pkg/iac/rego/metadata_test.go
Fixes:
```bash
2024-08-23T04:50:26Z    DEBUG   [misconf] 50:26.747428627 terraform.scanner.rego           Error occurred while parsing: root/.cache/trivy/policy/content/policies/cloud/policies/aws/ec2/no_public_ingress_sgr.rego, root/.cache/trivy/policy/content/policies/cloud/policies/aws/ec2/no_public_ingress_sgr.rego:44: rego_type_error: undefined function cidr.is_public. Trying to fallback to embedded check.
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/iac/rego.(*StaticMetadata).updateFrameworks(0xc004228500, 0xc0014cb5c0?)
/Users/nikita/projects/trivy/pkg/iac/rego/metadata.go:138 +0x1f3
github.com/aquasecurity/trivy/pkg/iac/rego.(*StaticMetadata).Update(0xc004228500, 0xc0014cb5c0) …
```
> fix(misconf): init frameworks before updating them

- pkg/iac/scanners/azure/arm/scanner.go
- pkg/iac/scanners/cloudformation/scanner.go
- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/executor/option.go
- pkg/iac/scanners/terraform/scanner.go
- pkg/iac/scanners/terraform/scanner_test.go
This PR adds deprecating support for Go checks for some scanners, which was not added [here](https://github.com/aquasecurity/trivy/pull/6664).
> fix(misconf): support deprecating for Go checks

- contrib/asff.tpl
Escape `Message` field in `asff.tpl`
- Close #7400
> fix(report): escape `Message` field in `asff.tpl` template

- pkg/iac/rego/embed.go
Access to metadata can cause panic in the event of an extraction failure.
> fix(misconf): use module to log when metadata retrieval fails

- docs/docs/scanner/misconfiguration/index.md
- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/ignore_test.go
- pkg/iac/terraform/block.go
Added ability to ignore by nested attributes and values.
- Part of https://github.com/aquasecurity/trivy/issues/7180
> feat(misconf): support for ignore by nested attributes

- pkg/iac/adapters/cloudformation/aws/ec2/adapt_test.go
- pkg/iac/adapters/cloudformation/aws/ec2/nacl.go
- pkg/iac/adapters/cloudformation/aws/ec2/security_group.go
- pkg/iac/adapters/terraform/aws/ec2/subnet.go
- pkg/iac/adapters/terraform/aws/ec2/subnet_test.go
- pkg/iac/adapters/terraform/aws/ec2/vpc.go
- pkg/iac/adapters/terraform/aws/ec2/vpc_test.go
- pkg/iac/providers/aws/ec2/vpc.go
- pkg/iac/scanners/cloudformation/parser/property_conversion.go
- Added port support for Network ACLs
- Added port and protocol support for security group rules
- The default protocol for Network ACL was `-1`. This is not mentioned in the documentation and the protocol is required, so it is changed to blank.
Refs:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-networkaclentry.html#cfn-ec2-networkaclentry-protocol
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl_rule#protocol
- Fixes https://github.com/aquasecurity/trivy/issues/7137
> feat(misconf): port and protocol support for EC2 networks

- pkg/fanal/secret/builtin-allow-rules.go
Current functionality is not ignoring test files which are not in all lower case.
PS: Didn't add tests for this because we are disabling "tests" built in allow rule in code tests. Didn't want to disrupt the pattern for a small case.
> chore: fix allow rule of ignoring test files to make it case insensitive

- pkg/fanal/secret/scanner.go
- pkg/fanal/secret/scanner_test.go
- pkg/fanal/secret/testdata/jwt-secret.txt
For long secret lines use only the line with the secret
before:
```bash
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
j.txt:3
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1   asd
2   aaaa
3 [ asd
aaaa
jwt: ***********************************************************************************************************************************************************
asda
4   
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
> fix(secret): use only line with secret for long secret lines

- docs/docs/configuration/filtering.md
- pkg/report/json.go
- pkg/report/writer.go
- pkg/types/report.go
`--show-suppressed` exports modified findings in JSON.
```
$ cat .trivyignore
CVE-2022-0563
$ trivy image -q -f json --show-suppressed debian:11 | jq ".Results[].ExperimentalModifiedFindings | length" 
0
```
```
$ cat .trivyignore
CVE-2022-0563
$ trivy image -q -f json --show-suppressed debian:11 | jq ".Results[].ExperimentalModifiedFindings | length" 
7
```
- Close https://github.com/aquasecurity/trivy/issues/7382
> feat(report): export modified findings in JSON

- integration/testdata/julia-spdx.json.golden
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
See more in #7397
Before:
```bash
"licenseConcluded": "NONE",
"licenseDeclared": "NONE",
```
After:
```bash
"licenseConcluded": "NOASSERTION",
"licenseDeclared": "NOASSERTION",
```
- Close #7402
> fix(sbom): use `NOASSERTION` for licenses fields in SPDX formats

- pkg/iac/scanners/terraform/parser/evaluator.go
Due to recreating the map with filesystems during submodule evaluation, the ability to retrieve file contents from other fs for results was lost.
> fix(misconf): do not recreate filesystem map

- pkg/iac/scanners/cloudformation/cftypes/types.go
- pkg/iac/scanners/cloudformation/parser/parser_test.go
An example of a CloudFormation template for which parsing fails:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
Email:
Type: String
Conditions:
SubscribeEmail: !Not [!Equals [ !Ref Email, ""]]
```
> fix(misconf): fix infer type for null value

- pkg/fanal/image/registry/azure/azure.go
- pkg/fanal/image/registry/azure/azure_test.go
- pkg/fanal/image/registry/ecr/ecr.go
- pkg/fanal/image/registry/ecr/ecr_test.go
- pkg/fanal/image/registry/google/google.go
- pkg/fanal/image/registry/google/google_test.go
- pkg/fanal/image/registry/intf/registry.go
- pkg/fanal/image/registry/token.go
This PR modified the ECR integration so that it obtains authorization tokens from the region hosting the ECR.  Current behaviour would be to use the default, resulting in authentication errors such as 
```
2024-02-26T18:56:03.738Z	ERROR	Error during vulnerabilities or misconfiguration scan: scan error: unable to initialize a scanner: unable to initialize an image scanner: 4 errors occurred:
* docker error: unable to inspect the image (127647282379.dkr.ecr.us-east-1.amazonaws.com/undistro-test-image:1.25.3): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
* containerd error: containerd socket not found: /run/containerd/containerd.sock
* podman error: unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no …
```
> fix(aws): handle ECR repositories in different regions

- pkg/dependency/parser/nodejs/pnpm/parse.go
- pkg/dependency/parser/nodejs/pnpm/parse_test.go
- pkg/dependency/parser/nodejs/pnpm/parse_testcase.go
- pkg/dependency/parser/nodejs/pnpm/testdata/pnpm-lock_v9.yaml
Check all `importers` to detect dev deps from pnpm-lock.yaml file.
More details in #7386
before:
```bash
➜ trivy -q fs ./pnpm-lock.yaml  --list-all-pkgs -f json --include-dev-deps
...
{
"ID": "sleep-utils@1.0.3",
"Name": "sleep-utils",
"Identifier": {
"PURL": "pkg:npm/sleep-utils@1.0.3",
"UID": "716b20f0563e731b"
},
"Version": "1.0.3",
"Dev": true,
"Indirect": true,
"Relationship": "indirect",
"Layer": {}
}
]
}
]
}
```
after:
```bash
➜ ./trivy -q fs ./pnpm-lock.yaml  --list-all-pkgs -f json --include-dev-deps
...
{
"ID": "sleep-utils@1.0.3",
"Name": "sleep-utils",
"Identifier": {
"PURL": "pkg:npm/sleep-utils@1.0.3",
"UID": "8981f07a21207ebb"
},
"Version": "1.0.3",
"Relationship": "direct",
"Layer": {}
}
]
}
]
}
```
- Close #7386
> fix(nodejs): check all `importers` to detect dev deps from pnpm-lock.yaml file

- helm/trivy/templates/statefulset.yaml
Hello, I made a quick fix to define explicitly all `volumeClaimTemplate` field.
This allows to use gitops tools (like argoCD) to sync raw k8s manifests (built via helm) with cluster resources. Without these fields defined, these will be added in the cluster resource resulting in an OutOfSync with the generated manifest.
Feel free to discuss this fix in the below linked discussion.
Like mentionned in [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/), I think this change is trivial. This is why I created this PR without any Issue linked.
Nevertheless, I oepened a discussion here: https://github.com/aquasecurity/trivy/discussions/7361
> fix(helm): explicitly define `kind` and `apiVersion` of `volumeClaimTemplate` element

- go.mod
- pkg/rekor/client.go
- pkg/rekor/client_test.go
* Added functionality to set the User-Agent header in Trivy when making requests to Sigstore's Rekor transparency log.
* Updated tests to cover the new functionality and ensure that the User-Agent header is properly set.
This enhancement is important for distinguishing requests to Rekor. It aids in tracking and managing Trivy requests more effectively.
Before the User-Agent header was just a plain `Go-http-client/2.0`. After the change, it becomes `trivy/version`.
> feat(sbom): set User-Agent header on requests to Rekor

- docs/docs/coverage/language/java.md
- pkg/dependency/parser/java/pom/artifact.go
- pkg/dependency/parser/java/pom/parse.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/pom.go
- pkg/dependency/parser/java/pom/testdata/happy/pom.xml
Add `test` scope support and mark these dependencies as `Dev`.
To show these deps - use `--include-dev-deps` flag.
- Close #7384
> feat(java): add `test` scope support for `pom.xml` files

- contrib/junit.tpl
> fix(license): add license handling to JUnit template

- pkg/dependency/parser/java/pom/parse.go
When we can't get `pom.xml` or `maven-metadata.xml` file from remote repository - we need to show more info.
See https://github.com/aquasecurity/trivy/discussions/7443#discussioncomment-10555485
Before:
```
2024-09-06T11:29:13+06:00       DEBUG   [pom] Failed to fetch   url="https://repo.maven.apache.org/maven2/abbot/abbot/1.4.0000/abbot-1.4.0000.pom"
```
After:
```
2024-09-06T11:23:02+06:00       DEBUG   [pom] Failed to fetch   url="https://repo.maven.apache.org/maven2/abbot/abbot/1.4.0/abbot-1.4.0.pom" err="Get \"https://repo.maven.apache.org/maven2/abbot/abbot/1.4.0/abbot-1.4.0.pom\": Bad Request"
```
```
2024-09-06T11:28:39+06:00       DEBUG   [pom] Failed to fetch   url="https://repo.maven.apache.org/maven2/abbot/abbot/1.4.0000/abbot-1.4.0000.pom" statusCode=404
```
> refactor(java): add error/statusCode for logs when we can't get pom.xml/maven-metadata.xml from remote repo

- helm/trivy/Chart.yaml
This PR bumps up Trivy version in the helm chart.
**Note**: There is a breaking change since Trivy 0.51.0 for kubernetes scan - #6323. It can affect on UX.
The Helm chart runs Trivy in `server` mode, so this update shouldn't mark as a breaking change.
> chore(helm): bump up Trivy Helm chart

- pkg/detector/ospkg/oracle/oracle.go
There is only one change:
- Oracle 7 EOL date has been updated to 31-12-2024 as per official site (https://endoflife.date/oracle-linux)
- Close #7479
> fix(oracle): Update EOL date for Oracle 7

- go.mod
- go.sum
- pkg/fanal/types/package.go
- pkg/report/template_test.go
A pointer receiver is used for `MarshalJSON` of some structs by mistake, causing some marshaling problems. If `DetectedVulnerability` is not a slice, custom `MarshalJSON` is not called.
<details><summary>PoC</summary>
<p>
```
package main
import (
"encoding/json"
"fmt"
)
type Status int
func (s *Status) MarshalJSON() ([]byte, error) {
return json.Marshal("hello")
}
type Foo struct {
Status Status
}
func main() {
f1 := []Foo{{Status: 1}}
jsonData, err := json.Marshal(f1)
if err != nil {
panic(err)
}
fmt.Println(string(jsonData))
f2 := Foo{Status: 1}
jsonData, err = json.Marshal(f2)
if err != nil {
panic(err)
}
fmt.Println(string(jsonData))
}
```
</p>
</details> 
- Close https://github.com/aquasecurity/trivy/issues/7464
> fix(report): change a receiver of MarshalJSON

- docs/docs/configuration/db.md
> docs(db): add a manifest example

- docs/docs/coverage/language/java.md
- pkg/dependency/parser/java/pom/artifact.go
- pkg/dependency/parser/java/pom/parse.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/pom.go
- pkg/dependency/parser/java/pom/testdata/happy/pom.xml
We discovered a few problems with #7414:
1. Child dependencies of test dependency are not marked as `Dev` (see #7486).
2. Trivy scans test dependencies even  if `--include-dev-deps` flag doesn't present (this is due to our logic for excluding dev dependencies). Not being able to disable `test` dependency scanning slows down Trivy significantly. More details in #7476. 
Fixing these issues will take some time to be considered.
To avoid further issues with fast merging, we have decided to revert #7414.
The functionality of #7414 will be added in other PRs.
- #7476
> revert(java): stop supporting of `test` scope for `pom.xml` files

- docs/docs/coverage/language/golang.md
@knqyf263 I hope I describe the current capabilities corerctly
> docs: refine go docs

- .vex/oci.openvex.json
Suppress CVE-2024-4741, CVE-2024-5535 and CVE-2024-6119 since the Trivy images are not using OpenSSL in OS packages.
```
$ trivy image ghcr.io/aquasecurity/trivy:0.55.1 --vex .vex/oci.openvex.json --show-suppressed --pkg-types os
2024-09-13T14:16:45+04:00       INFO    [vuln] Vulnerability scanning is enabled
ghcr.io/aquasecurity/trivy:0.55.1 (alpine 3.20.0)
=================================================
Suppressed Vulnerabilities (Total: 12)
======================================
┌───────────────┬────────────────┬──────────┬──────────────┬───────────────────────────────────────────────────┬───────────────────────┐
│    Library    │ Vulnerability  │ Severity │    Status    │                     Statement …
```
> chore(vex): suppress openssl vulnerabilities

- Dockerfile
Fixes multiple vulnerabilities in the base image.
List is visible with scanning the image itself with Trivy:
```docker run --rm aquasec/trivy  fs .```
> chore(deps): bump alpine from 3.20.0 to 3.20.3

- .vex/trivy.openvex.json
Trivy doesn't use vulnerable packages for CVE-2024-34155, CVE-2024-34156 and CVE-2024-34158:
```bash
➜  govulncheck -format openvex ./... | jq '.statements[]'                                               
{
"vulnerability": {
"@id": "https://pkg.go.dev/vuln/GO-2024-3105",
"name": "GO-2024-3105",
"description": "Stack exhaustion in all Parse functions in go/parser",
"aliases": [
"CVE-2024-34155"
]
},
"products": [
{
"@id": "Unknown Product"
}
],
"status": "not_affected",
"justification": "vulnerable_code_not_in_execute_path",
"impact_statement": "Govulncheck determined that the vulnerable code isn't called"
}
{
"vulnerability": {
"@id": "https://pkg.go.dev/vuln/GO-2024-3106",
"name": "GO-2024-3106",
"description": "Stack exhaustion in Decoder.Decode in encoding/gob",
"aliases": [ …
```
> chore(vex): add `CVE-2024-34155`, `CVE-2024-34156` and `CVE-2024-34158` in `trivy.openvex.json`

- pkg/dependency/parser/java/pom/parse.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-dependency/2.0.0/example-dependency-2.0.0.pom
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-parent/3.0.0/example-parent-3.0.0.pom
- pkg/dependency/parser/java/pom/testdata/use-dep-management-from-child-in-parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/use-root-dep-management-in-parent/pom.xml
We need to overwrite versions from `dependencyManagement` of root/child pom.xml files for dependencies from parents.
See #7493 for more details.
- Close #7493
> fix(java): use `dependencyManagement` from root/child pom's for dependencies from parents

- pkg/iac/rego/embed.go
- pkg/iac/rego/embed_test.go
- pkg/iac/rego/scanner.go
Only register checks when needed, removing the `init` function to do so.  
- Close https://github.com/aquasecurity/trivy/issues/7434
> feat(misconf): Register checks only when needed

- pkg/sbom/cyclonedx/testdata/happy/third-party-bom.json
- pkg/sbom/cyclonedx/unmarshal.go
See #7432 for more details.
- Close #7432
> fix(sbom): parse type `framework` as `library` when unmarshalling `CycloneDX` files

- pkg/iac/adapters/terraform/google/compute/adapt_test.go
- pkg/iac/adapters/terraform/google/compute/networks.go
- pkg/iac/adapters/terraform/google/compute/networks_test.go
- pkg/iac/providers/google/compute/firewall.go
- pkg/iac/rego/schemas/cloud.json
- Close https://github.com/aquasecurity/trivy/issues/7548
Before
```bash
5.52 real         8.00 user         0.36 sys
2330689536  maximum resident set size
```
After
```bash
2.81 real         0.78 user         0.09 sys
171065344  maximum resident set size
```
> perf(misconf): use port ranges instead of enumeration

- docs/docs/scanner/misconfiguration/index.md
Add more info on how to use arbitrary JSON/YAML scan feat
- Close https://github.com/aquasecurity/trivy/issues/7457
> docs(misconf): Add more info on how to use arbitrary JSON/YAML scan feat

- pkg/javadb/client.go
in addition to checking `NextUpdate` - also check that `trivy-java-db` was downloaded more than one day ago (check `DownloadedAt` field).
- https://github.com/aquasecurity/trivy/discussions/7591#discussioncomment-10748187
> fix(db): check `DownloadedAt` for `trivy-java-db`

- pkg/mapfs/fs.go
- pkg/mapfs/fs_test.go
The path “../” becomes “..” after cleaning, causing the MapFS [check](https://github.com/aquasecurity/trivy/blob/main/pkg/mapfs/fs.go#L148) that the path lies outside FS to fail.
```bash
trivy conf test/main.tf
2024-09-23T16:44:35+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2024-09-23T16:44:37+06:00       INFO    [terraform scanner] Scanning root module        file_path="."
2024-09-23T16:44:37+06:00       ERROR   [terraform evaluator] Failed to load module. Maybe try 'terraform init'?        err="file does not exist"
2024-09-23T16:44:37+06:00       INFO    Detected config files   num=1
```
```bash
./trivy conf test/main.tf
2024-09-23T17:23:36+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2024-09-23T17:23:37+06:00       INFO    [terraform …
```
> fix: allow access to '..' in mapfs

- pkg/iac/terraform/resource_block.go
- pkg/iac/terraform/resource_block_test.go
- Close https://github.com/aquasecurity/trivy/issues/7557
> fix(misconf): escape all special sequences

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
- pkg/misconf/scanner.go
- Close https://github.com/aquasecurity/trivy/issues/7368
> fix(misconf): disable DS016 check for image history analyzer

- .github/workflows/cache-test-images.yaml
- .github/workflows/test.yaml
Split `save` and `restore` cache actions:
- use `actions/cache/restore` in `tests`.
- use `actions/cache` in new `cache-test-images.yaml` workflow.
test runs:
- https://github.com/DmitriyLewen/trivy/actions/runs/11102892990/job/30843683889
> ci: split `save` and `restore` cache actions

- internal/dbtest/fake.go
- pkg/db/db.go
- pkg/fanal/artifact/image/remote_sbom.go
- pkg/javadb/client.go
- pkg/module/command.go
- pkg/oci/artifact.go
- pkg/oci/artifact_test.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
`oci.NewArtifact` doesn't return an error anymore.
> refactor: fix auth error handling

- integration/docker_engine_test.go
- internal/testutil/docker.go
- pkg/fanal/test/integration/library_test.go
Reduce dependencies of registry names in the code base as we might switch from GHCR to a different registry.
> test: use loaded image names

- pkg/commands/artifact/run.go
- pkg/commands/operation/operation.go
- pkg/db/db.go
- pkg/javadb/client.go
- pkg/k8s/commands/cluster.go
- pkg/log/logger.go
- pkg/oci/artifact.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
- pkg/version/version.go
Adding prefixes for each artifact.
```
2024-10-01T15:43:48+04:00       INFO    [db] Need to update DB
2024-10-01T15:43:48+04:00       INFO    Downloading vulnerability DB...
2024-10-01T15:43:48+04:00       INFO    Downloading  artifact...        repo="ghcr.io/aquasecurity/trivy-db:2"
53.85 MiB / 53.85 MiB [---------------------------------------------------------------------------------------------------------------] 100.00% 23.26 MiB p/s 2.5s
2024-10-01T15:43:51+04:00       INFO    Artifact successfully downloaded        repo="ghcr.io/aquasecurity/trivy-db:2"
```
```
2024-10-01T18:16:51+04:00       INFO    [vulndb] Need to update DB
2024-10-01T18:16:51+04:00       INFO    [vulndb] Downloading vulnerability DB...
2024-10-01T18:16:51+04:00       INFO    [vulndb] Downloading artifact... …
```
> chore: add prefixes to log messages

- pkg/iac/rego/load.go
This PR gets rid of those noisy messages for Rego libraries:
```bash
2024-10-03T08:53:28+06:00       WARN    [rego] Module has no input selectors - it will be loaded for all inputs!        file_path="Users/nikita/Library/Caches/trivy/policy/content/policies/test/lib/test.rego" module="Users/nikita/Library/Caches/trivy/policy/content/policies/test/lib/test.rego"
2024-10-03T08:53:28+06:00       WARN    [rego] Module has no input selectors - it will be loaded for all inputs!        file_path="Users/nikita/Library/Caches/trivy/policy/content/policies/cloud/lib/metadata.rego" module="Users/nikita/Library/Caches/trivy/policy/content/policies/cloud/lib/metadata.rego"
```
> fix(misconf): not to warn about missing selectors of libraries

- pkg/report/sarif.go
- pkg/report/sarif_test.go
Details are in #7644
- Close #7644
> fix(report): Fix invalid URI in SARIF report

- pkg/fanal/analyzer/pkg/rpm/archive.go
- pkg/fanal/analyzer/pkg/rpm/archive_test.go
If arch is not included in the PURL, the CycloneDX BOM-Ref will conflict and the UUID will be used.
```
$ TRIVY_EXPERIMENTAL_RPM_ARCHIVE=true ./trivy fs -q /tmp/rhel7 -f cyclonedx | jq '.components[]."bom-ref"'
"1b4f1e8d-5ab2-4cc1-82ee-e6a3e1c01d0f"
"3d5fbe66-61ae-4e94-99a3-a0733bb02f23"
"40b75c7a-c905-4705-bb0e-1d10a928100b"
"6945ac93-e8ea-4206-86e2-d9ecc535a831"
"6a99e954-0bab-400b-b1cb-41aa05e0d98a"
"d20ed80e-2bb9-4b31-87cf-29effae1f56b"
"f11347f2-5bd0-44c7-9bdf-a675e34348a9"
"pkg:rpm/redhat/ant@1.9.4-2.el7"
"pkg:rpm/redhat/audispd-plugins@2.8.5-4.el7"
"pkg:rpm/redhat/audit@2.8.5-4.el7"
"pkg:rpm/redhat/bind-chroot@32%3A9.11.4-26.P2.el7"
"pkg:rpm/redhat/bind@32%3A9.11.4-26.P2.el7"
"pkg:rpm/redhat/binutils@2.27-44.base.el7"
"pkg:rpm/redhat/cpio@2.11-28.el7" …
```
> fix(redhat): include arch in PURL qualifiers

- pkg/fanal/artifact/repo/git.go
This ensures that `git clone` output is directed to `os.Stderr` instead of `os.Stdout`.  Test added to demonstrate that stdout is empty after clone.
- Close #7547
> fix(repo): `git clone` output to Stderr

- docs/docs/configuration/reporting.md
The list format is broken in https://aquasecurity.github.io/trivy/dev/docs/configuration/reporting/#sarif since an empty line is required before the list.
The markdown parser used for Trivy documentation is stricter than the one used by GitHub.
The list punctuation is also now more consistent in the document.
- #7655
> docs(report): fix reporting doc format

- docs/docs/references/configuration/cli/trivy_sbom.md
- pkg/commands/app.go
Enable registry option also in SBOM command to download DBs stored in private registry
> fix(sbom): add options for DBs in private registries

- contrib/Trivy.gitlab-ci.yml
- docs/docs/advanced/private-registries/index.md
- docs/docs/references/configuration/cli/trivy.md
- docs/docs/references/configuration/cli/trivy_auth.md
- docs/docs/references/configuration/cli/trivy_auth_login.md
- docs/docs/references/configuration/cli/trivy_auth_logout.md
- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_sbom.md
- docs/docs/references/configuration/cli/trivy_server.md
- docs/docs/references/configuration/config-file.md
- docs/docs/target/container_image.md
- go.mod
- integration/registry_test.go
- mkdocs.yml
- pkg/commands/app.go
- pkg/commands/auth/run.go
- pkg/commands/auth/run_test.go
- pkg/flag/registry_flags.go
We have seen several use cases where people want to use Trivy in environments withoug container runtimes such as Docker. This PR adds `trivy auth login` and `trivy auth logout` to replace `docker login` and `docker logout`.
```
$ cat ~/my_password.txt | trivy auth login --username foo --password-stdin ghcr.io
$ trivy image ghcr.io/your/private_image
$ trivy auth logout ghcr.io
```
> feat(cli): add `trivy auth`

- pkg/commands/clean/run.go
- pkg/commands/clean/run_test.go
See #7703 
- Close https://github.com/aquasecurity/trivy/issues/7703
> fix(cli): `clean --all` deletes only relevant dirs

- docs/getting-started/installation.md
This package contains nothing of value since at least Focal/20.04:
https://packages.ubuntu.com/focal/all/apt-transport-https/filelist:
```
/usr/share/doc/apt-transport-https/NEWS.Debian.gz
/usr/share/doc/apt-transport-https/changelog.gz
/usr/share/doc/apt-transport-https/copyright
```
> docs: apt-transport-https is a transitional package

- contrib/Trivy.gitlab-ci.yml
- docs/docs/advanced/private-registries/index.md
- docs/docs/references/configuration/cli/trivy.md
- docs/docs/references/configuration/cli/trivy_registry.md
- docs/docs/references/configuration/cli/trivy_registry_login.md
- docs/docs/references/configuration/cli/trivy_registry_logout.md
- docs/docs/target/container_image.md
- integration/registry_test.go
- mkdocs.yml
- pkg/commands/app.go
Following the conversation in https://github.com/aquasecurity/trivy/pull/7664
> feat(cli): rename `trivy auth` to `trivy registry`

- pkg/iac/adapters/arm/storage/adapt.go
- pkg/iac/adapters/arm/storage/adapt_test.go
- pkg/iac/adapters/terraform/azure/storage/adapt.go
- pkg/iac/adapters/terraform/azure/storage/adapt_test.go
- pkg/iac/providers/azure/storage/storage.go
- pkg/iac/rego/schemas/cloud.json
The check will be fixed in trivy-checks
- Close https://github.com/aquasecurity/trivy/issues/6459
> feat(misconf): public network support for Azure Storage Account

- docs/docs/target/container_image.md
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/misconf/scanner.go
```bash
./trivy image --scanners misconfig --image-config-scanners misconfig registry.access.redhat.com/ubi8/python-312:1-16.1721725207
2024-10-14T14:57:39+06:00       INFO    [image] Container image config scanners scanners=[misconfig]
2024-10-14T14:57:39+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2024-10-14T14:57:41+06:00       INFO    Check disabled  ID="DS016" scanner="history-dockerfile" reason="See https://github.com/aquasecurity/trivy/issues/7368"
...
```
Related PRs:
- https://github.com/aquasecurity/trivy/pull/7540
> docs: add note about disabled DS016 check

- pkg/iac/adapters/terraform/google/sql/adapt.go
- pkg/iac/adapters/terraform/google/sql/adapt_test.go
- pkg/iac/providers/google/sql/sql.go
- pkg/iac/rego/schemas/cloud.json
This PR adds support for the ssl_mode attribute. The check will be fixed in trivy-checks.
- https://github.com/aquasecurity/trivy/issues/7565
> feat(misconf): ssl_mode support for GCP SQL DB instance

- pkg/iac/adapters/terraform/digitalocean/spaces/adapt.go
- pkg/iac/adapters/terraform/digitalocean/spaces/adapt_test.go
The [acl](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/spaces_bucket#acl) attribute of the `digitalocean_spaces_bucket` resource is [set](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/spaces/resource_spaces_bucket.go#L59) to `private` by default.
> fix(misconf): change default ACL of digitalocean_spaces_bucket to private

- pkg/iac/adapters/cloudformation/aws/ec2/adapt_test.go
- pkg/iac/scanners/cloudformation/parser/property_conversion.go
This PR fixes the panic of trying to convert a property that is missing from the template.
Template:
```yaml
---
AWSTemplateFormatVersion: 2010-09-09
Description: Godd example of excessive ports
Resources: 
NetworkACL:
Type: AWS::EC2::NetworkAcl
Rule:
Type: AWS::EC2::NetworkAclEntry
Properties:
NetworkAclId:
Ref: NetworkACL
```
Output:
```bash
trivy conf main.yaml
2024-09-23T23:28:45+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xe0 pc=0x10363f0c4]
goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/iac/scanners/cloudformation/parser.(*Property).Type(...)
/home/runner/work/trivy/trivy/pkg/iac/scanners/cloudformation/parser/property.go:10 …
```
> fix(misconf): check if property is not nil before conversion

- pkg/dependency/parser/java/pom/parse.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/pom.go
- pkg/dependency/parser/java/pom/testdata/inherit-scopes-from-child-deps-and-their-parents/pom.xml
- pkg/dependency/parser/java/pom/testdata/inherit-scopes-in-children-from-root/pom.xml
- pkg/dependency/parser/java/pom/testdata/inherit-scopes-in-parents-from-root/parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/inherit-scopes-in-parents-from-root/pom.xml
- pkg/dependency/parser/java/pom/testdata/inherit-scopes-in-parents-of-children-from-root/parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/inherit-scopes-in-parents-of-children-from-root/pom.xml
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-nested-scope-compile/1.0.0/example-nested-scope-compile-1.0.0.pom
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-nested-scope-compile/1.0.0/parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-nested-scope-empty/1.0.0/example-nested-scope-empty-1.0.0.pom
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-nested-scope-empty/1.0.0/parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-nested-scope-runtime/1.0.0/example-nested-scope-runtime-1.0.0.pom
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-nested-scope-runtime/1.0.0/parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-scope-compile/2.0.0/example-scope-compile-2.0.0.pom
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-scope-empty/2.0.0/example-scope-empty-2.0.0.pom
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-scope-runtime/2.0.0/example-scope-runtime-2.0.0.pom
- pkg/dependency/parser/java/pom/testdata/transitive-parents/base/pom.xml
- pkg/dependency/parser/java/pom/testdata/use-child-dep-management-in-parent/parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/use-child-dep-management-in-parent/pom.xml
- pkg/dependency/parser/java/pom/testdata/use-child-dep-management-in-parent/top-parent/pom.xml
Forward `dependencyManagement` and `Properties` field  from root/upper POM into parents.
`dependencyManagement` should be used as non-root dependencyManagement
See new test for more details.
- Close #7539
> fix(java): correctly inherit `version` and `scope` from upper/root `depManagement` and `dependencies` into parents

- integration/testimages.ini
- pkg/attestation/attestation_test.go
The GHCR rate limits are applied to the entire `aquasecurity` organization, and currently the images for testing cannot be pulled, causing testing to fail. As a workaround, we are considering moving trivy-db to a separate organization or creating a separate organization for Trivy, but both of these measures need to be done after careful discussion with GitHub. So we will use the forked image as a temporary workaround until a solution is decided.
- https://github.com/aquasecurity/trivy/pull/7739
> test: use forked images

- pkg/dependency/parser/java/pom/artifact.go
- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/pom.go
- pkg/dependency/parser/java/pom/testdata/with-spaces/pom.xml
This PR modifies the `pom.xml` parser so that the content of the fields are trimmed. It makes the parser behave in the same manner as maven.
- Close #7658
> feat(parser): ignore white space in pom.xml files

- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/kubernetes/parser/parser.go
- pkg/iac/scanners/kubernetes/scanner.go
- pkg/iac/scanners/kubernetes/scanner_test.go
In this PR:
- k8s scanner uses a generic scanner
- k8s parser simplified, now it's just 1 function
- duplicate tests were removed, large checks were replaced by compact ones
> refactor(misconf): simplify k8s scanner

- pkg/iac/adapters/arm/storage/adapt.go
- pkg/iac/adapters/arm/storage/adapt_test.go
1. `networkAcls` is an object, not a list.
2. `bypass` may contain multiple values separated by commas and may contain spaces. Spaces must be removed.
Doc: https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-arm-template
> fix(misconf): fix for Azure Storage Account network acls adaptation

- pkg/iac/scanners/terraform/module_test.go
- pkg/iac/scanners/terraform/parser/evaluator.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/attribute.go
- pkg/iac/terraform/block.go
This PR separates the logic for expanding dynamic blocks from expanding the `for-each` meta argument. 
- Close https://github.com/aquasecurity/trivy/issues/7611
- Close https://github.com/aquasecurity/trivy/issues/7586
> fix(misconf): properly expand dynamic blocks

- pkg/licensing/normalize.go
- pkg/licensing/normalize_test.go
"Universal Permissive License, Version 1.0" could not be normized because of the "v" in Permissive.
- None
> fix(license): fix license normalization for Universal Permissive License

- pkg/k8s/scanner/io.go
- pkg/k8s/scanner/io_test.go
- pkg/k8s/scanner/scanner.go
Trivy kubernetes scan tries to process the k8s configs in parallel.
but this leads to large overhead, due to initialize the scanner for each file separately (it needs to read rego policies).
This PR stores all k8s config in the same folder and scan this one at once.
it gives a boost about 9 times on my test minikube instance.
Before 
```sh
$ time trivy k8s --report all --skip-images -f json -o result.json
2024-10-10T10:12:01+06:00	INFO	Node scanning is enabled
2024-10-10T10:12:01+06:00	INFO	If you want to disable Node scanning via an in-cluster Job, please try '--disable-node-collector' to disable the Node-Collector job.
235 / 235 [-----------------------------------------------------------------------------------------------------------------] 100.00% 3 p/s
trivy k8s --report all …
```
> refactor(k8s): scan config files as a folder

- pkg/flag/rego_flags.go
An alias without a config name was added when the `skip-policy-update` flag was renamed, this caused the configuration tests ([TestConfiguration](https://github.com/aquasecurity/trivy/blob/main/integration/config_test.go#L76)) that used the old config to stop skipping the checks update.
> fix(cli): add config name to skip-policy-update alias

- integration/testdata/conda-spdx.json.golden
- integration/testdata/julia-spdx.json.golden
- integration/testdata/license-cyclonedx.json.golden
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_test.go
- pkg/sbom/spdx/testdata/happy/bom.json
- pkg/sbom/spdx/unmarshal.go
use `Annotation` instead of `AttributionTexts` for package properties.
examples:
- Packages:
before:
```
"attributionTexts": [
"PkgType: conda-pkg"
],
```
after:
```
"annotations": [
{
"annotator": "Tool: trivy-dev",
"annotationDate": "2021-08-25T12:20:30Z",
"annotationType": "OTHER",
"comment": "PkgType: conda-pkg"
}
]
```
- ContainerImage:
Before:
```
"attributionTexts": [
"SchemaVersion: 2",
"ImageID: sha256:49193a2310dbad4c02382da87ac624a80a92387a4f7536235f9ba590e5bcd7b5",
"DiffID: sha256:dd565ff850e7003356e2b252758f9bdc1ff2803f61e995e24c7844f6297f8fc3",
"RepoTag: maven-test-project:latest",
],
```
After:
```
"annotations": [
{
"annotator": "Tool: trivy-dev",
"annotationDate": "2024-10-29T06:50:38Z",
"annotationType": "OTHER",
"comment": "SchemaVersion: 2"
},
{
"annotator": "Tool: …
```
> fix(sbom):  use `Annotation` instead of `AttributionTexts` for `SPDX` formats

- docs/docs/coverage/language/java.md
Trivy doesn't check all `scopes`:
https://github.com/aquasecurity/trivy/blob/57e24aa85382f749df7f673e241caaf3fcbb45cb/pkg/dependency/parser/java/pom/parse.go#L430
We need to write about this in the docs.
> docs(java): add info about supported scopes

- pkg/oci/artifact.go
We should show the rate limit detail in the fatal error. Some users don't read log messages, and `--quiet` shows only a fatal log.
```
$ trivy image debian:12 --quiet
2024-10-31T14:09:06+04:00       FATAL   Fatal error     init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source
```
```
$ trivy image debian:12 --quiet
2024-10-31T14:08:14+04:00       FATAL   Fatal error     init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source: 1 error occurred:
* oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:ba0d01953a8c28331552412292b72f3639b …
```
> feat(db): append errors

- misc/lint/rules.go
- pkg/iac/scanners/cloudformation/parser/parser.go
- pkg/iac/terraform/block.go
- pkg/report/writer.go
- pkg/vex/repo/repo.go
`hashicorp/go-multierror.Append` displays more user-friendly errors than `errors.Join`.
https://go.dev/play/p/AYls8a96t-j
```
[errors.Join]
err1
err2
[go-multierror.Append]
2 errors occurred:
* err1
* err2
```
This PR adds a new lint rule as the usage should be consistent in the project.
- https://github.com/aquasecurity/trivy/pull/7843
> chore: lint `errors.Join`

- pkg/fanal/secret/scanner.go
This PR optimizes the performance of the keyword matching function by eliminating redundant ToLower operations inside the loop. Previously, content was being converted to lowercase in every loop iteration, which was inefficient. The change moves this operation outside the loop and stores the result in a variable for reuse.
Before:
```go
for _, kw := range r.Keywords {
if bytes.Contains(bytes.ToLower(content), []byte(strings.ToLower(kw))) {
return true
}
}
```
After
```
contentLower = bytes.ToLower(content)
for _, kw := range r.Keywords {
if bytes.Contains(contentLower, []byte(strings.ToLower(kw))) {
return true
}
}
```
> refactor(secret): optimize performance by moving ToLower operation outside loop

- go.mod
- go.sum
This PR introduces a default command handler for unknown Kubernetes platforms, such as Azure Kubernetes Service (AKS). When the platform type is unrecognized, the system will now return commands for Kubernetes (`k8s` type).
- Close #7786 
- https://github.com/aquasecurity/trivy-kubernetes/pull/409
> feat(k8s): add default commands for unknown platform

- go.mod
- go.sum
bump go-version to incorporate aquasecurity/go-version#8
- aquasecurity/go-version#7
> fix: Improve version comparisons when build identifiers are present

- pkg/fanal/artifact/local/fs.go
Trivy appears to be leaking `/tmp/analyzer-fs-*` directories when using FS artifacts.
This PR adds the call to `Cleanup()` that is already done in VM and Image artifacts.
> fix(fs): add missing defered Cleanup() call to post analyzer fs

- pkg/iac/scanners/cloudformation/parser/file_context.go
- pkg/iac/scanners/cloudformation/parser/parser.go
- pkg/iac/scanners/cloudformation/parser/parser_test.go
- Close https://github.com/aquasecurity/trivy/issues/7809
> fix(misconf): handle null properties in CloudFormation templates

- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_test.go
This adds a default null value for variables that don't  get a value (either supplied or default).
It allows expressions using those variables to be evaluated, rather than just be set to null.
E.g
```terraform
variable "v" {
type = string
}
locals {
l = ["foo", var.v]
d = {"foo": var.v}
}
```
would produce `l = ["foo" null]` and `d = {"foo": null}` rather than just being both `null`.
> fix(terraform): set null value as fallback for missing variables

- pkg/k8s/commands/run.go
Discussed in #6932 
In short, progress bar may lead someone(like me) confused. It show the download progress or scan image progress or scan K8s progress.
- Close #6996
> chore(k8s): enhance k8s scan log

- pkg/report/sarif.go
- pkg/report/sarif_private_test.go
- pkg/report/sarif_test.go
Overwrite `git@github.com` schema for misconfigs in `sarif` report.
- Close #7897
> fix(report): handle `git@github.com` schema for misconfigs in `sarif` report

- docs/ecosystem/ide.md
Add Trivy Headlamp plugin to eco docs
- [x ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
> docs: add Headlamp to the Trivy Ecosystem page

- pkg/fanal/analyzer/buildinfo/content_manifest.go
- pkg/fanal/analyzer/buildinfo/content_manifest_test.go
- pkg/fanal/analyzer/buildinfo/testdata/content_manifests/sbom-purl.json
We return empty `BuildInfo` if `root/buildinfo/content_manifests/*.json` doesn't contain contentSets.
But if `root/buildinfo/content_manifests/` doesn't have file with contentSets - we return error (because we don't use default contentSets)
That is why we need to return `nil` if contentSets are not found.
See #7911 to get example.
- Close #7911
> fix(redhat): don't return error if `root/buildinfo/content_manifests/` contains files that are not `contentSets` files

- pkg/k8s/report/report.go
- pkg/k8s/report/report_test.go
Previously, vulnerabilities were checked only for the first result of a resource. Now, all results are scanned.
Before
```sh
┌───────────┬──────────────────┬───────────────────┬───────────────────┬───────────────────┐
│ Namespace │     Resource     │  Vulnerabilities  │ Misconfigurations │      Secrets      │
│           │                  ├───┬───┬───┬───┬───┼───┬───┬───┬───┬───┼───┬───┬───┬───┬───┤
│           │                  │ C │ H │ M │ L │ U │ C │ H │ M │ L │ U │ C │ H │ M │ L │ U │
├───────────┼──────────────────┼───┼───┼───┼───┼───┼───┼───┼───┼───┼───┼───┼───┼───┼───┼───┤
│ test      │ Pod/postgres-pod │   │   │   │   │   │   │ 1 │ 4 │ 9 │   │   │   │   │   │   │
└───────────┴──────────────────┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┘ …
```
> fix(k8s): check all results for vulnerabilities

- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_vm.md
- docs/docs/references/configuration/config-file.md
- pkg/policy/policy.go
Merge once trivy-checks is available on DockerHub.
> fix(misconf): Update trivy-checks default repo to `mirror.gcr.io`

- docs/docs/coverage/language/index.md
- docs/docs/coverage/others/index.md
- mkdocs.yml
Add overview page for `others`
> docs: add `overview` page for `others`

- pkg/dependency/parser/golang/binary/parse.go
- pkg/dependency/parser/golang/binary/parse_test.go
- pkg/fanal/analyzer/language/golang/binary/binary_test.go
The construction of the relationship between the root package and direct dependencies is now done by the SBOM package, etc.
https://github.com/aquasecurity/trivy/blob/542a3808239e08a41087f8af531efe8762958f29/pkg/sbom/io/encode.go#L420-L462
However, since the logic has become complicated, it should be changed to be done on the analyzer side (strictly speaking, on the parser side) for the sake of simplification.
- https://github.com/aquasecurity/trivy/pull/7889
> feat(go): construct dependencies in the parser

- pkg/dependency/parser/golang/mod/parse.go
- pkg/dependency/parser/golang/mod/parse_test.go
- pkg/dependency/parser/golang/mod/parse_testcase.go
- pkg/fanal/analyzer/language/golang/mod/mod.go
- pkg/fanal/analyzer/language/golang/mod/mod_test.go
- pkg/fanal/analyzer/language/golang/mod/testdata/no-pkg-found/mod
- pkg/vex/vex.go
> feat(go): construct dependencies of `go.mod` main module in the parser

- pkg/iac/scanners/terraform/parser/evaluator.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/block.go
Example config:
```hcl
module "aws-rds" {
source         = "terraform-aws-modules/rds/aws"
version        = "~> 6.10.0"
identifier     = "mydb"
engine         = "postgres"
family         = "postgres13"
instance_class = "db.t4g.medium"
}
```
Before:
```
trivy conf -d . > log1.txt 2>&1
cat log1.txt |grep "Failed to expand"
2024-11-18T20:36:26+06:00       ERROR   [terraform evaluator] Failed to expand block. Invalid "for-each" argument. Must be known and iterable.  block="module.aws-rds.module.db_instance.dynamic.restore_to_point_in_time" value="cty.NilVal"
2024-11-18T20:36:26+06:00       ERROR   [terraform evaluator] Failed to expand block. Invalid "for-each" argument. Must be known and iterable.  block="module.aws-rds.module.db_instance.dynamic.s3_import" value="cty.NilVal" …
```
> fix(misconf): do not erase variable type for child modules

- pkg/iac/scanners/terraform/parser/evaluator.go
This PR lowers the message level when a block expand error occurs.
> chore: downgrade the failed block expand message to debug

- go.mod
- go.sum
- pkg/vex/csaf.go
- pkg/vex/document.go
This pull request migrates the dependency from csaf-poc/csaf_distribution to the new gocsaf/csaf module. The `csaf-poc/csaf_distribution` module has been moved to the official `gocsaf/csaf` repository, and as part of this update, the go.mod file has been modified to reflect the new module source.
- Close #7805
> chore(deps): update csaf module dependency from csaf-poc to gocsaf

- internal/testutil/util.go
- pkg/iac/scanners/terraform/count_test.go
- pkg/iac/scanners/terraform/deterministic_test.go
- pkg/iac/scanners/terraform/ignore_test.go
- pkg/iac/scanners/terraform/json_test.go
- pkg/iac/scanners/terraform/module_test.go
- pkg/iac/scanners/terraform/options.go
- pkg/iac/scanners/terraform/scanner_integration_test.go
- pkg/iac/scanners/terraform/scanner_test.go
- pkg/iac/scanners/terraform/setup_test.go
- pkg/iac/scanners/terraform/wildcard_test.go
Part of https://github.com/aquasecurity/trivy/issues/7718
> test: replace Go checks with Rego

- pkg/iac/scanners/terraform/parser/resolvers/cache_integration_test.go
- pkg/iac/scanners/terraform/parser/resolvers/options.go
- pkg/iac/scanners/terraform/parser/resolvers/registry.go
- pkg/iac/scanners/terraform/parser/resolvers/registry_integration_test.go
- pkg/iac/scanners/terraform/parser/resolvers/remote.go
- pkg/iac/scanners/terraform/parser/resolvers/testdata/terraform-aws-s3-bucket/README.md
- pkg/iac/scanners/terraform/parser/resolvers/testdata/terraform-aws-s3-bucket/modules/notification/README.md
- pkg/iac/scanners/terraform/parser/resolvers/testdata/terraform-aws-s3-bucket/modules/object/README.md
Script for preparing repositories:
```bash
#!/usr/bin/env bash
readonly num_repos=100
readonly repos=$(
gh repo list "cloudposse" -L $num_repos --json nameWithOwner,name | \
jq '[ .[] | select(.name | startswith("terraform-aws")) ]'
)
mkdir -p aws
while read repo
do
name=$(echo "$repo" | jq -r .name)
nameWithOwner=$(echo "$repo" | jq -r .nameWithOwner)
target=aws/$name
if [ -d $target ]; then
echo $name already exists
continue
fi
mkdir -p $target
git clone https://github.com/$nameWithOwner $target
done < <(echo "$repos" | jq -c '.[]')
```
First run to create the cache:
```bash
❯ rm -rf $TMPDIR/.aqua/cache
❯ ./trivy conf . -d --timeout 1h > log.txt 2>&1
❯ cat log.txt | grep "Module resolved from cache" | wc -l
5595
❯ cat log.txt |grep "Downloading module" |wc -l
328
```
Re-run using the …
> fix(misconf): load full Terraform module

- pkg/flag/report_flags_test.go
- pkg/result/ignore.go
- pkg/result/ignore_test.go
Also adds a log message to the debug stream when such a case occurs.
```shell
trivy --debug config --ignorefile ./invalid-file.yaml  /tmp
<snip>
2024-11-19T23:55:01-07:00       DEBUG   Specified ignore file does not exist        file="./invalid-file.yaml"
</snip>
```
- Fixes: https://github.com/aquasecurity/trivy/issues/7934
> fix(cli): Handle empty ignore files more gracefully

- pkg/sbom/io/encode.go
- pkg/sbom/io/encode_test.go
Refactor relationship generation in SBOM
- Blocked by
- https://github.com/aquasecurity/trivy/pull/7889
> refactor(sbom): simplify relationship generation

- docs/docs/references/terminology.md
- mkdocs.yml
This PR adds a new terminology page that documents the key concepts and terms used in Trivy. 
The page covers core components, scanning features, and infrastructure elements.
Note: The term "Scan Assets" is newly introduced in this PR to collectively refer to external data that Trivy downloads and uses during scanning (e.g., vulnerability database, Java database, checks bundle).
The goal is to provide a single source of truth for Trivy terminology and help users better understand the project's architecture and components.
> docs: add terminology page to explain Trivy concepts

- pkg/iac/rego/metadata.go
- pkg/iac/rego/scanner.go
- pkg/iac/rego/scanner_test.go
- pkg/iac/scan/flat.go
- pkg/iac/scan/result.go
- pkg/misconf/scanner.go
These options aren't often used due to reasons described in the [disucussion](https://github.com/aquasecurity/trivy/discussions/7961) and can be deprecated.
- Close https://github.com/aquasecurity/trivy/issues/7849
- https://github.com/aquasecurity/trivy/discussions/7961
> refactor(misconf): Remove unused options

- pkg/iac/adapters/cloudformation/aws/ecs/ecs_test.go
- pkg/iac/adapters/cloudformation/aws/ecs/task_definition.go
- pkg/iac/adapters/terraform/aws/ecs/adapt_test.go
- pkg/iac/providers/aws/ecs/ecs.go
EnvVar fields had primitive Go types that were not exported to Rego.
- https://github.com/aquasecurity/trivy-checks/pull/274
> fix(misconf): wrap AWS EnvVar to iac types

- pkg/iac/scanners/cloudformation/parser/property_conversion.go
This PR fixes logging when a property conversion fails, which could not be suppressed with the `quiet` flag.
Before:
```bash
property of type map cannot be converted to int
```
After:
```bash
2024-12-03T16:25:00+06:00       DEBUG   Failed to convert property      from="map" to="int" range="template.yaml:7-8"
```
> fix(misconf): use log instead of fmt for logging

- pkg/dependency/parser/java/pom/parse_test.go
- pkg/dependency/parser/java/pom/pom.go
- pkg/dependency/parser/java/pom/testdata/repository/org/example/example-dependency/1.7.30/example-dependency-1.7.30.pom
- pkg/dependency/parser/java/pom/testdata/root-pom-dep-management-for-deps-with-project-props/pom.xml
We should use resolved dependencies (with replaceable properties) to find dependencies in depManagements.
example:
pom file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.bbb.aaa</groupId>
<artifactId>aaa</artifactId>
<version>1.0.0</version>
<packaging>pom</packaging>
<name>aaa</name>
<description>desc</description>
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>3.2.11</version>
<relativePath />
</parent>
<dependencyManagement>
<dependencies>
<dependency> …
```
> fix(java): correctly overwrite version from depManagement if dependency uses `project.*` props

- pkg/commands/artifact/run.go
- pkg/flag/options.go
Currently we include all flags in the default config.
But Trivy returns an error for removed flags.
Unfortunately `viper` has no options to remove flags, so we need to reset viper and add the required flags to `--generate-default-config`
Before:
```
➜  trivy image --generate-default-config && cat trivy-default.yaml | grep reset
2024-12-04T17:35:49+06:00       INFO    Writing the default config to trivy-default.yaml...
reset-checks-bundle: false
reset: false
```
After:
```                                                             
➜  ./trivy image --generate-default-config && cat trivy-default.yaml | grep reset
2024-12-04T17:36:18+06:00       INFO    Writing the default config to trivy-default.yaml...
```
- Close #8043
> fix(flag): skip hidden flags for `--generate-default-config` command

- pkg/fanal/analyzer/sbom/sbom.go
- pkg/fanal/analyzer/sbom/sbom_test.go
We don't save `FilePath` for app with aggregatedTypes.
That is why we overwrite apps with same types.
See more in #7851
This PR adds filepath (path to the SBOM file) for Apps got from SBOM analyzer.
This helps with overwriting when merging layers.
Example:
```Dockerfile
FROM alpine
COPY ./api/report-api.spdx.json /api/report-api.spdx.json
COPY ./core/report-core.spdx.json /core/report-core.spdx.json
```
before:
```bash
➜ trivy -q image test:7846 -f json --list-all-pkgs --pkg-types library --cache-backend memory | grep -E '"ID"|"FilePath"'
"ID": "org.apache.logging.log4j:log4j-core:2.24.1",
"FilePath": "log4j-core-2.24.1.jar"
```
after:
```bash
➜ ./trivy -q image test:7846 -f json --list-all-pkgs --pkg-types library --cache-backend memory | grep -E '"ID"|"FilePath"'
"ID": …
```
> fix(sbom): fix wrong overwriting of applications obtained from different sbom files but having same app type

- pkg/iac/scanners/terraform/scanner_test.go
- pkg/iac/terraform/presets.go
- Close https://github.com/aquasecurity/trivy/issues/5357
> feat(misconf): generate placeholders for random provider resources

- pkg/oci/artifact.go
We found that `GCR` periodically returns `BLOW_UNKNOWN` error - #8020
We assume that this is related to their cache.
But in any case, we need to handle this error and check other repositories if loading a repository returns `BLOW_UNKNOWN` error.
> fix: handle `BLOW_UNKNOWN` error to download DBs

- docs/docs/target/kubernetes.md
Now #7444  is merged, we should clarify the position about association the result with the metadata for multi-container pdos. this PR adds a small note about it.
> docs(k8s): add a note about multi-container pods

- pkg/detector/ospkg/redhat/redhat.go
- pkg/detector/ospkg/redhat/redhat_test.go
- pkg/detector/ospkg/redhat/testdata/fixtures/redhat.yaml
Rewriting advisories for the same vulnerability is currently tied to the advisory order.
See #8061 and new tests for more details
This PR sets the order for advisories and fixes overwriting of advisories for the same vulnerability.
Example:
before:
```bash
➜  trivy -q image registry.access.redhat.com/ubi8/ubi --cache-backend memory | grep expat
│ expat                       │ CVE-2022-23990   │ MEDIUM   │                     │ 2.2.5-16.el8_10       │                 │ expat: integer overflow in the doProlog function             │
│                             │ CVE-2024-45491   │          │                     │                       │                 │ libexpat: Integer Overflow or Wraparound                     │
│                             │ CVE-2024-45492   │          │ …
```
> fix(redhat): correct rewriting of recommendations for the same vulnerability

- pkg/licensing/normalize.go
- pkg/licensing/normalize_test.go
See #8094
example:
test pom.xml file:
```xml
<licenses>
<license>
<name>
Dual license consisting of the CDDL v1.1 and GPL v2
</name>
<url>https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html</url>
<distribution>repo</distribution>
</license>
</licenses>
```
Before:
```bash
➜ trivy -q fs --scanners license /Users/dmitriy/work/tmp/8086/pom.xml -f json | grep '"Name"'
"Name": "\n                Dual license consisting of the CDDL v1.1 and GPL v2\n            ",
"Name": "CDDL-1.0",
```
After:
```bash
➜ ./trivy -q fs --scanners license /Users/dmitriy/work/tmp/8086/pom.xml -f json | grep '"Name"'
"Name": "Dual license consisting of the CDDL v1.1 and GPL v2",
"Name": "CDDL-1.0",
```
- Close #8094
> fix(license): always trim leading and trailing spaces for licenses

- go.mod
- go.sum
Bump `github.com/CycloneDX/cyclonedx-go` from `v0.9.1` to `v0.9.2`
This version includes fix for decoding `Component.Evidence.Identity` field.
- https://github.com/aquasecurity/trivy/issues/6902#issuecomment-2436379999
> chore(deps): bump `github.com/CycloneDX/cyclonedx-go` from `v0.9.1` to `v0.9.2`

- integration/repo_test.go
Tests for `nuget` may fail if the packages used in the tests are located on the developer's machine in the ~/.nuget/packages or `NUGET_PACKAGES` directory, since the analyser uses this directory to search for licenses:
```bash
--- FAIL: TestRepository (8.14s)
--- FAIL: TestRepository/nuget (0.01s)
/Users/nikita/projects/trivy/integration/integration_test.go:304: 
...
-     Licenses: ([]string) <nil>,
+     Licenses: ([]string) (len=1) {
+      (string) (len=3) "MIT"
+     },
...
```
This PR sets a dummy value for the `NUGET_PACKAGES` environment variable.
> test: set dummy value for NUGET_PACKAGES

- integration/testdata/fluentd-multiple-lockfiles.cdx.json.golden
- integration/testdata/julia-spdx.json.golden
- integration/testdata/npm-cyclonedx.json.golden
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/io/encode.go
- pkg/sbom/io/encode_test.go
Use root package for `unknown` dependencies (if exists)
e.g. for GoBinaries (see update test).
See #8102 for more details.
Also this PR fixes problem with VEX with subcomponents:
before:
```bash
➜ trivy -q i -s HIGH,CRITICAL --vex repo --cache-backend memory --pkg-types library --show-suppressed rancher/fleet:v0.10.2
usr/bin/fleet (gobinary)
Total: 1 (HIGH: 0, CRITICAL: 1)
┌─────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────┐
│       Library       │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                         Title                          │
├─────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼──────────────────── …
```
> fix(sbom): use root package for `unknown` dependencies (if exists)

- docs/docs/supply-chain/vex/file.md
To ensure the examples continue to work, we must use Debian images with a specific minor version (e.g. `debian:11.8`).
> docs(vex): use debian minor version in examples

- pkg/dependency/parser/python/packaging/parse.go
See #8160
Before:
```bash
2024-12-25T12:00:53+06:00       INFO    [python] License acquired from METADATA classifiers may be subject to additional terms  name="pip" version="24.2"
2024-12-25T12:00:53+06:00       INFO    [python] License acquired from METADATA classifiers may be subject to additional terms  name="autocommand" version="2.2.2"
2024-12-25T12:00:53+06:00       INFO    [python] License acquired from METADATA classifiers may be subject to additional terms  name="typeguard" version="4.3.0"
2024-12-25T12:00:53+06:00       INFO    [python] License acquired from METADATA classifiers may be subject to additional terms  name="mercurial" version="6.3.2"
```
After:
```bash
2024-12-25T12:01:29+06:00       INFO    [python] Licenses acquired from one or more METADATA files may be subject …
```
> refactor(python): use once + debug for `License acquired from METADATA...` logs

- docs/docs/configuration/reporting.md
Since, Trivy Open Source is currently using schema version 2 as discueed [here](https://github.com/aquasecurity/trivy/discussions/1050). But even after migrating to new change, the documentation still contains an [example](https://trivy.dev/v0.55/docs/configuration/reporting/#json) which shows result in older schema version 1. 
This PR addresses the JSON schema version change to 2 in Trivy documentaion. With the changes made in this PR, the trivy documentation page is showing example in updated schema version.
- [Close #7553](https://github.com/aquasecurity/trivy/issues/7553)
> docs: Updated JSON schema version 2 in the trivy documentation

- pkg/iac/scanners/terraform/parser/resolvers/remote.go
- Close https://github.com/aquasecurity/trivy/issues/8023
> fix(misconf): disable git terminal prompt on tf module load

- pkg/fanal/analyzer/buildinfo/content_manifest.go
- pkg/fanal/analyzer/buildinfo/content_manifest_test.go
In RHCOS you don't have permissions to the `/root` directory. 
That's why in `RHCOS` the content set files are in `/usr/share/buildinfo/*.json`
- Close #8213
> fix(redhat): check `usr/share/buildinfo/` dir to detect content sets

- docs/docs/scanner/misconfiguration/index.md
- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/helm/test/scanner_test.go
- pkg/iac/scanners/helm/test/testdata/expected/options/testchart/templates/deployment.yaml
- pkg/iac/scanners/helm/test/testdata/expected/testchart/templates/deployment.yaml
- pkg/iac/scanners/helm/test/testdata/testchart/templates/deployment.yaml
This PR adds support for ignoring misconfigurations in Helm configurations.
- Close https://github.com/aquasecurity/trivy/issues/8198
> feat(misconf): support for ignoring by inline comments for Helm

- pkg/iac/scanners/terraform/parser/load_module.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/block.go
We should only use null values for variables to preserve the type when passing them to modules. 
- Close https://github.com/aquasecurity/trivy/issues/8093
> fix(misconf): allow null values only for tf variables

- pkg/compliance/spec/compliance.go
The `spec` package simply uses functions from the `specs` package, so we can use `specs` directly.
> refactor: use trivy-checks/pkg/specs package

- .github/workflows/release-pr-check.yaml
Added workflow to prevent direct PRs to release branches (release/v*)
- Fails if PR is created by non-aqua-bot user
- Includes documentation link about the backporting process in error message
I confirmed this workflow correctly failed PRs from other than aqua-bot, but I didn't have a token of aqua-bot. I didn't have an idea to test it.
https://github.com/knqyf263/trivy/pull/68
> ci: add workflow to restrict direct PRs to release branches

- pkg/iac/rego/metadata.go
- pkg/iac/scan/rule.go
Previously, examples for checks were stored in separate files for each provider. For example, the examples for Terraform `<name>` checks were in the `<name>.tf.go` file, and the examples for CloudFormation were in` <name>.cf.go`. With the discontinuation of support for Go checks, there is no longer a need to store examples in Go files as it makes them harder to retrieve. Therefore, the examples for each check have been moved from Go to YAML with a new schema:
```yaml
cloudformation:
good:
- |-
...
bad:
- |-
...
terraform:
good:
- |-
...
bad:
- |-
...
```
Currently, the check metadata includes fields for each provider with the same structure:
```
```
I have an idea to convert [test data](https://github.com/aquasecurity/trivy-checks/tree/main/test/testdata) for Dockerfile and Kubernetes …
> feat: add a examples field to check metadata

- docs/docs/scanner/misconfiguration/index.md
- pkg/iac/scanners/dockerfile/scanner_test.go
- pkg/iac/scanners/generic/scanner.go
Example config:
```Dockerfile
FROM scratch
MAINTAINER moby@example.com
```
Before:
```bash
❯ trivy conf Dockerfile.dev |grep "AVD-DS-0022"
2024-12-17T18:12:25+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2024-12-17T18:12:26+06:00       INFO    Detected config files   num=1
AVD-DS-0022 (HIGH): MAINTAINER should not be used: 'MAINTAINER moby@example.com'
```
After:
```bash
❯ ./trivy conf Dockerfile.dev |grep "AVD-DS-0022"
2024-12-17T18:12:14+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2024-12-17T18:12:15+06:00       INFO    Detected config files   num=1
```
- Close https://github.com/aquasecurity/trivy/issues/8113
> feat(misconf): support for ignoring by inline comments for Dockerfile

- docs/docs/configuration/others.md
- docs/docs/references/configuration/config-file.md
- magefiles/docs.go
- pkg/fanal/types/image.go
- pkg/flag/options.go
- pkg/flag/registry_flags.go
- pkg/remote/remote.go
- pkg/remote/remote_test.go
- added `registry.mirrors` flag (only for config file)
e.g. :
```
registry:
mirrors:
index.docker.io:
- harbor.example.com/docker.io
- mirror.gcr.io
```
- add logic to check mirrors. If can't get image from mirrors - check host registry.
- Close #7966
> feat: add support for registry mirrors

- pkg/iac/scanners/kubernetes/parser/manifest_node.go
- pkg/iac/scanners/kubernetes/parser/manifest_test.go
This PR includes the following changes:
- Added support for binary and timestamp tags.
- Added export of float node to Rego.
- Log unsupported tags instead of returning an error.
- Close https://github.com/aquasecurity/trivy/issues/8252
> fix(misconf): correctly handle all YAML tags in K8S templates

- integration/testdata/conda-cyclonedx.json.golden
- integration/testdata/conda-environment-cyclonedx.json.golden
- integration/testdata/pom-cyclonedx.json.golden
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/artifact/local/fs_test.go
- pkg/fanal/artifact/repo/git_test.go
This PR modifies the cache key generation logic to use UUID with SHA256 hash. This ensures uniqueness and consistency in cache keys while maintaining a standardized SHA256 format.
- Modified `calcCacheKey` function to generate SHA256 hash from UUID
- Updated test cases to use `SetFakeUUID` for consistent test results
- Fixed test failures by ensuring each test case sets its own UUID
- Close https://github.com/aquasecurity/trivy/issues/8280
> fix(fs): fix cache key generation to use UUID

- cmd/trivy/main.go
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/config-file.md
- docs/docs/target/container_image.md
- go.mod
- integration/docker_engine_test.go
- pkg/commands/artifact/run.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/image_test.go
- pkg/fanal/artifact/image/remote_sbom_test.go
- pkg/fanal/test/integration/registry_test.go
- pkg/fanal/types/image.go
- pkg/flag/image_flags.go
- pkg/flag/image_flags_test.go
- pkg/types/error.go
This PR adds the `--max-image-size` flag. If the flag is specified and the uncompressed image size exceeds the maximum size, Trivy exits with an error. If the flag is not specified, the behaviour does not change.
For more implementation details, see https://github.com/aquasecurity/trivy/issues/8176
- Close https://github.com/aquasecurity/trivy/issues/8176
> feat(image): prevent scanning oversized container images

- .golangci.yaml
- pkg/dependency/id.go
- pkg/flag/db_flags.go
- pkg/iac/scan/result.go
- pkg/iac/scanners/azure/functions/utc_now_test.go
- pkg/iac/scanners/cloudformation/parser/fn_sub.go
- pkg/iac/scanners/cloudformation/parser/property_conversion.go
- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/parser/funcs/datetime.go
- pkg/report/table/misconfig.go
- pkg/report/table/secret.go
- pkg/sbom/spdx/marshal.go
enable and fixes all rules from perfsprint linter
> chore: enable int-conversion from perfsprint

- pkg/iac/scanners/dockerfile/parser/parser.go
- pkg/iac/scanners/dockerfile/parser/parser_test.go
Heredocs allow redirection of subsequent Dockerfile lines to the input of RUN or COPY commands. Right now, Trivy does not handle heredocs in instructions and only exports the first line as an instruction value:
```bash
TRACE | | | Unify {"Cmd": "run", "EndLine": 4, "Flags": [], "JSON": false, "Original": "RUN <<EOF", "Path": "Dockerfile", "Stage": 0, "StartLine": 2, "SubCmd": "", "Value": ["<<EOF"]} = instruction
```
The following scenarios are taken into account:
1. If the first line in the heredoc is a shebang, the value of the command is the file containing the contents of the heredoc for execution.
2. In the case of a simple heredoc, its contents are converted into commands.
3. In other cases, the heredoc is exported as is.
Example Dockerfile:
```Dockerfile
FROM alpine:3.21
RUN <<EOF …
```
> fix(misconf): handle heredocs in dockerfile instructions

- docs/docs/scanner/misconfiguration/custom/index.md
[This](https://github.com/aquasecurity/trivy/pull/7884) PR removed the emoji extension, which broke the emoji display. This PR replaces short codes with unicode emoji, which are used throughout the documentation.
> docs: replace short codes with Unicode emojis

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
This PR includes the following changes:
- extracts config conversion to dockerfile into a separate function to facilitate testing
- adds support for buildkit metadata instructions, e.g. `env`, `arg`. Such commands show up in the history without the `# buildkit` suffix, so Trivy ignored them.
```bash
ENTRYPOINT ["/bin/sh" "-c" "echo test"]
RUN /bin/sh -c apk add $pkg # buildkit
```
- fixes the handling of `run` with build arguments
- Close https://github.com/aquasecurity/trivy/issues/8277
> fix: improve conversion of image config to Dockerfile

- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/terraform/attribute.go
- pkg/iac/terraform/block.go
The abstraction layer serves as a convient layer for handling 'Value()' outputs. If the return value is unknown, the underlying raw HCL is useful for additional diagnostics.
Similarly, to print out diagnostics, the underlying parser files are required for the raw source code.
> chore(terraform): add accessors to underlying raw hcl values

- docs/docs/target/container_image.md
- integration/docker_engine_test.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/image_test.go
- pkg/fanal/artifact/image/remote_sbom_test.go
This PR optimizes the image size check by returning an error if the total size of the layers exceeds the limit, without the need to load the entire image.
> feat(image): return error early if total size of layers exceeds limit

- pkg/fanal/analyzer/sbom/sbom.go
- pkg/fanal/analyzer/sbom/sbom_test.go
- pkg/fanal/analyzer/sbom/testdata/ca-certificates.spdx.json
This PR fixes a bug in the SBOM analyzer where OS packages from multiple SBOM files were being overwritten during the merge process.
No changes in usage. This is a bug fix in how Trivy handles OS packages from multiple SBOM files.
When scanning container images with multiple SBOM files containing OS packages, only the packages from the last processed SBOM remained in the final result. This was because OS packages didn't have a file path set, causing them to be overwritten during the merge process.
This PR fixes the issue by:
1. Setting the SBOM file path as the package file path for OS packages
2. This ensures packages from different SBOMs are preserved as distinct entries
For example, when scanning an image with these SBOM files:
- `/opt/bitnami/debian/.spdx-ca-certificates.spdx`
- …
> fix(sbom): preserve OS packages from multiple SBOMs

- pkg/iac/adapters/cloudformation/aws/ecs/cluster.go
- pkg/iac/adapters/cloudformation/aws/ecs/ecs_test.go
- pkg/iac/adapters/terraform/aws/ecs/adapt.go
- pkg/iac/adapters/terraform/aws/ecs/adapt_test.go
ECS released support for enhanced container insights in [December 2024](https://aws.amazon.com/blogs/aws/container-insights-with-enhanced-observability-now-available-in-amazon-ecs/) 
This adds a new value to the [containerInsights cluster setting](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ClusterSetting.html) `enhanced`. This PR includes the enhanced settings when considering if Container Insights is enabled. 
- Didn't have an issue as it was a minor issue
> fix(misconf): ecs include enhanced for container insights

- go.mod
bump Go to `v1.23.5`.
It fixes `CVE-2024-45341` and `CVE-2024-45336`:
```bash
➜ trivy -q image --pkg-types library aquasec/trivy:0.59.0
usr/local/bin/trivy (gobinary)
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 0, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬──────────────────────────────┬──────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │        Fixed Version         │                            Title                             │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼──────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-45336 │ MEDIUM   │ fixed  │ v1.23.4           │ 1.22.11, …
```
> chore(deps): bump Go to `v1.23.5`

- pkg/report/sarif.go
- pkg/report/sarif_test.go
> fix(report): remove html escaping for `shortDescription` and `fullDescription` fields for sarif reports

- .github/workflows/spdx-cron.yaml
We added cron workflow to check SPDX License exceptions (#8077).
But i forgot to install `aqua-installer`.
This PR added this step.
Test run - https://github.com/DmitriyLewen/trivy/actions/runs/13150768822/job/36697700228
> ci(spdx): add `aqua-installer` step to fix `mage` error

- docs/community/contribute/checks/overview.md
- docs/community/contribute/checks/service-support.md
- docs/docs/compliance/compliance.md
- docs/docs/compliance/contrib-compliance.md
- docs/docs/coverage/language/golang.md
- docs/docs/scanner/license.md
- docs/docs/scanner/misconfiguration/custom/index.md
- docs/docs/scanner/misconfiguration/index.md
- docs/docs/target/container_image.md
- docs/docs/target/kubernetes.md
- docs/ecosystem/ide.md
- docs/getting-started/installation.md
- docs/tutorials/misconfiguration/custom-checks.md
- docs/tutorials/misconfiguration/terraform.md
Fixes typos in a number of doc files
- "contribue" -> "contribute" in docs/contribute/checks/overview.md
- "adatper" -> "adapter" in docs/contribute/checks/service-support.md
- "platfroms" -> "platforms" in docs/compliance/compliance.md
- "specifiy" -> "specify" in docs/compliance/compliance.md
- "supression" -> "suppression" in docs/compliance/compliance.md
- "complaince" -> "compliance" in docs/compliance/contrib-compliance.md
- "therefor" -> "therefore" in docs/coverage/language/golang.md
- "classifer" -> "classifier" in docs/scanner/license.md
- "kubenetes" -> "kubernetes" in docs/scanner/misconfiguration/custom/index.md
- "seperated" -> "separated" in docs/scanner/misconfiguration/index.md
- "shoud" -> "should" in docs/target/container_image.md
- "wil" -> "will" in …
> docs: Fix typos in documentation

- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_test.go
Submodule parsers should keep the same parser options as the root. Carrying forward options like "AllowDownload". Without this, submodules could download remote modules, even though the root explicitly disabled that behavior.
I believe this is safe, as options do pass to a depth of 1 before this change. This change ensures they pass to a depth of >1.
> fix(terraform): apply parser options to submodule parsing

- pkg/iac/terraform/block.go
- pkg/iac/terraform/module.go
Module path is required to distinguish between 2 modules loaded from the same root. Without the accessor, is difficult to know which `module` is which when iterating through the type `Modules`. There is value in exporting this.
> chore(terraform): export module path on terraform modules

- pkg/commands/auth/run.go
DockerHub returns error when we use `scope` (see #8386 ).
So we need to use empty scope to fix this error.
We can confirm that it works for DockerHub, GHCR (https://github.com/aquasecurity/trivy/issues/8386#issuecomment-2653143840). 
- Close #8386
> fix: don't use `scope` for `trivy registry login` command

- pkg/sbom/spdx/unmarshal.go
See #8379
Before:
```
➜  8367 trivy -q sbom alpine3212.spdx
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/sbom/spdx.(*SPDX).parseFiles(0x14001432780, 0x14000a90b40)
github.com/aquasecurity/trivy/pkg/sbom/spdx/unmarshal.go:127 +0x164
github.com/aquasecurity/trivy/pkg/sbom/spdx.(*SPDX).unmarshal(0x14001432780, 0x14000a90b40)
github.com/aquasecurity/trivy/pkg/sbom/spdx/unmarshal.go:75 +0x48
github.com/aquasecurity/trivy/pkg/sbom/spdx.(*TVDecoder).Decode(0x0?, {0x107750180, 0x14001432780})
github.com/aquasecurity/trivy/pkg/sbom/spdx/unmarshal.go:45 +0xb8
github.com/aquasecurity/trivy/pkg/sbom.Decode({_, _}, {_, _}, {_, _})
github.com/aquasecurity/trivy/pkg/sbom/sbom.go:226 +0x5dc
...
```
after:
```bash
➜  ./trivy  sbom …
```
> fix(spdx): init `pkgFilePaths` map for all formats

- docs/docs/target/container_image.md
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
The `AVD-DS-0007` check should only be applied to the final layer. This PR removes the recently added export of the `etrypoint` instruction to the Dockerfile and fixes a bug with exporting metadata instructions.
- Close https://github.com/aquasecurity/trivy/issues/8364
> fix(image): disable AVD-DS-0007 for history scanning

- pkg/iac/rego/build.go
- pkg/iac/rego/embed.go
- pkg/iac/rego/load.go
- pkg/iac/rego/load_test.go
- pkg/iac/rego/scanner.go
- pkg/iac/rego/scanner_test.go
- pkg/iac/rego/testdata/policies/invalid.rego
- pkg/iac/rego/testdata/policies/valid.rego
- pkg/iac/scanners/azure/arm/scanner.go
- pkg/iac/scanners/cloudformation/scanner.go
- pkg/iac/scanners/generic/scanner.go
- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/scanner.go
- pkg/iac/scanners/terraformplan/tfjson/scanner_test.go
The source type (cloud, dockerfile, k8s, etc.) determines the default input schema when creating the scanner and filtering checks during scanning. However, this scheme is not applied if at least one check (custom or built in trivy) already uses the scheme. Since all checks from the `trivy-checks` repository use schemas, the default scheme is effectively never applied. This eliminates the dependency of the Rego scanner on the source type, which in turn makes it possible to compile the checks once and use a single instance for all IaC scanners.
Let's consider the options of specifying schemes in custom checks:
- Schema not specified - Schema does not apply. Since the default scheme has never been used, the behavior will not change.
- Schema specified - Trivy will load it from standard …
> refactor(misconf): make Rego scanner independent of config type

- pkg/k8s/scanner/scanner.go
This PR adds a skipped option `PkgRelationships`.  
```sh
$ kind create cluster --image "kindest/node:v1.25.0"
$ trivy  k8s --scanners vuln --skip-images --report all
```
before
```sh
2025-02-24T16:05:17+06:00       INFO    Node scanning is enabled
2025-02-24T16:05:17+06:00       INFO    If you want to disable Node scanning via an in-cluster Job, please try '--disable-node-collector' to disable the Node-Collector job.
2025-02-24T16:05:17+06:00       INFO    Scanning K8s... K8s="kind-kind"
```
after
```sh
2025-02-24T16:05:22+06:00       INFO    Node scanning is enabled
2025-02-24T16:05:22+06:00       INFO    If you want to disable Node scanning via an in-cluster Job, please try '--disable-node-collector' to disable the Node-Collector job.
2025-02-24T16:05:22+06:00       INFO    Scanning …
```
> fix(k8s): add missed option `PkgRelationships`

- go.mod
- go.sum
- pkg/dependency/parser/rust/binary/parse.go
The go-rustaudit repository has moved to the rust-secure-code organization: https://github.com/rust-secure-code/go-rustaudit
This PR updates the module name/path of go-rustaudit.
> chore(deps): update go-rustaudit location

- docs/docs/supply-chain/vex/sbom-ref.md
- mkdocs.yml
- pkg/sbom/core/bom.go
- pkg/sbom/cyclonedx/unmarshal.go
- pkg/vex/document.go
- pkg/vex/sbomref.go
- pkg/vex/sbomref_test.go
- pkg/vex/vex.go
> feat(cyclonedx): Add initial support for loading external VEX files from SBOM references

- go.mod
- go.sum
- pkg/iac/scanners/kubernetes/parser/manifest.go
- pkg/iac/scanners/kubernetes/parser/manifest_node.go
- pkg/iac/scanners/kubernetes/parser/manifest_test.go
- pkg/iac/scanners/kubernetes/parser/parser.go
This PR uses `github.com/go-json-experiment/json` to parsing JSON manifests, which produces correct node positions, unlike the current approach where JSON is first converted to YAML and then parsed.
```bash
AVD-KSV-0021 (LOW): Container 'hello' of Pod 'hello-cpu-limit' should set 'securityContext.runAsGroup' > 10000
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Force the container to run with group ID > 10000 to avoid conflicts with the host’s user table.
See https://avd.aquasec.com/misconfig/ksv021
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test.json:7-12 …
```
> fix(misconf): fix incorrect k8s locations due to JSON to YAML conversion

- go.mod
- go.sum
- pkg/db/db.go
- pkg/db/db_test.go
- pkg/detector/library/driver_test.go
- pkg/detector/ospkg/debian/debian_test.go
- pkg/detector/ospkg/oracle/oracle_test.go
- pkg/detector/ospkg/photon/photon_test.go
- pkg/detector/ospkg/suse/suse_test.go
Fix case when Trivy uses empty `trivy-db`.
See more in #8454
- bump trivy-db to return error for these cases.
- update trivy-db if `trivy.db` file doesn't exist
- Close #8454
> fix(db): fix case when 2 trivy-db were copied at the same time

- go.mod
- go.sum
- integration/testdata/helm.json.golden
- integration/testdata/helm_testchart.json.golden
- integration/testdata/helm_testchart.overridden.json.golden
- pkg/iac/scanners/helm/test/scanner_test.go
chore(deps): Bump trivy-checks to v1.7.1
> chore(deps): Bump trivy-checks to v1.7.1

- .github/workflows/canary.yaml
- .github/workflows/release.yaml
- .github/workflows/reusable-release.yaml
Update cache action version from v4.0.2 to v4 in multiple workflow files
>Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v4.0.2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
https://github.com/aquasecurity/trivy/actions/runs/13629588758/job/38097043500
> ci: update GitHub Actions cache to v4

- pkg/vex/sbomref.go
- pkg/vex/sbomref_test.go
This PR refactors the SBOM reference handling code to better align with project conventions.
The changes focus on improving the code structure and readability in the VEX SBOM reference implementation:
- Added context-based logging for improved traceability and debugging
- Utilized `lo.FilterMap` for more concise and functional URL parsing
- Simplified error handling and logging patterns
- Improved code structure with cleaner function signatures and return patterns
- Enhanced test readability by using table-driven tests with clear test cases
- Refactored external VEX document retrieval with table-driven tests for better test coverage and maintainability
These changes maintain the same functionality while making the code more maintainable and consistent with the project's coding standards.
> refactor(vex): improve SBOM reference handling with project standards

- pkg/iac/scanners/terraform/parser/evaluator.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/scanners/terraform/parser/testdata/nested/main.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/canada/canada.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/canada/springfield/springfield.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/north-america.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/united-states/new-york/new-york-city/new-york-city.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/united-states/new-york/new-york.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/united-states/springfield/springfield.tf
- pkg/iac/scanners/terraform/parser/testdata/nested/north-america/united-states/united-states.tf
- pkg/iac/terraform/module.go
Setting 'parent' field was omitted for submodules.
This commit corrects that. Submodules can now traverse up their
parents until they hit the root module.
I made a unit test to really put it through the paces.
> chore(terraform): assign *terraform.Module 'parent' field

- docs/docs/references/abbreviations.md
- mkdocs.yml
This PR adds a list of standard abbreviations to serve as a guideline. While terms like *source* and *dependency* already have used abbreviations in Trivy, `--image-src` and `--include-dev-deps`, they are not included in this list. They should be `--image-sources` and `--include-dev-dependencies` respectively.
If necessary, we could add them as aliases in a separate PR for consistency, but it may not be strictly required since this is a guideline for maintainers.
- https://github.com/aquasecurity/trivy/discussions/8446
> docs: add abbreviation list

- .github/workflows/auto-update-labels.yaml
- .github/workflows/reusable-release.yaml
- .github/workflows/test.yaml
- .golangci.yaml
- Dockerfile.protoc
- aqua.yaml
- examples/module/spring4shell/spring4shell.go
- go.mod
- go.sum
- magefiles/magefile.go
- pkg/iac/scanners/terraform/parser/funcs/collection.go
- pkg/iac/scanners/terraform/parser/funcs/crypto.go
- pkg/module/module.go
- pkg/module/testdata/analyzer/analyzer.go
- pkg/module/testdata/happy/happy.go
- pkg/module/testdata/scanner/scanner.go
- pkg/module/wasm/sdk.go
This PR updates Go to version 1.24 and changes how we manage Go versions in GitHub Actions from `go-version` to `go-version-file`.
This PR includes the following changes:
1. Update Go version to 1.24 in go.mod
2. Bump golangci-lint to v1.64.2 that supports Go 1.24
3. Switch from `go-version` to `go-version-file` in GitHub Actions workflows
The switch to `go-version-file` was made to improve version management clarity and reduce confusion. Previously, we had a discussion in #6711 about using `go-version` to automatically use the latest patch version. However, this approach led to confusion as the version specified in the workflow could differ from the one in go.mod.
For example, in #8341, we unnecessarily updated the Go version even though the latest patch version would have been used …
> chore(deps): update Go to 1.24 and switch to go-version-file

- pkg/sbom/io/encode.go
- pkg/sbom/io/encode_test.go
This PR improves `belongToParent` logic for Direct dependencies:
- If parents contains `Root` or `Workspace` - doesn't bind dependency to the parent component (current logic)
- for other cases (if there are parents) we need to bind dependency to parent component (see #8488 for more details)
Example:
```json
{
"ID": "django@5.1.6",
"Name": "django",
"Identifier": {
"PURL": "pkg:pypi/django@5.1.6",
"UID": "69691e87e187021d"
},
"Version": "5.1.6",
"Relationship": "direct",
"DependsOn": [
"asgiref@3.8.1",
"sqlparse@0.5.3",
"tzdata@2025.1"
],
"Layer": {}
},
{
"ID": "sentry-sdk@2.22.0",
"Name": "sentry-sdk",
"Identifier": {
"PURL": "pkg:pypi/sentry-sdk@2.22.0",
"UID": "7e53a15e8bec68ad"
},
"Version": "2.22.0",
"Relationship": "direct",
"DependsOn": [
"certifi@2025.1.31",
"django@5.1.6", …
```
> fix(sbom): improve logic for binding direct dependency to parent component

- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_private_test.go
Save text licenses in `otherLicenses` without normalization.
This is necessary to avoid errors when parsing the license text.
Also, we did not include these "incorrect" licenses in the report.
See #8465 for more details.
Before (report doesn't contain this license):
```
➜  trivy image 8449 -f spdx-json | grep Redistribution 
...
2025-03-06T13:33:03+06:00       WARN    [spdx] Unable to marshal SPDX licenses  license="(GPL-2.0-only) AND (text://Redistribution and use in source and binary forms, with or without) AND (text://By obtaining, using, and/or copying this software and/or its) AND (text://Permission to use, copy, modify, and distribute this software and) AND (text://This software is provided 'as-is', without any express or implied) AND (text://Permission  is  hereby granted,  free …
```
> fix(spdx): save text licenses into `otherLicenses` without normalize

- pkg/iac/rego/scanner.go
While writing integration tests in trivy-checks, I noticed that it takes a lot of time to scan test data. Trivy parses the input data before Rego query for each scan, i.e. Trivy parses the input data n times, where n is the number of checks. This leads to large memory allocation and takes a lot of CPU time. 
This PR moves the parsing of the input data before running all checks.
```bash
/usr/bin/time -l trivy conf output -f json -o report1.json -q
23.12 real        30.69 user         1.17 sys
635666432  maximum resident set size
0  average shared memory size
0  average unshared data size
0  average unshared stack size
39678  page reclaims
5694  page faults
0  swaps
0  block input operations
0  block output operations
0  messages sent
0  messages received
3019  signals received
3912 …
```
> perf(misconf): parse input for Rego once

- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/schema.go
- Close https://github.com/aquasecurity/trivy/issues/8515
> fix(misconf): add ephemeral block type to config schema

- pkg/iac/rego/build.go
- pkg/iac/rego/custom.go
- pkg/iac/rego/embed.go
- pkg/iac/rego/embed_test.go
- pkg/iac/rego/load.go
- pkg/iac/rego/load_test.go
- pkg/iac/rego/metadata.go
- pkg/iac/rego/result.go
- pkg/iac/rego/runtime.go
- pkg/iac/rego/scanner.go
- pkg/iac/rego/store.go
- pkg/policy/policy.go
- pkg/result/filter.go
OPA v1 was recently released and packages outside of v1 are declared deprecated. This PR updates the import of OPA packages to use v1.
> refactor(misconf): use OPA v1

- pkg/fanal/analyzer/config/azurearm/azurearm.go
- pkg/fanal/analyzer/config/azurearm/azurearm_test.go
- pkg/iac/detection/detect.go
- pkg/iac/detection/detect_test.go
- pkg/iac/scanners/azure/arm/parser/parser.go
- pkg/iac/scanners/azure/arm/parser/template.go
- pkg/iac/scanners/azure/arm/parser/template_test.go
[CreateUiDefinition.json ](https://learn.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/create-uidefinition-overview)is detected as an ARM template because some fields match (schema and parameters), which causes a parsing error. We should skip it, as this file is used to define the UI when creating applications in the Azure portal. We should also log the error when the template parsing fails and continue scanning.
- Close https://github.com/aquasecurity/trivy/issues/8500
> fix(misconf): skip Azure CreateUiDefinition

- docs/docs/advanced/self-hosting.md
Fixed broken link in registry tools.
Small documentation fix; the MarkDown links were not rendered correctly, obscuring the registry tools to use.
> style: Fix MD syntax in self-hosting.md

- docs/docs/target/rootfs.md
- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/analyzer/buildinfo/content_manifest.go
- pkg/fanal/analyzer/buildinfo/dockerfile.go
- pkg/fanal/analyzer/const.go
- pkg/fanal/analyzer/os/alpine/alpine.go
- pkg/fanal/analyzer/os/amazonlinux/amazonlinux.go
- pkg/fanal/analyzer/os/debian/debian.go
- pkg/fanal/analyzer/os/redhatbase/alma.go
- pkg/fanal/analyzer/os/redhatbase/centos.go
- pkg/fanal/analyzer/os/redhatbase/fedora.go
- pkg/fanal/analyzer/os/redhatbase/oracle.go
- pkg/fanal/analyzer/os/redhatbase/redhatbase.go
- pkg/fanal/analyzer/os/redhatbase/rocky.go
- pkg/fanal/analyzer/os/release/release.go
- pkg/fanal/analyzer/os/ubuntu/esm.go
- pkg/fanal/analyzer/os/ubuntu/ubuntu.go
- pkg/fanal/analyzer/pkg/apk/apk.go
- pkg/fanal/analyzer/pkg/dpkg/copyright.go
- pkg/fanal/analyzer/pkg/dpkg/dpkg.go
- pkg/fanal/analyzer/pkg/rpm/rpm.go
- pkg/fanal/analyzer/pkg/rpm/rpmqa.go
- pkg/fanal/analyzer/repo/apk/apk.go
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/artifact/local/fs_test.go
- pkg/semaphore/semaphore.go
When scanning hosts with a large number of files, traversing the entire filesystem can be time-consuming and resource-intensive. This PR introduces an optimization that allows Trivy to directly access files with known absolute paths without traversing the filesystem.
- Added a `StaticPathAnalyzer` interface that allows analyzers to declare specific file paths they need to analyze
- Modified the analysis workflow to check if all enabled analyzers implement the `StaticPathAnalyzer` interface
- When all enabled analyzers implement this interface, Trivy will directly access only the required files instead of traversing the entire filesystem
- Added tests to verify both analysis strategies (direct access vs. filesystem traversal)
- Significantly reduces scanning time for hosts with large …
> feat(fs): optimize scanning performance by direct file access for known paths

- pkg/iac/adapters/terraform/aws/ec2/vpc.go
- pkg/iac/adapters/terraform/aws/ec2/vpc_test.go
This PR adds adaptation for [aws_default_security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_security_group) and also fixes protocol parsing in number format.
> feat(misconf): adapt aws_default_security_group

- pkg/fanal/analyzer/analyzer.go
- pkg/fanal/artifact/local/fs_test.go
To enable `StaticPaths` mode - all enabled analyzers must implement the `StaticPathAnalyzer` interface.
For this we need to check `analyzers`. And also `postAnalyzers` (changes in this PR)
Otherwise there may be cases when only postAnalyzser is enabled => we enable `StaticPaths` mode and skip files.
example:
Before:
```bash
➜  ./trivy -d conf ./integration/testdata/fixtures/k8s --table-mode summary
...
2025-03-13T13:55:11+06:00       DEBUG   [fs] Analyzing...       root="integration/testdata/fixtures/k8s"
2025-03-13T13:55:11+06:00       DEBUG   [fs] Analyzing files in static paths
...
Report Summary
┌────────┬──────┬───────────────────┐
│ Target │ Type │ Misconfigurations │
├────────┼──────┼───────────────────┤
│   -    │  -   │         -         │
└────────┴──────┴───────────────────┘ …
```
> fix(fs): check postAnalyzers for StaticPaths

- pkg/iac/adapters/cloudformation/aws/ec2/adapt_test.go
- pkg/iac/adapters/cloudformation/aws/ec2/ec2.go
- pkg/iac/adapters/cloudformation/aws/ec2/vpc.go
This PR adds adaptation to the state for the CloudFormation resource [AWS::EC2::VPC](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html).
> feat(misconf): adapt AWS::EC2::VPC

- pkg/iac/adapters/terraform/aws/elasticsearch/adapt.go
- pkg/iac/adapters/terraform/aws/elasticsearch/adapt_test.go
Amazon OpenSearch Service is the successor to Amazon Elasticsearch Service. For CloudFormation, we already support `AWS::OpenSearchService::Domain`.
> feat(misconf): adapt aws_opensearch_domain

- pkg/iac/adapters/cloudformation/aws/eks/cluster.go
- pkg/iac/adapters/cloudformation/aws/eks/eks_test.go
- Default value for [PublicAccessCidrs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-resourcesvpcconfig.html#cfn-eks-cluster-resourcesvpcconfig-publicaccesscidrs) is `0.0.0.0/0`.
- Default value for [EndpointPublicAccess](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-resourcesvpcconfig.html#cfn-eks-cluster-resourcesvpcconfig-endpointpublicaccess) is `true`.
> fix(misconf): set default values for AWS::EKS::Cluster.ResourcesVpcConfig

- docs/docs/references/configuration/cli/trivy_config.md
- docs/docs/references/configuration/cli/trivy_convert.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- docs/docs/references/configuration/cli/trivy_repository.md
- docs/docs/references/configuration/cli/trivy_rootfs.md
- docs/docs/references/configuration/cli/trivy_sbom.md
- docs/docs/references/configuration/cli/trivy_vm.md
- pkg/flag/options.go
This PR improves the display format of CLI flag values to enhance readability and consistency.
Introduce a bullet list format for flags with more than four allowed values
```
-s, --severity strings           severities of security issues to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL) (default [UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL])
--pkg-types strings           list of package types (os,library) (default [os,library])
```
```
-s, --severity strings           severities of security issues to be displayed
Allowed values:
- UNKNOWN
- LOW
- MEDIUM
- HIGH
- CRITICAL
(default [UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL])
--pkg-types strings           list of package types (allowed values: os,library) (default [os,library])
```
> docs(cli): improve flag value display format

- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/attribute.go
Now we return `cty.NilVal` as the value of the expression if its evaluation failed or returned an unknown value. The documentation says that `NilVal` is nil in the Go type system and is not a valid value in the cty type system. We should use `cty.NullVal` with a dynamic pseudo-type for null values, and in other cases we should use dynamic values `cty.DynamicVal` to allow them to be used in operations with other values.
Ref: https://github.com/zclconf/go-cty/blob/main/docs/types.md
- Close https://github.com/aquasecurity/trivy/issues/8563
> fix(misconf): do not use cty.NilVal for non-nil values

- pkg/iac/scanners/helm/test/parser_test.go
- pkg/iac/scanners/helm/test/scanner_test.go
This PR refactored the Helm scanner tests to improve their readability and reduce duplication.
> test: use table-driven tests in Helm scanner tests

- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/helm/test/scanner_test.go
Currently, Trivy identifies a Chart file by the prefix `Chart.yaml`, which can lead to false results. For example, a file named `testChart.yaml` may be misrecognized as a Chart file when it is not. This PR changes the way a Chart file is identified, moving to an exact name match.
- Close https://github.com/aquasecurity/trivy/issues/8588
> fix(misconf): identify the chart file exactly by name

- pkg/iac/adapters/terraform/aws/msk/adapt.go
- pkg/iac/adapters/terraform/azure/compute/adapt.go
- pkg/iac/adapters/terraform/azure/container/adapt.go
- pkg/iac/adapters/terraform/azure/database/adapt.go
- pkg/iac/adapters/terraform/azure/storage/adapt.go
- pkg/iac/adapters/terraform/google/gke/adapt.go
- pkg/iac/adapters/terraform/google/sql/adapt.go
- pkg/iac/adapters/terraform/google/sql/adapt_test.go
- pkg/iac/scanners/terraform/attribute_test.go
- pkg/iac/scanners/terraform/block_test.go
- pkg/iac/terraform/attribute.go
- pkg/iac/terraform/block.go
- pkg/iac/terraform/module.go
This PR fixes a potential panic when handling attributes and blocks in Terraform configuration due to an incorrect element type.
Previously, the following pattern was used to check for and retrieve a block or attribute in some parts of the codebase:
```go
if resource.HasChild("foo") {
resource.GetBlock("foo") // or resource.GetAttribute("foo")
}
```
The `HasChild` method returns true if the block contains an attribute or a child block with the specified name. This could lead to a panic when working with an element of the wrong type (e.g., attempting to handle an attribute as a block or vice versa).
Instead, the following safer and recommended pattern is now used:
```go
if fooBlock := resource.GetBlock("foo"); fooBlock != nil {
...
}
```
Changes:
- Removed the `HasChild` method to prevent …
> refactor(misconf): get a block or attribute without calling HasChild

- pkg/k8s/report/table.go
- pkg/k8s/writer_test.go
We added `table` mode in #8177.
But `k8s` command also uses table writer for `--report all` flag.
So we need to add table modes for this flag.
`k8s` has its own summary report, so we only need to show the `detailed` tables.
Before:
```bash
➜ trivy k8s --report all        
2025-03-27T11:20:37+06:00       INFO    Loaded  file_path="trivy.yaml"
2025-03-27T11:20:45+06:00       INFO    Node scanning is enabled
2025-03-27T11:20:45+06:00       INFO    If you want to disable Node scanning via an in-cluster Job, please try '--disable-node-collector' to disable the Node-Collector job.
2025-03-27T11:20:45+06:00       INFO    Scanning K8s... K8s="kind-kind"
219 / 219 [--------------------------------------------------------------------------------------------------------------------------------------- …
```
> fix(k8s): show report for `--report all`

- pkg/iac/scanners/terraform/executor/executor.go
- pkg/iac/scanners/terraform/scanner_test.go
Resolves a case where nested unresolvable values can trigger a panic while rendering causes.
- Fixes: https://github.com/aquasecurity/trivy/issues/8603
> fix(misconf): Check values wholly prior to evalution

- pkg/fanal/analyzer/pkg/dpkg/copyright.go
- pkg/fanal/analyzer/pkg/dpkg/testdata/license-pattern-and-classifier-copyright
Don't include empty licenses in report.
Also this PR fixes problem with invalid CycloneDX files:
Before:
```bash
➜  trivy -q image --format cyclonedx mcr.microsoft.com/playwright:v1.50.0-noble -o playwright-sbom.json 
➜  cyclonedx validate --input-format json --fail-on-errors --input-version v1_6 --input-file playwright-sbom.json
Validating JSON BOM...
Validation failed:
Expected 1 matching subschema but found 0
...
```
After:
```bash
➜  ./trivy -q image --format cyclonedx mcr.microsoft.com/playwright:v1.50.0-noble -o playwright-sbom.json
➜  cyclonedx validate --input-format json --fail-on-errors --input-version v1_6 --input-file playwright-sbom.json
Validating JSON BOM...
BOM validated successfully.
```
- Close #8621
> fix(debian): don't include empty licenses for `dpkgs`

- pkg/iac/rego/load.go
There's no reason to print these logs on the error stream as it is not an error but simply lack of support.
- Close  https://github.com/aquasecurity/trivy/issues/8632
> fix(misconf): Improve logging for unsupported checks

- pkg/flag/options.go
I hate to be "that guy" but I saw a tiny really insignificant typo that could do with being corrected. It's unlikely people will even hit this or see this, but in that tiny percentage that do, they'd be saying to themselves "what rego error? I'm using repos!"
I only found this because I am going through the code to see how it fits together. I'm simply trying to make use of Trivy (without calling the cli directly) to build some tooling that makes use of the repository scan elements for a personal project. While reading through it, I came across this. So figured I'd raise it.
Nothing groundbreaking or exciting here I'm afraid!
If you want to close this and fix it within a more broad PR  (or if I'm way off base of course) I'd totally understand and would be in no way offended 😃 
But if I see …
> chore: typo fix to replace `rego` with `repo` on the RepoFlagGroup options error output

- go.mod
- go.sum
- internal/testutil/docker.go
- pkg/fanal/image/daemon/containerd.go
- pkg/fanal/image/daemon/image.go
- pkg/fanal/image/daemon/podman.go
- pkg/fanal/test/integration/docker/docker.go
This allows Trivy to be compatible with Buf 1.51: https://github.com/bufbuild/buf/blob/c942c377342d383e6fb459edeaaccfac4b832bc4/go.mod#L20
> chore: update Docker lib

- pkg/k8s/report/summary.go
- pkg/k8s/writer_test.go
This PR removes passed misconfigs from the summary report. It's important if `--include-non-failures` is enabled.
```sh
$ minikube start
$ trivy k8s  --scanners=misconfig --report=summary --include-non-failures
```
Before:
```sh
┌───────────┬────────────────────┬───────────────────────┐
│ Namespace │      Resource      │   Misconfigurations   │
│           │                    ├────┬────┬────┬────┬───┤
│           │                    │ C  │ H  │ M  │ L  │ U │
├───────────┼────────────────────┼────┼────┼────┼────┼───┤
│ default   │ Service/kubernetes │ 26 │ 44 │ 25 │ 61 │   │
│           │ Node/minikube      │ 26 │ 44 │ 25 │ 61 │   │
└───────────┴────────────────────┴────┴────┴────┴────┴───┘
Severities: C=CRITICAL H=HIGH M=MEDIUM L=LOW …
```
> fix(k8s): skip passed misconfigs for the summary report

- .github/workflows/cache-test-images.yaml
- .github/workflows/test.yaml
- integration/testimages.ini
We used `ghcr.io/knqyf263/trivy-test-vm-images` and `ghcr.io/knqyf263/trivy-test-images` to avoid 429 errors.
But our error avoidance guide is working.
Therefore, I suggest returning to `aquasecurity`.
This will also avoid unexpected errors when the fork was changed without changes in aquasecurity, like this:
https://github.com/aquasecurity/trivy-test/actions/runs/14240065387/job/39909316221?pr=24#step:7:1750
`trivy-test-images:busybox-with-lockfile.` [has been changed](https://github.com/knqyf263/trivy-test-images/commit/7740ec2d080b0acab86a6c5cc742044d8cbb3a3b), so if tests don't use cache we will get error.
1. use `ghcr.io/aquasecurity/trivy-test-images` instead of `ghcr.io/knqyf263/trivy-test-images`
2. use `ghcr.io/aquasecurity/trivy-test-vm-images` instead of …
> test: use `aquasecurity` repository for test images

- pkg/cache/redis.go
- pkg/cache/redis_test.go
When using Redis as the cache backend, when trying to delete a blob at the end of the scan (in FS scan for example) it fails.
This is because the redis key that is built in the function is built for `artifact` and not for `blob`
- Close https://github.com/aquasecurity/trivy/discussions/8648
> fix(server): fix redis key when trying to delete blob

- .github/workflows/release-pr-check.yaml
We found that `github.actor` is `The username of the user that triggered the initial workflow run.`.
So when maintainer merges `main` branch - [release PR check workflow](https://github.com/aquasecurity/trivy/blob/main/.github/workflows/release-pr-check.yaml) shows error (e.g. https://github.com/aquasecurity/trivy/pull/8697).  
To check PR author we need to use `github.event.pull_request.user.login`.
- currently case:
- https://github.com/aquasecurity/trivy-test/pull/44
- https://github.com/aquasecurity/trivy-test/actions/runs/14330442330/job/40164978575?pr=44
- with these changes
- https://github.com/aquasecurity/trivy-test/pull/42
- https://github.com/aquasecurity/trivy-test/actions/runs/14330459819/job/40165033194?pr=42
> ci: use `github.event.pull_request.user.login` for release PR check workflow

- pkg/iac/adapters/terraform/google/gke/adapt.go
- pkg/iac/adapters/terraform/google/gke/adapt_test.go
- pkg/iac/providers/google/gke/gke.go
- pkg/iac/rego/schemas/cloud.json
This PR adds support for the `auto_provisioning_defaults` block of a `google_container_cluster` resource.
- https://github.com/aquasecurity/trivy/issues/8706
> feat(misconf): support auto_provisioning_defaults in google_container_cluster

- pkg/commands/app.go
- pkg/commands/app_test.go
- pkg/flag/aws_flags.go
- pkg/flag/cache_flags.go
- pkg/flag/clean_flags.go
- pkg/flag/db_flags.go
- pkg/flag/db_flags_test.go
- pkg/flag/global_flags.go
- pkg/flag/image_flags.go
- pkg/flag/image_flags_test.go
- pkg/flag/kubernetes_flags.go
- pkg/flag/license_flags.go
- pkg/flag/misconf_flags.go
- pkg/flag/module_flags.go
- pkg/flag/options.go
- pkg/flag/package_flags.go
- pkg/flag/package_flags_test.go
- pkg/flag/registry_flags.go
- pkg/flag/rego_flags.go
- pkg/flag/remote_flags.go
- pkg/flag/remote_flags_test.go
- pkg/flag/repo_flags.go
- pkg/flag/report_flags.go
- pkg/flag/report_flags_test.go
- pkg/flag/scan_flags.go
- pkg/flag/scan_flags_test.go
- pkg/flag/secret_flags.go
- pkg/flag/vulnerability_flags.go
This PR refactors the flag system to make it more extensible and improve its architecture by changing the Flags type from a struct to a slice of FlagGroup interfaces.
- Changed `Flags` type from struct with individual `FlagGroup` fields to a slice of `FlagGroup` interfaces
- Modified `ToOptions` methods to update a shared `Options` object instead of returning individual options types
- Removed redundant flag parsing from individual flag groups
- Centralized flag parsing in the `Flags.ToOptions` method
- Updated affected tests to work with the new architecture
- This change makes it easier to add new flag groups without modifying the `Flags` struct definition
The new architecture simplifies the process of adding new flag groups and makes the codebase more maintainable by removing …
> refactor(flag): improve flag system architecture and extensibility

- .github/workflows/semantic-pr.yaml
This PR improves the PR title validation workflow by enhancing security and removing external dependencies.
- Remove `pull_request_target` event to prevent potential security issues ([ref](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow))
- Remove unnecessary `GITHUB_TOKEN` usage
- Remove external action dependency (`amannn/action-semantic-pull-request`)
- Add specific error messages for different validation failures:
- Format validation with examples
- Type validation with available options
- Scope validation with categorized options
- Improve error message readability with better formatting and examples
Tested on https://github.com/aquasecurity/trivy-test/pull/45/
- invalid format: https://github.com/aquasecurity/trivy-test/actions/runs/14380642256/job/40323 …
> ci: improve PR title validation workflow

- pkg/k8s/writer_test.go
- pkg/report/table/table.go
After #8357 the rendering for table reports was introduced a buffer mechanism.
But k8s reports are displayed in separate sections (e.g., vulnerabilities, misconfigurations, etc.), printed to the screen incrementally. It allows to save memory, because k8s report can contains a lot of resources.
To prevent previously printed data from being shown again, the buffer is cleared after display data.
- Close #8715
> fix(report): clean buffer after flushing

- pkg/iac/rego/load.go
- pkg/iac/rego/load_test.go
This PR fixes a potential panic when falling back to embedded checks due to missing annotations.
> fix(misconf): check if metadata is not nil

- pkg/iac/adapters/terraform/tftestutil/testutil.go
- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_integration_test.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/scanners/terraform/performance_test.go
- pkg/iac/scanners/terraform/scanner.go
- pkg/iac/scanners/terraform/scanner_test.go
- pkg/iac/scanners/terraform/setup_test.go
This PR removes the module outputs returned by `parser.EvaluateAll` since they were not used anywhere.
> refactor(misconf): remove module outputs from parser.EvaluateAll

- pkg/iac/scanners/terraform/parser/funcs/filesystem.go
- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_test.go
Terraform filesystem functions only have access to the filesystem specified. It should never call out to files outside the filesystem.
There is no use to default to `os.Open` when `target` is nil. If the `moduleFS` is nil, a panic (now an error) occurs in [`ParseFS`](https://github.com/Emyrk/trivy/blob/main/pkg/iac/scanners/terraform/parser/parser.go#L157). To ensure terraform only can access files in it's provided file system, `os.Open` should be removed.
> chore(terraform): remove os.OpenPath call from terraform file functions

- .github/workflows/spdx-cron.yaml
`Skitionek/notify-microsoft-teams` fixed the issue and now we can use it instead of the fork
See - https://github.com/aquasecurity/notify-microsoft-teams/pull/1
tested for Trivy-db - https://github.com/DmitriyLewen/trivy-db/actions/runs/14485778659/job/40630965075
> ci: use `Skitionek/notify-microsoft-teams` instead of `aquasecurity` fork

- .github/workflows/publish-chart.yaml
- .github/workflows/release.yaml
- magefiles/helm.go
This PR changes the order of creating a PR for updating the Helm Chart version.
Now, the PR with the new version is created after the release workflow is fully executed, instead of being triggered by tag creation.  
Also the version update now uses the `Chart.yaml` file from the `main` branch. This ensures the correct version for a patch release, as `Chart.yaml` is usually modified after a release and does not appear in the `backport` branch.  
* workflow for PR creating: https://github.com/aquasecurity/trivy-test/actions/runs/14251655074
* the PR was created: https://github.com/aquasecurity/trivy-test/pull/33
* workflow for patch creatinng: https://github.com/aquasecurity/trivy-test/actions/runs/14251850015
* PR for the patch: https://github.com/aquasecurity/trivy-test/pull/35
> ci(helm): create a helm branch for patches from main

- pkg/iac/adapters/terraform/aws/iam/convert.go
- pkg/iac/adapters/terraform/aws/iam/policies.go
- pkg/iac/adapters/terraform/aws/iam/roles_test.go
This PR adds support for converting AWS managed policies by their ARN or name into full IAM documents. For now, the conversion is only implemented for `AmazonS3FullAccess` policies as part of the `AVD-AWS-0345` enhancement. No changes are required on the check side as it already works with IAM documents. An alternative solution is to export ARN policies to Rego and convert them in checks.
- Close https://github.com/aquasecurity/trivy/issues/8752
> feat(misconf): convert AWS managed policy to document

- .github/workflows/test.yaml
- .golangci.yaml
- magefiles/magefile.go
bump golangci-lint to v2.1.2
- Closes #8663
> chore(deps): bump golangci-lint to v2.1.2

- pkg/iac/adapters/terraform/aws/codebuild/adapt.go
- pkg/iac/adapters/terraform/aws/ec2/adapt.go
- pkg/iac/adapters/terraform/aws/ec2/autoscaling.go
- pkg/iac/adapters/terraform/aws/s3/bucket.go
- pkg/iac/terraform/attribute.go
This PR wraps operations in a safeOp function that checks that the attribute value is non-null and known before performing the operation. This is only done for operations that really need to work with a known value rather than an expression directly.
- Close https://github.com/aquasecurity/trivy/issues/8779
> fix(misconf): perform operations on attribute safely

- pkg/iac/scanners/kubernetes/parser/manifest.go
- pkg/iac/scanners/kubernetes/parser/manifest_node.go
- pkg/iac/scanners/kubernetes/parser/manifest_test.go
This PR fixes a panic that occurred when a node in the JSON manifest was `null`. Since `UnmarshalJSONFrom` is only called on the root node and does not handle nested `null` values, we now filter out `null` nodes during the manifest traversal after parsing.
https://github.com/aquasecurity/trivy-operator/actions/runs/14701034441/job/41250488412?pr=2528
> fix(misconf): filter null nodes when parsing json manifest

- pkg/iac/scanners/terraform/parser/parser_test.go
- pkg/iac/terraform/block.go
In one PR, we started storing unknown values in context to preserve their type instead of converting them to a dynamic value. After that, using an unknown value in `for-each` started to cause panic because the dynamic block expansion didn't check that the value was known. This PR adds a check that the value is known.
- Close https://github.com/aquasecurity/trivy/issues/8805
> fix(misconf): check if for-each is known when expanding dyn block

- .golangci.yaml
Fixes [use-any](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#use-any) rule from revive
It also removes exclusions that are useless
> fix: use-any from revive

- pkg/detector/ospkg/redhat/redhat.go
- pkg/detector/ospkg/redhat/redhat_test.go
This patch addresses a parsing error when scanning certain Red Hat images whose `/root/buildinfo/content_manifests/*.json` files include malformed content set names with an extra “__<digits>” suffix (e.g. `ubi-8-for-x86_64-baseos-rpms__8`). Those invalid entries prevent Trivy from mapping content sets to CPE indices and cause scan failures.
- Before mapping each `content_set` to a CPE, strip any trailing `__<number>` suffix using a regex (`__\d+$`).  
- Leave correctly formatted names untouched.  
- Add unit tests covering
- Closes aquasecurity/trivy-db#435
> fix(redhat): trim invalid suffix from content_sets in manifest parsing

- pkg/dependency/parser/gradle/lockfile/parse.go
- pkg/dependency/parser/gradle/lockfile/parse_test.go
- pkg/dependency/parser/gradle/lockfile/testdata/happy.lockfile
We need to mark development dependencies while scanning gradle lockfiles so that they are not included in the final scans
- Close #8755
> fix(java): exclude dev dependencies in gradle lockfile

- docs/docs/coverage/language/java.md
- docs/docs/references/configuration/cli/trivy_filesystem.md
- docs/docs/references/configuration/cli/trivy_repository.md
- pkg/flag/package_flags.go
We are now marking development dependencies while scanning gradle lockfiles so that they are not included in the final scans. So need to update the related docs as well
- Close #8755
> docs(java):  Update info about dev deps in gradle lock

- .github/ISSUE_TEMPLATE/maintainer.md
Due to recent changes on GitHub, maintainers are currently unable to create issues directly. This is inconvenient, so we're temporarily adding a dedicated issue template for maintainers. You can test it [here](https://github.com/aquasecurity/trivy-test/issues/new/choose).
Ideally, the maintainer template would appear at the bottom of the list, but based on my research, it's not possible to place external links at the top. As a result, the maintainer template appears first.
> chore: add an issue template for maintainers

- docs/docs/scanner/vulnerability.md
We [removed](https://github.com/aquasecurity/trivy-db/pull/345) Python advisories from OSV from trivy-db.
> docs(vuln): remove OSV for Python from data sources

- contrib/junit.tpl
```xml
...
<testsuite tests="9" failures="9" name="main.tf" errors="0" time="">
<properties>
<property name="type" value="terraform"></property>
</properties>
<testcase classname="Terraform Security Check" name="[HIGH] AVD-AWS-0086" time="">
<failure message="S3 Access block should block public ACL" type="description">S3 buckets should block public ACLs on buckets and any objects they contain. By blocking, PUTs with fail if the object has any public ACL a.&#xA;</failure>
</testcase>
<testcase classname="Terraform Security Check" name="[HIGH] AVD-AWS-0087" time="">
<failure message="S3 Access block should block public policy" type="description">S3 bucket policy should have block public policy to prevent users from putting a policy that enable public access.&#xA;</failure>
</testcase>
... …
```
> feat(misconf): add misconfiguration location to junit template

- pkg/fanal/handler/sysfile/filter.go
- pkg/fanal/handler/sysfile/filter_test.go
We didn't find reason why we skip only specific language types when filter files installed from package managers.
So we need to remove this logic.
If users will need to scan these files - they can use `--detection-priority` flag.
- Close #8795
> fix: filter all files when processing files installed from package managers

- docs/docs/advanced/container/unpacked-filesystem.md
- docs/docs/coverage/os/rhel.md
- docs/docs/target/rootfs.md
- docs/docs/target/vm.md
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/artifact/vm/vm.go
See #8819
Before:
```
➜  trivy -q fs -f json --list-all-pkgs /tmp/8200/ubi8/blobs/sha256 | jq  ' .Results[].Packages[1]'
{
"ID": "basesystem@11-5.el8.noarch",
"Name": "basesystem",
"Identifier": {
"PURL": "pkg:rpm/redhat/basesystem@11-5.el8?arch=noarch&distro=redhat-8.6",
"UID": "e67141531362fa78"
},
"Version": "11",
"Release": "5.el8",
"Arch": "noarch",
"SrcName": "basesystem",
"SrcVersion": "11",
"SrcRelease": "5.el8",
"Licenses": [
"Public Domain"
],
"Maintainer": "Red Hat, Inc.",
"DependsOn": [
"filesystem@3.8-6.el8.aarch64",
"setup@2.12.2-6.el8.noarch"
],
"Layer": {},
"Digest": "md5:31bc067a6462aacd3b891681bdb27512"
}
```
after:
```
➜  ./trivy -q fs -f json --list-all-pkgs /tmp/8200/ubi8/blobs/sha256 | jq  ' .Results[].Packages[1]'
{
"ID": "basesystem@11-5.el8.noarch",
"Name": …
```
> fix(redhat): save contentSets for OS packages in fs/vm modes

- pkg/x/json/jsonc.go
- pkg/x/json/jsonc_test.go
This PR adds support for [JSONC (JSON with Comments)](https://code.visualstudio.com/docs/languages/json#_json-with-comments) format by implementing a simple parser that converts JSONC to RFC 8259 compliant JSON. JSONC is widely used in configuration files (like in VS Code) and allows single-line (`//`) and multi-line (`/* */`) comments as well as trailing commas in objects and arrays.
- Added `ToRFC8259()` function that converts JSONC to standard JSON while preserving exact character offsets and line numbers
- Implemented `UnmarshalJSONC()` for parsing JSONC data directly into Go structs
- Maintained line position information for the correct locations
The implementation:
1. Preserves character positions by replacing comments and trailing commas with spaces
2. Handles both single-line …
> feat: add JSONC support for comments and trailing commas

- docs/docs/references/configuration/cli/trivy_image.md
- docs/docs/references/configuration/cli/trivy_kubernetes.md
- pkg/commands/app.go
- pkg/types/report.go
We don't need to use allowed values for `--complience` flag, because in this case users can't use custom compliance.
See more info in #8876.
So this PR removes allowed values and added built-in compiance's in flag description:
```
➜  ./trivy image --help | grep "\-\-compliance"   
--compliance string          compliance report to generate (built-in compliance's: docker-cis-1.6.0)
➜  ./trivy k8s --help | grep "\-\-compliance" -A 7
--compliance string          compliance report to generate
Built-in compliance's:
- k8s-nsa-1.0
- k8s-cis-1.23
- eks-cis-1.4
- rke2-cis-1.24
- k8s-pss-baseline-0.1
- k8s-pss-restricted-0.1
```
- Close #8876
> fix(cli): don't use allow values for `--compliance` flag

- integration/integration_test.go
- pkg/db/db.go
- pkg/db/db_test.go
We update the `DownloadAt` field after downloading (and copying) the DB to the cache folder.
Instead of deleting `metadata.json` before each download - we will check the field.
There are 2 cases when the `DownloadAt` field is zero.
But we cannot determine which case it is:
1. When copying after download was interrupted.
In this case, we mark this DB as requiring updating and show a warning about this case:
```
➜  ./trivy -d image alpine                 
...
2025-05-15T14:58:44+06:00       WARN    [vulndb] Trivy-db may be corrupted and will be re-downloaded. If you used `oras` to download DB - use the `--skip-db-update` flag to skip updating DB.
2025-05-15T14:58:44+06:00       INFO    [vulndb] Need to update DB
2025-05-15T14:58:44+06:00       INFO    [vulndb] Downloading vulnerability …
```
> refactor(db): change logic to detect wrong DB

- pkg/dependency/parser/julia/manifest/parse.go
- pkg/dependency/parser/julia/manifest/parse_test.go
- pkg/dependency/parser/julia/manifest/testdata/missed-child-dep/Manifest.toml
- pkg/dependency/parser/julia/manifest/testdata/multiple-same-deps/Manifest.toml
```
panic: runtime error: index out of range [0] with length 0
goroutine 60 [running]:
github.com/aquasecurity/trivy/pkg/dependency/parser/julia/manifest.decodeDependency(0xc009103b90, {{{0x83faa00, 0xc0091516b0}, {0xc009190b20, 0x2, 0x2}}, {0xc0085fa245, 0x24}, {0x0, 0x0}, ...}, ...)
github.com/aquasecurity/trivy/pkg/dependency/parser/julia/manifest/parse.go:146 +0x66d
github.com/aquasecurity/trivy/pkg/dependency/parser/julia/manifest.decodeManifest(0xc009103b90, 0xc00582bbc0)
github.com/aquasecurity/trivy/pkg/dependency/parser/julia/manifest/parse.go:122 +0x25e
github.com/aquasecurity/trivy/pkg/dependency/parser/julia/manifest.(*Parser).Parse(0xa6a0f40?, {0xa704f00, 0xc006cc4388})
github.com/aquasecurity/trivy/pkg/dependency/parser/julia/manifest/parse.go:59 +0x32d …
```
> fix: julia parser panicing

- docs/docs/references/configuration/cli/trivy_sbom.md
- pkg/commands/app.go
The `sbom` command can only scan a single SBOM file.
So we need to disable the `--skip-dir` and `--skip-files` flags.
- Close #8882
> fix(cli): disable `--skip-dir` and `--skip-files` flags for `sbom` command

- pkg/licensing/expression/expression.go
- pkg/licensing/expression/expression_test.go
- pkg/licensing/scanner.go
- pkg/licensing/scanner_test.go
- pkg/sbom/spdx/marshal.go
- Refactored the `Scan` method to utilize the new `Normalize` function, returning an expression instead of a string.
- Updated the `detectCategory` method to handle both simple and compound license expressions more effectively.
- Removed the deprecated `traverseLicenseExpression` and `compoundLicenseToCategory` methods to streamline the code.
- Removed `visited` as it's too much for a single license.
- Adjusted tests to reflect normalization signature changes and ensure license category detection accuracy.
- https://github.com/aquasecurity/trivy/pull/8816
> refactor(license): simplify compound license scanning

- pkg/iac/scanners/terraform/executor/executor.go
Removed result sorting from Terraform scanner, as it makes no sense at this stage. Sorting is done later - after scanning and result mapping is complete, where it is really needed.
> refactor(terraform): remove result sorting from scanner

- pkg/iac/scanners/cloudformation/scanner.go
Removed unused `ScanFile` method in `CloudFormation` scanner. Its functionality is fully covered by the `ScanFS` method.
> refactor(cloudformation): remove unused ScanFile method from Scanner

- pkg/fanal/applier/docker.go
This is a followup of #8910 where @knqyf263 rightfully pointed out that we shall not need a default content set for recent RHEL. Indeed there was another bug. This is required for future RHEL 10 support, yet RHEL 10 support is still partial.
Let's consider this Dockerfile:
```
[root@05f6cdd76f60 rhel10]# cat Dockerfile
FROM registry.access.redhat.com/ubi10/ubi:latest
RUN dnf install -y procps
```
We can build it, and look at the history of this image like this:
```
[root@05f6cdd76f60 rhel10]# docker build .                                                                                                                                                                            [+] Building 0.1s (6/6) FINISHED …
```
> fix(redhat): Also try to find buildinfo in root layer (layer 0)

- docs/docs/coverage/language/c.md
- docs/docs/coverage/language/elixir.md
- docs/docs/coverage/language/index.md
- docs/docs/scanner/misconfiguration/config/config.md
- docs/docs/scanner/misconfiguration/custom/schema.md
- pkg/commands/app.go
- pkg/types/report.go
This PR fixes found mistakes:
- name of `BuiltInK8sCompliances` array
- incorrect links in docs
- incorrect indents in docs
- Close #8949
> chore: fix errors and typos in docs

- pkg/db/db.go
- pkg/db/db_test.go
- Remove corrupted warning for first run.
- don't show `Skipping DB update...` for invalid matadata.json file.
- Close #8990
> fix: don't show corrupted trivy-db warning for first run

- pkg/iac/detection/detect.go
- pkg/iac/detection/detect_test.go
- pkg/iac/scanners/terraform/parser/parser.go
Add support for OpenTofu file extensions (`.tofu` and `.tofu.json`) to enable scanning of OpenTofu infrastructure as code files.
This PR adds detection support for OpenTofu file extensions (`.tofu` and `.tofu.json`). These files are functionally identical to Terraform files but use the OpenTofu extension, allowing Trivy to scan OpenTofu infrastructure as code files.
OpenTofu (`.tofu`) files are not recognized as infrastructure as code files.
```
$ trivy config /path/to/directory/with/tofu/files
2025-04-16 INFO [misconfig] Misconfiguration scanning is enabled
2025-04-16 INFO Detected config files num=0
```
OpenTofu (`.tofu`) files are correctly detected and scanned for security issues.
```
$ trivy config /path/to/directory/with/tofu/files
2025-04-16 INFO [misconfig] Misconfiguration …
```
> feat(misconf): add OpenTofu file extension support

- pkg/dependency/parser/nodejs/bun/parse.go
- pkg/dependency/parser/nodejs/bun/testdata/bun_happy.lock
`packages` array can use a different structure - https://bun.sh/reference/bun/BunLockFilePackageArray
So we need to parse `dependencies` from 2 or 3 elements of `package` array to avoid errors and missing dependencies
- Close #8995
> fix(nodejs): correctly parse `packages` array of `bun.lock` file

- pkg/iac/scanners/azure/value.go
- pkg/iac/scanners/azure/value_test.go
Time represented as int or float was not parsed because of early return from the method.
> fix(misconf): correct Azure value-to-time conversion in AsTimeValue

- pkg/commands/artifact/run.go
- pkg/notification/notice.go
- pkg/notification/notice_test.go
- pkg/notification/response.go
- pkg/notification/response_test.go
This optional constraint will be useful to prevent showing announcements in versions of Trivy where the announcement is not appropriate - for example when the announcement is that "from v0.64.0 x will happen", this shouldn't be shown in 0.64.0+
When date and version constraints are provided by the backend, both will be taken into account when deciding whether to print the announcements.
Version checking leverages the aqua go version semver parsing, if the version in the announcement isn't valid, the announcement won't be shown
- Close #9022
> feat(cli): add version constraints to annoucements

- docs/community/maintainer/pr-review.md
- mkdocs.yml
- Add PR review policy document to clearly define the review process
- Update mkdocs.yml to include the new policy page in the maintainer section
- Create `docs/community/maintainer/pr-review.md` with core principles:
- All changes must go through pull requests
- At least one CODEOWNER approval required
- Clear merge responsibility guidelines (author merges, except for hotfixes and external contributions)
> docs: add PR review policy for maintainers

- go.mod
- go.sum
- integration/docker_engine_test.go
- integration/integration_test.go
- pkg/fanal/image/daemon/containerd.go
- pkg/fanal/image/daemon/docker.go
- pkg/fanal/image/daemon/docker_test.go
- pkg/fanal/image/daemon/image.go
- pkg/fanal/image/daemon/image_test.go
- pkg/fanal/image/daemon/podman_test.go
- pkg/fanal/image/image_test.go
- pkg/fanal/test/integration/containerd_test.go
This PR updates Docker dependencies from v28.1.1 to v28.2.2 and addresses API compatibility issues that emerged with recent Docker versions, including fixing container cleanup errors in integration tests.
- Replace deprecated `ImageInspectWithRaw` with `ImageInspect` API
- Update Docker dependencies to v28.2.2
- Update testdocker to v0.0.0-20250616060700-ba6845ac6d17 for Docker v28.2.2 compatibility (see aquasecurity/testdocker#26)
- Remove usage of removed container configuration fields
- **Files**: `pkg/fanal/test/integration/containerd_test.go`
- **Issue**: Docker v28 API changes affected how the `ArgsEscaped` field is populated in image config
- **Solution**: Updated test expectations to expect `ArgsEscaped: true` instead of `false`
- **Files**: `go.mod`, `go.sum`
- **Issue**: Docker …
> chore(deps): update Docker to v28.2.2 and fix compatibility issues

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
In #6070 a change was made inject a "fake" `USER <name>` line when reconstructing the `Dockerfile` from an OCI/Docker image manifest/config. 
However, it only used this value when a `USER <name>` directive was _not_ found in the history. This is incorrect, in practice the `Config.User` value always takes precedence/is used by a container runtime. This PR ensures that if a value is configured, it is always appended to the reconstructed history.
We ran into this because we had an odd image which contained `USER root` in the Dockerfile history but was actually configured to run as `nonroot` in the final rendered image config (not built via Buildkit). 
I didn't create an issue for this, just the fix PR.
- #6070
> fix(misconf): .Config.User always takes precedence over USER in .History

- pkg/iac/rego/load.go
- pkg/iac/rego/load_test.go
- Close https://github.com/aquasecurity/trivy/issues/8944
> fix(misconf): reduce log noise on incompatible check

- pkg/iac/adapters/terraform/aws/iam/convert.go
- pkg/iac/adapters/terraform/aws/iam/policies_test.go
- pkg/iac/terraform/attribute.go
This PR adds partial evaluation of template expressions used when writing AWS policies in Terraform. Those parts of the template that could not be evaluated due to errors or unknown values are replaced with `__UNRESOLVED__` literal.
- Close https://github.com/aquasecurity/trivy/issues/8797
> feat(terraform): add partial evaluation for policy templates

- pkg/iac/rego/filter.go
- pkg/iac/rego/filter_test.go
- pkg/iac/rego/load.go
- pkg/iac/rego/metadata.go
- pkg/iac/rego/options.go
- pkg/iac/rego/scanner.go
This PR refactors Rego module filtering to use composable functional filters. This improves readability, maintainability, and makes testing individual filters easier. Unit tests are added for all filters.
> refactor(misconf): rewrite Rego module filtering using functional filters

- pkg/fanal/image/remote.go
- pkg/fanal/image/remote_test.go
Add validation to reject OCI artifacts that are not regular container images during remote image retrieval.
- Close https://github.com/aquasecurity/trivy/issues/9053
- Add artifact type validation in `tryRemote` function
- Return error when `ArtifactType` is not empty (indicating non-container artifacts like Helm charts, WASM modules)
- Add comprehensive tests for the `tryRemote` function including:
- Successful image retrieval
- Image not found scenarios  
- Unsupported artifact type validation
Manual testing confirms the validation works correctly:
```bash
$ ./trivy image --scanners vuln --image-src remote ghcr.io/knqyf263/helm-test-chart:0.1.0
2025-06-19T12:40:53+04:00    INFO    [vuln] Vulnerability scanning is enabled
To suppress version checks, run Trivy scans with the …
```
> feat: reject unsupported artifact types in remote image retrieval

- docs/docs/coverage/language/index.md
- docs/docs/coverage/language/python.md
Fix typo (`META-DATA`) in `wheel` file name.
> docs(python): fix type with METADATA file name

- integration/testdata/conda-cyclonedx.json.golden
- integration/testdata/fluentd-multiple-lockfiles-short.cdx.json.golden
- integration/testdata/fluentd-multiple-lockfiles.cdx.json.golden
- integration/testdata/npm-cyclonedx.json.golden
- pkg/licensing/expression/types.go
- pkg/log/logger.go
- pkg/sbom/cyclonedx/marshal.go
- pkg/sbom/cyclonedx/marshal_test.go
- pkg/sbom/spdx/marshal.go
- pkg/sbom/spdx/marshal_private_test.go
We need to use one of three correct field for component license (see #9042 for more details)
Normalize and check each package license:
1. Single license:
1.1. valid SPDX ID use licenseChoise.License.ID
1.2. text license - use licenseChoise.License.Name
1.3. invalid SPDX ID - use licenseChoise.License.Name
2. SPDX expression:
1.4. all parts of expression are valid SPDX IDs/SPDX exceptions - use licenseChoise.Expression
1.5. for other cases use licenseChoise.License.Name
CycloneDX report for `centos:8`:
Before
```
...
"license": {
"name": "GPLv2+"
}
...
"license": {
"name": "Public Domain"
}
...
"licenses": [
{
"license": {
"name": "GPLv2+ and LGPLv2+"
}
}
...
"license": {
"name": "BSD with advertising"
}
```
After:
```
...
"license": {
"id": "GPL-2.0-or-later"
}
...
"license": {
"name": …
```
> fix(sbom): use correct field for licenses in CycloneDX reports

- goreleaser.yml
This PR removes FreeBSD 32-bit (386) support from Trivy's build configuration.
FreeBSD 32-bit builds are failing due to type mismatches in the `modernc.org/libc` library, which is a dependency of Trivy. The upstream library has compatibility issues with FreeBSD 32-bit architectures that cause build failures.
- Removed `386` architecture from the `build-bsd` section in `goreleaser.yml`
- Added a comment explaining why FreeBSD 32-bit is no longer supported
- No changes needed for `goreleaser-canary.yml` as it doesn't build for FreeBSD
Upstream issue: https://gitlab.com/cznic/libc/-/issues/45
The issue shows multiple type mismatch errors when building on FreeBSD 32-bit:
- Cannot use `int64` values where `int32` is expected
- Type mismatches between `uint64` and `size_t`
- These errors …
> chore: drop FreeBSD 32-bit support

- pkg/fanal/image/image.go
This change adds debug logging to clearly show which image source (docker, remote, containerd, podman) was used to find an image during scanning.
The main benefits are:
- Users can easily identify when their image is being pulled from an unexpected source
- Especially helpful when users expect to use local images but a remote registry is used instead (and vice versa)
The implementation:
- Adds `[image]` prefix to logs using `log.WithContextPrefix` and `log.PrefixContainerImage`
- Uses context-aware logging with `DebugContext` and `WarnContext`
- Shows both image name and source in the debug message
```
2025-07-08T14:42:05+04:00	DEBUG	[image] Detected image ID	image_id="sha256:5a3b4d76fdf28473d4a7b7d0aadb65147bc4e5d870fb5cf57f837fda315ecd6d"
```
```
2025-07-08T14:42:05+04:00	DEBUG	[image] …
```
> chore: add debug log to show image source location

- pkg/fanal/applier/docker.go
- pkg/fanal/applier/docker_test.go
We added filter to remove duplicate OS packages in #8298.
But there are cases when we don't need to remove duplicates, e.g. when we found 2 same rpm archives from different locations.
That is why we need to check `Package.FilePath` when removing duplicate packages.
> fix: also check `filepath` when removing duplicate packages

- .github/workflows/cache-test-assets.yaml
- .github/workflows/cache-test-images.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
This PR optimizes golangci-lint performance in CI by implementing a cache-based strategy.
- **Added `cache-test-assets.yaml`**: Creates lint cache on main branch pushes
- **Modified `test.yaml`**: PRs restore cache from main branch but skip saving new cache (`skip-save-cache: true`)
- **Cache isolation**: To work around GitHub Actions cache restrictions, where PRs cannot access caches in other branches, the new workflow stores cache in the main branch
- **Trigger change**: Changed from daily cron to main branch push
- - **Reduced 429 errors**: Even if test images cache misses occur, Trivy DB migrated to mirror.gcr.io reduces rate limiting risks
- **Reduced cache eviction**: By disabling lint cache saves in PRs, test image caches are less likely to be evicted
Verified the optimization in …
> ci: optimize golangci-lint performance with cache-based strategy

- .github/workflows/auto-ready-for-review.yaml
This PR fixes the auto-ready-for-review workflow that was failing with `TypeError: Cannot read properties of undefined (reading 'number')` when processing pull requests from forked repositories.
The workflow was using `context.payload.workflow_run.pull_requests[0].number` to get the PR number, but for forked repositories, the `pull_requests` array is often empty. This is a known issue mentioned in [GitHub community discussions](https://github.com/orgs/community/discussions/25220) where the `workflow_run` event doesn't properly populate the `pull_requests` array when triggered by workflows from forked repositories.
**Solution**: Replace the direct array access with GitHub CLI (`gh pr view`) to reliably retrieve PR information by using proper branch format (`owner:branch` for forks, …
> ci: use gh pr view to get PR number for forked repositories in auto-ready workflow

- .github/workflows/canary.yaml
Add cache deletion step after uploading artifacts in canary workflow to prevent unnecessary cache accumulation.
This change adds a cleanup step that deletes the cache entry after all artifacts are successfully uploaded, preventing the cache from taking up storage space unnecessarily. Since GitHub Actions has a 10GB cache limit, removing unused caches helps prevent important caches from being evicted.
- Add `CACHE_KEY` environment variable at job level to avoid duplication
- Add cache deletion step using GitHub CLI after all artifacts are uploaded
- Prevents cache accumulation that wastes storage space
- Avoids hitting GitHub's 10GB cache limit which could cause important caches to be evicted
- Improves maintainability by using environment variables instead of duplicating cache keys
> ci: delete cache after artifacts upload in canary workflow

- pkg/iac/adapters/terraform/aws/iam/roles_test.go
- pkg/iac/scanners/terraform/parser/evaluator.go
for_each was being evaluated before the locals were evaluated which
was making it iterate over a `cty.DynamicPseudoType` which meant it
was iterating over the keys of a single instance resource instead of
the values of the for_each.
See the tests added for proof of the problem.   I've left the debug log
lines in because they were useful fixing the issue but I can remove them
if we don't want them.
You can see this when running `--debug`:
```
❯ go run cmd/trivy/main.go conf ../tfparse/tests/terraform/for_each --debug
2025-07-07T15:00:57-04:00	DEBUG	[terraform evaluator] Expanded block into clones via 'for_each' attribute.	module="root" block="aws_iam_role_policy_attachment.administrative_policy_attachment" clones=4
```
We expect 2 clones, not 4 with my example.   With this PR:
``` …
```
> fix(terraform): `for_each` on a map returns a resource for every key

- pkg/iac/adapters/terraform/google/compute/networks.go
- pkg/iac/adapters/terraform/google/compute/networks_test.go
- pkg/iac/providers/google/compute/subnetwork.go
- pkg/iac/rego/schemas/cloud.json
Added private ip google access attribute to subnetwork in order to test it in a new check.
> feat(misconf): add private ip google access attribute to subnetwork

- pkg/commands/artifact/run.go
When running with the number of cli args < 2 panic "Runtime Error: Index out of range [1] with Length 1" on the file 
https://github.com/aquasecurity/trivy/blob/60723e6cfce82ede2863cf545a189c581246f4e9/pkg/commands/artifact/run.go#L129
I replaced the call to lo.Ternary with lo.TernaryF, thereby eliminating the call to os.Args[1] when len(os.Args) < 2
> fix(cli): panic: attempt to get os.Args[1] when len(os.Args) < 2

- pkg/sbom/io/decode.go
- pkg/sbom/io/decode_test.go
This PR fixes an issue where out-of-graph OS packages (packages not directly connected to the OS component in the dependency graph) were not being properly merged with existing PackageInfo entries containing in-graph OS packages during SBOM decoding. This resulted in missing OS packages in the final SBOM output.
When both in-graph and out-of-graph OS packages exist, only in-graph packages were included in the final output, while out-of-graph packages were excluded.
This fix applies to all operating systems and SBOM formats (CycloneDX, SPDX), not just the Amazon Linux 2023 CycloneDX example used for testing.
- Modified `addOrphanPkgs` function in `pkg/sbom/io/decode.go` to use `lo.FindIndexOf` for finding existing PackageInfo entries with empty FilePath
- Out-of-graph OS packages are now …
> fix(sbom): merge in-graph and out-of-graph OS packages in scan results

- go.mod
- go.sum
- pkg/detector/library/compare/npm/compare.go
- pkg/detector/library/compare/npm/compare_test.go
This PR updates the NPM vulnerability comparison logic to include prerelease versions when matching constraints. The change enables proper detection of vulnerabilities in packages with prerelease versions (e.g., 1.45.1-lts.1).
GitHub advisory database don't use npm semver rules for prerelease versions - https://github.com/github/advisory-database/issues/5795#issuecomment-3044749160
But the current implementation was not properly handling prerelease versions when evaluating vulnerability constraints. This meant that packages with prerelease versions could be incorrectly assessed as safe when they should be flagged as vulnerable.
before:
```bash
➜ trivy -q rootfs package.json 
Report Summary
┌──────────────┬──────────┬─────────────────┬─────────┐
│    Target    │   Type   │ Vulnerabilities …
```
> fix(nodejs): don't use prerelease logic for compare npm constraints 

- docs/docs/coverage/os/index.md
- pkg/detector/ospkg/alma/alma.go
This pr adds vul support for almalinux 10
Scanning AlmaLinux:10 image 
`almalinux:10` with manually installed `git-core-2.47.1-2.el9_6.aarch64.rpm `:
```bash
➜  ./trivy image almalinux:10-with-git-core 
2025-07-17T12:52:24+06:00       INFO    [vuln] Vulnerability scanning is enabled
2025-07-17T12:52:24+06:00       INFO    [secret] Secret scanning is enabled
2025-07-17T12:52:24+06:00       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-07-17T12:52:24+06:00       INFO    [secret] Please see also https://trivy.dev/dev/docs/scanner/secret#recommendation for faster secret detection
2025-07-17T12:52:24+06:00       INFO    Detected OS     family="alma" version="10.0"
2025-07-17T12:52:24+06:00       INFO    [alma] Detecting …
```
> feat(alma): add AlmaLinux 10 support

- ci/deploy-rpm.sh
Update the script for generating rpms to use the get.trivy.dev download path
setting the `trivy.repo` to below then `dnf|yum update`
```
[trivy]
name=Trivy repository
baseurl=https://get.trivy.dev/rpm/releases/$basearch/
gpgcheck=1
enabled=1
gpgkey=https://get.trivy.dev/rpm/public.key
```
Checking where the installation is going to come from
```
$ dnf repoquery --location trivy
Updating and loading repositories:
Repositories loaded.
https://fedora.mirrorservice.org/fedora/linux/releases/42/Everything/aarch64/os/Packages/t/trivy-0.60.0-1.fc42.aarch64.rpm
https://fedora.mirrorservice.org/fedora/linux/updates/42/Everything/aarch64/Packages/t/trivy-0.63.0-1.fc42.aarch64.rpm
https://get.trivy.dev/rpm/v0.64.1/trivy_0.64.1_Linux-ARM64.rpm <------------------
```
Installing successfully
```
$ dnf …
```
> chore: update the rpm download Update

- .github/workflows/canary.yaml
This PR fixes the canary build failure by removing the invalid `--confirm` flag from the `gh cache delete` command.
The canary build was failing with:
```
Run gh cache delete "$CACHE_KEY" --confirm
unknown flag: --confirm
Usage:  gh cache delete [<cache-id> | <cache-key> | --all] [flags]
```
The `gh cache delete` command does not have a `--confirm` flag, so this PR removes it.
- Fixes the canary build failure at https://github.com/aquasecurity/trivy/actions/runs/16442985211/job/46469323654
- https://github.com/aquasecurity/trivy/pull/9233
> ci: remove invalid `--confirm` flag from `gh cache delete` command in canary builds

- go.mod
- go.sum
- pkg/detector/ospkg/alma/alma.go
- pkg/detector/ospkg/alpine/alpine.go
- pkg/detector/ospkg/amazon/amazon.go
- pkg/detector/ospkg/azure/azure.go
- pkg/detector/ospkg/chainguard/chainguard.go
- pkg/detector/ospkg/debian/debian.go
- pkg/detector/ospkg/echo/echo.go
- pkg/detector/ospkg/minimos/minimos.go
- pkg/detector/ospkg/oracle/oracle.go
- pkg/detector/ospkg/photon/photon.go
- pkg/detector/ospkg/rocky/rocky.go
- pkg/detector/ospkg/rootio/rootio.go
- pkg/detector/ospkg/suse/suse.go
- pkg/detector/ospkg/ubuntu/ubuntu.go
- pkg/detector/ospkg/wolfi/wolfi.go
We refactored `Getter` interface in trivy-db - https://github.com/aquasecurity/trivy-db/pull/558
Use `Getter` interface ( + `GetParams`) for all trivy-db sources (except RedHat)
> refactor(db): use `Getter` interface with `GetParams` for trivy-db sources

- goreleaser.yml
This PR updates the formula generated by goreleaser to have the
get.trivy.dev download url to count the downloads
The change updates the formula to have the following verifiable links
- https://get.trivy.dev/trivy?version=0.64.1&os=darwin&arch=amd64
- https://get.trivy.dev/trivy?version=0.64.1&os=darwin&arch=arm64
- https://get.trivy.dev/trivy?version=0.64.1&os=linux&arch=amd64
- https://get.trivy.dev/trivy?version=0.64.1&os=linux&arch=arm64
```bash 
brew install --formula ./dist/homebrew/trivy.rb
```
gives the result below, showing that the download is 302'd through get.trivy.dev
```
==> Fetching trivy
==> Downloading https://get.trivy.dev/trivy?version=0.64.1&os=darwin&arch=arm64
==> Downloading from https://release-assets.githubusercontent.com/github-production-release-asset/180687624/8 …
```
> chore: update template URL for brew formula

- cmd/trivy/main.go
- pkg/commands/signal.go
- pkg/oci/artifact.go
- pkg/rpc/server/listen.go
- pkg/x/io/io.go
- pkg/x/io/io_test.go
This PR implements graceful shutdown for Trivy by adding signal handling for SIGINT and SIGTERM. When a signal is received, Trivy will attempt to complete ongoing operations before exiting. Users can send a second signal to force immediate termination.
When pressing Ctrl+C, Trivy immediately terminates without cleanup:
```
$ trivy image alpine:latest
^C
```
Trivy now attempts graceful shutdown with user feedback:
```
$ trivy image alpine:latest
^C2024-07-23T10:00:00.000+0900	INFO	Received signal, attempting graceful shutdown...
2024-07-23T10:00:00.000+0900	INFO	Press Ctrl+C again to force exit
```
Server mode also supports graceful shutdown:
```
$ trivy server
^C2024-07-23T10:00:00.000+0900	INFO	Received signal, attempting graceful shutdown...
2024-07-23T10:00:00.000+0900	INFO	Press …
```
> feat: add graceful shutdown with signal handling

- cmd/trivy/main.go
- pkg/commands/signal.go
This PR fixes an issue where the graceful shutdown message "Received signal, attempting graceful shutdown..." was being displayed even during normal program exits.
- Related to #9242
The issue was caused by the `defer stop()` call in `main.go` which was canceling the context on normal exit, triggering the shutdown message in the signal handler goroutine.
1. Modified `NotifyContext()` to return only the context (removed the stop function)
2. Removed the `defer stop()` call from `main.go`
Now the graceful shutdown message only appears when an actual signal (SIGINT or SIGTERM) is received, not during normal program termination.
> fix: prevent graceful shutdown message on normal exit

- pkg/fanal/secret/scanner.go
- pkg/fanal/secret/scanner_test.go
- pkg/fanal/secret/testdata/invalid-utf8.txt
This PR adds UTF-8 validation to the secret scanner to prevent protobuf marshalling errors when scanning files with invalid UTF-8 content, such as translation files.
The issue occurred when scanning repositories like [juice-shop](https://github.com/juice-shop/juice-shop) that contain files with invalid UTF-8 sequences. The secret scanner would fail with 'string field contains invalid UTF-8' when marshalling results to protobuf format.
```
$ trivy repo https://github.com/juice-shop/juice-shop --server http://localhost:4954
...
2025-07-28T10:13:33+04:00       FATAL   Fatal error     repo scan error: scan error: scan failed: failed analysis: remote repository error: failed to store blob (sha256:e3e730cdeff2f1c66082bc550dcdd2226b8070382f6451040a13d203e1ff5325) in cache: unable to store cache …
```
> fix(secret): add UTF-8 validation in secret scanner to prevent protobuf marshalling errors

- pkg/flag/remote_flags.go
- pkg/flag/remote_flags_test.go
Add validation to ensure the `--server` flag includes HTTP or HTTPS schema. When the schema is missing, return a user-friendly error message suggesting proper usage (e.g., http://localhost:4954 instead of localhost:4954).
```bash
$ trivy image --server localhost:4954 alpine:latest
2025-07-29T17:28:51+04:00	FATAL	Fatal error	flag error: unable to convert flags to options: server address must include HTTP or HTTPS schema (e.g., http://localhost:4954 or https://localhost:4954)
```
```bash
$ trivy image --server ftp://localhost:4954 alpine:latest
2025-07-29T17:30:04+04:00	FATAL	Fatal error	flag error: unable to convert flags to options: server address must use HTTP or HTTPS schema, got 'ftp' (e.g., use http://localhost:4954 instead of ftp://localhost:4954)
```
```bash
$ trivy image --server …
```
> feat(flag): add schema validation for `--server` flag

- pkg/commands/artifact/run.go
- pkg/k8s/commands/run.go
- pkg/k8s/scanner/scanner_test.go
Suppose the user has an unexpected ordering of flags in their Trivy command. In that case, the simple approach of reading the first OS argument fails, and the information in the `Trivy-Command` header for telemetry is incorrect.
Rather than using the `os.Args`, this PR passes the `targetKind` into the `NewRunner` creation so that it can be used as the command name
Taking the following example
```bash
trivy -d image nginx
```
**Before**
`call req.Header.Get("Trivy-Command")` would result in `-d` as the first `os.Arg` would be returned
**With Change**
With this change, we now get consistently the correct command
`call req.Header.Get("Trivy-Command")` returns "image"
- #9259
> fix(cli): ensure correct command is picked by telemetry

- pkg/mapfs/file.go
- pkg/mapfs/fs_test.go
This PR fixes error shadowing in file.glob and ensures invalid glob patterns. Also adds a test case for malformed patterns.
> fix(fs): avoid shadowing errors in file.glob

- pkg/detector/ospkg/detect.go
- pkg/scan/ospkg/scan.go
This PR simplifies the `Detect` function signature in `pkg/detector/ospkg` by removing unused parameters and using `types.ScanTarget` to pass scan target information.
1. Removed the unused second parameter (was always an empty string `""`)
2. Removed the unused `time.Time` parameter (was always `time.Time{}`)
3. Consolidated individual parameters (`osFamily`, `osName`, `repo`, `pkgs`) into a single `types.ScanTarget` parameter
```go
func Detect(ctx context.Context, _, osFamily ftypes.OSType, osName string, repo *ftypes.Repository, _ time.Time, pkgs []ftypes.Package)
```
```go
func Detect(ctx context.Context, target types.ScanTarget, _ types.ScanOptions)
```
- Makes the function signature cleaner and more maintainable
- Aligns with the pattern used by other scanners in the codebase (e.g., …
> refactor: simplify Detect function signature

- pkg/iac/scanners/helm/parser/parser.go
- pkg/iac/scanners/helm/parser/parser_tar.go
- pkg/iac/scanners/helm/parser/parser_test.go
Refactor the parser to avoid mutating the input filesystem by tracking files along with their corresponding filesystem instances. Archives are now unpacked into separate in-memory filesystems instead of being merged.
Benefits:
- Improved code clarity and maintainability
- Better isolation of unpacked archives
- Prevention of side effects on the original filesystem
> refactor(misconf): decouple input fs and track extracted files with fs references

- pkg/notification/notice.go
Do not log context.Canceled and context.DeadlineExceeded errors as debug messages when the version check API request is interrupted. These errors are expected when scans complete before the API request finishes and should not be logged as failures.
Before this fix, the following debug message would appear:
```
DEBUG [notification] Failed getting response from Trivy api err="Get \"https://check.trivy.dev/updates\": context canceled"
```
After this fix, context cancellation errors are silently handled as expected behavior.
> fix: suppress debug log for context cancellation errors

- pkg/iac/scanners/terraform/parser/load_module.go
- pkg/iac/scanners/terraform/parser/parser.go
- pkg/iac/scanners/terraform/parser/parser_test.go
The current logic for resolving paths to submodules from sources like GitHub, Bitbucket, and registry-based modules (e.g., hashicorp/consul/aws//modules/consul-cluster) is incorrect.
For such modules, Trivy checks whether the module path from metadata ends with the relative path from the module source. If it doesn’t, Trivy appends the relative path to the existing metadata path. This workaround only works reliably for registry modules, where the source is clean and doesn’t contain additional parameters.
However, this logic breaks for Git-based modules, since their sources often include query parameters (e.g., ?ref=v1.2.0), which causes incorrect path resolution.
This logic is unnecessary because the metadata in .terraform/modules/modules.json already contains the full and correct path to …
> fix(misconf): preserve original paths of remote submodules from .terraform

- pkg/iac/scanners/terraform/parser/evaluator.go
- pkg/iac/scanners/terraform/parser/load_module_metadata.go
- pkg/iac/scanners/terraformplan/snapshot/scanner.go
- pkg/iac/scanners/terraformplan/snapshot/snapshot.go
- pkg/iac/scanners/terraformplan/snapshot/snapshot_test.go
This PR updates the Terraform plan scanner to load remote modules from the local .terraform directory instead of downloading them from external sources like the Terraform Registry or GitHub. This makes scanning more reliable and independent of network availability.
> feat(terraform): use .terraform cache for remote modules in plan scanning

- Dockerfile
- Dockerfile.canary
Docker images should respect the process signals trivy supports since 0.65.0.
> chore(deps): bump alpine from 3.21.4 to 3.22.1

- pkg/iac/scanners/helm/scanner.go
- pkg/iac/scanners/helm/test/parser_test.go
- pkg/iac/scanners/helm/test/scanner_test.go
This PR fixes the ignoring of misfigurations in Helm charts when the chart is in a subdirectory. The `archived chart` test case caught this when refactoring the test.
> fix(misconf): ensure ignore rules respect subdirectory chart paths

- pkg/iac/adapters/terraform/google/storage/adapt.go
- pkg/iac/adapters/terraform/google/storage/adapt_test.go
See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#log_bucket-1
> fix(misconf): use correct field log_bucket instead of target_bucket in gcp bucket

- pkg/plugin/index.go
Fixes plugin directory removal during index updates by changing the download strategy for index.yaml files. Previously, the plugin manager would use downloader.Download() which could inadvertently remove the entire plugin directory
during index updates.
See the following code:
https://github.com/aquasecurity/trivy/blob/8f5b56005a4e8752976524750089dc9ea2c91e40/pkg/downloader/download.go#L58-L60
This change ensures that installed plugins are preserved when updating the plugin index.
The fix implements a safer approach by:
- Downloading the index file to a temporary directory using downloader.DownloadToTempDir()
- Explicitly copying only the index.yaml file to the plugin directory using fsutils.CopyFile()
Before:
```bash
➜ trivy plugin list
Installed Plugins:
Name:    referrer
Version: 0.3.1 …
```
> fix(plugin): don't remove plugins when updating index.yaml file

- docs/commercial/compare.md
Fix broken link to "Built-in Checks" from "IaC/CSPM scanning" table on comparison page.
Introduced in #8045.
> docs: Fix broken link to "Built-in Checks"

- pkg/fanal/analyzer/fs.go
Previously, files were saved under /tmp/analyzer-fs-*/file-*, and since Cleanup removed /tmp/analyzer-fs-*, the cleanup process completed successfully.
However, due to the following commit, analyzer-composite-* and analyzer-file-* are now placed separately under /tmp/trivy-*. 
https://github.com/aquasecurity/trivy/commit/8f5b56005a4e8752976524750089dc9ea2c91e40
Considering the previous behavior, I think analyzer-file-* should be created under /tmp/trivy-*/analyzer-composite-*/.
> fix: create temp file under composite fs dir

- .github/workflows/auto-close-issue.yaml
- .github/workflows/auto-update-labels.yaml
- .github/workflows/backport.yaml
- .github/workflows/cache-test-assets.yaml
- .github/workflows/canary.yaml
- .github/workflows/mkdocs-dev.yaml
- .github/workflows/mkdocs-latest.yaml
- .github/workflows/publish-chart.yaml
- .github/workflows/release-please.yaml
- .github/workflows/release.yaml
- .github/workflows/reusable-release.yaml
- .github/workflows/roadmap.yaml
- .github/workflows/scan.yaml
- .github/workflows/spdx-cron.yaml
- .github/workflows/stale-issues.yaml
- .github/workflows/test-docs.yaml
- .github/workflows/test.yaml
- .github/workflows/triage.yaml
Migrates all GitHub Actions from version tags to SHA pinning to comply with GitHub's new policy that can enforce SHA pinning for enhanced supply chain security.
GitHub has introduced a new Actions policy feature that can [enforce SHA pinning and block specific actions](https://github.blog/changelog/2025-08-15-github-actions-policy-now-supports-blocking-and-sha-pinning-actions/). Organizations and repositories can now require workflows to use full commit SHAs instead of version tags, causing workflows without SHA pinning to fail.
- **New GitHub capability**: Repositories can now enforce SHA pinning, making non-SHA references fail
- **Supply chain security**: SHA pinning prevents malicious code injection through moved or compromised tags
- **Immutability**: Commit SHAs provide immutable …
> ci: migrate GitHub Actions from version tags to SHA pinning

- pkg/iac/scanners/terraform/parser/load_module.go
- pkg/iac/scanners/terraform/parser/modules.go
- pkg/iac/scanners/terraform/parser/modules_test.go
- pkg/iac/scanners/terraform/parser/parser_test.go
- Close https://github.com/aquasecurity/trivy/issues/9397
> fix(misconf): ensure module source is known

- internal/gittest/server.go
- pkg/fanal/artifact/repo/git_test.go
- pkg/iac/scanners/terraform/parser/resolvers/cache_integration_test.go
- pkg/plugin/manager_unix_test.go
Add HTTP basic authentication functionality to the Git test server in gittest package. This allows testing authentication scenarios in Git repository scanning.
- Added `Options` struct with `Username` and `Password` fields to configure authentication
- Modified `NewServer` and `NewTestServer` to accept `Options` parameter directly
- Implemented authentication using gitkit's `AuthFunc`
- Added tests for both environment variable and URL-embedded authentication
The implementation includes tests for:
- Environment variable authentication (GITHUB_TOKEN, GITLAB_TOKEN)
- URL-embedded credentials (username:password@host format)
- Authentication failure scenarios
- Local repository scanning after authenticated clone
> test: add HTTP basic authentication to git test server

- pkg/dependency/parser/nodejs/pnpm/parse.go
- pkg/dependency/parser/nodejs/pnpm/parse_test.go
- pkg/dependency/parser/nodejs/pnpm/parse_testcase.go
- pkg/dependency/parser/nodejs/pnpm/testdata/pnpm-lock_v9.yaml
- pkg/dependency/parser/nodejs/pnpm/testdata/pnpm-lock_v9_same-vers-diff-peers.yaml
- pkg/dependency/parser/nodejs/pnpm/types.go
- pkg/fanal/types/package.go
This PR enhances pnpm lockfile parsing to properly handle packages with the same version but different peer dependencies. The key improvement addresses cases where `pnpm.lock` contains multiple package instances for the same name/version combination due to different peer dependency contexts.
Key Changes
- Refactored package ID generation: Modified the parser to use snapshot strings (dependency paths) as Package.ID instead of simple name@version format
- Enhanced snapshot processing: Updated resolvedSnapshots to store arrays of snapshotPackage structs, allowing multiple instances per package
- Improved dependency resolution: Dependencies now use original dependency paths to maintain proper relationships between packages with different peer contexts
- Added package sorting: Enhanced the …
> fix(nodejs): use snapshot string as `Package.ID` for pnpm packages

- go.mod
Cancelling a query (e.g. by cancelling the context passed to one of the query methods) during a call to the Scan method of the returned Rows can result in unexpected results if other queries are being made in parallel. This can result in a race condition that may overwrite the expected results with those of another query, causing the call to Scan to return either unexpected results from the other query or an error.
> chore: bump Go to 1.24.7

- docs/docs/configuration/reporting.md
Add information about using `-` for the secret/license scanner in the summary table when no findings are found.
- Close #9440
> docs(report): add nuanses about secret/license scanner in summary table

- .github/workflows/release.yaml
When performing a release, we need to trigger the release mechanism in trivy-chocolatey to push a new package.
This update adds a new section to us gh workflow to trigger the workflow_dispatch trigger with the latest version (ref_name) as the version.
- Close #9461
> chore: Update release flow to include chocolatey

- .github/dependabot.yml
Add a 3-day cooldown period for Go module dependency updates in Dependabot configuration to protect against supply chain attacks and early-release bugs.
Recent supply chain attacks have shown that malicious packages are often detected and removed within hours or days of publication:
- npm debug and chalk packages compromised
- S1ngularity campaign targeting NX packages  
- Various other incidents across package ecosystems
The cooldown period provides:
1. **Supply chain protection**: Buffer time for security scanners and the community to detect malicious code
2. **Stability**: Avoid immediate bugs in fresh releases
> ci(deps): add 3-day cooldown period for Dependabot updates

- docs/tutorials/misconfiguration/terraform.md
Fixes a minor typo I noticed in the Terraform docs yesterday.
> docs: Fix typo in terraform docs

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
This PR fixes restoring Dockerfile instructions from image history when builder metadata suffixes (e.g. |inheritLabels=false) are present.
- Close https://github.com/aquasecurity/trivy/issues/9485
> fix(misconf): strip build metadata suffixes from image history

- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile.go
- pkg/fanal/analyzer/imgconf/dockerfile/dockerfile_test.go
Some Dockerfiles use legacy ENV in the form:
```dockerfile
ENV key val1 val2
```
Docker stores this in image history as:
```dockerfile
❯ docker history --no-trunc --format '{{json .}}' diss-9494 | jq -r '.CreatedBy'
ENV TEST=val1 val2
...
```
This can cause parsing errors, because extra tokens (e.g., `val2`) are treated as separate keys.
This PR fixes the issue by wrapping ENV values in quotes, preserving internal spaces, so that the Dockerfile parser correctly interprets legacy ENV instructions.
- Close https://github.com/aquasecurity/trivy/issues/9496
> fix(misconf): wrap legacy ENV values in quotes to preserve spaces

- pkg/dependency/parser/nodejs/npm/parse.go
- pkg/dependency/parser/nodejs/npm/parse_test.go
- pkg/dependency/parser/nodejs/npm/parse_testcase.go
- pkg/dependency/parser/nodejs/npm/testdata/package-lock_v3_with_workspace_as_object.json
- pkg/dependency/parser/nodejs/packagejson/parse.go
This PR fixes npm workspace parsing to properly handle workspace configurations defined as objects rather than just string arrays. The npm workspaces field supports two formats:
- String array: "workspaces": ["packages/*", "plugins/*"]
- Object format: "workspaces": {"packages": ["packages/*", "plugins/*"]}
- Updated npm lock parser: Changed Workspaces field type from []string to any in the Package struct to accommodate both formats
- Exported ParseWorkspaces function: Made the workspace parsing function public so it can be reused across npm-related parsers
- Enhanced workspace parsing logic: The ParseWorkspaces function now properly extracts workspace paths from both string arrays and object configurations
- Added comprehensive test coverage: Included test data and test cases for …
> fix(nodejs): parse workspaces as objects for package-lock.json files

- pkg/iac/scanners/cloudformation/parser/fn_find_in_map.go
- pkg/iac/scanners/cloudformation/parser/fn_find_in_map_test.go
Add support for Fn::FindInMap enhancements, including default values ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/intrinsic-function-reference-findinmap-enhancements.html)).
Also support list values in Mappings, as allowed: "The values can be of type String or List." ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html#mappings-section-structure-syntax)).
> feat(cloudformation): support default values and list results in Fn::FindInMap

- cmd/trivy/main.go
- pkg/cache/fs.go
- pkg/commands/artifact/run.go
- pkg/commands/run.go
- pkg/k8s/commands/run.go
This PR improves user experience by displaying a documentation URL when database lock errors occur, guiding users to troubleshooting resources. This addresses cases where users encounter lock errors but cannot find the relevant documentation, as seen in discussions like #9525 and #9472.
The error handling has been centralized in `pkg/commands/run.go` to eliminate code duplication and ensure consistent messaging.
- Added new `Run()` function in `pkg/commands/run.go` with centralized error handling
- Display error message with troubleshooting URL for `bberrors.ErrTimeout` 
- Removed duplicate timeout error handling from artifact and k8s commands
- Fixed import to use `bberrors` from `go.etcd.io/bbolt/errors` package instead of deprecated `bolt.ErrTimeout`
- Addresses user confusion in …
> feat: add documentation URL for database lock errors

- .github/workflows/backport.yaml
- validate the backport workflow’s extracted branch name before exporting to `GITHUB_ENV`
- reject empty or unsafe names while allowing dotted release branches like `release/v0.53.1`
- verified on knqyf263/trivy#69 that safe names proceed (workflow run [18117590123](https://github.com/knqyf263/trivy/actions/runs/18117590123)) and unsafe names abort immediately (run [18117630437](https://github.com/knqyf263/trivy/actions/runs/18117630437) and [18121474365](https://github.com/knqyf263/trivy/actions/runs/18121474365))
> fix: validate backport branch name

- internal/cachetest/cache.go
- pkg/cache/cache.go
- pkg/cache/fs.go
- pkg/cache/fs_test.go
- pkg/cache/memory.go
- pkg/cache/memory_test.go
- pkg/cache/nop.go
- pkg/cache/redis.go
- pkg/cache/redis_test.go
- pkg/cache/remote.go
- pkg/cache/remote_test.go
- pkg/commands/clean/run.go
- pkg/fanal/applier/applier.go
- pkg/fanal/applier/applier_test.go
- pkg/fanal/artifact/image/image.go
- pkg/fanal/artifact/image/image_test.go
- pkg/fanal/artifact/local/fs.go
- pkg/fanal/artifact/repo/git_test.go
- pkg/fanal/artifact/sbom/sbom.go
- pkg/fanal/artifact/vm/ebs.go
- pkg/fanal/artifact/vm/file.go
- pkg/fanal/test/integration/containerd_test.go
- pkg/fanal/test/integration/library_test.go
- pkg/fanal/test/integration/registry_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
- pkg/scan/local/service.go
- pkg/scan/local/service_test.go
Adding the context to the cache interface functions allows for the
tenant ID to be attached to the context and passed through to the cache.
This opens up multi-tenancy redis cache so we can safely store blobs and
artifacts in the cache and key them to the Trivy cloud organization
- Close #9564
> chore: add context to the cache interface

- go.mod
- pkg/iac/rego/metadata.go
- pkg/k8s/scanner/scanner.go
Module `github.com/mitchellh/mapstructure` is not maintained anymore and is replaced by `github.com/go-viper/mapstructure/v2`
> chore(deps): Switch to go-viper/mapstructure

- pkg/iac/rego/metadata.go
- pkg/iac/scan/rule.go
- pkg/iac/scanners/cloudformation/scanner_test.go
- pkg/iac/scanners/dockerfile/scanner_test.go
- pkg/iac/scanners/generic/scanner_test.go
This PR adds the `ID` field to the `Rule` struct.
The ID field will be needed in `avd-generator` to add the ID to the existing aliases, for example:
```yaml
aliases: [
"/cspm/aws/s3/s3-bucket-logging",
"/misconfig/aws/s3-bucket-logging",
"/misconfig/s3-bucket-logging",
"/misconfig/avd-aws-0089",
"/misconfig/aws/s3/avd-aws-0089",
]
```
This allows referencing a check by ID, e.g., `misconfig/{ID}`, and ensures a smooth migration from the AVDID field to ID.
> refactor(misconf): add ID to scan.Rule

- docs/docs/configuration/filtering.md
- pkg/result/filter.go
- pkg/result/filter_test.go
- pkg/result/testdata/ignore-by-type.rego
- pkg/types/finding.go
- pkg/types/license.go
- pkg/types/misconfiguration.go
- pkg/types/secret.go
- pkg/types/vulnerability.go
Allow ignoring findings by type in Rego to avoid conflicts when multiple finding types share fields with the same name.
- Close https://github.com/aquasecurity/trivy/issues/6450
> feat: allow ignoring findings by type in Rego

- go.mod
- go.sum
- pkg/fanal/image/registry/google/google.go
- pkg/fanal/image/registry/google/google_test.go
This PR updates the `docker-credential-gcr` dependency to the module-compatible version `v2`.
> chore(deps): update to module-compatible docker-credential-gcr/v2
